# gazelle:resolve py prometheus_operator_crds //cluster/cdk8s/crd_bindings/prometheus_operator:servicemonitor
# gazelle:resolve py prometheus_operator_prometheusrule_crds //cluster/cdk8s/crd_bindings/prometheus_operator:prometheusrule
# gazelle:resolve py prometheus_operator_podmonitor_crds //cluster/cdk8s/crd_bindings/prometheus_operator:podmonitor

load("//devinfra/js:cdk8s_import.bzl", "cdk8s_import")

cdk8s_import(
    name = "servicemonitor",
    crd = "@prometheus_operator_servicemonitor_crd//file",
    module_name = "prometheus_operator_crds",
    module_path = "com/coreos/monitoring",
    visibility = ["//visibility:public"],
)

cdk8s_import(
    name = "prometheusrule",
    crd = "@prometheus_operator_prometheusrule_crd//file",
    module_name = "prometheus_operator_prometheusrule_crds",
    module_path = "com/coreos/monitoring",
    visibility = ["//visibility:public"],
)

cdk8s_import(
    name = "podmonitor",
    crd = "@prometheus_operator_podmonitor_crd//file",
    module_name = "prometheus_operator_podmonitor_crds",
    module_path = "com/coreos/monitoring",
    visibility = ["//visibility:public"],
)
