apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin-initial
  namespace: harbor
stringData:
  HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:n73xnXE4pOspKo1YY9qd5m/AC1r6is2AQu9/Lrky56bFGMF5W7hrCnKY+g==,iv:MGUvvnAMlei4rMY8pS6in1wJA8IC7BCbblS8uyUy3dc=,tag:uEeyBzT1YzE/W5TqJMQn2g==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSjBocUNnVjFtWGI2c2Zs
        UHVNSE9KUVgzMlNDSGFRVTFER0hDNTZWMDFVClF1Vi9HbWNYWklzWXdSWGlIWHF5
        N2owcXlrYWJNZWd1TGlGeEN4Q2thbmcKLS0tIGFXaGhzNVRMVEt4Vlgvb1dUTzVk
        eTdoMTR3MUdWa3E0RU53RGRUa09tR1kKh9uCttg7HEmCmhoyB1iMopmfSpprgeQ+
        iPuTyZRPppOAtY8Wh+zAvgpI0mWYdQiFGIu7UO10dW7nsouEiILSQg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRERBbHgxakhHR3JKcWNj
        bVZGVnNQSmtWZ2ZjTmU5eW8wQmUvQ3F5M0VBCm1EQ0NpNmdwOElBYmI4c2M3ZTVa
        RlRITWFic2ZzV3hYOHU1UFNUM3BtU1kKLS0tIDNtSFlXdWhGMnl3cGlvcTRrbytG
        VlBOUU5KSUlqaDQ5QS9QWmpBSDZwTlEKMUqvYvCF5cx4B/ZqXh72d61KaWC9KCQ0
        Cf6iGrpuHrD8z31gNUZnJrpYYbEBMylpCCYGGYuUOO8/OcdE7m0rHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T02:50:07Z"
  mac: ENC[AES256_GCM,data:+vp7nW1SsqzUyCMekHhXxXNQlHdMpWSwSSHRSdjoKHKK6goBEoHrt6vit5Ac+/qYiJYM1SFp4wJ8qZDah11cZ8p6jFljlCaqaRTI1QYy0S40Xxj+NBUMyzhT9mIFyQugSSnWSOsziJSpTDMYoVi/8PKibTTx0fyMhcRsy8GAo0g=,iv:ey69DfoYIUrQoYwHnpOOkZve1JvdYIUCYvHG887nPWE=,tag:4+Y0IiyZDUOEMmbCQvlhAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
