apiVersion: v1
kind: Service
metadata:
  name: haku-egress-proxy
  namespace: haku-egress-proxy
spec:
  selector:
    app.kubernetes.io/name: haku-egress-proxy
  ports:
    - name: proxy
      port: 3128
      targetPort: 3128
