load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "stubs",
    srcs = [
        "resources_stub.py",
        "server_stubs.py",
        "typed_stubs.py",
    ],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//mcp_infra/compositor",
        "//mcp_infra/resources",
        "@pypi//fastmcp",
        "@pypi//mcp",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "resources_stub",
    srcs = ["resources_stub.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//mcp_infra",
    ],
)

py_library(
    name = "server_stubs",
    srcs = ["server_stubs.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//fastmcp"],
)

py_library(
    name = "typed_stubs",
    srcs = ["typed_stubs.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//mcp_infra",
        "@pypi//fastmcp",
        "@pypi//mcp",
        "@pypi//pydantic",
    ],
)
