apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.k8s.yaml
  - certificate.yaml
  - trust-bundle.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - cnp-cloud-api-egress.k8s.yaml
  - ccnp-sandbox-proxy-egress.yaml
