load("//devinfra/python:defs.bzl", "py_binary", "py_library", "py_test")

py_library(
    name = "grid_generator",
    srcs = ["grid_generator.py"],
    deps = [
        "//laser/lightburn:lbrn2_writer",
        "//laser/ruida:rd_writer",
        "@pypi//pydantic",
    ],
)

py_binary(
    name = "grid_generator_bin",
    main_module = "laser.material_test.grid_generator",
    deps = [":grid_generator"],
)

py_test(
    name = "test_grid_generator",
    srcs = ["test_grid_generator.py"],
    data = [
        "example_config.toml",
        "example_config_3d.toml",
    ],
    deps = [
        ":grid_generator",
        "//:conftest",
        "//laser/lightburn:lbrn2_writer",
        "//util/bazel:runfiles",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
