load("//devinfra/python:defs.bzl", "py_binary", "py_library", "py_test")

# gazelle:exclude material_test.py
# gazelle:exclude test_material_test.py

py_library(
    name = "material_test_lib",
    srcs = ["material_test.py"],
    deps = [
        "//laser/lightburn:lbrn2_writer",
        "//laser/ruida:rd_writer",
        "@pypi//pydantic",
    ],
)

py_binary(
    name = "material_test",
    main_module = "laser.material_test.material_test",
    deps = [":material_test_lib"],
)

py_test(
    name = "test_material_test",
    srcs = ["test_material_test.py"],
    data = [
        "example_config.toml",
        "example_config_3d.toml",
    ],
    deps = [
        ":material_test_lib",
        "//laser/lightburn:lbrn2_writer",
        "//util/bazel:runfiles",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
