# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

package(default_visibility = ["//cluster/cdk8s:__pkg__"])

py_library(
    name = "client",
    srcs = ["client.py"],
    visibility = [
        "//cluster/cdk8s:__pkg__",
        "//cluster/cdk8s/clickhouse:__pkg__",
    ],
    deps = [
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
        "@pypi//constructs",
    ],
)

py_library(
    name = "schema",
    srcs = ["schema.py"],
    visibility = [
        "//cluster/cdk8s:__pkg__",
        "//cluster/validation:__pkg__",
    ],
    deps = [
        ":client",
        "//cluster/cdk8s:artifact_generators",
        "//cluster/cdk8s:fleet_rules",
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s:metadata",
        "//cluster/cdk8s:pod_spec_patches",
        "//cluster/cdk8s/crd_bindings/flux:kustomization",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
    ],
)

py_library(
    name = "flux_kustomizations",
    srcs = ["flux_kustomizations.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:artifact_generators",
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s/crd_bindings/flux:kustomization",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
    ],
)

py_library(
    name = "operator",
    srcs = ["operator.py"],
    deps = [
        "//cluster/cdk8s:artifact_generators",
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s:metadata",
        "//cluster/cdk8s/crd_bindings/flux:helmrelease",
        "//cluster/cdk8s/crd_bindings/flux:helmrepository",
        "//cluster/cdk8s/crd_bindings/flux:kustomization",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
    ],
)
