# gazelle:ignore

load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("//devinfra/testing:defs.bzl", "py_test")

package(default_visibility = [
    "//cluster:__subpackages__",
    "//devinfra/precommit:__pkg__",
])

py_library(
    name = "k8s",
    srcs = ["k8s.py"],
    imports = ["../.."],
    deps = [
        "@pypi//pydantic",
        "@pypi//pyyaml",
    ],
)

py_library(
    name = "kustomize",
    srcs = ["kustomize.py"],
    imports = ["../.."],
    deps = [
        ":k8s",
        "@pypi//pydantic",
        "@pypi//pyyaml",
    ],
)

py_library(
    name = "flux",
    srcs = ["flux.py"],
    imports = ["../.."],
    deps = [
        "@pypi//pydantic",
        "@pypi//pyyaml",
    ],
)

py_library(
    name = "cluster",
    srcs = ["cluster.py"],
    imports = ["../.."],
    deps = [
        ":flux",
        ":k8s",
        ":kustomize",
        "@pypi//networkx",
        "@pypi//numpy",
        "@pypi//types_networkx",
    ],
)

py_library(
    name = "dependencies",
    srcs = ["dependencies.py"],
    imports = ["../.."],
    deps = [
        ":cluster",
        ":crd_layering",
        ":flux",
        "@pypi//networkx",
        "@pypi//numpy",
        "@pypi//types_networkx",
    ],
)

py_library(
    name = "health_checks",
    srcs = ["health_checks.py"],
    imports = ["../.."],
    deps = [
        ":cluster",
        ":k8s",
        ":kustomize",
    ],
)

py_library(
    name = "crd_layering",
    srcs = ["crd_layering.py"],
    imports = ["../.."],
    deps = [":kustomize"],
)

py_library(
    name = "sealed_secrets",
    srcs = ["sealed_secrets.py"],
    imports = ["../.."],
    deps = [
        ":cluster",
        "//util/bazel:runfiles",
        "//util/bazel:workspace",
    ],
)

py_library(
    name = "helm_templates",
    srcs = ["helm_templates.py"],
    imports = ["../.."],
    deps = ["//util/bazel:runfiles"],
)

py_library(
    name = "kustomize_build_all_lib",
    srcs = ["kustomize_build_all.py"],
    imports = ["../.."],
    deps = [
        ":cluster",
        ":k8s",
        ":kustomize",
        "//util/bazel:runfiles",
        "@pypi//pydantic",
        "@pypi//pyyaml",
    ],
)

py_binary(
    name = "kustomize_build_all",
    data = ["@multitool//tools/kustomize"],
    imports = ["../.."],
    main_module = "cluster.validation.kustomize_build_all",
    deps = [":kustomize_build_all_lib"],
)

py_test(
    name = "test_k8s",
    srcs = ["test_k8s.py"],
    imports = ["../.."],
    deps = [
        ":k8s",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_flux",
    srcs = ["test_flux.py"],
    data = glob(["testdata/**"]),
    imports = ["../.."],
    deps = [
        ":cluster",
        ":dependencies",
        ":flux",
        "//util/bazel:runfiles",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_dependencies",
    srcs = ["test_dependencies.py"],
    imports = ["../.."],
    deps = [
        ":cluster",
        ":dependencies",
        ":flux",
        ":k8s",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_health_checks",
    srcs = ["test_health_checks.py"],
    imports = ["../.."],
    deps = [
        ":cluster",
        ":flux",
        ":health_checks",
        ":k8s",
        ":kustomize",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_crd_layering",
    srcs = ["test_crd_layering.py"],
    data = glob(["testdata/crd_layering/**"]),
    imports = ["../.."],
    deps = [
        ":crd_layering",
        ":k8s",
        ":kustomize",
        "//util/bazel:runfiles",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
        "@pypi//pyyaml",
    ],
)

py_test(
    name = "test_cluster_integration",
    srcs = ["test_cluster_integration.py"],
    data = ["//cluster/k8s:cluster_yaml_files"],
    imports = ["../.."],
    deps = [
        ":cluster",
        ":dependencies",
        ":health_checks",
        "//cluster/scripts/validate_cluster:checks",
        "//util/bazel:runfiles",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
        "@pypi//pyyaml",
    ],
)
