"""Invariants over every egress allowlist in the cluster.

Five host lists bound what agent workloads reach: four Cilium `toFQDNs` fences generated by
`cluster/cdk8s/egress_fences.py` plus the openclaw spike's app-level iron transform. The
`public-coder` proxy holds none -- a deliberate waiver documented at
`cluster/cdk8s/public_coder_proxy.py:_egress_policy` -- so it is out of scope here.

A generated fence's hosts live once: its `toFQDNs` groups and its DNS rule derive from the
same tuple, so what a fence holds gets no pin here (editing the tuple is the review). What
stays are the claims no single tuple can express -- the named host groups below and the rules
over which fences may hold them -- and the one agreement still spanning two artifacts: the
spike's hand-written iron allowlist against the DNS rule generated from its copy.

Every set here bounds a proxy's reach on the public internet and nothing else: in-cluster
traffic is admitted by a `toEntities: cluster` rule, and a `*.allegedly.works` entry in a
`toFQDNs` group enforces nothing (`cluster/cdk8s/egress_fences.py`). Known gaps, among them
that which pod is *routed* through which proxy is unverified: `cluster/k8s/TODO.md`
§ Egress fences.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Any, cast

import pytest
import pytest_bazel
import yaml
from cdk8s import (
    App,
    Chart,
    Testing as Cdk8sTesting,  # pytest would collect a class named Testing
)
from more_itertools import one

from cluster.cdk8s import egress_fences


def hosts(*names: str) -> frozenset[str]:
    """A named host group, kept one indent deep at the call site."""
    return frozenset(names)


# GitHub's source and release-artifact hosts. Split out of the build bucket because "reads
# source, builds nothing" is a real posture -- the Claude runner pool holds these and no
# package registry -- and that is a decision rather than the drift the all-or-none rule
# exists to catch. Still one trust level internally, so it is all-or-none in its own right.
# Anonymous these are read-only; a fence that also substitutes a credential for them (see
# haku-claude) turns them into a push surface.
GITHUB_GIT = hosts(
    "github.com",
    "codeload.github.com",
    "objects.githubusercontent.com",
    "raw.githubusercontent.com",
    "release-assets.githubusercontent.com",
)

# The shared build-registry bucket: public package, source and toolchain registries. Every
# fence that builds code carries the whole set -- see `test_build_registries_are_all_or_none`.
# They share one trust level (public, read-only, credential-gated to publish to), so splitting
# them into nine groups bought a precision nobody used while letting the fences quietly drift
# apart.
BUILD_REGISTRIES = GITHUB_GIT | hosts(
    "ftp.gnu.org",
    # Language package registries and toolchains
    "pypi.org",
    "files.pythonhosted.org",
    "registry.npmjs.org",
    "nodejs.org",
    # Nix
    "cache.nixos.org",
    "nixos.org",
    "channels.nixos.org",
    # Bazel
    "releases.bazel.build",
    "bcr.bazel.build",
    # Rust: the toolchain tarballs and the sparse crate registry. Needed since augur's
    # simulator became a Rust extension, so a consumer that builds `finance/augur/rust`
    # cold-fetches rustc and its crates.
    "static.rust-lang.org",
    "index.crates.io",
    "static.crates.io",
    # Container images and OS packages
    "ghcr.io",
    "pkg-containers.githubusercontent.com",
    "snapshot.debian.org",
    # Forgejo's own public release/CDN hosts, not the in-cluster instance
    "code.forgejo.org",
    "data.forgejo.org",
)

# A write surface, deliberately outside the bucket: anonymous github.com is read-only, while
# the API is what makes gists, issues and pushes reachable. Folding it in would hand every
# build fence a way to publish at once.
GITHUB_API = hosts("api.github.com")

# Hosts serving the operator's own accounts. A prompt-injected agent holding these reads the
# operator's mail, finances and study data, so the group is named to keep
# `test_operator_data_reaches_only_haku_sandbox` honest as consumers are added.
OPERATOR_DATA = hosts("api.coinbase.com", "haku-mailbox.allegedly.works", "*.ankiweb.net")

# The operator's Google account (mail, calendar, tasks). No fence here reaches it: agents reach
# it only through services that hold the token for them (agentplane's egress proxy, google-mcp).
OPERATOR_GOOGLE = hosts("www.googleapis.com", "gmail.googleapis.com", "tasks.googleapis.com")

# The fences the assertions below single out: a generated fence by its policy name, a
# hand-written half by its manifest path, so a failure names the thing to open.
OPERATOR_DATA_FENCE = "allow-haku-cloud-api-egress"
HAKU_CLAUDE_FENCE = "allow-haku-claude-oauth-proxy-egress"
HAKU_OPENCLAW_DNS_FENCE = "allow-haku-openclaw-spike-proxy-egress"
HAKU_OPENCLAW_FENCE = "agents/haku-egress-proxy/openclaw-spike-iron.yaml"


def _cilium_hosts(document: dict[str, Any]) -> set[str]:
    """Every host named by a `toFQDNs` rule, ignoring DNS query patterns."""
    return {host for rule in document["spec"]["egress"] for entry in rule.get("toFQDNs", ()) for host in entry.values()}


def _cilium_dns_names(document: dict[str, Any]) -> set[str]:
    """Every name a `toPorts.rules.dns` rule permits the pod to look up."""
    return {
        name
        for rule in document["spec"]["egress"]
        for port_rule in rule.get("toPorts", ())
        for entry in port_rule.get("rules", {}).get("dns", ())
        for name in entry.values()
    }


def _iron_hosts(document: dict[str, Any]) -> set[str]:
    return set(one(t for t in document["transforms"] if t["name"] == "allowlist")["config"]["domains"])


def _load(k8s_dir: Path, path: str) -> dict[str, Any]:
    return cast(dict[str, Any], yaml.safe_load((k8s_dir / path).read_text()))


def _synth(build: Callable[[App], Chart]) -> dict[str, Any]:
    return cast(dict[str, Any], one(Cdk8sTesting.synth(build(Cdk8sTesting.app()))))


@pytest.fixture(scope="session")
def generated_fences() -> dict[str, dict[str, Any]]:
    """Every generated fence, rendered, keyed by policy name."""
    builders = (
        egress_fences.haku_cloud_api,
        egress_fences.haku_claude,
        egress_fences.haku_openclaw_spike,
        egress_fences.mitmproxy_cloud_api,
    )
    return {policy["metadata"]["name"]: policy for policy in map(_synth, builders)}


@pytest.fixture(scope="session")
def allowlists(generated_fences: dict[str, dict[str, Any]], k8s_dir: Path) -> dict[str, frozenset[str]]:
    """What each fence may connect to: `toFQDNs` for a Cilium fence, the `allowlist` transform
    for iron."""
    return {
        **{name: frozenset(_cilium_hosts(policy)) for name, policy in generated_fences.items()},
        HAKU_OPENCLAW_FENCE: frozenset(_iron_hosts(_load(k8s_dir, HAKU_OPENCLAW_FENCE))),
    }


def test_openclaw_spike_resolves_exactly_its_iron_allowlist(
    generated_fences: dict[str, dict[str, Any]], allowlists: dict[str, frozenset[str]]
) -> None:
    """The spike's two layers are enforced by different components from two files: the iron
    allowlist is app config, the DNS rule is Cilium's. That rule is the only Cilium-side bound
    on the proxy, so it is pinned to the allowlist rather than left open -- until the iron
    config is generated from the same tuple (cluster/cdk8s/TODO.md)."""
    expected = allowlists[HAKU_OPENCLAW_FENCE] | set(egress_fences.CLUSTER_DNS)
    assert _cilium_dns_names(generated_fences[HAKU_OPENCLAW_DNS_FENCE]) == expected


def test_build_registries_are_all_or_none(allowlists: dict[str, frozenset[str]]) -> None:
    """No fence carries part of the bucket.

    The hosts are grouped because they share a trust level, so a fence holding a subset is
    drift rather than a decision -- which is exactly how the fences diverged before they were
    pinned. GITHUB_GIT is separable from the package registries (a fence may read source
    without building), but neither bucket may be held in part.
    """
    for fence, allowed in allowlists.items():
        for bucket in (GITHUB_GIT, BUILD_REGISTRIES - GITHUB_GIT):
            assert allowed & bucket in (frozenset(), bucket), fence


def test_operator_data_reaches_only_haku_sandbox(allowlists: dict[str, frozenset[str]]) -> None:
    """The tier that reads the operator's own accounts stays in one fence.

    A coding agent that gained these would turn each of its injection surfaces into a path to
    the operator's mail and finances.
    """
    assert allowlists[OPERATOR_DATA_FENCE] >= OPERATOR_DATA
    for fence, allowed in allowlists.items():
        if fence != OPERATOR_DATA_FENCE:
            assert not (allowed & OPERATOR_DATA), fence


def test_no_fence_reaches_the_operators_google_account(allowlists: dict[str, frozenset[str]]) -> None:
    for fence, allowed in allowlists.items():
        assert not (allowed & OPERATOR_GOOGLE), fence


def test_github_api_reaches_only_declared_holders(allowlists: dict[str, frozenset[str]]) -> None:
    """`api.github.com` is a write surface, so every grant is named explicitly."""
    holders = {fence for fence, allowed in allowlists.items() if allowed & GITHUB_API}
    assert holders == {HAKU_OPENCLAW_FENCE, HAKU_CLAUDE_FENCE}


if __name__ == "__main__":
    pytest_bazel.main()
