"""FreeCAD AppImage repository rule and Bazel integration.

Provides:
  freecad_appimage_ext  - module extension (register in MODULE.bazel)
  freecad_appimage_rloc - macro to expose the AppImage as a test data dep

Usage in MODULE.bazel:
  freecad_appimage = use_extension("//devinfra/freecad_appimage:defs.bzl", "freecad_appimage_ext")
  use_repo(freecad_appimage, "freecad_appimage")

Usage in BUILD:
  load("//devinfra/freecad_appimage:defs.bzl", "freecad_appimage_rloc")
  freecad_appimage_rloc(name = "freecad_appimage", testonly = True)

At test runtime, read the .rloc file via runfiles to get the AppImage path, then
run it directly:
  appimage = get_required_path(rloc_file.read_text().strip())
  subprocess.run([appimage, "freecadcmd", script], env={..., "QT_QPA_PLATFORM": "offscreen"})

The AppImage's AppRun sets up PYTHONHOME, PATH_TO_FREECAD_LIBDIR, etc. automatically.
"""

load("@aspect_bazel_lib//lib:paths.bzl", "to_rlocation_path")

# ── Repository rule ────────────────────────────────────────────────────────────

def _freecad_appimage_repo_impl(rctx):
    rctx.download(
        url = rctx.attr.urls,
        output = "FreeCAD.AppImage",
        sha256 = rctx.attr.sha256,
        executable = True,
    )

    rctx.file("BUILD.bazel", """\
# Auto-generated by //devinfra/freecad_appimage:defs.bzl

filegroup(
    name = "appimage",
    srcs = ["FreeCAD.AppImage"],
    visibility = ["//visibility:public"],
)
""")

_freecad_appimage_repo = repository_rule(
    implementation = _freecad_appimage_repo_impl,
    attrs = {
        "urls": attr.string_list(mandatory = True),
        "sha256": attr.string(mandatory = True),
    },
)

# ── Module extension ───────────────────────────────────────────────────────────

_FREECAD_APPIMAGE_URL = "https://github.com/FreeCAD/FreeCAD/releases/download/1.1.0/FreeCAD_1.1.0-Linux-x86_64-py311.AppImage"
_FREECAD_APPIMAGE_SHA256 = "ef85f171f2d09eec93f358bc49c1730d33f72bfbd353e6465609b30e45acf2f0"

def _freecad_appimage_ext_impl(module_ctx):
    _freecad_appimage_repo(
        name = "freecad_appimage",
        urls = [_FREECAD_APPIMAGE_URL],
        sha256 = _FREECAD_APPIMAGE_SHA256,
    )
    return module_ctx.extension_metadata(
        root_module_direct_deps = ["freecad_appimage"],
        root_module_direct_dev_deps = [],
        reproducible = True,
    )

freecad_appimage_ext = module_extension(
    implementation = _freecad_appimage_ext_impl,
)

# ── .rloc rule ─────────────────────────────────────────────────────────────────

def _freecad_appimage_rloc_impl(ctx):
    """Write .rloc with the rlocation of FreeCAD.AppImage."""
    out = ctx.actions.declare_file(ctx.label.name + ".rloc")
    ctx.actions.write(out, to_rlocation_path(ctx, ctx.file.appimage))
    runfiles = ctx.runfiles(files = [out, ctx.file.appimage])
    return [DefaultInfo(files = depset([out]), runfiles = runfiles)]

_freecad_appimage_rloc = rule(
    implementation = _freecad_appimage_rloc_impl,
    attrs = {
        "appimage": attr.label(mandatory = True, allow_single_file = True),
    },
)

def freecad_appimage_rloc(name, visibility = None, testonly = False):
    """Expose FreeCAD.AppImage as a test data dep.

    Generates :<name>.rloc containing the rlocation of FreeCAD.AppImage.
    At runtime: appimage = get_required_path(rloc_file.read_text().strip())
    """
    _freecad_appimage_rloc(
        name = name,
        appimage = "@freecad_appimage//:appimage",
        visibility = visibility,
        testonly = testonly,
    )
