"""FreeCAD AppImage repository rule and Bazel integration.

Provides:
  freecad_appimage_ext  - module extension (register in MODULE.bazel)
  freecad_appimage_rloc - macro to expose the extracted AppImage as a test data dep

Usage in MODULE.bazel:
  freecad_appimage = use_extension("//devinfra/freecad_appimage:defs.bzl", "freecad_appimage_ext")
  use_repo(freecad_appimage, "freecad_appimage")

Usage in BUILD:
  load("//devinfra/freecad_appimage:defs.bzl", "freecad_appimage_rloc")
  freecad_appimage_rloc(name = "freecad_appimage", testonly = True)

At test runtime, read the .rloc file via runfiles, resolve freecadcmd, derive
squashfs-root as freecadcmd.parents[2] (squashfs-root/usr/bin/freecadcmd),
then set env vars (PYTHONHOME, PATH_TO_FREECAD_LIBDIR, QT_QPA_PLATFORM=offscreen).
"""

load("@aspect_bazel_lib//lib:paths.bzl", "to_rlocation_path")

# ── Repository rule ────────────────────────────────────────────────────────────

def _freecad_appimage_repo_impl(rctx):
    rctx.download(
        url = rctx.attr.urls,
        output = "FreeCAD.AppImage",
        sha256 = rctx.attr.sha256,
        executable = True,
    )

    # --appimage-extract extracts the squashfs filesystem without FUSE.
    result = rctx.execute(
        ["./FreeCAD.AppImage", "--appimage-extract"],
        timeout = 300,
        quiet = False,
    )
    if result.return_code != 0:
        fail("FreeCAD AppImage extraction failed:\n" + result.stderr)

    rctx.file("BUILD.bazel", """\
# Auto-generated by //devinfra/freecad_appimage:defs.bzl

filegroup(
    name = "squashfs_root",
    srcs = glob(
        ["squashfs-root/**/*"],
        allow_empty = False,
    ),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "freecadcmd",
    srcs = ["squashfs-root/usr/bin/freecadcmd"],
    visibility = ["//visibility:public"],
)
""")

_freecad_appimage_repo = repository_rule(
    implementation = _freecad_appimage_repo_impl,
    attrs = {
        "urls": attr.string_list(mandatory = True),
        "sha256": attr.string(mandatory = True),
    },
)

# ── Module extension ───────────────────────────────────────────────────────────

_FREECAD_APPIMAGE_URL = "https://github.com/FreeCAD/FreeCAD/releases/download/1.1.0/FreeCAD_1.1.0-Linux-x86_64-py311.AppImage"
_FREECAD_APPIMAGE_SHA256 = "ef85f171f2d09eec93f358bc49c1730d33f72bfbd353e6465609b30e45acf2f0"

def _freecad_appimage_ext_impl(module_ctx):
    _freecad_appimage_repo(
        name = "freecad_appimage",
        urls = [_FREECAD_APPIMAGE_URL],
        sha256 = _FREECAD_APPIMAGE_SHA256,
    )
    return module_ctx.extension_metadata(
        root_module_direct_deps = ["freecad_appimage"],
        root_module_direct_dev_deps = [],
        reproducible = True,
    )

freecad_appimage_ext = module_extension(
    implementation = _freecad_appimage_ext_impl,
)

# ── .rloc rule (mirrors oci_layout_rloc pattern) ──────────────────────────────

def _freecad_appimage_rloc_impl(ctx):
    """Write .rloc with the rlocation of freecadcmd; add squashfs_root to runfiles."""
    out = ctx.actions.declare_file(ctx.label.name + ".rloc")
    ctx.actions.write(out, to_rlocation_path(ctx, ctx.file.freecadcmd))

    # Use transitive_files (not merge/default_runfiles) so that the filegroup's
    # files depset is included in the runfiles tree of any test that depends on
    # this target.  merge(default_runfiles) does not propagate filegroup srcs
    # from external repositories correctly.
    runfiles = ctx.runfiles(
        files = [out],
        transitive_files = ctx.attr.squashfs_root[DefaultInfo].files,
    )
    return [DefaultInfo(files = depset([out]), runfiles = runfiles)]

_freecad_appimage_rloc = rule(
    implementation = _freecad_appimage_rloc_impl,
    attrs = {
        "freecadcmd": attr.label(mandatory = True, allow_single_file = True),
        "squashfs_root": attr.label(mandatory = True),
    },
)

def freecad_appimage_rloc(name, visibility = None, testonly = False):
    """Expose the extracted FreeCAD AppImage as a test data dep.

    Generates :<name>.rloc containing the rlocation of freecadcmd.
    Add to data= in tests; at runtime:
      rloc_path = get_required_path("<workspace>/path/to/<name>.rloc").read_text().strip()
      freecadcmd = get_required_path(rloc_path)
      squashfs_root = freecadcmd.parents[2]  # squashfs-root/usr/bin/freecadcmd
    """
    _freecad_appimage_rloc(
        name = name,
        freecadcmd = "@freecad_appimage//:freecadcmd",
        squashfs_root = "@freecad_appimage//:squashfs_root",
        visibility = visibility,
        testonly = testonly,
    )
