apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clickhouse-operator
  namespace: ducktape-flux
spec:
  retryInterval: 1m
  interval: 10m
  path: ./cluster/k8s/clickhouse/operator
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age-cluster-secrets
  sourceRef:
    kind: GitRepository
    name: ducktape
    namespace: ducktape-flux
  timeout: 10m
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: clickhouse-operator
      namespace: clickhouse
  dependsOn:
    - name: clickhouse-namespace
      namespace: ducktape-flux
    - name: monitoring-stack
      namespace: ducktape-flux
