apiVersion: v1
kind: Secret
metadata:
  name: buildbuddy-api-key
  namespace: claude-sandbox
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: openclaw-sandbox
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: openclaw-sandbox
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:Et7Y8ZxMzB42B23ViOLKxXSuAKA=,iv:I4Zrkpe+d/JyF+EW6PsfgxmatUqoQfqgfzmgiep3+Ps=,tag:qK1MNXqLdO6WmJuLYEM2Xw==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNHpnSU0rcXpNNjM2bTQx
        aStocW93ZGxoUnN6SkpQbW0xWW1lbzRQdm1vClhSK2xhQkJwcjVOL1ZsUDQ2aWR3
        emppd3FiR3h4c2Y3NHF4d0JpbkZYYWMKLS0tIDVtSEU3ekNsUmFWOHF6clNUVnNJ
        L1ROdTF5VDhTUDV0YkZneFd3TE5yRFUKw47YoFGmVZeq5T0crK+j2FSfUS7jFFPq
        90BWRM6CAhE7uumi01qijpGDWiyu3bJZQcHueiXmMv+uXtonLmRCLw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MkdYRGVIYk1TSGZzUThk
        TG5maHUwcHk4ZkpHbUhEMUxDRXROekJHK1VBCkdkLzc0dklUSVI3TXJpaFNDQ3or
        N0tZem5RcURDRURHRkVsQlZsWTg3bk0KLS0tIGw4SUFVZ3d5Z1lubjhaVTVvRVky
        YWIwSis4TWR1U1JpOUllMy9abVJlOEUK+kquC60ZQsMMc4/n3mSTyzfChUTBLVQz
        2Y5urUYqpqLryom4Hw/ML07BiLzXK52t68UgLGQkZuuVYGLWSMipxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T19:50:17Z"
  mac: ENC[AES256_GCM,data:wlSQD4sOGgEnOexsYRvwEFo/x+FZx7KUgkLhpag3YztBBEbAITnAfrd+vxCcZz2troVWsKbhU6IZJIJ7b9ivhmK7qqYhj8Y7YBIbBMwHXL4QazgxxpAj/k/ZzfdBp1I63CoUuumPWn9wZeuKUVKts99xhuMywpTph2imjHJNJBI=,iv:/2JQIZ26J5EF2YZupeJLve1SYUJHQFIAtceuwjVkYi0=,tag:jMdR6UTuAaZbx8UQ1qh9QA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
