apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: haku-console-static
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: haku-console-static
  filterTags:
    pattern: '^devel-\d{14}-[0-9a-f]{7}$'
  policy:
    alphabetical:
      order: asc
