apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: props-registry-proxy
  namespace: flux-system
spec:
  image: ghcr.io/agentydragon/props-registry-proxy
  interval: 5m
