// Reconstructed from binary 495ea204
// Source: internal/o11y/discard_o11y_service.go

package o11y

import (
	"context"
	"io"
	"log/slog"

	"go.opentelemetry.io/otel/trace"
)

// DiscardO11yService is a no-op implementation of O11yService that
// discards all metrics and returns a discard logger handler.
//
// Binary itab: go:itab.DiscardO11yService,O11yService at 0xf65430
type DiscardO11yService struct{}

// LogHandler returns a slog.TextHandler that writes to io.Discard.
// Binary address: 0xa51520
func (d DiscardO11yService) LogHandler() slog.Handler {
	return slog.NewTextHandler(io.Discard, &slog.HandlerOptions{
		Level: slog.LevelError,
	})
}

// Shutdown is a no-op; returns nil error.
// Binary address: 0xa51680
func (d DiscardO11yService) Shutdown(_ context.Context) error {
	return nil
}

// Increment is a no-op; discards the metric.
// Binary address: 0xa516a0
func (d DiscardO11yService) Increment(_ string, _ *O11yMetric, _ []TagProvider) {
}

// RecordGauge is a no-op; discards the metric.
// Binary address: 0xa516c0
func (d DiscardO11yService) RecordGauge(_ string, _ *O11yFunctionMetric, _ []TagProvider, _ float64) {
}

// Tracer returns the singleton no-op Tracer. NEW in Build ID 0b86a2a0.
//
// Binary address: 0x2009740 (FKPKJ5B0zZ.NR2MTNm.Tracer) — a bare tail call to
// noopTracer() at 0x2015720.
func (d DiscardO11yService) Tracer() trace.Tracer {
	return noopTracer()
}

// RecordLongRunningStep is a no-op; discards the step metric.
//
// TODO(re): Build ID 0b86a2a0's DiscardO11yService (FKPKJ5B0zZ.NR2MTNm) has no
// such method — its method set is exactly {Increment, LogHandler, RecordGauge,
// Shutdown, Tracer}. CARRIED from the 495ea204 RE; not current.
func (d DiscardO11yService) RecordLongRunningStep(_ string, _ string, _ []TagProvider) {
}

// Pointer-receiver wrappers generated by the compiler (495ea204 addresses):
// (*DiscardO11yService).Increment at 0xa57d80
// (*DiscardO11yService).LogHandler at 0xa57dc0
// (*DiscardO11yService).RecordGauge at 0xa57f60
// (*DiscardO11yService).Shutdown at 0xa57fa0
//
// Build ID 0b86a2a0 equivalents (FKPKJ5B0zZ.(*NR2MTNm).*):
// Increment 0x2024840, LogHandler 0x2024880, RecordGauge 0x20248e0,
// Shutdown 0x2024920, Tracer 0x2024960.
