apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openclaw-config.yaml
  - github-token-eso.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy-egress.yaml
  - networkpolicy-ingress.yaml
