# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "db",
    srcs = ["db.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:cnpg",
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s/agentplane:node_scheduling",
        "//cluster/cdk8s/crd_bindings/cnpg:cluster",
        "//cluster/cdk8s/crd_bindings/flux:kustomization",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
    ],
)

py_library(
    name = "namespace",
    srcs = ["namespace.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = ["//cluster/cdk8s:generation"],
)
