apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.k8s.yaml
  - admin-credentials.sops.yaml
  - aiquota-credentials.sops.yaml
  - langfuse-credentials.sops.yaml
  - grafana-credentials.sops.yaml
  - public-coder-credentials.sops.yaml
