apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-public-coder-credentials
    namespace: clickhouse
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: public-coder-agent
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: public-coder-agent
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1iACWJAZUm28vZqa9/rIksSeoKA6RA==,iv:SM3x+Sbm3JTPJrAPoI6ZqlbfULjzwssEcnzmwh5gz3c=,tag:tqWbrsxjUEmtbvI4PJMHDA==,type:str]
    password: ENC[AES256_GCM,data:Y0PPtRjVRtrP+AcReOfXJHXdPorDr7X7E4ssgV3rs0ADrxexeUe8cs0qsKRnW4xL7tomyOQQCor1Rkunkp8t4Q==,iv:R0O9ats4Axt/ikyraAV/W3FwuEjWiL9jY2i22W17oWc=,tag:eH5ThHed/4hyXrNyQqq83A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWXVPZG52K09VSHdlRjNn
            UWRXbzJUaWpNeGhSRFNBM29QTGMrQ3hwQ2lJCjBpNjhPY0dobjZibFVKc3o0RTVV
            cTY1Q1FvbVY2U2E1aVhrN05EeUlSNWsKLS0tIEdreUdjMTNBZ1U3N1JxUjQyUHpV
            YkVBQ2FtZnJuM2F5UjJNREw0d1p2NWMK7ZWyu9lFi645BOEdbGGhf18oIArfO647
            g9HhxqWfHbISwXRIxl9QCDKmrmQ7UxDP7+lw8bPjPYpJV7FGPOhGMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNd2YrNURHK2ZCaysxSU02
            SFpYSVgrUXdsczRlUWlvSmpNV0xMM2pFaTJRClNZUnFxdk5TeS9OaFNGY0ZIU2Yy
            VWpuMG9Ub1kvRUdFV25jY0k2blViblEKLS0tIGdTVVFyRGlSUCtUMUd3cTJWem1V
            TUxBb3dkN0hONkZROGVWUmR1VGVTcVEKzchcJEI9/MpNUwAxz1XUS2p9Q5PDA7fV
            EL0WN+eoCzTRJp2vj8iqVDqKiVDUPcIY0/h7FmnxXPkf+CTHolTjXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T10:45:26Z"
    mac: ENC[AES256_GCM,data:qg9KC2BS2QzscVxj8PedbT5NLZ4rxj4M8ecRyguKzSWVAZPf0FRe4ejJgS8CKglGwZ3BaCrZSwf2IlR7PKHt0PsmNuOtI5l4JLn7TjV8yapsK/9gTQ7OkbsOs5LHz3e8kgQk4owIQUBfneuZfw/VlkIId5W3ekX+nsCwgqB3jzI=,iv:UfYJyHCFwLe/4QzOrpbwbX4aBzbMLk1gZFHJAW7FeX0=,tag:4MyuQvcB77ZXfGTOvCn98Q==,type:str]
    version: 3.13.3
