load("//devinfra/python:defs.bzl", "py_test")
load("//skills:defs.bzl", "skill_mapping", "skill_package")

skill_package(
    name = "cpap",
    contents = [
        skill_mapping(
            srcs = ["SKILL.md"],
            preserve_paths = True,
        ),
        skill_mapping(
            srcs = [
                "//cpap/skill/examples:parse_str_edf.py",
                "//cpap/skill/examples:read_waveforms.py",
            ],
            prefix = "examples",
        ),
    ],
)

py_test(
    name = "test_parse_str_edf",
    srcs = ["test_parse_str_edf.py"],
    deps = [
        "//:conftest",
        "//cpap/skill/examples:generate_test_edf",
        "//cpap/skill/examples:parse_str_edf",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
