load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "orchestrator",
    srcs = [
        "hooks.go",
        "orchestrator.go",
        "poll_hook.go",
        "poller.go",
        "whoami.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/orchestrator",
    visibility = ["//claude_web_env/re/environment_manager/6b49f1ca/src:__subpackages__"],
    deps = [
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/o11y",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/sandbox",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/util",
    ],
)
