# gazelle:ignore
load("//devinfra/python:defs.bzl", "py_binary", "py_library")

package(default_visibility = ["//finance/plaid/spend/desktop:__pkg__"])

py_library(
    name = "credentials",
    srcs = ["credentials.py"],
)

py_library(
    name = "oauth",
    srcs = ["oauth.py"],
    deps = [
        ":credentials",
        "@pypi//httpx",
    ],
)

py_library(
    name = "daemon",
    srcs = ["daemon.py"],
    deps = [
        ":credentials",
        ":oauth",
        "@pypi//dbus_next",
        "@pypi//httpx",
    ],
)

py_library(
    name = "cli",
    srcs = ["cli.py"],
    deps = [
        "@pypi//babel",
        "@pypi//dbus_next",
    ],
)

py_binary(
    name = "plaid_spend_cli",
    main_module = "finance.plaid.spend.desktop.plaid_spend_desktop.cli",
    visibility = ["//visibility:public"],
    deps = [":cli"],
)

py_library(
    name = "package_init",
    srcs = ["__init__.py"],
)
