// Reconstructed from binary 495ea204
// Source: internal/o11y/discard_o11y_service.go

package o11y

import (
	"context"
	"io"
	"log/slog"
)

// DiscardO11yService is a no-op implementation of O11yService that
// discards all metrics and returns a discard logger handler.
//
// Binary itab: go:itab.DiscardO11yService,O11yService at 0xf65430
type DiscardO11yService struct{}

// LogHandler returns a slog.TextHandler that writes to io.Discard.
// Binary address: 0xa51520
func (d DiscardO11yService) LogHandler() slog.Handler {
	return slog.NewTextHandler(io.Discard, &slog.HandlerOptions{
		Level: slog.LevelError,
	})
}

// Shutdown is a no-op; returns nil error.
// Binary address: 0xa51680
func (d DiscardO11yService) Shutdown(_ context.Context) error {
	return nil
}

// Increment is a no-op; discards the metric.
// Binary address: 0xa516a0
func (d DiscardO11yService) Increment(_ string, _ *O11yMetric, _ []TagProvider) {
}

// RecordGauge is a no-op; discards the metric.
// Binary address: 0xa516c0
func (d DiscardO11yService) RecordGauge(_ string, _ *O11yFunctionMetric, _ []TagProvider, _ float64) {
}

// RecordLongRunningStep is a no-op; discards the step metric.
func (d DiscardO11yService) RecordLongRunningStep(_ string, _ string, _ []TagProvider) {
}

// Pointer-receiver wrappers generated by the compiler:
// (*DiscardO11yService).Increment at 0xa57d80
// (*DiscardO11yService).LogHandler at 0xa57dc0
// (*DiscardO11yService).RecordGauge at 0xa57f60
// (*DiscardO11yService).Shutdown at 0xa57fa0
