apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea-servicemonitor
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  path: ./cluster/k8s/gitea/servicemonitor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: gitea
    - name: monitoring-stack
