load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "manager",
    srcs = [
        "manager.go",
        "mcp.go",
        "tunnel_register.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/manager",
    visibility = ["//devinfra/claude/web_env/re/environment_manager/a6f96673/src:__subpackages__"],
    deps = [
        "//devinfra/claude/web_env/re/environment_manager/a6f96673/src/internal/config",
        "//devinfra/claude/web_env/re/environment_manager/a6f96673/src/internal/envtype",
        "//devinfra/claude/web_env/re/environment_manager/a6f96673/src/internal/mcp",
        "//devinfra/claude/web_env/re/environment_manager/a6f96673/src/internal/o11y",
        "//devinfra/claude/web_env/re/environment_manager/a6f96673/src/internal/o11y/diag",
        "//devinfra/claude/web_env/re/environment_manager/a6f96673/src/internal/tunnel/actions",
        "//devinfra/claude/web_env/re/environment_manager/a6f96673/src/internal/tunnel/actions/deploy",
    ],
)
