load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

exports_files(
    ["main.tf"],
    visibility = ["//cluster/k8s/haku/dispatch/litellm:__pkg__"],
)

tf_providers_versions(
    name = "providers",
    providers = {
        "kubernetes": "hashicorp/kubernetes:~>2.35",
        "litellm": "ncecere/litellm:~>2.0",
        "random": "hashicorp/random:~>3.7.0",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "litellm-keys",
    providers = [
        "kubernetes",
        "litellm",
        "random",
    ],
    providers_versions = ":providers",
)
