import CodeMirror from "@uiw/react-codemirror";
import { type Extension, type Range } from "@codemirror/state";
import { Decoration, EditorView, highlightSpecialChars, WidgetType } from "@codemirror/view";
import hljs from "highlight.js/lib/core";
import bash from "highlight.js/lib/languages/bash";
import go from "highlight.js/lib/languages/go";
import javascript from "highlight.js/lib/languages/javascript";
import json from "highlight.js/lib/languages/json";
import nix from "highlight.js/lib/languages/nix";
import protobuf from "highlight.js/lib/languages/protobuf";
import python from "highlight.js/lib/languages/python";
import rust from "highlight.js/lib/languages/rust";
import typescript from "highlight.js/lib/languages/typescript";
import yaml from "highlight.js/lib/languages/yaml";
import { type JSX, useCallback, useEffect, useMemo, useRef, useState } from "react";

import "./code_block.css";

// Keep syntax highlighting curated: highlight.js's default entry point registers every language it
// ships, which is most of a megabyte. This list covers the code the agent commonly emits.
hljs.registerLanguage("bash", bash);
hljs.registerLanguage("go", go);
hljs.registerLanguage("javascript", javascript);
hljs.registerLanguage("json", json);
hljs.registerLanguage("nix", nix);
hljs.registerLanguage("protobuf", protobuf);
hljs.registerLanguage("python", python);
hljs.registerLanguage("rust", rust);
hljs.registerLanguage("typescript", typescript);
hljs.registerLanguage("yaml", yaml);

export type Language =
  "bash" | "go" | "javascript" | "json" | "nix" | "protobuf" | "python" | "rust" | "typescript" | "yaml";

const REGISTERED_LANGUAGES: ReadonlySet<string> = new Set<Language>([
  "bash",
  "go",
  "javascript",
  "json",
  "nix",
  "protobuf",
  "python",
  "rust",
  "typescript",
  "yaml",
]);

/** Whether `language` names one of the grammars this widget can highlight. */
export function isRegisteredLanguage(language: string): language is Language {
  return REGISTERED_LANGUAGES.has(language);
}

// Render Unicode bidi controls, default-ignorable code points (including zero-width characters),
// and C0/C1 controls as widgets. Newlines and tabs remain normal layout characters. The document
// itself is never rewritten, so copying from the read-only editor retains the original value.
export const VISIBLE_SPECIAL_CHARS =
  /[\p{Bidi_Control}\p{Default_Ignorable_Code_Point}\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F\u2028\u2029\uFFF9-\uFFFC]/gu;
const BIDI_CONTROLS = /\p{Bidi_Control}/u;
const CONTROL_NAMES = new Map<number, string>([
  [0x0000, "NUL"],
  [0x0001, "SOH"],
  [0x0002, "STX"],
  [0x0003, "ETX"],
  [0x0004, "EOT"],
  [0x0005, "ENQ"],
  [0x0006, "ACK"],
  [0x0007, "BEL"],
  [0x0008, "BS"],
  [0x000b, "VT"],
  [0x000c, "FF"],
  [0x000e, "SO"],
  [0x000f, "SI"],
  [0x0010, "DLE"],
  [0x0011, "DC1"],
  [0x0012, "DC2"],
  [0x0013, "DC3"],
  [0x0014, "DC4"],
  [0x0015, "NAK"],
  [0x0016, "SYN"],
  [0x0017, "ETB"],
  [0x0018, "CAN"],
  [0x0019, "EM"],
  [0x001a, "SUB"],
  [0x001b, "ESC"],
  [0x001c, "FS"],
  [0x001d, "GS"],
  [0x001e, "RS"],
  [0x001f, "US"],
  [0x007f, "DEL"],
  [0x00ad, "SHY"],
  [0x061c, "ALM"],
  [0x200b, "ZWSP"],
  [0x200c, "ZWNJ"],
  [0x200d, "ZWJ"],
  [0x200e, "LRM"],
  [0x200f, "RLM"],
  [0x202a, "LRE"],
  [0x202b, "RLE"],
  [0x202c, "PDF"],
  [0x202d, "LRO"],
  [0x202e, "RLO"],
  [0x2060, "WJ"],
  [0x2066, "LRI"],
  [0x2067, "RLI"],
  [0x2068, "FSI"],
  [0x2069, "PDI"],
  [0xfeff, "BOM"],
]);

function codePointLabel(code: number): string {
  return CONTROL_NAMES.get(code) ?? `U+${code.toString(16).toUpperCase().padStart(4, "0")}`;
}

export function renderSpecialChar(code: number, description: string | null, _placeholder: string): HTMLElement {
  const codePoint = `U+${code.toString(16).toUpperCase().padStart(4, "0")}`;
  const isBidi = BIDI_CONTROLS.test(String.fromCodePoint(code));
  const isControl = code <= 0x001f || (code >= 0x007f && code <= 0x009f);
  const kind = isBidi
    ? "bidirectional control"
    : isControl
      ? "control character"
      : code === 0x2028
        ? "line separator"
        : code === 0x2029
          ? "paragraph separator"
          : "default-ignorable character";
  const label = codePointLabel(code);
  const marker = document.createElement("span");
  marker.className = `cm-agentplane-special-char ${isBidi ? "cm-agentplane-special-char-bidi" : isControl ? "cm-agentplane-special-char-control" : "cm-agentplane-special-char-ignorable"}`;
  marker.setAttribute("aria-label", `${kind}: ${description ?? label}, ${codePoint}`);
  marker.title = `${kind}: ${label} (${codePoint})`;
  marker.textContent = `⟦${label}⟧`;
  return marker;
}

/** Token HTML generated by highlight.js. Its grammars escape source text, and this markup is only
 * parsed in a detached container so we can map token classes to CodeMirror decoration ranges. The
 * HTML itself is never inserted into the live document. */
export function highlightedMarkup(text: string, language: Language): string {
  return hljs.highlight(text, { language }).value;
}

function syntaxDecorations(text: string, language: Language): Extension {
  const container = document.createElement("div");
  container.innerHTML = highlightedMarkup(text, language);

  const ranges: Range<Decoration>[] = [];
  let position = 0;
  const visit = (node: Node, inheritedTokens: readonly string[]): void => {
    if (node.nodeType === Node.TEXT_NODE) {
      const value = node.textContent ?? "";
      const to = position + value.length;
      if (value.length > 0 && inheritedTokens.length > 0) {
        ranges.push(Decoration.mark({ class: inheritedTokens.join(" ") }).range(position, to));
      }
      position = to;
      return;
    }
    if (node instanceof Element) {
      const tokens = [...inheritedTokens, ...Array.from(node.classList).filter((name) => /^hljs-[\w-]+$/.test(name))];
      for (const child of node.childNodes) visit(child, tokens);
    }
  };
  for (const child of container.childNodes) visit(child, []);

  // Some DOM implementations normalize parser fragments differently. Never apply misaligned
  // ranges to a different character than the grammar tokenized.
  if (position !== text.length || ranges.length === 0) return [];
  return EditorView.decorations.of(Decoration.set(ranges, true));
}

class StreamingCursor extends WidgetType {
  eq(other: WidgetType): boolean {
    return other === this;
  }
  toDOM(): HTMLElement {
    const cursor = document.createElement("span");
    cursor.className = "agentplane-streaming-cursor";
    cursor.setAttribute("role", "img");
    cursor.setAttribute("aria-label", "Streaming");
    cursor.setAttribute("data-character", "|");
    return cursor;
  }
}

const STREAMING_CURSOR_WIDGET = new StreamingCursor();

function streamingCursorDecoration(offset: number): Extension {
  return EditorView.decorations.of(
    Decoration.set([Decoration.widget({ widget: STREAMING_CURSOR_WIDGET, side: 1 }).range(offset)])
  );
}

const CODE_THEME = EditorView.theme({
  "&": {
    backgroundColor: "var(--mantine-color-body)",
    border: "1px solid var(--mantine-color-default-border)",
    borderRadius: "var(--mantine-radius-sm)",
    color: "var(--mantine-color-text)",
    fontSize: "var(--mantine-font-size-sm)",
  },
  ".cm-content": {
    fontFamily: "var(--mantine-font-family-monospace)",
    padding: "var(--mantine-spacing-xs)",
  },
  ".cm-scroller": { fontFamily: "inherit" },
  "&.cm-focused": { outline: "none" },
});

const LABEL_CODE_THEME = EditorView.theme({
  "&": {
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "0",
    color: "var(--mantine-color-text)",
    fontSize: "var(--mantine-font-size-sm)",
    fontWeight: "600",
  },
  ".cm-content": {
    fontFamily: "var(--mantine-font-family-monospace)",
    padding: 0,
  },
  ".cm-scroller": { fontFamily: "inherit" },
  "&.cm-focused": { outline: "none" },
});

const MUTED_CODE_THEME = EditorView.theme({
  "&": {
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "0",
    color: "var(--mantine-color-dimmed)",
    fontSize: "var(--mantine-font-size-xs)",
  },
  ".cm-content": {
    fontFamily: "var(--mantine-font-family-monospace)",
    padding: 0,
  },
  ".cm-scroller": { fontFamily: "inherit" },
  "&.cm-focused": { outline: "none" },
});

const MOUNT_MARGIN_PX = 600;
const PLACEHOLDER_LINE_REM = 1.25;

function useNearViewport(): { ref: (node: HTMLDivElement | null) => void; near: boolean } {
  const [near, setNear] = useState(typeof IntersectionObserver === "undefined");
  const observerRef = useRef<IntersectionObserver | null>(null);
  useEffect(() => () => observerRef.current?.disconnect(), []);
  const ref = useCallback(
    (node: HTMLDivElement | null) => {
      observerRef.current?.disconnect();
      observerRef.current = null;
      if (!node || near) return;
      const observer = new IntersectionObserver(
        (entries) => {
          if (!entries.some((entry) => entry.isIntersecting)) return;
          observer.disconnect();
          setNear(true);
        },
        { rootMargin: `${MOUNT_MARGIN_PX}px` }
      );
      observer.observe(node);
      observerRef.current = observer;
    },
    [near]
  );
  return { ref, near };
}

function MountedCodeBlock({
  text,
  language,
  streamingCursorOffset,
  presentation,
}: {
  text: string;
  language?: Language;
  streamingCursorOffset?: number;
  presentation: "block" | "label" | "muted";
}): JSX.Element {
  const extensions = useMemo(() => {
    const result = [
      EditorView.lineWrapping,
      highlightSpecialChars({ specialChars: VISIBLE_SPECIAL_CHARS, render: renderSpecialChar }),
      presentation === "label" ? LABEL_CODE_THEME : presentation === "muted" ? MUTED_CODE_THEME : CODE_THEME,
    ];
    if (language) result.push(syntaxDecorations(text, language));
    if (streamingCursorOffset !== undefined) result.push(streamingCursorDecoration(streamingCursorOffset));
    return result;
  }, [text, language, streamingCursorOffset, presentation]);

  return (
    <CodeMirror
      className={`agentplane-code-block agentplane-code-block-${presentation}`}
      value={text}
      theme="none"
      readOnly
      editable={false}
      extensions={extensions}
      basicSetup={false}
    />
  );
}

/** Read-only code and text viewer for Agentplane payloads. Syntax tokens, hidden Unicode markers,
 * and copy all share the same original document. Editor views mount near the viewport because
 * transcript history can contain many code-bearing rows. */
export function CodeBlock({
  text,
  language,
  streamingCursorOffset,
  presentation = "block",
}: {
  text: string;
  language?: Language;
  streamingCursorOffset?: number;
  presentation?: "block" | "label" | "muted";
}): JSX.Element {
  const { ref, near } = useNearViewport();
  if (!near) {
    const lineCount = Math.max(1, text.split("\n").length);
    return (
      <div
        ref={ref}
        className={`agentplane-code-block-placeholder${presentation !== "block" ? ` agentplane-code-block-placeholder-${presentation}` : ""}`}
        style={{ height: `${lineCount * PLACEHOLDER_LINE_REM}rem` }}
      />
    );
  }
  return (
    <MountedCodeBlock
      text={text}
      language={language}
      streamingCursorOffset={streamingCursorOffset}
      presentation={presentation}
    />
  );
}
