apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cluster-gateway
  namespace: gateway-system
  annotations:
    cert-manager.io/cluster-issuer: "${LETSENCRYPT_ISSUER}"
spec:
  gatewayClassName: cilium
  listeners:
    - name: https-wildcard
      hostname: "*.allegedly.works"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-allegedly-works-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: https-apex
      hostname: "allegedly.works"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: apex-allegedly-works-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: kube-api-passthrough
      hostname: "api.allegedly.works"
      port: 443
      protocol: TLS
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
