load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "anthropic",
    srcs = [
        "anthropic.go",
        "config.go",
        "skill_content.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/envtype/anthropic",
    visibility = ["//devinfra/claude/web_env/re/environment_manager/64bc4dc1/src:__subpackages__"],
    deps = [
        "//devinfra/claude/web_env/re/environment_manager/64bc4dc1/src/internal/config",
        "//devinfra/claude/web_env/re/environment_manager/64bc4dc1/src/internal/envtype",
        "//devinfra/claude/web_env/re/environment_manager/64bc4dc1/src/internal/envtype/anthropic/install_scripts",
        "//devinfra/claude/web_env/re/environment_manager/64bc4dc1/src/internal/o11y",
        "//devinfra/claude/web_env/re/environment_manager/64bc4dc1/src/internal/process",
    ],
)
