load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_library", "js_run_binary")

js_library(
    name = "hooks_zod",
    srcs = ["hooks.zod.js"],
    tags = ["no-lint"],
)

js_binary(
    name = "export_json_schema_bin",
    data = [
        ":hooks_zod",
        "//:node_modules",
    ],
    entry_point = "export_json_schema.mjs",
    tags = ["no-lint"],
)

js_run_binary(
    name = "hook_schemas",
    outs = [
        "hook_input.json",
        "hook_output.json",
    ],
    args = [
        "hookOutput=hook_output.json",
        "AnyHookInput=hook_input.json",
    ],
    chdir = package_name(),
    tool = ":export_json_schema_bin",
    visibility = ["//devinfra/claude:__subpackages__"],
)
