"""Shared git-repo test fixtures for devinfra/gc's test suite."""

from __future__ import annotations

import hashlib
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path

import pygit2
import pytest

_SIGNATURE = pygit2.Signature("t", "t@t")


@dataclass(frozen=True, slots=True)
class GitRepo:
    """A throwaway git working tree for tests — a main checkout, or one of its worktrees.

    Setup goes through pygit2 (already a production dependency) rather than shelling out to
    `git`, except where pygit2 has no direct equivalent (cherry-pick, a detached checkout) —
    `run` is the escape hatch for those.
    """

    path: Path

    def _pygit2(self) -> pygit2.Repository:
        return pygit2.Repository(str(self.path))

    def run(self, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(["git", "-C", str(self.path), *args], check=True, capture_output=True, text=True)

    def commit(self, name: str, content: str, message: str) -> None:
        (self.path / name).write_text(content)
        pg = self._pygit2()
        index = pg.index
        index.add(name)
        index.write()
        tree = index.write_tree()
        parents = [] if pg.head_is_unborn else [pg.head.target]
        pg.create_commit("HEAD", _SIGNATURE, _SIGNATURE, message, tree, parents)

    def rev(self, ref: str) -> str:
        return str(self._pygit2().revparse_single(ref).id)

    def branch(self, name: str, start: str = "main") -> None:
        pg = self._pygit2()
        pg.branches.local.create(name, pg.revparse_single(start).peel(pygit2.Commit))

    def has_branch(self, name: str) -> bool:
        return self._pygit2().branches.local.get(name) is not None

    def worktree(self, name: str, branch: str, start: str = "main") -> GitRepo:
        pg = self._pygit2()
        target = pg.revparse_single(start).peel(pygit2.Commit)
        branch_ref = pg.branches.local.create(branch, target)
        path = self.path.parent / name
        pg.add_worktree(name, str(path), branch_ref)
        return GitRepo(path)

    def clone(self, name: str) -> GitRepo:
        """A real `git clone` of this repo: unlike `.worktree()`, an independent `.git` with
        its own `origin` remote-tracking state (`refs/remotes/origin/HEAD` included) — the
        shape a genuine foreign clone has in production. pygit2's `clone_repository` does not
        set up that remote-tracking state the way the `git` CLI does, so this is the `run`
        escape hatch, not a pygit2 call."""
        path = self.path.parent / name
        self.run("clone", "--quiet", str(self.path), str(path))
        return GitRepo(path)

    def set_origin(self, url: str) -> None:
        """Point `origin` at `url` — adds it if absent, otherwise repoints it."""
        pg = self._pygit2()
        try:
            pg.remotes["origin"]
        except KeyError:
            pg.remotes.create("origin", url)
        else:
            pg.remotes.set_url("origin", url)


@pytest.fixture
def repo(tmp_path: Path) -> GitRepo:
    """A one-commit repo on `main`, ready for worktrees/branches to build test scenarios on."""
    path = tmp_path / "repo"
    pygit2.init_repository(str(path), initial_head="main")
    git_repo = GitRepo(path)
    git_repo.commit("base", "0\n", "init")
    return git_repo


@pytest.fixture
def proc(tmp_path: Path) -> Path:
    """An empty /proc stand-in so no recorded pid ever looks live unless a test wires one."""
    root = tmp_path / "proc"
    root.mkdir()
    return root


@pytest.fixture
def mountinfo(tmp_path: Path) -> Path:
    """An empty mountinfo so no path ever looks like a mount point unless a test writes one."""
    path = tmp_path / "mountinfo"
    path.write_text("")
    return path


def _base_name(workspace: Path) -> str:
    return hashlib.md5(os.fsencode(workspace), usedforsecurity=False).hexdigest()


def make_base(root: Path, workspace: Path, *, name: str | None = None) -> Path:
    """A synthetic Bazel output base directory recording `workspace` the way a real one does."""
    base = root / (name or _base_name(workspace))
    (base / "server").mkdir(parents=True)
    (base / "lock").write_bytes(b"")
    (base / "README").write_bytes(b"WORKSPACE: " + os.fsencode(workspace) + b"\n\nGenerated by Bazel.\n")
    (base / "DO_NOT_BUILD_HERE").write_bytes(os.fsencode(workspace))
    (base / "server" / "cmdline").write_bytes(
        b"bazel(test)\0--output_base="
        + os.fsencode(base.resolve())
        + b"\0--workspace_directory="
        + os.fsencode(workspace)
    )
    return base
