import hashlib
import os
import subprocess
from pathlib import Path

import pytest
import pytest_bazel

from devinfra.gc import workspace_scan
from devinfra.gc.branch_gc import PrunableBranch, RetainedBranch
from devinfra.gc.output_base_gc import PrunableBase, RetainedBase
from devinfra.gc.worktree_gc import PrunableWorktree, RetainedWorktree


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True)


def _commit(path: Path, name: str, content: str, message: str) -> None:
    (path / name).write_text(content)
    _git(path, "add", "--", name)
    _git(path, "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", message)


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q", "-b", "main")
    _commit(repo, "base", "0\n", "init")
    return repo


@pytest.fixture
def proc(tmp_path: Path) -> Path:
    root = tmp_path / "proc"
    root.mkdir()
    return root


@pytest.fixture
def mountinfo(tmp_path: Path) -> Path:
    path = tmp_path / "mountinfo"
    path.write_text("")
    return path


def _add(repo: Path, name: str, branch: str) -> Path:
    path = repo.parent / name
    _git(repo, "worktree", "add", "-q", "-b", branch, str(path), "main")
    return path


def _scan(
    repo: Path, proc: Path, mountinfo: Path, output_user_root: Path | None = None
) -> workspace_scan.WorkspaceScan:
    return workspace_scan.scan_workspace(
        repo,
        main="main",
        default_branch="main",
        pr_states={},
        output_user_root=output_user_root,
        proc_root=proc,
        mountinfo_path=mountinfo,
    )


def test_branch_follows_its_holding_worktree(repo: Path, proc: Path, mountinfo: Path) -> None:
    prunable_wt = _add(repo, "wt_merged", "merged")  # empty branch → prunable worktree
    kept_wt = _add(repo, "wt_kept", "kept")
    (kept_wt / "scratch").write_text("x\n")  # dirty → retained worktree

    scan = _scan(repo, proc, mountinfo)

    worktrees = {item.worktree.path: item for item in scan.worktrees}
    assert isinstance(worktrees[prunable_wt], PrunableWorktree)
    assert isinstance(worktrees[kept_wt], RetainedWorktree)

    branches = {item.branch.name: item for item in scan.branches}
    # Held by a prunable worktree → eligible, with the worktree recorded for apply ordering.
    assert isinstance(branches["merged"], PrunableBranch)
    assert branches["merged"].checkout == prunable_wt
    # Held by a retained worktree → not provably deletable.
    assert isinstance(branches["kept"], RetainedBranch)
    assert "retained worktree" in branches["kept"].reason
    # The default branch, checked out on the main worktree, is always kept.
    assert isinstance(branches["main"], RetainedBranch)
    assert branches["main"].reason == "default branch"


def _make_base(root: Path, workspace: Path) -> Path:
    base = root / hashlib.md5(os.fsencode(workspace), usedforsecurity=False).hexdigest()
    (base / "server").mkdir(parents=True)
    (base / "lock").write_bytes(b"")
    (base / "README").write_bytes(b"WORKSPACE: " + os.fsencode(workspace) + b"\n\nGenerated by Bazel.\n")
    (base / "DO_NOT_BUILD_HERE").write_bytes(os.fsencode(workspace))
    (base / "server" / "cmdline").write_bytes(
        b"bazel(test)\0--output_base="
        + os.fsencode(base.resolve())
        + b"\0--workspace_directory="
        + os.fsencode(workspace)
    )
    return base


def test_base_whose_workspace_is_a_prunable_worktree_is_annotated(
    repo: Path, proc: Path, mountinfo: Path, tmp_path: Path
) -> None:
    prunable_wt = _add(repo, "wt_merged", "merged")  # a prunable worktree, still on disk
    root = tmp_path / "output"
    _make_base(root, prunable_wt.resolve())  # its workspace is that worktree

    scan = _scan(repo, proc, mountinfo, output_user_root=root)

    (base,) = scan.bases
    # The workspace exists (the worktree is still there), so the base is retained for now …
    assert isinstance(base, RetainedBase)
    # … but flagged because pruning the worktree would orphan it.
    assert "prunable worktree" in base.reason


def test_base_with_absent_workspace_is_prunable(repo: Path, proc: Path, mountinfo: Path, tmp_path: Path) -> None:
    root = tmp_path / "output"
    _make_base(root, tmp_path / "gone")

    scan = _scan(repo, proc, mountinfo, output_user_root=root)

    assert [type(base) for base in scan.bases] == [PrunableBase]


if __name__ == "__main__":
    pytest_bazel.main()
