load("@aspect_rules_js//js:defs.bzl", "js_library", "js_test")
load("//devinfra/js:openapi.bzl", "js_openapi_schema", "js_openapi_zod")

package(default_visibility = ["//visibility:public"])

js_openapi_schema(
    name = "schema",
    generator = "//augur/app:export_schema_bin",
)

js_openapi_zod(
    name = "schema_zod",
    generator = "//augur/app:export_schema_bin",
)

js_library(
    name = "casing",
    srcs = ["casing.js"],
)

js_library(
    name = "columnar",
    srcs = ["columnar.js"],
)

js_library(
    name = "backend_client",
    srcs = ["backend_client.js"],
)

js_library(
    name = "scenario_set_state",
    srcs = ["scenario_set_state.js"],
    deps = [
        ":casing",
        ":schema",
    ],
)

js_test(
    name = "scenario_set_state_test",
    data = [
        ":_schema_openapi_json",
        ":scenario_set_state",
    ],
    entry_point = "scenario_set_state_test.mjs",
)
