# Shared JavaScript/TypeScript Bazel macros.

load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("//devinfra/python:defs.bzl", "py_binary")

js_binary(
    name = "strip_ts_types",
    data = ["//:node_modules/typescript"],
    entry_point = "strip_ts_types.mjs",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "spa_fingerprint",
    srcs = ["spa_fingerprint.py"],
    visibility = ["//visibility:public"],
)
