# Shared JavaScript/TypeScript Bazel macros.

load("@aspect_rules_js//js:defs.bzl", "js_binary")

js_binary(
    name = "strip_ts_types",
    data = ["//:node_modules/typescript"],
    entry_point = "strip_ts_types.mjs",
    visibility = ["//visibility:public"],
)

js_binary(
    name = "openapi_const_to_enum",
    entry_point = "openapi_const_to_enum.mjs",
    visibility = ["//visibility:public"],
)
