"""TypeScript message types from a `.proto`, generated by protobuf-es's `protoc-gen-es`.

The generator is protobuf-es's plugin from the npm lockfile, driven by the same grpcio-tools protoc
that generates the Python stubs (`//devinfra/python:grpc.bzl`), so both sides of a protocol come
from one file with no hand-written schema between them. The messages parse and serialize
proto-JSON (`fromJson`, `toJson`), the encoding the Python side's `json_format` speaks.
"""

load("@npm_ducktape//:@bufbuild/protoc-gen-es/package_json.bzl", protoc_gen_es_bin = "bin")
load("//devinfra/js:ts_library.bzl", "ts_library")

_PROTOC = "//devinfra/python:protoc"

def ts_proto_library(name, proto, tsconfig, visibility = None):
    """`<name>`: a `ts_library` of `<stem>_pb.ts` generated from `proto`, a `.proto` in any package.

    Consumers import `./<stem>_pb` from this package. The proto may import only the well-known
    types bundled with protoc: no other `.proto` is on its include path.

    Args:
      name: the library's name.
      proto: label of the `.proto` file.
      tsconfig: the package's shared `ts_config`, as for `ts_library`.
      visibility: visibility of the library.
    """
    stem = proto.split(":")[-1].split("/")[-1].removesuffix(".proto")
    plugin = "_" + name + "_protoc_gen_es"
    protoc_gen_es_bin.protoc_gen_es_binary(name = plugin)
    native.genrule(
        name = "_" + name + "_codegen",
        srcs = [proto],
        outs = [stem + "_pb.ts"],
        # BAZEL_BINDIR is how a rules_js binary finds its runfiles when a genrule runs it.
        cmd = " ".join([
            "BAZEL_BINDIR=$(BINDIR)",
            "$(execpath %s)" % _PROTOC,
            "-I$$(dirname $(execpath %s))" % proto,
            "--plugin=protoc-gen-es=$(execpath :%s)" % plugin,
            "--es_out=$(RULEDIR)",
            "--es_opt=target=ts",
            "$(execpath %s)" % proto,
        ]),
        tools = [_PROTOC, ":" + plugin],
    )
    ts_library(
        name = name,
        srcs = [":_" + name + "_codegen"],
        tsconfig = tsconfig,
        # Generated code, not ours to lint.
        tags = ["no-lint"],
        visibility = visibility,
        deps = ["//:node_modules/@bufbuild/protobuf"],
    )
