"""TypeScript message types from a `.proto`, generated by protobuf-es's `protoc-gen-es`.

The generator is protobuf-es's plugin from the npm lockfile, driven by the same grpcio-tools protoc
that generates the Python stubs (`//devinfra/python:grpc.bzl`), so both sides of a protocol come
from one file with no hand-written schema between them. The messages parse and serialize
proto-JSON (`fromJson`, `toJson`), the encoding the Python side's `json_format` speaks.
"""

load("@npm_ducktape//:@bufbuild/protoc-gen-es/package_json.bzl", protoc_gen_es_bin = "bin")
load("//devinfra/js:ts_library.bzl", "ts_library")

_PROTOC = "//devinfra/python:protoc"

def _source_path(proto):
    if proto.startswith("//"):
        package, filename = proto.removeprefix("//").split(":")
        return package + "/" + filename
    return proto

def ts_proto_library(name, proto, tsconfig, imports = [], visibility = None):
    """`<name>`: generated TypeScript protobuf modules from `proto` and its imports.

    Generated modules preserve project-relative paths below this package. `imports` are generated
    alongside `proto`, so imports in generated TypeScript resolve without a hand-written schema.

    Args:
      name: the library's name.
      proto: label of the `.proto` file.
      tsconfig: the package's shared `ts_config`, as for `ts_library`.
      imports: project-local `.proto` labels this proto imports, including transitive imports.
      visibility: visibility of the library.
    """
    protos = [proto] + imports
    plugin = "_" + name + "_protoc_gen_es"
    protoc_gen_es_bin.protoc_gen_es_binary(name = plugin)
    native.genrule(
        name = "_" + name + "_codegen",
        srcs = protos,
        outs = [_source_path(item).removesuffix(".proto") + "_pb.ts" for item in protos],
        # BAZEL_BINDIR is how a rules_js binary finds its runfiles when a genrule runs it.
        cmd = " ".join([
            "BAZEL_BINDIR=$(BINDIR)",
            "$(execpath %s)" % _PROTOC,
            "-I.",
            "--plugin=protoc-gen-es=$(execpath :%s)" % plugin,
            "--es_out=$(RULEDIR)",
            "--es_opt=target=ts",
        ] + ["$(execpath %s)" % item for item in protos]),
        tools = [_PROTOC, ":" + plugin],
    )
    ts_library(
        name = name,
        srcs = [":_" + name + "_codegen"],
        tsconfig = tsconfig,
        # Generated code, not ours to lint.
        tags = ["no-lint"],
        visibility = visibility,
        deps = ["//:node_modules/@bufbuild/protobuf"],
    )
