"""Macros: vitest_config, vitest_test, check_vitest_specs — vitest specs as ordinary test targets.

`vitest_test(name = "sidebar_test", srcs = ["sidebar.test.tsx"], deps = [...])` is the test, as a
`py_test` or `cc_test` is: `bbr test //pkg:sidebar_test` compiles the spec and runs it alone.

Specs reach vitest already compiled: the macro compiles `srcs` with a `testonly` `ts_library`
(<ts_library.bzl>, named `<name>_lib`), whose tsc action type-checks them and emits the `.js`
that vitest runs. Nothing is transformed at run time, so no package carries a `vitest.config.*`:
a package's one `vitest_config` generates it, and each `vitest_test` names that config.

A spec file that no `vitest_test` compiles never runs, and nothing downstream notices.
`check_vitest_specs()`, called at the end of a BUILD file, fails the load for a `*.test.ts[x]`
in the package that no `vitest_test` in it lists in `srcs`. `glob` stops at package boundaries,
so each package holding specs calls it; nothing checks that one that does not has no specs.
"""

load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@npm_ducktape//:vitest/package_json.bzl", vitest_bin = "bin")
load(":ts_library.bzl", "ts_library")

_SPEC_GLOBS = ["**/*.test.ts", "**/*.test.tsx"]

# Marks the `ts_library` a `vitest_test` compiles its specs with, for `check_vitest_specs`.
_SPEC_TAG = "vitest-spec"

# Each environment's implementation package, which vitest imports by name at run time.
_ENVIRONMENT_PACKAGES = {
    "happy-dom": ["//:node_modules/happy-dom"],
    "jsdom": ["//:node_modules/jsdom"],
    "node": [],
}

def vitest_config(name, environment, setup_files = [], data = []):
    """The vitest config shared by a package's specs, generated, and what running them needs.

    Args:
        name: Target the package's `vitest_test`s name in `config`, and those of its
            subpackages by label. The generated file is `<name>.mjs`.
        environment: vitest's `environment` for every spec without an `// @vitest-environment`
            pragma: `node`, `happy-dom` or `jsdom`. Required: whether a package's specs get a DOM
            is its own decision, and a default would be wrong for most of them. A spec's pragma
            may name another one, whose package must then be in `data`.
        setup_files: Files, relative to the package, vitest runs before each spec file.
        data: Further runtime files, such as the packages pragmas select.
    """
    if environment not in _ENVIRONMENT_PACKAGES:
        fail("%s: environment must be one of %s, got %r" % (name, sorted(_ENVIRONMENT_PACKAGES), environment))

    test = {"environment": environment, "include": ["**/*.test.js"]}
    if setup_files:
        test["setupFiles"] = ["./" + setup_file for setup_file in setup_files]
    write_file(
        name = name + "_file",
        out = name + ".mjs",
        content = [
            "// Generated by vitest_config (//devinfra/js:vitest.bzl).",
            "export default " + json.encode_indent({"cacheDir": ".vitest-cache", "test": test}, indent = "  ") + ";",
        ],
        testonly = True,
        visibility = ["//visibility:private"],
    )
    js_library(
        name = name,
        testonly = True,
        srcs = [":" + name + "_file"] + setup_files,
        deps = ["//:node_modules/vitest"] + _ENVIRONMENT_PACKAGES[environment] + data,
        visibility = ["//%s:__subpackages__" % native.package_name()],
    )

def _split_label(label):
    if label.startswith("//"):
        package, _, name = label.removeprefix("//").partition(":")
        return package, name
    return native.package_name(), label.removeprefix(":")

def _compiled(spec):
    if not (spec.endswith(".test.ts") or spec.endswith(".test.tsx")):
        fail("%s is not a spec: a `vitest_test` compiles `*.test.ts` and `*.test.tsx` files" % spec)
    return spec.rsplit(".test.", 1)[0] + ".test.js"

def vitest_test(name, srcs, config, tsconfig, deps = [], isolated_typecheck = False, **kwargs):
    """Compiles spec files and runs them under vitest, alone.

    Args:
        name: The test target.
        srcs: The spec files, `*.test.ts` or `*.test.tsx`.
        config: The `vitest_config` of this package or of an ancestor package, as a label.
        tsconfig: The shared `ts_config`, as for `ts_library`.
        deps: What the specs import, as for `ts_library`. Vitest itself, and the packages the
            environment needs, come from `config`.
        isolated_typecheck: As for `ts_library`.
        **kwargs: Passed to the test, e.g. `size`, `timeout`, `tags`, `env`.
    """
    package = native.package_name()
    config_package, config_name = _split_label(config)
    if package != config_package and not package.startswith(config_package + "/"):
        fail("//%s:%s: config %s is not in this package or an ancestor of it" % (package, name, config))
    path_prefix = package.removeprefix(config_package).removeprefix("/")
    if path_prefix:
        path_prefix += "/"

    ts_library(
        name = name + "_lib",
        testonly = True,
        srcs = srcs,
        tsconfig = tsconfig,
        deps = deps,
        isolated_typecheck = isolated_typecheck,
        tags = [_SPEC_TAG],
    )
    vitest_bin.vitest_test(
        name = name,
        args = ["run", "--config", config_name + ".mjs"] + [path_prefix + _compiled(spec) for spec in srcs],
        chdir = config_package,
        data = [config, ":" + name + "_lib"],
        **kwargs
    )

def check_vitest_specs():
    """Fails the package's load for a spec file that no `vitest_test` in it compiles."""
    listed = {}
    for rule in native.existing_rules().values():
        if _SPEC_TAG in rule.get("tags", []):
            for src in rule.get("srcs", []):
                listed[src.rpartition(":")[2]] = True
    for spec in native.glob(_SPEC_GLOBS, allow_empty = True):
        if spec not in listed:
            fail("//%s: spec file %s is in no `vitest_test`; add one listing it in `srcs`" % (native.package_name(), spec))
