load("@aspect_rules_js//js:defs.bzl", "js_library", "js_test")

_BABEL_DEPS = [
    "//:node_modules/@babel/generator",
    "//:node_modules/@babel/parser",
    "//:node_modules/@babel/traverse",
    "//:node_modules/@babel/types",
]

js_library(
    name = "libs",
    srcs = [
        "atomic_modules.mjs",
        "decl_graph.mjs",
        "init_region.mjs",
        "logical_modules.mjs",
        "materialize_logical_modules.mjs",
        "merge.mjs",
        "planner.mjs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//devinfra/js/debundle/analysis:libs",
        "//devinfra/js/debundle/common:libs",
        "//devinfra/js/debundle/split:libs",
    ] + _BABEL_DEPS,
)

js_test(
    name = "decl_graph_test",
    data = [
        "decl_graph.mjs",
        "init_region.mjs",
        "planner.mjs",
        "//devinfra/js/debundle/analysis:libs",
        "//devinfra/js/debundle/common:sources",
        "//devinfra/js/debundle/split:libs",
        "//devinfra/js/debundle/test_support:sources",
    ] + _BABEL_DEPS,
    entry_point = "decl_graph_test.mjs",
)

js_test(
    name = "extraction_test",
    data = [
        "decl_graph.mjs",
        "logical_modules.mjs",
        "planner.mjs",
        "//devinfra/js/debundle/analysis:libs",
        "//devinfra/js/debundle/common:sources",
    ] + _BABEL_DEPS,
    entry_point = "extraction_test.mjs",
)
