use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use anyhow::Result;

use crate::plan::PlanSummaryV2;

#[allow(dead_code)]
pub fn emit_rewritten_modules(out_root: &Path, plan: &PlanSummaryV2) -> Result<()> {
    let rewrite_root = out_root.join("rewrite");
    fs::create_dir_all(&rewrite_root)?;

    for (index, group) in plan.extraction_groups.iter().enumerate() {
        let mut body = String::from("// generated by debundle_rust emitter_v2\n");
        for module in group {
            let _ = writeln!(&mut body, "import \"../{module}\";");
        }
        let _ = writeln!(&mut body, "export const __group_index = {index};");
        fs::write(rewrite_root.join(format!("group_{index:03}.js")), body)?;
    }
    Ok(())
}
