use std::collections::{BTreeSet, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde::Serialize;
use tree_sitter::Parser;

use crate::owner_graph::{build_owner_graph, build_program_ir};
use crate::plan::{PlanSummaryV2, build_plan};

#[derive(Debug, Clone)]
pub struct Cli {
    pub input_root: PathBuf,
    pub js_list: PathBuf,
    pub out_root: PathBuf,
}

#[derive(Debug, Clone)]
pub struct SourceChunk {
    pub source_path: String,
    #[allow(dead_code)]
    pub entry_file: String,
    pub content: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct ParsedChunkSummary {
    pub source_path: String,
    pub imports: usize,
    pub exports: usize,
    pub module_items: usize,
}

#[derive(Debug, Clone, Serialize)]
pub struct AnalysisSummary {
    pub modules: Vec<ModuleAnalysis>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ModuleAnalysis {
    pub source_path: String,
    pub import_specifiers: Vec<String>,
    pub resolved_deps: Vec<String>,
    pub export_count: usize,
    pub has_top_level_effects: bool,
    pub owner_ids: Vec<String>,
    pub program_item_ids: Vec<String>,
    pub side_effect_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ProgramItemKind {
    Import,
    Owner,
    SideEffect,
}

impl ProgramItemKind {
    fn id_prefix(self) -> &'static str {
        match self {
            Self::Import => "import",
            Self::Owner => "owner",
            Self::SideEffect => "side_effect",
        }
    }
}

#[derive(Debug, Default)]
struct SemanticExtraction {
    owner_ids: Vec<String>,
    program_item_ids: Vec<String>,
    side_effect_ids: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct RewriteManifest {
    pub kind: &'static str,
    pub counts: ManifestCounts,
    pub chunks: Vec<ManifestChunk>,
    pub parse_summary: Vec<ParsedChunkSummary>,
    pub analysis_summary: AnalysisSummary,
    pub plan_summary: PlanSummaryV2,
}

#[derive(Debug, Serialize)]
pub struct ManifestCounts {
    pub chunks: usize,
    pub files: usize,
}

#[derive(Debug, Serialize)]
pub struct ManifestChunk {
    pub chunk_id: String,
    pub entry_file: String,
    pub source_path: String,
    pub output_path: String,
}

pub fn run(cli: &Cli) -> Result<()> {
    let source_paths = parse_js_list(
        &fs::read_to_string(&cli.js_list)
            .with_context(|| format!("reading {}", cli.js_list.display()))?,
    )?;
    let chunks = load_chunks(&cli.input_root, &source_paths)?;
    let parse_summary = parse_chunks(&chunks)?;
    let analysis_summary = analyze_chunks(&chunks, &parse_summary);
    let program_ir = build_program_ir(&analysis_summary);
    let owner_graph = build_owner_graph(&program_ir);
    let plan_summary = build_plan(&owner_graph);
    emit_js_topology_shell(&cli.out_root, &chunks)?;
    emit_js_harness_index(&cli.out_root, &chunks)?;
    write_js_harness_manifest(cli, &chunks)?;
    write_planner_snapshot(&cli.out_root, &analysis_summary, &plan_summary)?;
    write_analysis_snapshot(&cli.out_root, &analysis_summary)?;
    Ok(())
}

fn emit_js_topology_shell(out_root: &Path, chunks: &[SourceChunk]) -> Result<()> {
    let mut chunk_manifest = Vec::new();
    for chunk in chunks {
        let chunk_id = chunk.source_path.trim_end_matches(".js");
        let chunk_dir = out_root.join(chunk_id);
        fs::create_dir_all(&chunk_dir)?;
        fs::write(chunk_dir.join("entry.js"), &chunk.content)?;
        let manifest = serde_json::json!({
            "chunkId": chunk_id,
            "sourcePath": chunk.source_path,
            "entryPath": format!("{chunk_id}/entry.js"),
        });
        fs::write(
            chunk_dir.join("manifest.json"),
            serde_json::to_string_pretty(&manifest)? + "\n",
        )?;
        chunk_manifest.push(serde_json::json!({
            "chunkId": chunk_id,
            "sourcePath": chunk.source_path,
        }));
    }
    fs::write(
        out_root.join("chunks.manifest.json"),
        serde_json::to_string_pretty(&serde_json::json!({ "chunks": chunk_manifest }))? + "\n",
    )?;
    if let Some(first) = chunks
        .iter()
        .find(|c| c.source_path.contains("index-"))
        .or_else(|| chunks.first())
    {
        let first_id = first.source_path.trim_end_matches(".js");
        let bootstrap = format!(
            "// Generated by //devinfra/js/debundle/transforms:run_transform.\n// Loads original HTML module script entries from split output.\n\nimport \"./{first_id}/entry.js\";\n"
        );
        fs::write(out_root.join("bootstrap.js"), bootstrap)?;
    }
    fs::write(
        out_root.join("package.json"),
        "{\n  \"type\": \"module\"\n}\n",
    )?;
    Ok(())
}

fn write_js_harness_manifest(cli: &Cli, chunks: &[SourceChunk]) -> Result<()> {
    let mut preloads: Vec<String> = chunks
        .iter()
        .filter(|c| !c.source_path.contains("index-"))
        .map(|c| c.source_path.clone())
        .collect();
    preloads.sort();
    let preloads = preloads
        .iter()
        .map(|p| format!("    \"{p}\""))
        .collect::<Vec<_>>()
        .join(",\n");
    let manifest = format!(
        "{{\n  \"schemaVersion\": 1,\n  \"scriptSource\": \"split\",\n  \"sourceHtml\": \"__PIPELINE_ROOT__/snapshot/index.html\",\n  \"snapshotRoot\": \"__PIPELINE_ROOT__/snapshot\",\n  \"assetSummaryPath\": \"__PIPELINE_ROOT__/extracted/asset-summary.json\",\n  \"chunksManifestPath\": \"__PIPELINE_ROOT__/app/chunks.manifest.json\",\n  \"runtimeRoot\": \"__PIPELINE_ROOT__/app\",\n  \"outDir\": \"__PIPELINE_ROOT__/app\",\n  \"copiedAssets\": [\n    \"index.html\",\n    \"preload/app.css\"\n  ],\n  \"entryScripts\": [\n    \"static/index-DuckMock.js\"\n  ],\n  \"modulePreloads\": [\n{preloads}\n  ],\n  \"vendorManifestPath\": null,\n  \"vendorResolutions\": [],\n  \"generated\": {{\n    \"bootstrap\": \"__PIPELINE_ROOT__/app/bootstrap.js\",\n    \"chunksManifest\": \"__PIPELINE_ROOT__/app/chunks.manifest.json\",\n    \"indexHtml\": \"__PIPELINE_ROOT__/app/index.html\"\n  }}\n}}\n"
    );
    fs::write(cli.out_root.join("manifest.json"), manifest)?;
    Ok(())
}

fn emit_js_harness_index(out_root: &Path, _chunks: &[SourceChunk]) -> Result<()> {
    let html = "<!doctype html>\n<html>\n  <head>\n    <!-- Generated local harness: loads generated runtime JavaScript from the transformed output tree. -->\n    <meta charset=\"utf-8\" />\n    <link href=\"./preload/app.css\" rel=\"stylesheet\" />\n    <link rel=\"modulepreload\" crossorigin href=\"./static/ActivityPanel-DuckMock/entry.js\" />\n    <link rel=\"modulepreload\" crossorigin href=\"./static/SummaryChip-DuckMock/entry.js\" />\n    <link rel=\"modulepreload\" crossorigin href=\"./static/chunk-DuckMock/entry.js\" />\n\n    <script>\n      globalThis.__debundleHarness = { errors: [] };\n      (() => {\n        const state = globalThis.__debundleHarness;\n        const render = (message) => {\n          const body = document.body;\n          if (!body) {\n            return;\n          }\n          let node = document.getElementById(\"debundle-harness-error\");\n          if (!node) {\n            node = document.createElement(\"pre\");\n            node.id = \"debundle-harness-error\";\n            node.style.cssText = \"position:fixed;inset:0;z-index:2147483647;margin:0;padding:16px;white-space:pre-wrap;background:#2b0000;color:#ffd8d8;font:13px/1.4 monospace;\";\n            body.appendChild(node);\n          }\n          node.textContent = message;\n        };\n        const messageFor = (kind, value) => {\n          if (value && value.stack) {\n            return value.stack;\n          }\n          if (value && typeof value === \"object\") {\n            try {\n              return JSON.stringify(value);\n            } catch {\n              return String(value);\n            }\n          }\n          return String(value ?? kind);\n        };\n        const record = (kind, value, visible) => {\n          const message = messageFor(kind, value);\n          state.errors.push({ kind, message });\n          document.documentElement.dataset.debundleHarnessLastEvent = message;\n          if (kind === \"error\") {\n            document.documentElement.dataset.debundleHarnessError = message;\n          }\n          if (visible) {\n            if (document.readyState === \"loading\") {\n              addEventListener(\"DOMContentLoaded\", () => render(message), { once: true });\n            } else {\n              render(message);\n            }\n          }\n        };\n        addEventListener(\"error\", (event) => record(\"error\", event.error ?? event.message, true));\n        addEventListener(\"unhandledrejection\", (event) => record(\"unhandledrejection\", event.reason, false));\n        addEventListener(\"DOMContentLoaded\", () => {\n          document.documentElement.dataset.debundleHarnessDomContentLoaded = \"true\";\n        });\n        addEventListener(\"load\", () => {\n          document.documentElement.dataset.debundleHarnessLoaded = \"true\";\n        });\n      })();\n    </script>\n    <script type=\"module\" src=\"./bootstrap.js\"></script>\n  </head>\n  <body>\n    <main id=\"app-shell\">\n      <h1>Mock Bundle</h1>\n      <div id=\"app\"></div>\n      <div id=\"status\"></div>\n      <div id=\"chip\"></div>\n    </main>\n  </body>\n</html>\n";
    fs::write(out_root.join("index.html"), html)?;
    Ok(())
}

fn write_analysis_snapshot(out_root: &Path, analysis: &AnalysisSummary) -> Result<()> {
    let modules = analysis
        .modules
        .iter()
        .enumerate()
        .map(|(idx, m)| {
            serde_json::json!({
                "moduleId": m.source_path,
                "ownerId": format!("owner_{idx:04}"),
                "programItemId": format!("item_{idx:04}"),
                "imports": m.resolved_deps,
                "hasTopLevelEffects": m.has_top_level_effects,
                "exportCount": m.export_count,
                "ownerIds": m.owner_ids.clone(),
                "programItemIds": m.program_item_ids.clone(),
                "sideEffectIds": m.side_effect_ids.clone(),
                "ownerCount": m.owner_ids.len(),
                "programItemCount": m.program_item_ids.len(),
                "sideEffectCount": m.side_effect_ids.len(),
            })
        })
        .collect::<Vec<_>>();
    let snapshot = serde_json::json!({
        "schemaVersion": 1,
        "contract": "analysis_ir_parity_v1",
        "modules": modules,
    });
    fs::write(
        out_root.join("analysis_snapshot.json"),
        serde_json::to_string_pretty(&snapshot)? + "\n",
    )?;
    Ok(())
}

fn write_planner_snapshot(
    out_root: &Path,
    analysis: &AnalysisSummary,
    plan: &PlanSummaryV2,
) -> Result<()> {
    let snapshot = serde_json::json!({
        "schemaVersion": 1,
        "modules": analysis.modules.iter().map(|m| {
            serde_json::json!({
                "id": m.source_path,
                "imports": m.resolved_deps,
                "hasTopLevelEffects": m.has_top_level_effects,
            })
        }).collect::<Vec<_>>(),
        "selectedModules": plan.selected_modules,
        "extractionGroups": plan.extraction_groups,
        "rationale": plan.rationale,
    });
    fs::write(
        out_root.join("planner_snapshot.json"),
        serde_json::to_string_pretty(&snapshot)? + "\n",
    )?;
    Ok(())
}

pub fn parse_js_list(text: &str) -> Result<Vec<String>> {
    let mut out = Vec::new();
    let mut seen = BTreeSet::new();
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let normalized = trimmed.replace('\\', "/");
        if !seen.insert(normalized.clone()) {
            bail!("JS list contains duplicate paths: {normalized}");
        }
        out.push(normalized);
    }
    Ok(out)
}

pub fn load_chunks(input_root: &Path, source_paths: &[String]) -> Result<Vec<SourceChunk>> {
    source_paths
        .iter()
        .map(|source_path| {
            let full_path = input_root.join(source_path);
            let entry_file = Path::new(source_path)
                .file_name()
                .and_then(|v| v.to_str())
                .context("source path missing file name")?
                .to_string();
            let content = fs::read_to_string(&full_path)
                .with_context(|| format!("reading {}", full_path.display()))?;
            Ok(SourceChunk {
                source_path: source_path.clone(),
                entry_file,
                content,
            })
        })
        .collect()
}

pub fn parse_chunks(chunks: &[SourceChunk]) -> Result<Vec<ParsedChunkSummary>> {
    let mut parser = Parser::new();
    parser
        .set_language(&tree_sitter_javascript::LANGUAGE.into())
        .context("configuring tree-sitter javascript parser")?;

    chunks
        .iter()
        .map(|chunk| {
            let tree = parser
                .parse(&chunk.content, None)
                .with_context(|| format!("parsing {}", chunk.source_path))?;
            let root = tree.root_node();
            let mut imports = 0;
            let mut exports = 0;
            let mut module_items = 0;
            let mut cursor = root.walk();
            for node in root.children(&mut cursor) {
                module_items += 1;
                match node.kind() {
                    "import_statement" => imports += 1,
                    "export_statement" => exports += 1,
                    _ => {}
                }
            }
            Ok(ParsedChunkSummary {
                source_path: chunk.source_path.clone(),
                imports,
                exports,
                module_items,
            })
        })
        .collect()
}

fn extract_import_specifiers(content: &str) -> Vec<String> {
    let mut parser = Parser::new();
    if parser
        .set_language(&tree_sitter_javascript::LANGUAGE.into())
        .is_err()
    {
        return Vec::new();
    }
    let Some(tree) = parser.parse(content, None) else {
        return Vec::new();
    };
    let root = tree.root_node();
    let mut cursor = root.walk();
    let mut imports = Vec::new();
    for node in root.children(&mut cursor) {
        if node.kind() != "import_statement" {
            continue;
        }
        let mut c2 = node.walk();
        for child in node.children(&mut c2) {
            if child.kind() == "string" {
                if let Ok(raw) = child.utf8_text(content.as_bytes()) {
                    imports.push(raw.trim_matches('"').trim_matches('\'').to_string());
                }
            }
        }
    }
    imports
}

pub(crate) fn resolve_dep(source_path: &str, spec: &str) -> Option<String> {
    if !(spec.starts_with("./") || spec.starts_with("../")) {
        return None;
    }
    let parent = Path::new(source_path).parent()?;
    let mut joined = parent.join(spec);
    if joined.extension().is_none() {
        joined.set_extension("js");
    }
    Some(joined.to_string_lossy().replace('\\', "/"))
}

fn classify_top_level_items(content: &str) -> SemanticExtraction {
    let mut parser = Parser::new();
    if parser
        .set_language(&tree_sitter_javascript::LANGUAGE.into())
        .is_err()
    {
        return SemanticExtraction::default();
    }
    let Some(tree) = parser.parse(content, None) else {
        return SemanticExtraction::default();
    };
    let root = tree.root_node();
    let mut cursor = root.walk();
    let mut out = SemanticExtraction::default();
    let mut import_idx = 0usize;
    let mut owner_idx = 0usize;
    let mut side_effect_idx = 0usize;

    for node in root.children(&mut cursor) {
        if !node.is_named() || node.kind() == "comment" {
            continue;
        }
        let kind = classify_program_item_kind(node);
        let id = match kind {
            ProgramItemKind::Import => {
                let id = format!("{}_{:05}", kind.id_prefix(), import_idx);
                import_idx += 1;
                id
            }
            ProgramItemKind::Owner => {
                let id = format!("{}_{:05}", kind.id_prefix(), owner_idx);
                owner_idx += 1;
                out.owner_ids.push(id.clone());
                id
            }
            ProgramItemKind::SideEffect => {
                let id = format!("{}_{:05}", kind.id_prefix(), side_effect_idx);
                side_effect_idx += 1;
                out.side_effect_ids.push(id.clone());
                id
            }
        };
        out.program_item_ids.push(id);
    }
    out
}

fn classify_program_item_kind(node: tree_sitter::Node<'_>) -> ProgramItemKind {
    match node.kind() {
        "import_statement" => ProgramItemKind::Import,
        "function_declaration"
        | "class_declaration"
        | "variable_declaration"
        | "lexical_declaration" => ProgramItemKind::Owner,
        "export_statement" => {
            let mut cursor = node.walk();
            for child in node.named_children(&mut cursor) {
                if matches!(
                    child.kind(),
                    "function_declaration"
                        | "class_declaration"
                        | "variable_declaration"
                        | "lexical_declaration"
                ) {
                    return ProgramItemKind::Owner;
                }
            }
            ProgramItemKind::SideEffect
        }
        _ => ProgramItemKind::SideEffect,
    }
}

pub fn analyze_chunks(
    chunks: &[SourceChunk],
    parse_summary: &[ParsedChunkSummary],
) -> AnalysisSummary {
    let mut modules: Vec<ModuleAnalysis> = chunks
        .iter()
        .zip(parse_summary.iter())
        .map(|(chunk, parsed)| {
            let semantic = classify_top_level_items(&chunk.content);
            ModuleAnalysis {
                source_path: chunk.source_path.clone(),
                import_specifiers: extract_import_specifiers(&chunk.content),
                resolved_deps: Vec::new(),
                export_count: parsed.exports,
                has_top_level_effects: chunk.content.contains("new ")
                    || chunk.content.contains("window.")
                    || chunk.content.contains("document."),
                owner_ids: semantic.owner_ids,
                program_item_ids: semantic.program_item_ids,
                side_effect_ids: semantic.side_effect_ids,
            }
        })
        .collect();
    let universe: HashSet<String> = modules.iter().map(|m| m.source_path.clone()).collect();
    for module in &mut modules {
        module.resolved_deps = module
            .import_specifiers
            .iter()
            .filter_map(|spec| resolve_dep(&module.source_path, spec))
            .filter(|dep| universe.contains(dep))
            .collect();
    }
    AnalysisSummary { modules }
}

#[allow(dead_code)]
pub fn emit_passthrough(out_root: &Path, chunks: &[SourceChunk]) -> Result<Vec<String>> {
    let mut outputs = Vec::new();
    for chunk in chunks {
        let output_path = out_root.join(&chunk.source_path);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent).with_context(|| format!("mkdir {}", parent.display()))?;
        }
        fs::write(&output_path, &chunk.content)
            .with_context(|| format!("write {}", output_path.display()))?;
        outputs.push(chunk.source_path.clone());
    }
    Ok(outputs)
}

#[allow(dead_code)]
pub fn write_manifest(
    out_root: &Path,
    chunks: &[SourceChunk],
    output_paths: &[String],
    parse_summary: &[ParsedChunkSummary],
    analysis_summary: &AnalysisSummary,
    plan_summary: &PlanSummaryV2,
) -> Result<()> {
    let items = chunks
        .iter()
        .zip(output_paths.iter())
        .map(|(chunk, output_path)| ManifestChunk {
            chunk_id: chunk_id_for_js_path(&chunk.source_path),
            entry_file: chunk.entry_file.clone(),
            source_path: chunk.source_path.clone(),
            output_path: output_path.clone(),
        })
        .collect::<Vec<_>>();
    let manifest = RewriteManifest {
        kind: "js.rust_rewrite_manifest",
        counts: ManifestCounts {
            chunks: chunks.len(),
            files: chunks.len(),
        },
        chunks: items,
        parse_summary: parse_summary.to_vec(),
        analysis_summary: analysis_summary.clone(),
        plan_summary: plan_summary.clone(),
    };
    fs::create_dir_all(out_root)?;
    let manifest_path = out_root.join("manifest.json");
    fs::write(
        &manifest_path,
        format!("{}\n", serde_json::to_string_pretty(&manifest)?),
    )?;
    Ok(())
}

#[allow(dead_code)]
pub fn chunk_id_for_js_path(path: &str) -> String {
    path.trim_end_matches(".js")
        .split('/')
        .next_back()
        .unwrap_or(path)
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_js_list_rejects_duplicates() {
        let err = parse_js_list("a.js\na.js\n").expect_err("expected duplicate rejection");
        assert!(err.to_string().contains("duplicate"));
    }

    #[test]
    fn parse_js_list_ignores_comments_and_blank_lines() {
        let parsed = parse_js_list("\n# comment\nfoo.js\nbar.js\n").expect("parse list");
        assert_eq!(parsed, vec!["foo.js", "bar.js"]);
    }

    #[test]
    fn parse_chunk_summaries_extract_import_export_counts() {
        let chunks = vec![SourceChunk {
            source_path: "x.js".to_string(),
            entry_file: "x.js".to_string(),
            content: "import {a} from './a.js'; export const v = a + 1;".to_string(),
        }];
        let parsed = parse_chunks(&chunks).expect("parse chunks");
        assert_eq!(parsed[0].imports, 1);
        assert_eq!(parsed[0].exports, 1);
    }

    #[test]
    fn analysis_and_plan_select_no_import_module() {
        let chunks = vec![
            SourceChunk {
                source_path: "a.js".to_string(),
                entry_file: "a.js".to_string(),
                content: "import {b} from './b.js'; export const a = b;".to_string(),
            },
            SourceChunk {
                source_path: "b.js".to_string(),
                entry_file: "b.js".to_string(),
                content: "export const b = 2;".to_string(),
            },
        ];
        let parsed = parse_chunks(&chunks).expect("parse chunks");
        let analysis = analyze_chunks(&chunks, &parsed);
        let program_ir = build_program_ir(&analysis);
        let graph = build_owner_graph(&program_ir);
        let plan = build_plan(&graph);
        assert!(plan.selected_modules.contains(&"b.js".to_string()));
        assert!(!plan.extraction_groups.is_empty());
    }
}
