# gazelle:resolve py cnpg_cluster_crds //cluster/cdk8s/crd_bindings/cnpg:cluster
# gazelle:resolve py cnpg_database_crds //cluster/cdk8s/crd_bindings/cnpg:database
# gazelle:resolve py cnpg_scheduledbackup_crds //cluster/cdk8s/crd_bindings/cnpg:scheduledbackup
# gazelle:resolve py barman_cloud_objectstore_crds //cluster/cdk8s/crd_bindings/cnpg:objectstore

load("//devinfra/js:cdk8s_import.bzl", "cdk8s_import")

cdk8s_import(
    name = "cluster",
    crd = "@cnpg_cluster_crd//file",
    module_name = "cnpg_cluster_crds",
    module_path = "io/cnpg/postgresql",
    visibility = ["//visibility:public"],
)

cdk8s_import(
    name = "database",
    crd = "@cnpg_database_crd//file",
    module_name = "cnpg_database_crds",
    module_path = "io/cnpg/postgresql",
    visibility = ["//visibility:public"],
)

cdk8s_import(
    name = "scheduledbackup",
    crd = "@cnpg_scheduledbackup_crd//file",
    module_name = "cnpg_scheduledbackup_crds",
    module_path = "io/cnpg/postgresql",
    visibility = ["//visibility:public"],
)

cdk8s_import(
    name = "objectstore",
    crd = "@barman_cloud_objectstore_crd//file",
    module_name = "barman_cloud_objectstore_crds",
    module_path = "io/cnpg/barmancloud",
    visibility = ["//visibility:public"],
)
