fullnameOverride: sealed-secrets-controller

image:
  registry: docker.io
  repository: bitnami/sealed-secrets-controller
  tag: v0.24.5
  pullPolicy: IfNotPresent

resourcesPreset: none
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

podSecurityContext:
  enabled: true
  fsGroup: 65534
  fsGroupChangePolicy: Always
  supplementalGroups: []
  sysctls: []

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  seccompProfile:
    type: RuntimeDefault

serviceAccount:
  create: true
  name: sealed-secrets-controller
  automountServiceAccountToken: true

service:
  type: ClusterIP
  ports:
    http: 8080

metrics:
  enabled: true
  service:
    ports:
      metrics: 8081
