{
 "title": "GitHub API quotas",
 "tags": [
  "github",
  "quotas"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "GraphQL quota remaining",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * github_rate_remaining{resource=\"graphql\"} / on (github_account, resource) github_rate_limit_limit{resource=\"graphql\"}",
     "legendFormat": "{{github_account}}"
    }
   ]
  },
  {
   "title": "GraphQL quota history",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "github_rate_remaining{resource=\"graphql\"}",
     "legendFormat": "{{github_account}} remaining"
    },
    {
     "expr": "github_rate_limit_limit{resource=\"graphql\"}",
     "legendFormat": "{{github_account}} limit"
    }
   ]
  },
  {
   "title": "Remaining quota by API resource",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "github_rate_remaining",
     "legendFormat": "{{github_account}} / {{resource}}"
    }
   ]
  }
 ]
}