version: 1
metadata:
  name: User Management
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:
  # Personal admin user
  - model: authentik_core.user
    id: personal-user
    state: present
    identifiers:
      username: agentydragon
    attrs:
      username: agentydragon
      name: agentydragon
      email: agentydragon@gmail.com
      is_active: true
      groups:
        - !Find [authentik_core.group, [name, gitea-admins]]
        - !Find [authentik_core.group, [name, gitea-users]]
        - !Find [authentik_core.group, [name, rspcache-admins]]
