load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

tf_providers_versions(
    name = "providers",
    providers = {
        "kubernetes": "hashicorp/kubernetes:~>2.35",
        "random": "hashicorp/random:~>3.7.0",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "ollama-bearer-token",
    providers = [
        "kubernetes",
        "random",
    ],
    providers_versions = ":providers",
)
