apiVersion: v1
kind: Secret
metadata:
    name: llm-zai
    namespace: ducktape-flux
    annotations:
        ducktape.allegedly.works/credential-class: external-llm
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:1N4U7QAHJYoLtbHF/lrgeweU+jRc57EWA/nIdCUZMWxS/7l6M/xus964ot3ZgcCZZw==,iv:eiZrFDdvN9+iXmAWSnM3le3gg4nwRSg2pnztLn5CHLs=,tag:/JEuPTPRDAYV8sCWjaEPIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bjN6WThsQVg3SjI1bVZL
            VHdIcTZNZ1FLa2NPbEFGUklKem9DV3drSnl3CmtuWEYrRVdMdzllelVkYW1GcHR1
            WTRPVGhTUVpJYmJqSTk1b2FlbGFRcXcKLS0tIE1zOXdlMTZKU3c4b0VQV1BEVXNh
            UXhwVlFwY1g2RUlJeU1xdWpmc0FkT3cK9WyyS9SZ2MKDFkwECtcY3sXbgcYtTvt4
            bc8cpubvyZh6Yh9ERtsKH2fhq4nZAN/2bmCmcFIJzfV0zw4gNwl9CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMnZjR1dmZkdMNDNQL3V2
            YjJrd0NPN0RtWGtqQnpoR21EVVRheXpYMXhZClFwOFZCTCtXYTFDQnZMY1ozRUhZ
            VGc0NW82aW9PMDdzNEVMTDdQcXFDZVUKLS0tIGJadHFidFJjTXNRQ3d5dUJPbkdU
            RFhVQjhnd2pjeVFhUTl0RFFKblBvaFEKStL1HNEqCAI9Jb+uAkIckPe3vecoiAze
            +H2VRSR9UPSMI2rfRbmyB5W6TUImvye0/d2flNI+ID/XTA73N93+/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T22:54:57Z"
    mac: ENC[AES256_GCM,data:b8Ku4bGTRYbqFy2NBQTeCTmeAhjnVms1+d2MzmiX9++tnlw5xq+aXsHeuFukjcBxHmNjvxp5Pu+qqyOliEAbw/BEr6zA+AQohxZ35mGDFiHPs28S7Gl6drMF0wl9LAL3qk4Ech4pkanWKaDqGUPALJ3vf4fTVGOE7gqFbOWQEeg=,iv:sIsdk5e15lU2P8++KPI2U42qFQ069p+UKduvZ0DhtQc=,tag:f8HF4ufr59Q1FrQs9qlCbQ==,type:str]
    version: 3.13.3
