load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "kubespandctrl",
    srcs = [
        "config.go",
        "node_metadata.go",
        "os_root.go",
    ],
    importpath = "github.com/agentydragon/ducktape/cluster/kubespand/controllers/kubespand",
    visibility = ["//cluster/kubespand:__subpackages__"],
    deps = [
        "//cluster/kubespand/agentconfig",
        "@com_github_cosi_project_runtime//pkg/controller",
        "@com_github_cosi_project_runtime//pkg/resource",
        "@com_github_cosi_project_runtime//pkg/safe",
        "@com_github_cosi_project_runtime//pkg/state",
        "@com_github_siderolabs_crypto//x509",
        "@com_github_siderolabs_talos_pkg_machinery//config/machine",
        "@com_github_siderolabs_talos_pkg_machinery//nethelpers",
        "@com_github_siderolabs_talos_pkg_machinery//resources/cluster",
        "@com_github_siderolabs_talos_pkg_machinery//resources/config",
        "@com_github_siderolabs_talos_pkg_machinery//resources/k8s",
        "@com_github_siderolabs_talos_pkg_machinery//resources/kubespan",
        "@com_github_siderolabs_talos_pkg_machinery//resources/network",
        "@com_github_siderolabs_talos_pkg_machinery//resources/runtime",
        "@com_github_siderolabs_talos_pkg_machinery//resources/secrets",
        "@org_uber_go_zap//:zap",
    ],
)
