load("@rules_python//python:defs.bzl", "py_binary", "py_test")

py_binary(
    name = "find_orphans",
    srcs = ["find_orphans.py"],
    imports = ["../.."],
    visibility = ["//:__subpackages__"],
    deps = [
        "//bazel_util:query",
        "//bazel_util:workspace",
        "@pypi//pathspec",
        "@pypi//pygit2",
    ],
)

py_test(
    name = "test_find_orphans",
    srcs = ["test_find_orphans.py"],
    imports = ["../.."],
    deps = [
        ":find_orphans",
        "@pypi//pytest_bazel",
    ],
)
