load("//devinfra/python:defs.bzl", "py_library")

package(
    default_testonly = True,
    default_visibility = ["//x/agentplane/app:__pkg__"],
)

py_library(
    name = "kubernetes",
    srcs = ["kubernetes.py"],
    deps = [
        "//x/agentplane/app:egress",
        "//x/agentplane/app:inventory",
        "@pypi//kubernetes_asyncio",
    ],
)

py_library(
    name = "egress_proxy",
    srcs = ["egress_proxy.py"],
    deps = ["@pypi//httpx"],
)
