load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

tf_providers_versions(
    name = "providers",
    providers = {
        "authentik": "goauthentik/authentik:~>2026.2",
        "kubernetes": "hashicorp/kubernetes:~>2.35",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "alloy-otlp-bearer-token",
    providers = [
        "authentik",
        "kubernetes",
    ],
    providers_versions = ":providers",
)
