load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

exports_files(
    ["main.tf"],
    visibility = ["//cluster/validation:__pkg__"],
)

tf_providers_versions(
    name = "providers",
    providers = {
        "aws": "hashicorp/aws:~>5.0",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "dns-records",
    providers = [
        "aws",
    ],
    providers_versions = ":providers",
)
