load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

exports_files(["variables.tf"])

tf_providers_versions(
    name = "providers",
    providers = {
        "aws": "hashicorp/aws:~>6.0",
    },
    tf_version = "1.12.6",
)

tf_module(
    name = "dns-records",
    providers = [
        "aws",
    ],
    providers_versions = ":providers",
)
