apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - haku-mailbox.k8s.yaml
  - haku-mailbox-admin.sops.yaml
  - haku-mail-token.sops.yaml
components:
  - ./image-pins
configMapGenerator:
  - name: haku-mailbox-config
    namespace: haku-mailbox
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    files:
      - initialize.sh
      - config.json
      - mailbox-plan.ndjson
  - name: haku-mailbox-smtp-ingress
    namespace: haku-mailbox
    files:
      - nginx.conf
