apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-logs-configmaps-reader
  namespace: oci-cache
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logs-configmaps-reader
subjects:
  - kind: Group
    name: oidc-ksbx-groups:kubectl-sandbox-users
    apiGroup: rbac.authorization.k8s.io
