load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "process",
    srcs = [
        "process.go",
        "script.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/process",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/util",
    ],
)
