load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "status",
    srcs = [
        "action.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/tunnel/actions/status",
    visibility = ["//devinfra/claude/web_env/re/environment_manager/a6f96673/src:__subpackages__"],
    deps = [
        "//devinfra/claude/web_env/re/environment_manager/a6f96673/src/internal/tunnel/actions",
    ],
)
