load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "__init__",
    srcs = ["__init__.py"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "clean_models",
    srcs = ["clean_models.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//pydantic",
        "@pypi//tomli",
        "@pypi//tomli_w",
    ],
)

py_library(
    name = "loader",
    srcs = ["loader.py"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "models",
    srcs = ["models.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//pydantic"],
)
