# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "flux_kustomizations",
    srcs = ["flux_kustomizations.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:flux_sources",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s/crd_bindings/flux:kustomization",
        "@pypi//cdk8s",
    ],
)
