apiVersion: v1
kind: Secret
metadata:
  name: aws-route53-credentials
  namespace: cert-manager
  annotations:
    description: AWS IAM key for Route 53 DNS-01 challenges (allegedly.works)
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:OKAbxRWXc6fXIl2M4P/7ZJPYTe4=,iv:MGMiIp3SqMOcmEQ3/nEVq5WyGoDM19nRgetzL3v6zuU=,tag:kiZpLK00d9mOHaFuIsJCjA==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:8njUixP2iIWO,iv:qTHSTPAbWITPQAmEW5VCmA0n2K2aleYM3RHEQxPSvRU=,tag:zcVb5GEhs0aYmdJpc/YOPg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SE/YaD0oz0sK6Qi9p8V/sa0i86TOaNaGJE+3HVbnpYp55pWfVKkSLw==,iv:mpy/ftCShH5dI6II7rAH7PYLeyVhAIhCtsaTRwRR1kw=,tag:LJFWZAH97LlvKi1kj+35vA==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aGNwWXJYTG5kY291SU5x
        REJRU0JWN1h5YStFTlpEdmFVbHE2RklDOHhFCmlBQmF6SFRVV2pDSGRETGU1WTUx
        aHp6KzJVTjlBSTR4dFFyUlZrRTBuTm8KLS0tIEVBeUM1enE4aTlOc0NTcFB2a1hH
        N0tFS2pCckdDWWN0U3VPMlF0a2JrQWsKHp5+Uwgy24O4bWPnV7IYhBD5pCVHdHee
        3NtoXEMUjm+ivRuxfXVRUA6vEmUIWQ17sX9HGD9SAt3rlJG59K2Dfw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZXZPWmdoTWlleWJ0OFF1
        RDk0MzVoN09Scmx0bnBGUzFtMjd4UG83aWpVCmUveHRaMlNia3pSYVN0c0JxOHAr
        Ym1DR0QydnR2Ly9ESDRoMHRCQXh3MmcKLS0tIGdPNEhwK0Y4YU01YlZ6d3Rqb0J1
        dFFzMk5PMEFzSWdaNnNhZVArSjNtK2MKCjbLMLu/m6KZrxgX7skme9EPDdfh+Fxa
        J86euXUVSbQhayAkDziirukjOmOslNBMbxpXWIc0puM9bDQAcOT3bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T01:49:38Z"
  mac: ENC[AES256_GCM,data:4GinP3XeOf1u5wCBJ3EB6toofCQ5AuZ4sUE/WBhSqyz7Qrb4hStzStX3VK5VtWqlyOh8+4rOp7nvQSoiCKnYYUan1BLv8/64UaUotgvuyKT8623sNBtCGpsdv0gmRWEmYgMt5+UhGnQVfodazDIVQx9OIG4WBo/Xt7HLvCNUcQY=,iv:NJlzLX81dShqF9WgsjrYrTKaoIeEUoVVwzdVEtE8BPU=,tag:x+ffSJh6nZW5x5JC9gBR0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
