apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-environment
  namespace: ducktape-flux
spec:
  retryInterval: 1m
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: cert-manager-environment
    namespace: ducktape-flux
  path: ./cluster/k8s/cert-manager/environment
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age-cluster-secrets
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cert-manager-issuer-config
  dependsOn:
    - name: cert-manager
      namespace: ducktape-flux
    - name: cert-manager-trust
      namespace: ducktape-flux
    - name: cert-manager-issuer-config
      namespace: ducktape-flux
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt-prod
      namespace: ""
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt-staging
      namespace: ""
