load("//devinfra/python:defs.bzl", "py_test")

py_test(
    name = "test_e2e_browser",
    size = "medium",
    srcs = [
        "conftest.py",
        "test_e2e_browser.py",
    ],
    data = [
        "//x/auragon_study_casino/frontend:bundle",
        "@playwright_browsers//:chromium-headless-shell",
    ],
    env = {
        "CHROMIUM_HEADLESS_SHELL": "$(rootpath @playwright_browsers//:chromium-headless-shell)",
    },
    requires_docker = True,
    deps = [
        "//util:net",
        "//util:playwright",
        "//util/bazel:runfiles",
        "//x/auragon_study_casino:app",
        "//x/auragon_study_casino:config",
        "//x/auragon_study_casino:conftest",
        "@pypi//playwright",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
        "@pypi//uvicorn",
    ],
)
