load("//devinfra/python:defs.bzl", "py_test")

py_test(
    name = "test_e2e_browser",
    size = "medium",
    srcs = [
        "conftest.py",
        "test_e2e_browser.py",
    ],
    data = [
        "//x/auragon_study_casino/frontend:bundle",
        "@playwright_browsers//:chromium-headless-shell",
    ],
    env = {
        "CHROMIUM_HEADLESS_SHELL": "$(rootpath @playwright_browsers//:chromium-headless-shell)",
    },
    requires_docker = True,
    deps = [
        "//util:net",
        "//util:playwright",
        "//util/bazel:runfiles",
        "//x/auragon_study_casino:app",
        "//x/auragon_study_casino:config",
        "//x/auragon_study_casino:conftest",
        "@pypi//playwright",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
        "@pypi//uvicorn",
    ],
)

py_test(
    name = "visual_golden_test",
    size = "large",
    srcs = ["visual_golden_test.py"],
    data = [
        "//third_party/containers:postgres_18",
        "//third_party/containers:ryuk",
        "//x/auragon_study_casino/frontend:bundle",
        "//x/auragon_study_casino/frontend:visual_golden_snapshots",
        "@playwright_browsers//:chromium-headless-shell",
    ],
    env = {
        "CHROMIUM_HEADLESS_SHELL": "$(rootpath @playwright_browsers//:chromium-headless-shell)",
    },
    requires_docker = True,
    deps = [
        "//third_party/containers:rlocations",
        "//util:net",
        "//util:oci",
        "//util:playwright",
        "//util/bazel:runfiles",
        "//util/testing:png_diff",
        "//util/testing:undeclared_outputs",
        "//x/auragon_study_casino:app",
        "//x/auragon_study_casino:config",
        "@pypi//playwright",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
        "@pypi//testcontainers",
        "@pypi//uvicorn",
    ],
)
