load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "testprobe_lib",
    srcs = ["main.go"],
    importpath = "github.com/agentydragon/ducktape/cluster/kubespan_agent/testprobe",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_google_nftables//:nftables",
        "@com_github_google_nftables//expr",
        "@org_golang_x_net//icmp",
        "@org_golang_x_net//ipv6",
        "@org_golang_x_sys//unix",
    ],
)

go_binary(
    name = "testprobe",
    testonly = True,
    embed = [":testprobe_lib"],
    goarch = "amd64",
    goos = "linux",
    static = "on",
    visibility = ["//cluster/kubespan_agent:__subpackages__"],
)
