# ============================================================================
# kubectl-sandbox-client-credentials — machine-to-machine OIDC for kubeconfig
# ============================================================================
# Non-interactive sibling of kubectl-sandbox-mcp: confidential OAuth2 client
# using `client_credentials` grant, so a CronJob can mint JWTs without a
# browser. Reuses the same kube-apiserver trusted issuer/audience for every
# machine identity; the provider's machine-only scope mapping is an explicit
# principal-to-groups allowlist.
#
# Consumer: cluster/k8s/agents/authentik-jwt-rotation/ CronJob. It runs
# biweekly, exchanges client_id + client_secret for a JWT, commits the JWT
# SOPS-encrypted to secrets/claude-web-k8s-jwt.yaml. `write_kubeconfig.py`
# on Claude Code sessions decrypts and embeds it.

resource "authentik_provider_oauth2" "kubectl_sandbox_client_credentials" {
  name        = "kubectl-sandbox-client-credentials"
  client_id   = "kubectl-sandbox-client-credentials"
  client_type = "confidential" # client_secret auto-generated by Authentik

  authorization_flow = data.authentik_flow.implicit_consent.id
  invalidation_flow  = data.authentik_flow.invalidation.id
  signing_key        = data.authentik_certificate_key_pair.self_signed.id

  issuer_mode                = "per_provider"
  include_claims_in_id_token = true

  # 45d access-token validity — comfortable margin over the biweekly rotation
  # CronJob. See cluster/k8s/agents/authentik-jwt-rotation/ for cadence math.
  access_token_validity = "hours=1080"

  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
    authentik_property_mapping_provider_scope.kubectl_machine_groups.id,
  ]

  # client_credentials doesn't redirect, so allowed_redirect_uris is omitted.
}

resource "authentik_application" "kubectl_sandbox_client_credentials" {
  name              = "kubectl-sandbox-client-credentials"
  slug              = "kubectl-sandbox-client-credentials"
  protocol_provider = authentik_provider_oauth2.kubectl_sandbox_client_credentials.id
  meta_description  = "Machine-to-machine kubectl access with explicit Authentik principal-to-group mapping"
}

# Authentik auto-creates an internal service account for client_credentials
# grants (username: ak-<slug>-client_credentials). The client_credentials flow
# authenticates as this user. Without a policy binding for it, the grant is
# rejected with invalid_grant.
data "authentik_user" "kubectl_sandbox_cc_auto" {
  username = "ak-kubectl-sandbox-client-credentials-client_credentials"
}

resource "authentik_policy_binding" "kubectl_sandbox_cc_auto_user" {
  target = authentik_application.kubectl_sandbox_client_credentials.uuid
  user   = data.authentik_user.kubectl_sandbox_cc_auto.pk
  order  = 0
}

# K8s Secret holding the client_id + client_secret. Lives in agents-infra
# (where the authentik-jwt-rotation CronJob runs) and is the only place this
# credential exists outside Authentik — the CC web sandbox only ever holds
# the already-minted JWT (in secrets/claude-web-k8s-jwt.yaml SOPS).
resource "kubernetes_secret" "kubectl_sandbox_client_credentials" {
  metadata {
    name      = "kubectl-sandbox-client-credentials"
    namespace = "agents-infra"
    annotations = {
      description = "client_id + client_secret for kubectl-sandbox-client-credentials OIDC provider (mounted by authentik-jwt-rotation CronJob)"
    }
  }

  data = {
    client_id     = authentik_provider_oauth2.kubectl_sandbox_client_credentials.client_id
    client_secret = authentik_provider_oauth2.kubectl_sandbox_client_credentials.client_secret
  }
}
