apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: git.allegedly.works/ducktape-ci/haku-openclaw-spike
    newTag: devel-20260921180419-c4d5a25 # {"$imagepolicy": "flux-system:haku-openclaw-spike:tag"}
