"""Network utilities package."""

load("@rules_python//python:defs.bzl", "py_library")
load("//tools/lint:linters.bzl", "ruff_test")

py_library(
    name = "net_util",
    srcs = [
        "__init__.py",
        "docker.py",
        "net.py",
    ],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//aiodocker",
        "@pypi//tenacity",
    ],
)

ruff_test(
    name = "ruff",
    srcs = [":net_util"],
)

py_library(
    name = "__init__",
    srcs = ["__init__.py"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "docker",
    srcs = ["docker.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//aiodocker"],
)

py_library(
    name = "net",
    srcs = ["net.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//tenacity"],
)
