"""Network utilities package."""

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "net_util",
    srcs = [
        "docker.py",
        "net.py",
    ],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//aiodocker",
        "@pypi//tenacity",
    ],
)

py_library(
    name = "docker",
    srcs = ["docker.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//aiodocker"],
)

py_library(
    name = "net",
    srcs = ["net.py"],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = ["@pypi//tenacity"],
)
