load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "sources",
    srcs = [
        "git.go",
        "sources.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/sources",
    visibility = ["//claude_web_env/re/environment_manager/6b49f1ca/src:__subpackages__"],
    deps = [
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/auth",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/config",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/gitproxy",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/o11y",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/o11y/diag",
    ],
)
