module github.com/anthropics/anthropic/api-go/environment-manager

go 1.26.0

require (
	github.com/DataDog/datadog-go/v5 v5.9.1
	github.com/google/uuid v1.6.0
	github.com/gorilla/websocket v1.5.4-0.20250319132907-e064f32e3674
	// RE(0b86a2a0): bumped v0.37.0 -> v0.54.1.
	// Lower bound >= v0.54.1: server.clientInfoStore is embedded, so
	// Get/SetClientInfo appear twice — a real body on the store type and an
	// <autogenerated> promotion wrapper on the session type (0x16c0f80 /
	// 0x17676a0). v0.54.0 declares them directly on *streamableHttpSession.
	// Upper bound < v0.55.0: mcp-go/util's 4-function stdLogger package is
	// still linked at 0x16ae320, immediately before mcp-go/server; v0.55.0
	// deleted util/ in favour of *slog.Logger.
	// See internal/mcp/README.md.
	github.com/mark3labs/mcp-go v0.58.0
	github.com/mitchellh/mapstructure v1.5.0
	github.com/spf13/cobra v1.10.2
	go.opentelemetry.io/contrib/bridges/otelslog v0.20.1
	go.opentelemetry.io/otel v1.46.0
	go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp v0.21.0
	go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v1.45.0
	go.opentelemetry.io/otel/exporters/stdout/stdoutmetric v1.45.0
	go.opentelemetry.io/otel/metric v1.46.0
	go.opentelemetry.io/otel/sdk v1.45.0
	go.opentelemetry.io/otel/sdk/log v0.21.0
	go.opentelemetry.io/otel/sdk/metric v1.45.0
	golang.org/x/sync v0.23.0
	google.golang.org/protobuf v1.36.12
)

require (
	github.com/cenkalti/backoff/v5 v5.0.3 // indirect
	github.com/cespare/xxhash/v2 v2.3.0 // indirect
	github.com/go-logr/logr v1.4.4 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	// RE(0b86a2a0): added — mcp-go v0.54.1's JSON Schema model. Exported names
	// in package `Bo9xYr` (ApplyDefaults, CloneSchemas, Resolve, Schema,
	// Validate) and the unexported field name `resolvedRef` are exclusive to
	// this library; none of them exist in the old binary.
	github.com/google/jsonschema-go v0.4.2 // indirect
	github.com/grpc-ecosystem/grpc-gateway/v2 v2.29.0 // indirect
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	// RE(0b86a2a0): added — mcp-go v0.54.1's JSON Schema validator, used for
	// tool output-schema validation. Identified from the (mis-capitalised)
	// struct tag `json:"AbsoluteKeywordLocation,omitempty"` unique to v6's
	// output.go, the `//go:embed metaschemas` tree
	// (metaschemas/draft-0{4,6,7}/schema, metaschemas/draft/20{19-09,20-12}/…)
	// and the URN `urn:mem:metaschema` (draft.go:292).
	github.com/santhosh-tekuri/jsonschema/v6 v6.0.2 // indirect
	github.com/spf13/cast v1.7.1 // indirect
	github.com/spf13/pflag v1.0.9 // indirect
	github.com/yosida95/uritemplate/v3 v3.0.2 // indirect
	go.opentelemetry.io/auto/sdk v1.2.1 // indirect
	go.opentelemetry.io/otel/log v0.22.0 // indirect
	go.opentelemetry.io/otel/trace v1.46.0
	go.opentelemetry.io/proto/otlp v1.11.0 // indirect
	golang.org/x/net v0.59.0 // indirect
	golang.org/x/sys v0.48.0 // indirect
	golang.org/x/text v0.42.0 // indirect
	google.golang.org/genproto/googleapis/api v0.0.0-20260803160001-6ac0973c030d // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20260803160001-6ac0973c030d // indirect
	google.golang.org/grpc v1.83.0 // indirect
)

require go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.45.0

require (
	github.com/Microsoft/go-winio v0.5.0 // indirect
	github.com/stretchr/objx v0.5.2 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.45.0 // indirect
)
