# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "driver",
    srcs = ["driver.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:helm",
        "//cluster/cdk8s:manifest_roots",
        "//cluster/cdk8s:namespaces",
        "//cluster/cdk8s:node_scheduling",
        "//cluster/cdk8s/providers/flux:git_repository",
        "//cluster/cdk8s/providers/flux:gitrepository",
        "//cluster/cdk8s/providers/flux:helmrelease",
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
        "@pypi//constructs",
    ],
)
