apiVersion: v1
kind: Service
metadata:
  name: {{ include "rspcache.adminName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labelsWith" (dict "context" . "extra" (dict "app.kubernetes.io/name" (include "rspcache.adminName" .) "app.kubernetes.io/component" "admin")) | indent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "rspcache.adminName" . }}
    app.kubernetes.io/component: admin
  ports:
    - name: http
      port: {{ .Values.admin.service.port }}
      targetPort: http
