apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: props-ollama-consumer
  namespace: props
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ollama-api-consumer
subjects:
  - kind: ServiceAccount
    name: default
    namespace: props
