# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_binary", "py_library", "py_test")

py_library(
    name = "generate_litellm",
    srcs = ["generate_litellm.py"],
    deps = [
        "//devinfra:prettier",
        "//util/bazel:workspace",
        "@pypi//pyyaml",
    ],
)

py_binary(
    name = "generate_litellm_bin",
    main_module = "cluster.k8s.litellm.app.generate_litellm",
    deps = [":generate_litellm"],
)

py_test(
    name = "test_generate_litellm",
    srcs = ["test_generate_litellm.py"],
    data = ["proxy-config.yaml"],
    deps = [
        ":generate_litellm",
        "//util/bazel:runfiles",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
        "@pypi//pyyaml",
    ],
)
