"""Generates cluster/k8s/litellm/app/proxy-config.yaml (raw LiteLLM proxy config).

Run to regenerate the committed file:
    bazel run //cluster/k8s/litellm/app:generate_litellm_bin

Parity enforced by:
    bazel test //cluster/k8s/litellm/app:test_generate_litellm

# TODO: Consider alternatives that render at apply time, eliminating this
# generator + parity test entirely:
#
# - Local Helm chart via kustomize `helmCharts`: write a tiny chart with a
#   Go template that ranges over a model list in values.yaml. Flux's
#   kustomize-controller renders it on reconcile — no committed output.
#   Natural fit with the existing kustomize/Flux stack.
#
# - Timoni: CUE-based module rendered by the Flux Timoni controller.
#   Stronger typing than Go templates; same "no committed output" property.
"""

from collections.abc import Iterator

import yaml

from devinfra.prettier import prettier_format_in_place
from util.bazel.workspace import get_build_workspace_directory

_OLLAMA_BASE = "http://ollama.ollama.svc.cluster.local:11434"

# (name suffix, num_ctx). None num_ctx = model default (128k for gpt-oss).
_CTX_VARIANTS: list[tuple[str, int | None]] = [("128k", None), ("256k", 262_144), ("512k", 524_288), ("1m", 1_048_576)]

# (ollama model tag, context variants to expose)
_MODELS: list[tuple[str, list[tuple[str, int | None]]]] = [
    ("gpt-oss:20b", _CTX_VARIANTS),
    ("gpt-oss:120b", [("128k", None)]),
    # gemma4 trains at 128k; expose only that ctx variant.
    ("gemma4:31b-it-q8_0", [("128k", None)]),
]

# z.ai (GLM) served via z.ai's Anthropic Messages endpoint. The key comes from the
# ZAI_API_KEY env var (litellm-zai-key secret). Routing GLM through the Anthropic shape
# avoids the union-tool-input bug GLM hits on the OpenAI chat shape (z.ai's Anthropic
# adapter parses GLM's XML tool calls back into proper JSON `tool_use.input` objects). See
# docs/zai_api.md. LiteLLM fronts it so it logs to Langfuse (via `litellm_metadata`) and
# props need not hold ZAI_API_KEY. Exposed via LiteLLM's `/v1/messages` endpoint; props'
# llm-proxy routes its /v1/messages here. The OpenAI-shaped coding-plan route was removed
# in favor of this one.
_ZAI_ANTHROPIC_BASE = "https://api.z.ai/api/anthropic"
# Full GLM matrix z.ai serves on the Anthropic endpoint (per /api/anthropic/v1/models, 2026-06).
_ZAI_ANTHROPIC_MODELS: list[str] = ["glm-4.5", "glm-4.5-air", "glm-4.6", "glm-4.7", "glm-5", "glm-5-turbo", "glm-5.1"]


def _zai_anthropic_entries() -> Iterator[dict]:
    for model in _ZAI_ANTHROPIC_MODELS:
        yield {
            "model_name": f"{model}-anthropic",
            "litellm_params": {
                # `anthropic/` provider → LiteLLM posts Anthropic Messages to
                # {api_base}/v1/messages with x-api-key, no shape translation.
                "model": f"anthropic/{model}",
                "api_base": _ZAI_ANTHROPIC_BASE,
                "api_key": "os.environ/ZAI_API_KEY",
            },
            "model_info": {"mode": "chat", "supports_function_calling": True},
        }


def _model_entries(tag: str, ctx_variants: list[tuple[str, int | None]]) -> Iterator[dict]:
    name_base = tag.replace(":", "-")
    for api, suffix, api_base in [
        ("openai", "-openai-chat", f"{_OLLAMA_BASE}/v1"),
        ("ollama", "-ollama-native", _OLLAMA_BASE),
    ]:
        for ctx_suffix, num_ctx in ctx_variants:
            params: dict = {"model": f"{api}/{tag}", "api_base": api_base}
            # Ollama doesn't require an API key, but the OpenAI SDK (used by
            # LiteLLM's openai provider) refuses to initialize without one.
            # TODO: Use a real API key once Ollama per-user auth is deployed
            # (see cluster/docs/plan.md "Ollama: per-user auth").
            if api == "openai":
                params["api_key"] = "ollama"
            if num_ctx is not None:
                params["extra_body"] = {"options": {"num_ctx": num_ctx}}
            yield {
                "model_name": f"{name_base}-{ctx_suffix}{suffix}",
                "litellm_params": params,
                "model_info": {"mode": "chat", "supports_function_calling": True},
            }


def generate() -> str:
    model_list: list[dict] = []
    for tag, ctx_variants in _MODELS:
        model_list.extend(_model_entries(tag, ctx_variants))
    model_list.extend(_zai_anthropic_entries())

    # Master key and Langfuse credentials are injected as env vars in the
    # Deployment; not repeated here.
    proxy_config = {"model_list": model_list, "litellm_settings": {"drop_params": True, "callbacks": ["langfuse_otel"]}}

    header = "# Generated by //cluster/k8s/litellm/app:generate_litellm_bin — do not edit by hand.\n"
    return header + yaml.dump(proxy_config, default_flow_style=False, sort_keys=False, allow_unicode=True)


def main() -> None:
    out_path = get_build_workspace_directory() / "cluster/k8s/litellm/app/proxy-config.yaml"
    out_path.write_text(generate())
    prettier_format_in_place(out_path)
    print(f"Generated {out_path}")


if __name__ == "__main__":
    main()
