apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litellm
resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - httproute.yaml

configMapGenerator:
  - name: litellm-config
    options:
      disableNameSuffixHash: true
    files:
      - config.yaml=proxy-config.yaml
