apiVersion: v1
kind: Service
metadata:
  name: wayback-archive
  namespace: wayback-cache
  labels:
    app.kubernetes.io/name: wayback-archive
spec:
  selector:
    app.kubernetes.io/name: wayback-archive
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
