apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount-agentplane-egress.yaml
  - role-agentplane-egress.yaml
  - rolebinding-agentplane-egress.yaml
  - clusterrole-agentplane-staging-egress-token-reviewer.yaml
  - egresspolicy-github-public.yaml
  - certificate-agentplane-egress-ca.yaml
  - trust-bundle.yaml
  - deployment-agentplane-egress.yaml
  - service-agentplane-egress.yaml
  - service-agentplane-egress-admin.yaml
  - networkpolicy.yaml
