# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "matrix",
    srcs = ["matrix.py"],
    visibility = ["//cluster/cdk8s:__subpackages__"],
    deps = [
        "//cluster/cdk8s:cnpg",
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:gateway",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s:helm",
        "//cluster/cdk8s:manifest_roots",
        "//cluster/cdk8s:metadata",
        "//cluster/cdk8s/crd_bindings/flux:helmrelease",
        "//cluster/cdk8s/crd_bindings/flux:helmrepository",
        "//cluster/cdk8s/crd_bindings/flux:kustomization",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "//cluster/cdk8s/providers/cnpg:cluster",
        "//cluster/cdk8s/providers/gateway_api:httproute",
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
        "@pypi//constructs",
    ],
)

py_library(
    name = "user_provisioner",
    srcs = ["user_provisioner.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        ":matrix",
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:forgejo_images",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s:manifest_roots",
        "//cluster/cdk8s/crd_bindings/flux:kustomization",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
    ],
)
