load("//devinfra/python:defs.bzl", "py_binary", "py_library", "py_test")

py_library(
    name = "patch_qwen38_template",
    srcs = ["patch_qwen38_template.py"],
)

py_binary(
    name = "derive_qwen38_template",
    srcs = ["derive_qwen38_template_cli.py"],
    data = ["qwen38-chat-template.jinja"],
    main = "derive_qwen38_template_cli.py",
    deps = [":patch_qwen38_template"],
)

py_test(
    name = "test_patch_qwen38_template",
    srcs = ["test_patch_qwen38_template.py"],
    data = ["qwen38-chat-template.jinja"],
    deps = [
        ":patch_qwen38_template",
        "//:conftest",
        "@pypi//jinja2",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "derive_qwen38_template_cli",
    srcs = ["derive_qwen38_template_cli.py"],
    deps = [":patch_qwen38_template"],
)
