apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ollama
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - clusterrole-ollama-consumer.yaml
  - job-setup-gpt-oss-v1.yaml
  - role-ollama-reader.yaml

configMapGenerator:
  - name: gpt-oss-scripts
    options:
      disableNameSuffixHash: true
    files:
      - setup-gpt-oss-v1.sh
  - name: ollama-auth-proxy
    options:
      disableNameSuffixHash: true
    files:
      - default.conf.template=nginx-auth-proxy.conf.template
