apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: git.allegedly.works/ducktape-ci/attic-jwt-rotation
    newTag: devel-20260917082433-6645f7d # {"$imagepolicy": "flux-system:attic-jwt-rotation:tag"}
