- name: Install dev env
  become: true
  ansible.builtin.apt:
    pkg:
      # TODO: - python-is-python3
      # broken: google-cloud-sdk
      #- asciidoc
      #- bison
      #- cabal-install
      - clang
      - ninja-build
      - clang-format
      - cloc
      - cmake
      - flex
      - gcc
      - gcc
      - ghc
      - git
      - gitk
      - gnuplot
      - golang
      - golang
      - jq
      - jupyter-nbconvert
      - make
      - markdown
      - sloccount
      - tidy  # HTML tidy
      #- npm <- "you have requested an impossible situations"

      # TODO: this seems to not provide tree-sitter cli though
      # so does not provide latex higlihting
      # - libtree-sitter0  # tree-sitter for neovim syntax stuff

      #- protobuf-compiler
      #- pyqt5-dev-tools

# TODO: cargo broken
#- name: Install stylua (Lua formatter for Neovim)
#  community.general.cargo:
#    name: stylua

# Include heavy/optional dev packages (controlled by include_heavy_dev_packages variable)
- include_tasks: dev-env-heavy.yml

# Include user-level development tools
- import_tasks: dev-env-user.yml
