apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seaweedfs-langfuse-bucket
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./cluster/k8s/seaweedfs/langfuse-bucket
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: seaweedfs-cluster
      namespace: flux-system
    - name: seaweedfs-secrets
      namespace: flux-system
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: seaweed.seaweedfs.com/v1
      kind: Bucket
      name: langfuse
      namespace: seaweedfs
