# Forgejo repo + service user for the budget Beancount ledger.
#
# Provisions a private `budget-ledger/ledger` repo owned by a dedicated
# `budget-ledger` service user (so the user has full read/write on it without a
# separate collaborator grant), plus a Kubernetes Secret carrying that user's git
# credentials in the `budget` namespace -- consumed by the exporter CronJob
# (push) and the Fava git-sync sidecar (pull). Auth is HTTPS Basic over the
# in-cluster Forgejo service (no SSH endpoint needed).

data "kubernetes_secret" "forgejo_admin" {
  metadata {
    name      = "forgejo-admin-password"
    namespace = "forgejo"
  }
}

provider "forgejo" {
  host     = var.forgejo_url
  username = data.kubernetes_secret.forgejo_admin.data["username"]
  password = data.kubernetes_secret.forgejo_admin.data["password"]
}

resource "random_password" "budget_ledger" {
  length  = 48
  special = false
}

resource "forgejo_user" "budget_ledger" {
  login                = "budget-ledger"
  email                = "budget-ledger@allegedly.works"
  password             = random_password.budget_ledger.result
  must_change_password = false
  visibility           = "private"
}

resource "forgejo_repository" "ledger" {
  owner          = forgejo_user.budget_ledger.login
  name           = "ledger"
  description    = "Budget Beancount ledger, generated by the augur budget exporter. Do not edit by hand."
  private        = true
  default_branch = "main"
  # Create an initial commit so `main` exists for the exporter to clone/push and
  # the Fava git-sync sidecar to pull.
  auto_init = true
}

# Git credentials for the exporter + Fava, in the budget namespace. Reflected into
# the augur namespace (emberstack reflector) so the exporter CronJob -- which runs
# alongside augur to reuse its config ConfigMap + plaid DB creds -- can read them.
resource "kubernetes_secret" "budget_ledger_git_creds" {
  metadata {
    name      = "budget-ledger-git-creds"
    namespace = "budget"
    annotations = {
      "reflector.v1.k8s.emberstack.com/reflection-allowed"            = "true"
      "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces" = "augur"
      "reflector.v1.k8s.emberstack.com/reflection-auto-enabled"       = "true"
      "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces"    = "augur"
    }
  }

  data = {
    username = forgejo_user.budget_ledger.login
    password = random_password.budget_ledger.result
    repo_url = "http://forgejo-http.forgejo:3000/${forgejo_user.budget_ledger.login}/${forgejo_repository.ledger.name}.git"
  }
}
