# Forgejo repo + service user for the budget Beancount ledger.
#
# Provisions a private `budget-ledger/ledger` repo owned by a dedicated
# `budget-ledger` service user (so the user has full read/write on it without a
# separate collaborator grant), read-only collaborator grants for agent users,
# plus a Kubernetes Secret carrying that user's git credentials in the `forgejo`
# namespace -- copied into `budget` by ESO for the exporter CronJob (push) and the
# Fava git-sync sidecar (pull). Auth is HTTPS Basic over the in-cluster Forgejo
# service (no SSH endpoint needed).

data "kubernetes_secret" "forgejo_admin" {
  metadata {
    name      = "forgejo-admin-password"
    namespace = "forgejo"
  }
}

provider "forgejo" {
  host     = var.forgejo_url
  username = data.kubernetes_secret.forgejo_admin.data["username"]
  password = data.kubernetes_secret.forgejo_admin.data["password"]
}

resource "random_password" "budget_ledger" {
  length  = 48
  special = false
}

resource "forgejo_user" "budget_ledger" {
  login                = "budget-ledger"
  email                = "budget-ledger@allegedly.works"
  password             = random_password.budget_ledger.result
  must_change_password = false
  visibility           = "private"
}

resource "forgejo_repository" "ledger" {
  owner          = forgejo_user.budget_ledger.login
  name           = "ledger"
  description    = "Budget Beancount ledger, generated by the augur budget exporter. Do not edit by hand."
  private        = true
  default_branch = "main"
  # Create an initial commit so `main` exists for the exporter to clone/push and
  # the Fava git-sync sidecar to pull.
  auto_init = true
}

# Read-only access for the claude agent account (user provisioned by
# tf/gitops/forgejo-claude; until it exists this resource fails and the
# Terraform CR retries on its interval).
resource "forgejo_collaborator" "claude" {
  repository_id = forgejo_repository.ledger.id
  user          = "claude"
  permission    = "read"
}

# Read-only access for the haku agent account (user provisioned by
# tf/gitops/haku-state).
resource "forgejo_collaborator" "haku" {
  repository_id = forgejo_repository.ledger.id
  user          = "haku"
  permission    = "read"
}

# Git credentials for the exporter + Fava. The budget namespace copies them in
# through ESO and Reflector mirrors that copy into augur, where the exporter
# CronJob runs alongside augur to reuse its config ConfigMap + plaid DB creds
# (cluster/cdk8s/forgejo/budget_namespace.py).
resource "kubernetes_secret" "budget_ledger_git_creds_source" {
  metadata {
    name      = "budget-ledger-git-creds"
    namespace = "forgejo"
  }

  data = {
    username = forgejo_user.budget_ledger.login
    password = random_password.budget_ledger.result
    repo_url = "http://forgejo-http.forgejo:3000/${forgejo_user.budget_ledger.login}/${forgejo_repository.ledger.name}.git"
  }
}

# The budget ExternalSecret adopts the Secret this address created there.
# CLEANUP(added 2026-09-28): Remove once the budget_ledger state has forgotten
# kubernetes_secret.budget_ledger_git_creds. Never destroy the ESO-owned Secret.
removed {
  from = kubernetes_secret.budget_ledger_git_creds
  lifecycle {
    destroy = false
  }
}
