apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: git.allegedly.works/ducktape-ci/homeassistant-provisioner
    newTag: devel-20260923225748-306e5af # {"$imagepolicy": "flux-system:homeassistant-provisioner:tag"}
