apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: git.allegedly.works/ducktape-ci/homeassistant-provisioner
    newTag: devel-20260923224621-b56a8f7 # {"$imagepolicy": "flux-system:homeassistant-provisioner:tag"}
