apiVersion: v1
kind: ServiceAccount
metadata:
  name: volsync-metrics
  namespace: volsync-system
---
apiVersion: v1
kind: Secret
metadata:
  name: volsync-metrics-token
  namespace: volsync-system
  annotations:
    kubernetes.io/service-account.name: volsync-metrics
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volsync-metrics-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volsync-metrics-reader
subjects:
  - kind: ServiceAccount
    name: volsync-metrics
    namespace: volsync-system
