load("//devinfra/python:defs.bzl", "py_library")

exports_files([
    "0001_session_history.py",
    "0002_session_open_reservations.py",
    "0003_history_feed_state.py",
])

py_library(
    name = "0001_session_history",
    srcs = ["0001_session_history.py"],
    deps = [
        "@pypi//alembic",
        "@pypi//sqlalchemy",
    ],
)

py_library(
    name = "0002_session_open_reservations",
    srcs = ["0002_session_open_reservations.py"],
    deps = [
        "@pypi//alembic",
        "@pypi//sqlalchemy",
    ],
)

py_library(
    name = "0003_history_feed_state",
    srcs = ["0003_history_feed_state.py"],
    deps = [
        "@pypi//alembic",
        "@pypi//sqlalchemy",
    ],
)
