load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "actions",
    srcs = ["registry.go"],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/tunnel/actions",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/tunnel/tunnelpb",
    ],
)
