# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "app",
    srcs = ["app.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s:metadata",
        "//cluster/cdk8s/crd_bindings/flux:helmrelease",
        "//cluster/cdk8s/crd_bindings/flux:helmrepository",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
    ],
)

py_library(
    name = "policies",
    srcs = ["policies.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        ":proxy_injection",
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s/crd_bindings/kyverno:clusterpolicy",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
    ],
)

py_library(
    name = "proxy_injection",
    srcs = ["proxy_injection.py"],
    deps = [
        "//cluster/cdk8s/crd_bindings/kyverno:clusterpolicy",
        "@pypi//cdk8s",
    ],
)
