load("//devinfra/python:defs.bzl", "py_library", "py_test")

py_library(
    name = "report",
    srcs = ["report.py"],
    deps = ["@pypi//mitmproxy"],
)

py_test(
    name = "test_report",
    srcs = ["test_report.py"],
    deps = [
        ":report",
        "//:conftest",
        "@pypi//mitmproxy",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "cloud_report",
    srcs = ["cloud_report.py"],
    deps = ["@pypi//mitmproxy"],
)

py_test(
    name = "test_cloud_report",
    srcs = ["test_cloud_report.py"],
    deps = [
        ":cloud_report",
        "//:conftest",
        "@pypi//mitmproxy",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "block_cloud_github",
    srcs = ["block_cloud_github.py"],
    deps = ["@pypi//mitmproxy"],
)

py_test(
    name = "test_block_cloud_github",
    srcs = ["test_block_cloud_github.py"],
    deps = [
        ":block_cloud_github",
        "//:conftest",
        "@pypi//mitmproxy",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
