load("@rules_oci//oci:defs.bzl", "oci_image")
load("//devinfra/oci:defs.bzl", "oci_layout_rloc")
load("//devinfra/python:defs.bzl", "py_library", "py_test")

exports_files([
    "squid.yaml",
    "squid.lock.json",
])

oci_image(
    name = "squid_test_image",
    testonly = True,
    base = "@debian_trixie_slim_linux_amd64",
    tars = ["@github_relay_squid//:flat"],
)

oci_layout_rloc(
    name = "squid_image",
    testonly = True,
    image = ":squid_test_image",
)

py_test(
    name = "test_relay_config",
    size = "medium",
    srcs = ["test_relay_config.py"],
    data = [
        "prepare_trust.sh",
        ":squid_image",
    ],
    requires_docker = True,
    deps = [
        ":relay_config",
        "//:conftest",
        "//util:oci",
        "//util/bazel:runfiles",
        "//util/testing:undeclared_outputs",
        "@pypi//cryptography",
        "@pypi//docker",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
        "@pypi//tenacity",
    ],
)

py_library(
    name = "report",
    srcs = ["report.py"],
    deps = ["@pypi//mitmproxy"],
)

py_test(
    name = "test_report",
    srcs = ["test_report.py"],
    deps = [
        ":report",
        "//:conftest",
        "@pypi//mitmproxy",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "cloud_report",
    srcs = ["cloud_report.py"],
    deps = ["@pypi//mitmproxy"],
)

py_test(
    name = "test_cloud_report",
    srcs = ["test_cloud_report.py"],
    deps = [
        ":cloud_report",
        "//:conftest",
        "@pypi//mitmproxy",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "block_cloud_github",
    srcs = ["block_cloud_github.py"],
    deps = ["@pypi//mitmproxy"],
)

py_test(
    name = "test_block_cloud_github",
    srcs = ["test_block_cloud_github.py"],
    deps = [
        ":block_cloud_github",
        "//:conftest",
        "@pypi//mitmproxy",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "session_ws_metadata",
    srcs = ["session_ws_metadata.py"],
    visibility = ["//cluster/proxies/github_api_proxy:__pkg__"],
    deps = ["@pypi//mitmproxy"],
)

py_test(
    name = "test_session_ws_metadata",
    srcs = ["test_session_ws_metadata.py"],
    deps = [
        ":session_ws_metadata",
        "//:conftest",
        "@pypi//mitmproxy",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_session_ws_metadata_integration",
    srcs = ["test_session_ws_metadata_integration.py"],
    deps = [
        ":session_ws_metadata",
        "//:conftest",
        "@pypi//aiohttp",
        "@pypi//mitmproxy",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "relay_config",
    srcs = ["relay_config.py"],
)
