"""Tests for automatic example generation from critic_scopes_expected_to_recall data.

Examples are now auto-generated by a database VIEW that combines file_sets
and whole-snapshot entries. These tests verify the VIEW produces correct examples.
"""

from __future__ import annotations

import pytest_bazel

from props.core.ids import SnapshotSlug
from props.core.models.examples import ExampleKind, SingleFileSetExample, WholeSnapshotExample
from props.core.splits import Split
from props.db.database import Database
from props.db.examples import Example
from props.db.models import FileSet, FileSetMember, Snapshot


def test_generate_examples_train_split(synced_db: Database):
    """Test example VIEW for TRAIN split creates per-file-set examples + whole-snapshot."""
    with synced_db.session() as session:
        # Use test-trivial fixture (train split)
        slug = SnapshotSlug("test-fixtures/train1")
        snapshot = session.query(Snapshot).filter_by(slug=slug).one()
        assert snapshot.split == Split.TRAIN

        # Query examples from VIEW
        examples = session.query(Example).filter_by(snapshot_slug=slug).all()

        # Should have multiple examples (one per unique file set + full-specimen)
        assert len(examples) > 1

        # Each example should be an Example ORM object
        for example in examples:
            assert isinstance(example, Example)

            # Check example_kind is valid
            assert isinstance(example.example_kind, ExampleKind)
            assert example.example_kind in [ExampleKind.WHOLE_SNAPSHOT, ExampleKind.FILE_SET]

            # Verify example_spec conversion works
            example_spec = example.to_example_spec()
            assert isinstance(example_spec, WholeSnapshotExample | SingleFileSetExample)

            if example.example_kind == ExampleKind.WHOLE_SNAPSHOT:
                # Whole snapshot examples
                assert example.files_hash is None
                assert isinstance(example_spec, WholeSnapshotExample)
            else:
                # Single file set examples
                assert example.example_kind == ExampleKind.FILE_SET
                assert example.files_hash is not None
                assert isinstance(example_spec, SingleFileSetExample)
                assert example_spec.files_hash == example.files_hash

        # One example should be whole-snapshot
        full_specimen_found = any(ex.example_kind == ExampleKind.WHOLE_SNAPSHOT for ex in examples)
        assert full_specimen_found, "Whole-snapshot example not found in generated examples"


def test_generate_examples_valid_test_split(synced_db: Database):
    """Test example VIEW for VALID split (per-file + whole-snapshot) and TEST split (whole-snapshot only)."""
    with synced_db.session() as session:
        # Test VALID split using test-validation fixture
        slug = SnapshotSlug("test-fixtures/valid1")
        valid_snapshot = session.query(Snapshot).filter_by(slug=slug).one()
        assert valid_snapshot.split == Split.VALID

        # Query examples from VIEW
        valid_examples = session.query(Example).filter_by(snapshot_slug=slug).all()

        # VALID should have multiple examples (per-file + whole-snapshot)
        assert len(valid_examples) > 1, "VALID split should generate per-file examples for targeted mode"

        # At least one should be whole-snapshot
        full_specimen_found = any(ex.example_kind == ExampleKind.WHOLE_SNAPSHOT for ex in valid_examples)
        assert full_specimen_found, "VALID split should include whole-snapshot example"

        # Note: TEST split testing skipped - no test-fixtures/test snapshot in git
        # TEST split behavior is well-defined: only generate full-specimen example


def test_generate_examples_unique_file_sets(synced_db: Database):
    """Test that duplicate file sets are deduplicated by the VIEW using git fixtures."""
    with synced_db.session() as session:
        slug = SnapshotSlug("test-fixtures/train1")

        # test-trivial fixture already has multiple file sets; the view should deduplicate them
        examples = session.query(Example).filter_by(snapshot_slug=slug).all()
        assert examples, "Expected examples for test-trivial fixture"

        file_set_examples = [ex for ex in examples if ex.example_kind == ExampleKind.FILE_SET]
        whole_snapshot_examples = [ex for ex in examples if ex.example_kind == ExampleKind.WHOLE_SNAPSHOT]

        assert whole_snapshot_examples, "Whole-snapshot example not found"
        assert file_set_examples, "Expected at least one file-set example"

        # Deduplication: file_set_examples should have unique (snapshot_slug, files_hash)
        file_set_keys = {(ex.snapshot_slug, ex.files_hash) for ex in file_set_examples}
        assert len(file_set_keys) == len(file_set_examples), "File-set examples should already be deduplicated"

        # Expect exactly one whole-snapshot row
        assert len(whole_snapshot_examples) == 1, "Expected exactly one whole-snapshot example"

        # Total examples = unique file sets + one whole-snapshot
        assert len(examples) == len(file_set_examples) + 1


def test_recall_denominator_counts_at_occurrence_level(synced_db: Database):
    """Regression: recall_denominator must count at the occurrence level, not TP level.

    tp-006 has two occurrences: occ-add (scoped to add.py) and occ-subtract
    (scoped to subtract.py). The file-set example for add.py should only count
    occ-add, not both. Before the fix, is_tp_in_expected_recall_scope operated
    at the TP level, so if any occurrence matched, all occurrences of that TP
    were counted — inflating recall_denominator.
    """
    slug = SnapshotSlug("test-fixtures/train1")

    with synced_db.session() as session:
        # Find the file-set example containing only subtract.py
        subtract_fs = (
            session.query(FileSet)
            .join(FileSetMember)
            .filter(FileSet.snapshot_slug == slug, FileSetMember.file_path == "subtract.py")
            .first()
        )
        assert subtract_fs is not None

        # Verify subtract.py is the only file in this set
        subtract_members = (
            session.query(FileSetMember.file_path)
            .filter_by(snapshot_slug=slug, files_hash=subtract_fs.files_hash)
            .all()
        )
        assert [m.file_path for m in subtract_members] == ["subtract.py"]

        subtract_example = (
            session.query(Example)
            .filter_by(snapshot_slug=slug, example_kind=ExampleKind.FILE_SET, files_hash=subtract_fs.files_hash)
            .one()
        )

        # tp-001 has occ-1 scoped to subtract.py -> counts
        # tp-006 has occ-subtract scoped to subtract.py -> counts
        # tp-006 has occ-add scoped to add.py -> must NOT count (different file)
        # tp-005 has scope [divide.py, subtract.py] -> counts (subtract.py is a subset? no,
        #   the scope is {divide.py, subtract.py} which is NOT a subset of {subtract.py})
        # So only tp-001/occ-1 and tp-006/occ-subtract should count = 2
        assert subtract_example.recall_denominator == 2, (
            f"subtract.py file-set should have recall_denominator=2 "
            f"(tp-001/occ-1 + tp-006/occ-subtract), got {subtract_example.recall_denominator}"
        )

        # Same check for add.py
        add_fs = (
            session.query(FileSet)
            .join(FileSetMember)
            .filter(FileSet.snapshot_slug == slug, FileSetMember.file_path == "add.py")
            .first()
        )
        assert add_fs is not None

        add_members = (
            session.query(FileSetMember.file_path).filter_by(snapshot_slug=slug, files_hash=add_fs.files_hash).all()
        )
        assert [m.file_path for m in add_members] == ["add.py"]

        add_example = (
            session.query(Example)
            .filter_by(snapshot_slug=slug, example_kind=ExampleKind.FILE_SET, files_hash=add_fs.files_hash)
            .one()
        )

        # tp-002 has occ-1 scoped to add.py -> counts
        # tp-004 has occ-1 scoped to [add.py] OR [multiply.py] -> add.py scope is subset -> counts
        # tp-006 has occ-add scoped to add.py -> counts
        # tp-006 has occ-subtract scoped to subtract.py -> must NOT count
        assert add_example.recall_denominator == 3, (
            f"add.py file-set should have recall_denominator=3 "
            f"(tp-002/occ-1 + tp-004/occ-1 + tp-006/occ-add), got {add_example.recall_denominator}"
        )

        # Whole-snapshot should include ALL 7 occurrences (6 TPs, tp-006 has 2)
        whole_example = (
            session.query(Example).filter_by(snapshot_slug=slug, example_kind=ExampleKind.WHOLE_SNAPSHOT).one()
        )
        assert whole_example.recall_denominator == 7, (
            f"Whole-snapshot should count all 7 occurrences, got {whole_example.recall_denominator}"
        )


if __name__ == "__main__":
    pytest_bazel.main()
