"""Settings for the auth-aware Grocy MCP server.

Pure environment-variable config. Mirrors <x/authentik_mcp_poc/config.py>.
"""

from __future__ import annotations

from urllib.parse import urlparse, urlunparse

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class ServerSettings(BaseSettings):
    """Config for the Grocy MCP server."""

    model_config = SettingsConfigDict(env_prefix="GROCY_MCP_")

    oidc_issuer: str = Field(
        description="Authentik per-provider issuer URL, e.g. https://auth.allegedly.works/application/o/grocy-mcp/"
    )
    oidc_client_id: str = Field(description="OAuth2 client_id for the Authentik user-login OAuth2 provider")
    oidc_client_secret: str = Field(description="OAuth2 client_secret for the Authentik user-login OAuth2 provider")
    public_base_url: str = Field(
        description="Public URL at which this MCP server is reachable, e.g. https://grocy-mcp.allegedly.works"
    )
    grocy_url: str = Field(
        description="Public URL of the outpost-protected Grocy instance, e.g. https://grocy.allegedly.works"
    )
    # Used as `client_id` in the RFC 7521 jwt-bearer token exchange that each
    # tool call performs before hitting Grocy. See auth.py::AuthentikExchangeAuth
    # and NOTES.md §5 in x/authentik_mcp_poc.
    grocy_proxy_client_id: str = Field(
        description=(
            "client_id of the existing Grocy authentik_provider_proxy (the inner "
            "OAuth2 client auto-generated by Authentik on the proxy provider). "
            "Used as the `client_id` in the JWT-bearer token exchange."
        )
    )
    host: str = "0.0.0.0"
    port: int = 8765

    def normalized_public_base_url(self) -> str:
        return self.public_base_url.rstrip("/")

    def normalized_issuer(self) -> str:
        return self.oidc_issuer.rstrip("/")

    def authentik_token_endpoint(self) -> str:
        """Global Authentik `/application/o/token/` URL derived from `oidc_issuer`.

        Derivation rules match <x/authentik_mcp_poc/config.py>: strip only the
        trailing provider slug, preserving any reverse-proxy path prefix before
        `/application/o/`, so `.../auth/application/o/<slug>/` yields
        `.../auth/application/o/token/`.
        """
        parsed = urlparse(self.oidc_issuer.rstrip("/"))
        prefix, marker, provider_slug = parsed.path.rpartition("/application/o/")
        if not marker or not provider_slug or "/" in provider_slug:
            raise ValueError(
                "oidc_issuer must end in an Authentik per-provider issuer path "
                f"like `.../application/o/<slug>/`; got {self.oidc_issuer!r}"
            )
        return urlunparse(parsed._replace(path=f"{prefix}{marker}token/"))
