# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "image_automation",
    srcs = ["image_automation.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s:manifest_roots",
        "//cluster/cdk8s:metadata",
        "//cluster/cdk8s/providers/flux:gitrepository",
        "//cluster/cdk8s/providers/flux:imagepolicy",
        "//cluster/cdk8s/providers/flux:imagerepository",
        "//cluster/cdk8s/providers/flux:imageupdateautomation",
        "//cluster/cdk8s/providers/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
    ],
)
