load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "sandbox",
    srcs = [
        "config.go",
        "install.go",
        "runtime.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/sandbox",
    visibility = ["//claude_web_env/re/environment_manager/a6f96673/src:__subpackages__"],
)
