"""Private native financial primitives; Python owns domain objects and sessions."""

from typing import Literal

from finance.augur.sim.prepared import CompiledRun

class _PreparedWorlds:
    """One parsed immutable input shared by independently owned financial worlds."""

    def __init__(self, run: CompiledRun) -> None: ...
    def world(
        self, rollout_id: int, initial_marks_json: str, *,
        capture: Literal["summary", "dense", "forensic"],
        actor: str | None = None, product_actor: str | None = None,
    ) -> _World: ...

class _World:
    """Exactly one rollout's books; the caller supplies all ordering and stop decisions."""

    def prepare_month(self, month: int) -> None: ...
    def observe_json(self, actor: str) -> str: ...
    def apply_json(self, actor: str, action_json: str, action_index: int) -> str: ...
    def account_balance(self, actor: str, account: str) -> int | None: ...
    def component_distribution(self, distribution_index: int, total: int) -> None: ...
    def apply_component_json(
        self, actor: str, cause_id: str, effects_json: str,
        action_json: str | None = None, *,
        operation: Literal["modeled_realization", "redemption"] = "modeled_realization",
    ) -> None: ...
    def set_component_marks_json(self, marks_json: str) -> None: ...
    def scheduled_sale(self, sale_index: int) -> None: ...
    def settle_claims_json(self) -> str: ...
    def run_private_equity(self) -> None: ...
    def unpaid_claims_json(self, actor: str) -> str: ...
    def close_month(self, *, failed: bool, shortfall: int) -> None: ...
    def finish_json(self) -> str: ...
