load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "ortools_cpsat_smoke_test",
    size = "small",
    srcs = ["ortools_cpsat_smoke_test.cc"],
    deps = [
        "@abseil-cpp//absl/log:check",
        "@or-tools//ortools/sat:cp_model",
        "@or-tools//ortools/sat:cp_model_solver",
    ],
)
