# Authentik wiring for the Authentik MCP POC.
#
# Creates two providers bound together by JWT federation:
#
#   1. OAuth2 provider "authentik-mcp-poc" — the user-login authorization
#      server that FastMCP's OIDCProxy wraps. claude.ai runs the OAuth 2.1 +
#      PKCE + RFC 7591 DCR flow against the MCP server, which proxies it to
#      this provider and returns an Authentik-signed JWT.
#
#   2. Proxy provider "authentik-mcp-poc-backend" — sits in front of the
#      whoami backend via the shared embedded Authentik outpost. Its
#      jwt_federation_providers list references the OAuth2 provider above,
#      so the outpost accepts JWTs minted for the MCP server as Bearer auth
#      on the backend. The outpost then rewrites to internal_host and
#      injects X-Authentik-* headers that the backend trusts.
#
# See tf/gitops/airlock-oidc-proxy/main.tf (OAuth2 side) and
# tf/gitops/agent-machine-access/main.tf (proxy side) for
# the templates this module is stitched from.

terraform {
  required_version = ">= 1.0"

  required_providers {
    authentik = {
      source  = "goauthentik/authentik"
      version = "~> 2026.2"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.35"
    }
  }

  backend "kubernetes" {
    secret_suffix = "authentik-mcp-poc"
    namespace     = "flux-system"
  }
}

data "kubernetes_secret" "authentik_bootstrap" {
  metadata {
    name      = "authentik-bootstrap"
    namespace = "authentik"
  }
}

provider "authentik" {
  url   = "http://authentik-server.authentik.svc.cluster.local"
  token = data.kubernetes_secret.authentik_bootstrap.data["AUTHENTIK_BOOTSTRAP_TOKEN"]
}

# --- Shared data sources (flows, signing key, scopes, groups) ---

data "authentik_flow" "authentication" {
  slug = "default-authentication-flow"
}

data "authentik_flow" "implicit_consent" {
  slug = "default-provider-authorization-implicit-consent"
}

data "authentik_flow" "invalidation" {
  slug = "default-provider-invalidation-flow"
}

data "authentik_certificate_key_pair" "self_signed" {
  name = "authentik Self-signed Certificate"
}

data "authentik_property_mapping_provider_scope" "openid" {
  managed = "goauthentik.io/providers/oauth2/scope-openid"
}

data "authentik_property_mapping_provider_scope" "email" {
  managed = "goauthentik.io/providers/oauth2/scope-email"
}

data "authentik_property_mapping_provider_scope" "profile" {
  managed = "goauthentik.io/providers/oauth2/scope-profile"
}

data "authentik_group" "admins" {
  name = "authentik Admins"
}

# --- OAuth2 provider + application (user login, OIDCProxy upstream) ---
# Confidential client; client_secret auto-generated by Authentik and shipped
# to the app namespace via kubernetes_secret below.

resource "authentik_provider_oauth2" "mcp_poc" {
  name               = "authentik-mcp-poc"
  client_id          = "authentik-mcp-poc"
  client_type        = "confidential"
  authorization_flow = data.authentik_flow.implicit_consent.id
  invalidation_flow  = data.authentik_flow.invalidation.id
  signing_key        = data.authentik_certificate_key_pair.self_signed.id

  issuer_mode                = "per_provider"
  include_claims_in_id_token = true

  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]

  allowed_redirect_uris = [
    {
      matching_mode = "strict"
      # OIDCProxy's redirect path defaults to "/auth/callback" relative to the
      # FastMCP server's `base_url`. We deliberately set `base_url` to the bare
      # public URL (no /mcp) in x/authentik_mcp_poc/server.py so OAuth metadata
      # URLs collapse correctly — see the comment in `_build_auth` for why.
      url = "https://authentik-mcp-poc.allegedly.works/auth/callback"
    },
  ]
}

resource "authentik_application" "mcp_poc" {
  name              = "Authentik MCP POC"
  slug              = "authentik-mcp-poc"
  protocol_provider = authentik_provider_oauth2.mcp_poc.id
  meta_description  = "POC remote MCP server — OIDCProxy upstream for user login"
  meta_launch_url   = "https://authentik-mcp-poc.allegedly.works"
}

resource "authentik_policy_binding" "mcp_poc_admins" {
  target = authentik_application.mcp_poc.uuid
  group  = data.authentik_group.admins.id
  order  = 0
}

# --- Proxy provider + application (backend forward-auth via outpost) ---
# jwt_federation_providers makes the embedded outpost accept Bearer JWTs
# issued by authentik_provider_oauth2.mcp_poc above. The outpost forwards
# to internal_host with X-Authentik-{Username,Email,Groups} headers set.

resource "authentik_provider_proxy" "mcp_poc_backend" {
  name                = "authentik-mcp-poc-backend"
  external_host       = "https://authentik-mcp-poc-backend.allegedly.works"
  internal_host       = "http://authentik-mcp-poc-backend.authentik-mcp-poc.svc.cluster.local:8080"
  mode                = "proxy"
  authentication_flow = data.authentik_flow.authentication.id
  authorization_flow  = data.authentik_flow.implicit_consent.id
  invalidation_flow   = data.authentik_flow.invalidation.id

  access_token_validity = "hours=24"

  # The crux of the POC: Bearer JWTs from the MCP server's OAuth2 provider
  # authenticate against this proxy outpost.
  jwt_federation_providers = [authentik_provider_oauth2.mcp_poc.id]
}

resource "authentik_application" "mcp_poc_backend" {
  name              = "Authentik MCP POC Backend"
  slug              = "authentik-mcp-poc-backend"
  protocol_provider = authentik_provider_proxy.mcp_poc_backend.id
  meta_description  = "POC whoami backend, sits behind the Authentik proxy outpost"
}

resource "authentik_policy_binding" "mcp_poc_backend_admins" {
  target = authentik_application.mcp_poc_backend.uuid
  group  = data.authentik_group.admins.id
  order  = 0
}

# --- K8s secret with OAuth2 client credentials for the MCP server ---
#
# The namespace is owned by the sibling `namespace/` Flux Kustomization
# (cluster/k8s/agents/authentik-mcp-poc/namespace), which the Flux
# Kustomization that applies this TF module dependsOn. Bootstrap order:
# namespace Kustomization → TF (writes secret into namespace) → app
# Kustomization (consumes secret).

resource "kubernetes_secret" "mcp_poc_oidc" {
  metadata {
    name      = "authentik-mcp-poc-oidc"
    namespace = "authentik-mcp-poc"
  }

  data = {
    # OIDCProxy wraps the user-login OAuth2 provider — these are the creds
    # it uses to complete the authorization_code grant with Authentik.
    client_id     = authentik_provider_oauth2.mcp_poc.client_id
    client_secret = authentik_provider_oauth2.mcp_poc.client_secret
    # The proxy provider's auto-generated OAuth2 client_id. The MCP server
    # uses this as the `client_id` in its JWT-bearer token exchange against
    # Authentik — see x/authentik_mcp_poc/server.py::_exchange_token_for_backend
    # and NOTES.md §5. No client_secret is needed: the JWT assertion IS the
    # authentication, and Authentik's __post_init_client_credentials_jwt
    # does not require a matching client_secret for the client_credentials
    # grant path.
    backend_client_id = authentik_provider_proxy.mcp_poc_backend.client_id
  }
}
