apiVersion: v1
kind: Service
metadata:
  name: public-coder-agent-proxy
  namespace: public-coder-agent
spec:
  selector:
    app.kubernetes.io/name: public-coder-agent-proxy
  ports:
    - name: proxy
      port: 8080
      targetPort: 8080
    - name: web
      port: 8081
      targetPort: 8081
