load("//devinfra/python:defs.bzl", "py_library", "py_test")

py_library(
    name = "lbrn2_writer",
    srcs = ["lbrn2_writer.py"],
    visibility = ["//laser:__subpackages__"],
)

py_test(
    name = "test_lbrn2_writer",
    srcs = ["test_lbrn2_writer.py"],
    deps = [
        ":lbrn2_writer",
        "//:conftest",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
