load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "benchmark_ollama_lib",
    srcs = ["benchmark_ollama.py"],
    imports = ["../.."],
    deps = [
        "//util/bazel:workspace",
        "@pypi//openai",
    ],
)

py_binary(
    name = "benchmark_ollama",
    imports = ["../.."],
    main_module = "hack.benchmark_ollama.benchmark_ollama",
    deps = [":benchmark_ollama_lib"],
)
