# gazelle:python_library_naming_convention $package_name$_lib
load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("//tools/lint:linters.bzl", "ruff_test")

py_library(
    name = "difftree_lib",
    srcs = [
        "__init__.py",
        "__main__.py",
        "config.py",
        "diff_tree.py",
        "parser.py",
        "progress_bar.py",
        "tree.py",
    ],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//click",
        "@pypi//rich",
        "@pypi//unidiff",
    ],
)

py_binary(
    name = "difftree",
    srcs = ["__main__.py"],
    main = "__main__.py",
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//click",
        "@pypi//rich",
    ],
)

py_test(
    name = "test_all",
    srcs = [
        "conftest.py",
        "test_cli.py",
        "test_config.py",
        "test_diff_tree.py",
        "test_e2e.py",
        "test_parser.py",
        "test_progress_bar.py",
        "test_snapshots.py",
        "test_tree.py",
    ],
    data = ["__snapshots__/test_snapshots.ambr"],
    imports = [".."],
    main = "test_diff_tree.py",
    deps = [
        ":difftree_lib",
        "@pypi//click",
        "@pypi//pyhamcrest",
        "@pypi//pytest",
        "@pypi//pytest_asyncio",  # keep
        "@pypi//pytest_bazel",
        "@pypi//rich",
        "@pypi//syrupy",
    ],
)

ruff_test(
    name = "ruff",
    srcs = [":difftree_lib"],
)

py_library(
    name = "__init__",
    srcs = ["__init__.py"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "config",
    srcs = ["config.py"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "diff_tree",
    srcs = ["diff_tree.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//rich"],
)

py_library(
    name = "parser",
    srcs = ["parser.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//unidiff"],
)

py_library(
    name = "progress_bar",
    srcs = ["progress_bar.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//rich"],
)

py_library(
    name = "tree",
    srcs = ["tree.py"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":__init__",
        "@pypi//pytest",
        "@pypi//rich",
    ],
)

py_test(
    name = "test_cli",
    srcs = ["test_cli.py"],
    deps = [
        ":__init__",
        "@pypi//click",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_config",
    srcs = ["test_config.py"],
    deps = [
        ":__init__",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_diff_tree",
    srcs = ["test_diff_tree.py"],
    deps = [
        ":__init__",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
        "@pypi//rich",
    ],
)

py_test(
    name = "test_e2e",
    srcs = ["test_e2e.py"],
    deps = [
        ":__init__",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_parser",
    srcs = ["test_parser.py"],
    deps = [
        ":__init__",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_progress_bar",
    srcs = ["test_progress_bar.py"],
    deps = [
        ":__init__",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_snapshots",
    srcs = ["test_snapshots.py"],
    deps = [
        ":__init__",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_tree",
    srcs = ["test_tree.py"],
    deps = [
        ":__init__",
        "@pypi//pyhamcrest",
        "@pypi//pytest_bazel",
    ],
)
