apiVersion: v1
kind: Secret
metadata:
    name: litellm-gemini-key
    namespace: litellm
    annotations:
        description: Google AI (Gemini) API key for LiteLLM gemini upstream chat models.
type: Opaque
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:nFJIAy+7pBiQQ3asKtFDUJtziMdo6lGbggJtimPHcCcnYJKQAoEE,iv:1vp5A7wt2effBxnzGEsOizLD/IRhWh3nBs127QmsWtE=,tag:IZ0LmlngkTcPGBz5DYC7HQ==,type:str]
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dll3QVNSRWFhSlF1ZTFz
            U3JFV1NjbTRyWTFWOWdHd0prUWloL2lxWHpzCll2UUQwUEVGdDZWcUFnY3hwUGlw
            c3BKUUlEMmVZSWRhRlh4TlU2d1hLL0EKLS0tIHZqOUdLbzhGUytCaVR1VnhGdnU2
            cVVNYjVwWTBZcVhUb3R1MG1ZRk5JTVUKxlRX65v58b/TxZzmkhCjzx0I1Od2C8XU
            /bysfDrTq++cszV0j+uUbJmpSnPFM9+JQvUmbG+K9VwdLOelazoCpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSmJ1a0pCNzU4YnNqcjBl
            cXFoZEwzanBSS2N2SnQ5cXM5SVlYeDN1L2tNCjZsOWVLRmJ4bHh2dk1WODhoMDU1
            TnhvekprM3N6a0lnK0JJNkY3dEZNV1kKLS0tIGRXTlRiSTBHWHROZ0pLd2JpeSt5
            Tno5NDM5MjhxMkdJN3R4bzJDNVdQSXcK7138EvzRvH3bcEjpv0tEJ6aPqtUr00b9
            t05XduUrdCBVkb7DiCaqv+kznQ3mVGgzeOszFYtKjK9vktmwXXgsHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T12:58:11Z"
    mac: ENC[AES256_GCM,data:PtOuwMtDTpzIioJhOoC55S+hVVNhSXaL5loOigDSayX0Pk4QMmS6H/KzJMKIC2u2KPPXPtKKENsNTEBgR04vJQMiKoL2q1mdFcEWrpX5lYlMqfPEfXx6xr/7hXtFqMc0WHUw6i92eQPUdcdrIBB5Tjv4dEemmYpcvvXBDgMscFY=,iv:Or9+wqSXJzkb9w88okG7BFk+QVWKSQ3Ruv3PwE20PEo=,tag:XDm6BLJPjgX3R6FhOhgkxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
