apiVersion: v1
kind: Secret
metadata:
    name: litellm-groq-key
    namespace: litellm
    annotations:
        description: Groq API key for LiteLLM's groq upstream models (whisper + Llama chat).
type: Opaque
stringData:
    GROQ_API_KEY: ENC[AES256_GCM,data:OJxxVVuQTvqdfEHJSNVjbnucHJFLOE7J+/zWmylpnhN7Gqq4EIVZUrmsxhrSaYmnmAdDiUsfy+8=,iv:kYMR97elkrlyqndHnO8kHDrXd7CT/mFeUF6V12PfK3s=,tag:aeEFhYyrq3emHe0VgVfRKw==,type:str]
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySVQwMmxmSktCTVNITWs3
            WFZwd05nZFNjUG82QUpzQ2VpaVRiRzh1c2pNCjFHUUd5S0NEV2R6ODljMnhXMW5P
            SGx4a2hncnRxWFB2U3VHOEprUVRTMnMKLS0tIHkrT3liUWpMRHhuRjlybG5mTEdo
            MElPYUtmTXRpdG9oTGpuTFBqY2pCS3cKRqnmnAzmIb16z4VpcvW1c9xuHCFDwJiu
            pmiZxixNQD4E+BKhQpu0aUCAcqodlSe5QNoLkcrhf/JwxkMpgzi4wg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcDlvck5ZZzl6ZExacUZC
            czhKcjdQNWxzNStWZ2R6QWI0MDlSTkdRbTJZCmlFOFkrTTZZVlBWOS9sTGNOTXN2
            b3BxVVdxL3FqVml0NytKZGFQK01GaGMKLS0tIGtzSDNpYVI5Y0xYU01WanZGZVIr
            d2pMRk1ob1VyRUVIS2RsejZxbS9kdzQKYc4lNkOSpwk1MG7AgOfQhAN05niOeS/e
            G7SwcZnw5SQzIGSkxOhEaUKOpHpCvArw4tJf4Qt4XTNA58p6x2K/EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T10:51:17Z"
    mac: ENC[AES256_GCM,data:DH9MmKf9DnWew/ZuLqWj0xzFMKyzrPeUM2Di3lNgs8p2OUp5RzltFa2LSLMqgunSCMwSOpJxgR1vByTzAb0l+De1t+C64zuwhHBoCVtcs48KCaK/gozhANyKymNOCTO1xWIcVPxl8aaEJsb4hq0ezojBlZJ2de/4Fh1CwoSjlyo=,iv:L63dOkpD7wbiZNXASO6JS4pr6qtxr5TEA10UQ/jI6M4=,tag:+sV0E8w6WFy1L9dfX8lKiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
