//! Concrete payment actions and their financial execution. Expected request rejections
//! change no books; arithmetic/accounting defects remain explicit simulator errors.
//! The actor runner must stop that rollout at the first rejection, preserving preceding
//! successful actions; this primitive does not call policy or attempt a rescue.

use super::*;

/// Pay one identified claim in full from a declared cash account of its payer.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct PayClaim {
    pub request_id: u64,
    pub cause_id: String,
    pub claim: claims::ClaimId,
    pub from: AccountRef,
    pub amount: Money,
}

/// Chosen consumption paid to another actor, not a liability generated by a contract.
/// Moving cash between one's own accounts is a transfer, not consumption.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct Consume {
    pub request_id: u64,
    pub cause_id: String,
    pub component_id: String,
    pub from: AccountRef,
    pub to: AccountRef,
    pub amount: Money,
}

#[derive(Clone, Debug)]
pub enum Request {
    PayClaim(PayClaim),
    Consume(Consume),
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
#[serde(tag = "kind")]
pub enum Target {
    Claim(claims::ClaimId),
    Consumption { component_id: String },
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
#[serde(tag = "kind")]
pub enum Rejection {
    UnknownClaim,
    AlreadyPaid,
    WrongActor,
    SameActorRecipient,
    UnknownAccount,
    InvalidAmount,
    EmptyIdentifier,
    InsufficientCash { available: Money },
    UnfundedGroup { available: Money, due: Money },
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
#[serde(tag = "kind", content = "reason")]
pub enum Outcome {
    Paid,
    Rejected(Rejection),
}

/// Request IDs are caller-owned within the routed actor/decision batch. Claims have
/// separate engine-owned occurrence IDs. Full payment or rejection are the supported
/// outcomes; a rejected request is not a partly funded payment.
#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
pub struct Receipt {
    pub request_id: u64,
    pub target: Target,
    pub amount_requested: Money,
    pub outcome: Outcome,
}

impl Receipt {
    pub fn amount_paid(&self) -> Money {
        if self.outcome == Outcome::Paid {
            self.amount_requested
        } else {
            Money(0)
        }
    }

    /// Shared projection for a resolved payment target. Callers choose their reporting
    /// label; it is not the request ID or the engine's claim-occurrence identity.
    pub(super) fn obligation(
        &self,
        request: &Request,
        target: &Description<'_>,
        month: u32,
        obligation_id: &str,
    ) -> Result<ObligationOutcome, ArithmeticError> {
        let amount_paid = self.amount_paid();
        Ok(ObligationOutcome {
            month,
            cause_id: request.cause_id().into(),
            obligation_id: obligation_id.into(),
            obligation_type: target.obligation_type.into(),
            from: request.from().clone(),
            to: target.to.clone(),
            amount_due: self.amount_requested,
            amount_paid,
            shortfall: self.amount_requested.checked_sub(amount_paid)?,
            failure_active: self.outcome != Outcome::Paid,
        })
    }
}

pub(super) struct Description<'a> {
    pub to: &'a AccountRef,
    pub obligation_type: &'a str,
    pub label: &'a str,
    pub is_tax_payment: bool,
}

impl Request {
    pub(super) fn describe<'a>(&'a self, claims: &'a Claims) -> Option<Description<'a>> {
        Some(match self {
            Self::PayClaim(request) => {
                if request.claim.month != claims.month {
                    return None;
                }
                let claim = claims.entries.get(request.claim.index)?;
                Description {
                    to: &claim.to,
                    obligation_type: &claim.obligation_type,
                    label: &claim.cause_id,
                    is_tax_payment: matches!(
                        claim.effect,
                        ObligationEffect::TaxPayment { .. } | ObligationEffect::TaxTrueUp { .. }
                    ),
                }
            }
            Self::Consume(request) => Description {
                to: &request.to,
                obligation_type: "cash_spend",
                label: &request.component_id,
                is_tax_payment: false,
            },
        })
    }
    pub(super) fn from(&self) -> &AccountRef {
        match self {
            Self::PayClaim(request) => &request.from,
            Self::Consume(request) => &request.from,
        }
    }

    pub(super) fn amount(&self) -> Money {
        match self {
            Self::PayClaim(request) => request.amount,
            Self::Consume(request) => request.amount,
        }
    }

    pub(super) fn cause_id(&self) -> &str {
        match self {
            Self::PayClaim(request) => &request.cause_id,
            Self::Consume(request) => &request.cause_id,
        }
    }

    pub(super) fn receipt(&self, outcome: Outcome) -> Receipt {
        let (request_id, target) = match self {
            Self::PayClaim(request) => (request.request_id, Target::Claim(request.claim)),
            Self::Consume(request) => (
                request.request_id,
                Target::Consumption {
                    component_id: request.component_id.clone(),
                },
            ),
        };
        Receipt {
            request_id,
            target,
            amount_requested: self.amount(),
            outcome,
        }
    }
}

pub(super) struct Context<'a> {
    pub fixture: &'a ExecutionInput,
    pub ledger: &'a mut Ledger,
    pub recorder: &'a mut Recorder,
    pub tax: &'a mut TaxState,
    pub properties: &'a [PropertyState],
    pub mortgages: &'a mut [MortgageState],
    pub tax_liabilities: &'a mut [TaxLiabilityState],
    pub month: u32,
}

struct Payment<'a> {
    cause_id: &'a str,
    obligation_type: &'a str,
    from: &'a AccountRef,
    to: &'a AccountRef,
    amount: Money,
    effect: &'a ObligationEffect,
}

impl Context<'_> {
    fn execute_funded(&mut self, payment: &Payment<'_>) -> Result<(), SimulationError> {
        let fixture = self.fixture;
        let month = self.month;
        let ledger = &mut *self.ledger;
        let recorder = &mut *self.recorder;
        let tax = &mut *self.tax;
        let mortgages = &mut *self.mortgages;
        let properties = self.properties;
        let tax_liabilities = &mut *self.tax_liabilities;
        let firing_id = payment.cause_id.to_owned();
        match *payment.effect {
            ObligationEffect::None => transfer_money(
                ledger,
                recorder,
                month,
                &firing_id,
                payment.from,
                payment.to,
                payment.amount,
            )?,
            ObligationEffect::OrdinaryDeduction {
                deductible_fraction_ppb,
            } => {
                transfer_money(
                    ledger,
                    recorder,
                    month,
                    &firing_id,
                    payment.from,
                    payment.to,
                    payment.amount,
                )?;
                record_ordinary_deduction(
                    tax,
                    &payment.from.agent_id,
                    payment.amount,
                    deductible_fraction_ppb,
                )?;
            }
            ObligationEffect::PropertyTax {
                ref owner_agent_id,
                rented_fraction_ppb,
            } => {
                transfer_money(
                    ledger,
                    recorder,
                    month,
                    &firing_id,
                    payment.from,
                    payment.to,
                    payment.amount,
                )?;
                record_property_tax_paid(tax, owner_agent_id, payment.amount, rented_fraction_ppb)?;
            }
            ObligationEffect::TaxPayment { profile_index } => {
                book_tax_payment(
                    ledger,
                    recorder,
                    month,
                    &firing_id,
                    &fixture.scenario.tax_profiles[profile_index],
                    payment.from,
                    payment.amount,
                )?;
            }
            ObligationEffect::TaxTrueUp {
                profile_index,
                tax_year_end_month,
            } => {
                book_tax_payment(
                    ledger,
                    recorder,
                    month,
                    &firing_id,
                    &fixture.scenario.tax_profiles[profile_index],
                    payment.from,
                    payment.amount,
                )?;
                let profile = &fixture.scenario.tax_profiles[profile_index];
                let settled = settle_tax_liabilities(
                    ledger,
                    recorder,
                    tax_liabilities,
                    month,
                    profile,
                    tax_year_end_month,
                )?;
                recorder.record_tax_settlement(TaxSettlementOutcome {
                    month,
                    cause_id: format!(
                        "{}_tax_settlement_y{}",
                        profile.agent_id,
                        (tax_year_end_month - 11) / 12
                    ),
                    agent_id: profile.agent_id.clone(),
                    tax_year_end_month,
                    amount: settled,
                })?;
            }
            ObligationEffect::Mortgage {
                mortgage_index,
                interest,
                principal,
            } => {
                let mortgage = &mut mortgages[mortgage_index];
                recorder.apply_entry(
                    ledger,
                    JournalEntry {
                        month,
                        cause_id: firing_id.clone(),
                        postings: vec![
                            Posting {
                                account: payment.from.clone(),
                                amount: payment.amount.checked_neg()?,
                            },
                            Posting {
                                account: payment.to.clone(),
                                amount: payment.amount,
                            },
                            Posting {
                                account: mortgage_liability_account(
                                    &mortgage.agent_id,
                                    &mortgage.liability_id,
                                ),
                                amount: principal,
                            },
                            Posting {
                                account: mortgage_interest_expense_account(
                                    &mortgage.agent_id,
                                    &mortgage.liability_id,
                                ),
                                amount: interest,
                            },
                            Posting {
                                account: mortgage_receivable_account(
                                    &mortgage.counterparty_agent_id,
                                    &mortgage.liability_id,
                                ),
                                amount: principal.checked_neg()?,
                            },
                            Posting {
                                account: mortgage_interest_income_account(
                                    &mortgage.counterparty_agent_id,
                                    &mortgage.liability_id,
                                ),
                                amount: interest.checked_neg()?,
                            },
                        ],
                    },
                )?;
                mortgage.principal = mortgage.principal.checked_sub(principal)?;
                mortgage.interest_paid_ytd = mortgage.interest_paid_ytd.checked_add(interest)?;
                let rented_fraction_ppb = properties
                    .iter()
                    .find(|property| property.property_id == mortgage.property_id)
                    .map_or(0, |property| property.rented_fraction_ppb);
                let rental_interest = interest.scaled_by(
                    Factor::parts_per_billion(rented_fraction_ppb),
                    "rental mortgage interest",
                )?;
                mortgage.rental_interest_paid_ytd = mortgage
                    .rental_interest_paid_ytd
                    .checked_add(rental_interest)?;
                record_rental_interest_deduction(tax, &mortgage.agent_id, rental_interest)?;
                if mortgage.principal == Money(0) {
                    mortgage.active = false;
                }
                recorder.record_mortgage_payment(MortgagePaymentOutcome {
                    month,
                    cause_id: firing_id.clone(),
                    liability_id: mortgage.liability_id.clone(),
                    agent_id: mortgage.agent_id.clone(),
                    counterparty_agent_id: mortgage.counterparty_agent_id.clone(),
                    property_id: mortgage.property_id.clone(),
                    from_account_id: payment.from.account_id.clone(),
                    to_account_id: mortgage.counterparty_account_id.clone(),
                    interest,
                    principal,
                    total_payment: payment.amount,
                })?;
            }
        }

        if matches!(
            payment.effect,
            ObligationEffect::TaxPayment { .. } | ObligationEffect::TaxTrueUp { .. }
        ) {
            recorder.record_tax_payment(TaxPaymentOutcome {
                month,
                cause_id: firing_id.clone(),
                agent_id: payment.from.agent_id.clone(),
                obligation_type: payment.obligation_type.into(),
                amount_due: payment.amount,
                amount_paid: payment.amount,
                shortfall: Money(0),
            })?;
        }
        if payment.amount.0 > 0 {
            recorder.record_transfer(TransferOutcome {
                month,
                cause_id: firing_id,
                from: payment.from.clone(),
                to: payment.to.clone(),
                amount: payment.amount,
                income_category: None,
            });
        }
        Ok(())
    }

    fn prepare<'a>(
        &self,
        actor: &str,
        claims: &'a claims::Claims,
        request: &'a Request,
    ) -> Result<Payment<'a>, Rejection> {
        if request.from().agent_id != actor {
            return Err(Rejection::WrongActor);
        }
        if request.cause_id().is_empty() {
            return Err(Rejection::EmptyIdentifier);
        }
        let payment = match request {
            Request::PayClaim(request) => {
                if request.claim.month != self.month || request.claim.month != claims.month {
                    return Err(Rejection::UnknownClaim);
                }
                let claim = claims
                    .entries
                    .get(request.claim.index)
                    .ok_or(Rejection::UnknownClaim)?;
                if claim.from.agent_id != actor {
                    return Err(Rejection::WrongActor);
                }
                if claim.paid {
                    return Err(Rejection::AlreadyPaid);
                }
                if request.amount != claim.amount_due {
                    return Err(Rejection::InvalidAmount);
                }
                Payment {
                    cause_id: &request.cause_id,
                    obligation_type: &claim.obligation_type,
                    from: &request.from,
                    to: &claim.to,
                    amount: request.amount,
                    effect: &claim.effect,
                }
            }
            Request::Consume(request) => {
                if request.to.agent_id == actor {
                    return Err(Rejection::SameActorRecipient);
                }
                if request.amount.0 <= 0 {
                    return Err(Rejection::InvalidAmount);
                }
                if request.component_id.is_empty() {
                    return Err(Rejection::EmptyIdentifier);
                }
                Payment {
                    cause_id: &request.cause_id,
                    obligation_type: "cash_spend",
                    from: &request.from,
                    to: &request.to,
                    amount: request.amount,
                    effect: &ObligationEffect::None,
                }
            }
        };
        for account in [payment.from, payment.to] {
            if !self
                .fixture
                .scenario
                .accounts
                .iter()
                .any(|spec| &spec.account == account)
            {
                return Err(Rejection::UnknownAccount);
            }
        }
        Ok(payment)
    }

    pub(super) fn execute(
        &mut self,
        actor: &str,
        claims: &mut claims::Claims,
        request: &Request,
    ) -> Result<Receipt, SimulationError> {
        let payment = match self.prepare(actor, claims, request) {
            Ok(payment) => payment,
            Err(reason) => return Ok(request.receipt(Outcome::Rejected(reason))),
        };
        let available = self.ledger.balance(payment.from)?;
        if available.0 < payment.amount.0 {
            return Ok(
                request.receipt(Outcome::Rejected(Rejection::InsufficientCash { available }))
            );
        }
        self.execute_funded(&payment)?;
        if let Request::PayClaim(request) = request {
            claims.entries[request.claim.index].paid = true;
        }
        Ok(request.receipt(Outcome::Paid))
    }
}
