load("//devinfra/python:defs.bzl", "py_binary", "py_library", "py_test")

py_library(
    name = "check_run",
    srcs = ["check_run.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//pydantic",
        "@pypi//pygithub",
    ],
)

py_binary(
    name = "check_run_bin",
    main_module = "devinfra.pr_visuals.check_run",
    deps = [":check_run"],
)

py_library(
    name = "publisher",
    srcs = ["publisher.py"],
    data = [
        "pr_visual_test.html.j2",
        "pr_visuals.html.j2",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        ":check_run",
        "//devinfra/ci:invocation_ids",
        "//util:visual_diff",
        "//util:visual_review",
        "@pypi//boto3",
        "@pypi//botocore",
        "@pypi//jinja2",
        "@pypi//pydantic",
        "@pypi//pygithub",
        "@pypi//tenacity",
    ],
)

py_test(
    name = "test_check_run",
    srcs = ["test_check_run.py"],
    deps = [
        ":check_run",
        "//:conftest",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_binary(
    name = "publisher_bin",
    main_module = "devinfra.pr_visuals.publisher",
    deps = [":publisher"],
)

py_test(
    name = "test_publisher",
    srcs = ["test_publisher.py"],
    deps = [
        ":publisher",
        "//:conftest",
        "//devinfra/ci:invocation_ids",
        "//util:visual_diff",
        "//util:visual_review",
        "@pypi//pillow",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
