load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "input",
    srcs = [
        "secret.go",
        "v0_parser.go",
        "v1_parser.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/input",
    visibility = ["//claude_web_env/re/environment_manager/a6f96673/src:__subpackages__"],
    deps = [
        "//claude_web_env/re/environment_manager/a6f96673/src/internal/api",
        "//claude_web_env/re/environment_manager/a6f96673/src/internal/auth",
        "//claude_web_env/re/environment_manager/a6f96673/src/internal/claude",
        "//claude_web_env/re/environment_manager/a6f96673/src/internal/config",
        "//claude_web_env/re/environment_manager/a6f96673/src/internal/o11y",
    ],
)
