"""Managed file output for session_start hook.

Files generated by the session_start hook contain a canary marker that
identifies them as hook-generated. On subsequent runs the hook always
overwrites these files with the latest content so that configuration
stays in sync with the running hook version.
"""

import configparser
import io
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

CANARY_MARKER = "CANARY:SESSION_START_HOOK"
CANARY_HEADER = f"# {CANARY_MARKER} — Generated by tools/claude_hooks (session_start hook).\n"


def add_canary(content: str) -> str:
    """Insert canary header into content, respecting shebangs."""
    if content.startswith("#!"):
        first_newline = content.index("\n") + 1
        return content[:first_newline] + CANARY_HEADER + content[first_newline:]
    return CANARY_HEADER + content


def write_config(path: Path, content: str, description: str, *, canary: bool = True) -> None:
    """Write config file, always keeping it in sync with the hook.

    - File doesn't exist: create it (with canary header if canary=True)
    - File exists with exact same content: no-op (idempotent)
    - File exists with different content: overwrite with new content
    """
    full_content = add_canary(content) if canary else content
    if path.exists():
        existing = path.read_text()
        if existing == full_content:
            logger.debug("Config %s already has expected content", path)
            return
        logger.info("Updating %s at %s", description, path)
    path.write_text(full_content)
    logger.debug("Wrote %s to %s", description, path)


def write_ini_config(path: Path, config: configparser.ConfigParser, description: str) -> None:
    """Write a ConfigParser as a canary-protected INI file."""
    buf = io.StringIO()
    config.write(buf)
    write_config(path, buf.getvalue(), description)
