load("//devinfra/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//x/agentplane:__subpackages__"])

py_library(
    name = "process",
    srcs = ["process.py"],
    deps = ["@pypi//pydantic"],
)

py_test(
    name = "test_process",
    srcs = ["test_process.py"],
    deps = [
        ":process",
        "//:conftest",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
