apiVersion: v1
kind: Service
metadata:
  name: talos-etcd-metrics
  labels:
    app.kubernetes.io/name: talos-etcd-metrics
    app.kubernetes.io/part-of: monitoring
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 2381
      targetPort: 2381
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: talos-etcd-metrics
  labels:
    kubernetes.io/service-name: talos-etcd-metrics
    endpointslice.kubernetes.io/managed-by: ducktape-static
addressType: IPv4
ports:
  - name: metrics
    protocol: TCP
    port: 2381
endpoints:
  - addresses: ["10.42.0.13"]
    hostname: ovh-ns103656
    nodeName: ovh-ns103656
    conditions:
      ready: true
  - addresses: ["10.42.0.16"]
    hostname: ovh-ns104952
    nodeName: ovh-ns104952
    conditions:
      ready: true
  - addresses: ["10.42.0.17"]
    hostname: ovh-ns104963
    nodeName: ovh-ns104963
    conditions:
      ready: true
