apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: talos-etcd
  labels:
    app.kubernetes.io/name: talos-etcd-metrics
    app.kubernetes.io/part-of: monitoring
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: talos-etcd-metrics
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_endpointslice_endpoint_hostname]
          targetLabel: node
