load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

tf_providers_versions(
    name = "providers",
    providers = {
        "harbor": "goharbor/harbor:~>3.11",
        "kubernetes": "hashicorp/kubernetes:~>2.35",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "harbor-proxy-cache",
    providers = [
        "harbor",
        "kubernetes",
    ],
    providers_versions = ":providers",
)
