# Harbor Pull-Through Cache Configuration
# Creates proxy cache projects for upstream registries
# This module is independent of SSO/OIDC configuration

# Read Harbor admin password from Kubernetes secret
# Password generated by terraform/gitops/harbor-admin/main.tf
# Synced from Vault by ExternalSecret to harbor/harbor-admin-initial
data "kubernetes_secret" "harbor_admin_password" {
  metadata {
    name      = "harbor-admin-initial"
    namespace = "harbor"
  }
}

# Harbor provider using database auth
# Note: Admin user (UserID 1) always uses database auth, even when OIDC is configured
provider "harbor" {
  url      = var.harbor_url
  username = "admin"
  password = data.kubernetes_secret.harbor_admin_password.data["HARBOR_ADMIN_PASSWORD"]
}

# Docker Hub registry endpoint
resource "harbor_registry" "dockerhub" {
  provider_name = "docker-hub"
  name          = "dockerhub"
  endpoint_url  = "https://hub.docker.com"
  description   = "Docker Hub upstream registry"
}

# Docker Hub proxy cache project (PUBLIC for anonymous pulls)
resource "harbor_project" "dockerhub_proxy" {
  name        = "docker-hub-proxy"
  public      = true # Allow anonymous pulls without authentication
  registry_id = harbor_registry.dockerhub.registry_id

  lifecycle {
    prevent_destroy = false
  }
}

# GitHub Container Registry (GHCR) endpoint
resource "harbor_registry" "ghcr" {
  provider_name = "github"
  name          = "ghcr"
  endpoint_url  = "https://ghcr.io"
  description   = "GitHub Container Registry"
}

# GHCR proxy cache project
resource "harbor_project" "ghcr_proxy" {
  name        = "ghcr-proxy"
  public      = true
  registry_id = harbor_registry.ghcr.registry_id

  lifecycle {
    prevent_destroy = false
  }
}

# Quay.io registry endpoint
# Uses docker-registry adapter: quay adapter doesn't support proxy cache
resource "harbor_registry" "quay" {
  provider_name = "docker-registry"
  name          = "quay"
  endpoint_url  = "https://quay.io"
  description   = "Quay.io Container Registry"
}

# Quay proxy cache project
resource "harbor_project" "quay_proxy" {
  name        = "quay-proxy"
  public      = true
  registry_id = harbor_registry.quay.registry_id

  lifecycle {
    prevent_destroy = false
  }
}

# registry.k8s.io endpoint (Kubernetes official registry)
resource "harbor_registry" "k8s_registry" {
  provider_name = "docker-registry"
  name          = "k8s-registry"
  endpoint_url  = "https://registry.k8s.io"
  description   = "Kubernetes official registry"
}

# registry.k8s.io proxy cache project
resource "harbor_project" "k8s_registry_proxy" {
  name        = "registry-k8s-io-proxy"
  public      = true
  registry_id = harbor_registry.k8s_registry.registry_id

  lifecycle {
    prevent_destroy = false
  }
}

# Google Container Registry (GCR) endpoint
# Uses docker-registry adapter: google-gcr adapter's health check fails
# (GCR deprecated in favor of Artifact Registry)
resource "harbor_registry" "gcr" {
  provider_name = "docker-registry"
  name          = "gcr"
  endpoint_url  = "https://gcr.io"
  description   = "Google Container Registry"
}

# GCR proxy cache project
resource "harbor_project" "gcr_proxy" {
  name        = "gcr-proxy"
  public      = true
  registry_id = harbor_registry.gcr.registry_id

  lifecycle {
    prevent_destroy = false
  }
}
