load("@rules_python//python:defs.bzl", "py_binary")
load(":smoke_test.bzl", "smoke_test")

exports_files(["ruff.toml"])

platform(
    name = "rbe_linux_x64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
)

py_binary(
    name = "remote_smoke",
    srcs = ["remote_smoke.py"],
)

smoke_test(
    name = "remote_test_smoke",
    src = "test_smoke.sh",
    tags = ["manual"],
)

smoke_test(
    name = "local_test_smoke",
    src = "test_smoke.sh",
    tags = [
        "manual",
        "no-remote-exec",
    ],
)
