"""Derives the files that name an SSH target's host and pin its host key, one source per fact.

ssh-mcp's `known_hosts` and `settings.yaml` (cluster/k8s/ssh-mcp) and sshpiper's devbox `Pipe`
(cluster/k8s/agents/public-coder-agent/sshpiper) all name the devbox by its Service DNS and pin its
sshd key. The hostname comes from the devbox Service manifest and the key from
`ssh_keys/public-coder-devbox-host.pub`; the Nebula hosts' keys and the ssh-mcp target roster are
the tables below. `//cluster/ssh_targets:test_generate` fails until the committed output matches:

    bb run //cluster/ssh_targets:generate_bin
"""

from __future__ import annotations

import base64
from collections.abc import Callable, Mapping
from dataclasses import asdict, dataclass
from pathlib import Path

import yaml

from util.bazel.workspace import get_build_workspace_directory

DEVBOX_HOST_KEY = "ssh_keys/public-coder-devbox-host.pub"
DEVBOX_SERVICE = "cluster/k8s/agents/public-coder-agent/devbox/service.yaml"
# The Agent's downstream key; private half in cluster/k8s/agents/public-coder-agent/app/devbox-ssh-key.sops.yaml.
AGENT_DOWNSTREAM_KEY = "ssh_keys/public-coder-agent-devbox.pub"

SSH_MCP_KNOWN_HOSTS = "cluster/k8s/ssh-mcp/known_hosts"
SSH_MCP_SETTINGS = "cluster/k8s/ssh-mcp/settings.yaml"
SSHPIPER_PIPE = "cluster/k8s/agents/public-coder-agent/sshpiper/pipe-devbox.yaml"

_GENERATED = (
    "# Generated by `bb run //cluster/ssh_targets:generate_bin` (cluster/ssh_targets/generate.py); do not edit.\n"
)
_CONFIG_MAP_INPUT = (
    "# configMapGenerator input for ssh-mcp; not a standalone Kubernetes manifest (kubeconform-excluded).\n"
)

# The ssh-mcp-config ConfigMap's mount (cluster/k8s/ssh-mcp/deployment.yaml).
_SSH_MCP_CONFIG_DIR = "/etc/ssh-mcp"

_WYRM2 = "wyrm2.nebula.allegedly.works"
_RUGGED = "rugged.nebula.allegedly.works"
_ATLAS = "atlas.nebula.allegedly.works"

# Captured with ssh-keyscan over Nebula and cross-checked against the operator's own
# ~/.ssh/known_hosts fingerprints (wyrm2 SHA256:4pleXe119NlxDgg+Avgv7DRMokIe4jbQjJ3KKHarYzo; rugged
# SHA256:nh/8a1v7SFWm9UQVbTl6BfYXIjQ/RB5Y8yh+lg5nZjA, the same as its `rugged.tailnet.allegedly.works`
# entry) -- not blind first-contact TOFU. Unlike the devbox's, nothing in the repo persists these
# hosts' sshd keys, so a host-side rotation silently strands them until re-captured here (#6831).
# atlas is absent on purpose: it is not NixOS and ansible/atlas.yaml installs no host key, so its
# targets stay listed and fail closed until an operator runs
# `ssh-keyscan -t ed25519 atlas.nebula.allegedly.works` and adds the line.
_NEBULA_HOST_KEYS = {
    _WYRM2: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICAwoT0hzkNNzOUjFqb1g7jKQ3phR5XmPU5R52hfFCJZ",
    _RUGGED: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA5khWiTDnTSkz83F+0JwYIOOT+QpV0/u3cc02L5LLFm",
}


@dataclass(frozen=True)
class Target:
    host: str
    user: str
    identity_file: str  # container-side path; the Secret mounts are in cluster/k8s/ssh-mcp/deployment.yaml


def _targets(devbox: str) -> list[Target]:
    """(host, user) is a target's identity; a missing key file keeps it listed as unavailable."""
    return [
        Target(_WYRM2, "agentydragon", "/etc/ssh-mcp/keys/wyrm2-agentydragon"),
        Target(_WYRM2, "root", "/etc/ssh-mcp/keys/wyrm2-root"),
        Target(_RUGGED, "agentydragon", "/etc/ssh-mcp/keys/rugged-agentydragon"),
        Target(_RUGGED, "root", "/etc/ssh-mcp/keys/rugged-root"),
        # An in-cluster KubeVirt VM reached over its own ClusterIP Service, not a Nebula hostAlias.
        Target(devbox, "root", "/etc/ssh-mcp/keys-public-coder-devbox/public-coder-devbox-root"),
        Target(devbox, "coder", "/etc/ssh-mcp/keys-public-coder-devbox/public-coder-devbox-coder"),
        # A Nebula peer like wyrm2/rugged but not a Kubernetes node (Proxmox VE, ansible-managed);
        # fails closed until its host key is captured (_NEBULA_HOST_KEYS).
        Target(_ATLAS, "root", "/etc/ssh-mcp/keys-atlas/atlas-root"),
        Target(_ATLAS, "agentydragon", "/etc/ssh-mcp/keys-atlas/atlas-agentydragon"),
    ]


class _Dumper(yaml.SafeDumper):
    """Indents block sequences under their key, as prettier (pre-commit) formats them."""

    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
        super().increase_indent(flow, False)


def _yaml(header: str, document: Mapping[str, object]) -> str:
    return header + yaml.dump(document, Dumper=_Dumper, sort_keys=False)


def _b64(text: str) -> str:
    return base64.b64encode(text.encode()).decode()


def render(locate: Callable[[str], Path]) -> dict[str, str]:
    """Generated file contents by repo-relative path; `locate` resolves a source's repo-relative path."""
    service = yaml.safe_load(locate(DEVBOX_SERVICE).read_text())
    devbox = f"{service['metadata']['name']}.{service['metadata']['namespace']}.svc.cluster.local"
    [ssh_port] = service["spec"]["ports"]
    key_type, key, *_comment = locate(DEVBOX_HOST_KEY).read_text().split()
    devbox_key = f"{key_type} {key}"

    known_hosts = {**_NEBULA_HOST_KEYS, devbox: devbox_key}
    settings = {
        "known_hosts_file": f"{_SSH_MCP_CONFIG_DIR}/{Path(SSH_MCP_KNOWN_HOSTS).name}",
        "command_timeout_seconds": 300,
        "connect_timeout_seconds": 10,
        "output_limit_bytes": 65536,
        "max_concurrent_executions": 4,
        "targets": [asdict(target) for target in _targets(devbox)],
    }
    # Both spellings: which one sshpiper matches depends on how it normalizes the dialed address.
    pinned = "".join(f"{name} {devbox_key}\n" for name in (devbox, f"[{devbox}]:{ssh_port['port']}"))
    pipe = {
        "apiVersion": "sshpiper.com/v1beta1",
        "kind": "Pipe",
        "metadata": {"name": "devbox", "namespace": "public-coder-agent"},
        "spec": {
            # Exact username match, no username_regex_match: one downstream name, one route.
            "from": [{"username": "devbox", "authorized_keys_data": _b64(locate(AGENT_DOWNSTREAM_KEY).read_text())}],
            "to": {
                "host": f"{devbox}:{ssh_port['port']}",
                # `coder`, never `root`: the devbox authorizes the mapping key for that account only, so
                # the confinement does not depend on this file (haku/docs/security.md invariant #9).
                "username": "coder",
                "private_key_secret": {"name": "public-coder-agent-sshpiper-devbox-key"},
                # Left empty, sshpiper connects to whatever answers -- the failure mode this whole
                # arrangement exists to prevent.
                "known_hosts_data": _b64(pinned),
            },
        },
    }
    return {
        SSH_MCP_KNOWN_HOSTS: _GENERATED
        + _CONFIG_MAP_INPUT
        + "".join(f"{host} {host_key}\n" for host, host_key in known_hosts.items()),
        SSH_MCP_SETTINGS: _yaml(_GENERATED + _CONFIG_MAP_INPUT, settings),
        SSHPIPER_PIPE: _yaml(
            _GENERATED
            + "# The Agent's one route: `ssh devbox` in the Agent Pod lands here as downstream user `devbox` and\n"
            + "# is re-originated as `coder` on the VM with a mapping key the Agent never sees (README.md).\n",
            pipe,
        ),
    }


def main() -> None:
    repo = get_build_workspace_directory()
    for relative, text in render(lambda source: repo / source).items():
        (repo / relative).write_text(text)


if __name__ == "__main__":
    main()
