# gazelle:resolve py kyverno_clusterpolicy_crds //cluster/cdk8s/crd_bindings/kyverno:clusterpolicy
# gazelle:resolve py kyverno_cleanuppolicy_crds //cluster/cdk8s/crd_bindings/kyverno:cleanuppolicy

load("//devinfra/js:cdk8s_import.bzl", "cdk8s_import")

cdk8s_import(
    name = "clusterpolicy",
    crd = "@kyverno_clusterpolicy_crd//file",
    module_name = "kyverno_clusterpolicy_crds",
    module_path = "io/kyverno",
    visibility = ["//visibility:public"],
)

cdk8s_import(
    name = "cleanuppolicy",
    crd = "@kyverno_cleanuppolicy_crd//file",
    module_name = "kyverno_cleanuppolicy_crds",
    module_path = "io/kyverno",
    visibility = ["//visibility:public"],
)
