package supabase

import (
	"context"
	"log/slog"
	"os"
	"path/filepath"

	"github.com/anthropics/anthropic/api-go/environment-manager/internal/auth"
	"github.com/anthropics/anthropic/api-go/environment-manager/internal/mcp"
	mcplib "github.com/mark3labs/mcp-go/mcp"
)

// MigrationResponse is the API response type for migration list/apply operations.
//
// Binary: type:.eq.supabase.MigrationResponse (new in b71486df).
// TODO(re): field names and JSON tags not recovered from binary.
type MigrationResponse struct {
	// TODO(re): fields not recovered
}

// TypesResponse is the API response type for type generation.
//
// Binary: supabase.TypesResponse (referenced in GenerateTypes handler).
// TODO(re): field names and JSON tags not recovered from binary.
type TypesResponse struct {
	// TODO(re): fields not recovered
}

// QueryErrorResponse is the API error response for query failures.
//
// Binary: supabase.QueryErrorResponse (referenced in RunQuery handler).
// TODO(re): field names and JSON tags not recovered from binary.
type QueryErrorResponse struct {
	// TODO(re): fields not recovered
}

// SupabaseMCPServer implements mcp.MCPServer for Supabase database management.
//
// Binary: type:.eq.supabase.SupabaseMCPServer (new in b71486df).
// itab: go:itab.*supabase.SupabaseMCPServer,mcp.MCPServer.
// Provides tools: apply_migration, run_query, list_migrations, generate_types.
//
// TODO(re): exact struct layout not confirmed; field order inferred from
// configureServer and handler method field accesses.
type SupabaseMCPServer struct {
	*mcp.BaseServer
	client  *Client
	workDir string
	authCtx *auth.AuthContext
}

// GetName returns the server name "supabase".
// Binary: supabase.SupabaseMCPServer.GetName (autogenerated forwarder to BaseServer).
func (s *SupabaseMCPServer) GetName() string {
	return s.BaseServer.GetName()
}

// Start starts the MCP server.
// Binary: supabase.SupabaseMCPServer.Start (autogenerated forwarder to BaseServer).
func (s *SupabaseMCPServer) Start(logger *slog.Logger, name string) (int, error) {
	return s.BaseServer.Start(logger, name)
}

// Stop stops the MCP server.
// Binary: supabase.SupabaseMCPServer.Stop (autogenerated forwarder to BaseServer).
func (s *SupabaseMCPServer) Stop() bool {
	return s.BaseServer.Stop()
}

// ShouldRegisterWithClaude always returns true.
//
// Binary: supabase.(*SupabaseMCPServer).ShouldRegisterWithClaude (new in b71486df).
// Assembly: MOVL $0x1, AX; RET — trivially returns true.
func (s *SupabaseMCPServer) ShouldRegisterWithClaude() bool {
	return true
}

// getProjectDir returns the project directory for Supabase operations.
//
// Binary: supabase.(*SupabaseMCPServer).getProjectDir (new in b71486df).
// Joins workDir + "project" (7 chars); checks if it exists via os.Stat.
// Falls back to workDir if "project" subdirectory doesn't exist.
func (s *SupabaseMCPServer) getProjectDir() string {
	projectPath := filepath.Join(s.workDir, "project")
	if info, err := os.Stat(projectPath); err == nil && info.IsDir() {
		return projectPath
	}
	return s.workDir
}

// GetTools returns the MCP tool definitions for the Supabase server.
//
// Binary: supabase.(*SupabaseMCPServer).GetTools (new in b71486df).
// Tools: apply_migration, run_query, list_migrations, generate_types.
// TODO(re): exact tool descriptions and parameter schemas not recovered.
func (s *SupabaseMCPServer) GetTools() []mcp.ToolConfig {
	return []mcp.ToolConfig{
		{
			Tool:    mcplib.NewTool("apply_migration" /* TODO(re): description and params not recovered */),
			Handler: s.handleMigrate,
		},
		{
			Tool:    mcplib.NewTool("run_query" /* TODO(re): description and params not recovered */),
			Handler: s.handleQuery,
		},
		{
			Tool:    mcplib.NewTool("list_migrations" /* TODO(re): description not recovered */),
			Handler: s.handleListMigrations,
		},
		{
			Tool:    mcplib.NewTool("generate_types" /* TODO(re): description not recovered */),
			Handler: s.handleGenerateTypes,
		},
	}
}

// handleMigrate handles the apply_migration MCP tool call.
//
// Binary: supabase.(*SupabaseMCPServer).handleMigrate (new in b71486df).
// Validates migration name against migrationNamePattern.
// Calls client.ApplyMigration.
// TODO(re): parameter extraction and response formatting not recovered.
func (s *SupabaseMCPServer) handleMigrate(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	// TODO(re): extract "name" and "sql" parameters from req.Params
	// TODO(re): validate name against migrationNamePattern
	// TODO(re): call s.client.ApplyMigration(ctx, name, sql)
	// TODO(re): return success/error result
	return &mcplib.CallToolResult{}, nil
}

// handleQuery handles the run_query MCP tool call.
//
// Binary: supabase.(*SupabaseMCPServer).handleQuery (new in b71486df).
// Validates sql parameter: "sql must not be empty".
// Calls client.RunQuery.
// TODO(re): parameter extraction and response formatting not recovered.
func (s *SupabaseMCPServer) handleQuery(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	// TODO(re): extract "sql" parameter from req.Params
	// TODO(re): call s.client.RunQuery(ctx, sql)
	// TODO(re): format query results as MCP content
	return &mcplib.CallToolResult{}, nil
}

// handleListMigrations handles the list_migrations MCP tool call.
//
// Binary: supabase.(*SupabaseMCPServer).handleListMigrations (new in b71486df).
// Calls client.ListMigrations and returns the list.
// TODO(re): response formatting not recovered.
func (s *SupabaseMCPServer) handleListMigrations(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	// TODO(re): call s.client.ListMigrations(ctx)
	// TODO(re): format migration list as MCP content
	return &mcplib.CallToolResult{}, nil
}

// handleGenerateTypes handles the generate_types MCP tool call.
//
// Binary: supabase.(*SupabaseMCPServer).handleGenerateTypes (new in b71486df).
// Calls client.GenerateTypes with the project directory.
// Error strings observed: "Failed to write types file" (26 chars), "Type generation failed: %v" (26 chars).
// TODO(re): file path and response formatting not recovered.
func (s *SupabaseMCPServer) handleGenerateTypes(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	// TODO(re): call s.client.GenerateTypes(ctx, s.getProjectDir())
	// TODO(re): on write error: "Failed to write types file"
	// TODO(re): on API error: "Type generation failed: %v"
	return &mcplib.CallToolResult{}, nil
}
