"""Bazel utility libraries."""

load("//devinfra/python:defs.bzl", "py_library", "py_test")

py_library(
    name = "workspace",
    srcs = ["workspace.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "runfiles",
    srcs = ["runfiles.py"],
    visibility = ["//visibility:public"],
    deps = ["@rules_python//python/runfiles"],
)

py_library(
    name = "subprocess",
    srcs = ["subprocess.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "test_subprocess",
    srcs = ["test_subprocess.py"],
    deps = [
        ":subprocess",
        "//:conftest",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_workspace",
    srcs = ["test_workspace.py"],
    deps = [
        ":workspace",
        "//:conftest",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
