"""Bazel utility libraries."""

load("@rules_python//python:defs.bzl", "py_library")
load("//tools/testing:defs.bzl", "py_test")

py_library(
    name = "workspace",
    srcs = ["workspace.py"],
    imports = ["../.."],
    visibility = ["//visibility:public"],
)

py_library(
    name = "runfiles",
    srcs = ["runfiles.py"],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = ["@rules_python//python/runfiles"],
)

py_library(
    name = "subprocess",
    srcs = ["subprocess.py"],
    imports = ["../.."],
    visibility = ["//visibility:public"],
)

py_library(
    name = "query",
    srcs = ["query.py"],
    imports = ["../.."],
    visibility = ["//visibility:public"],
)

py_test(
    name = "test_subprocess",
    srcs = ["test_subprocess.py"],
    deps = [
        ":subprocess",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_query",
    srcs = ["test_query.py"],
    deps = [
        ":query",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
