# gazelle:resolve py gateway_api_crds //cluster/cdk8s/crd_bindings/gateway_api:httproute

load("//devinfra/js:cdk8s_import.bzl", "cdk8s_import")

cdk8s_import(
    name = "httproute",
    crd = "@gateway_api_httproute_crd//file",
    module_name = "gateway_api_crds",
    module_path = "io/k8s/networking/gateway",
    visibility = ["//visibility:public"],
)
