# gazelle:resolve py gateway_api_crds //cluster/cdk8s/crd_bindings/gateway_api:httproute
# gazelle:resolve py gateway_api_gateway_crds //cluster/cdk8s/crd_bindings/gateway_api:gateway
# gazelle:resolve py gateway_api_tlsroute_crds //cluster/cdk8s/crd_bindings/gateway_api:tlsroute

load("//devinfra/js:cdk8s_import.bzl", "cdk8s_import")

cdk8s_import(
    name = "httproute",
    crd = "@gateway_api_httproute_crd//file",
    module_name = "gateway_api_crds",
    module_path = "io/k8s/networking/gateway",
    visibility = ["//visibility:public"],
)

cdk8s_import(
    name = "gateway",
    crd = "@gateway_api_gateway_crd//file",
    module_name = "gateway_api_gateway_crds",
    module_path = "io/k8s/networking/gateway",
    visibility = ["//visibility:public"],
)

cdk8s_import(
    name = "tlsroute",
    crd = "@gateway_api_tlsroute_crd//file",
    module_name = "gateway_api_tlsroute_crds",
    module_path = "io/k8s/networking/gateway",
    visibility = ["//visibility:public"],
)
