apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: seaweedfs
stringData:
    seaweedfs_s3_config.json: ENC[AES256_GCM,data:XKJI1141mOEEw5msOXCgWhCW/NPaE/K9WOYn5hzVW+ohw2ryb9UMhooVG5jbRmYbZBoKRdzk3wix/HaAQ4Y6qOi2Rrv1GdCJmpdKttRC4H9qcliTh4c16i7THJdHdIUoYHprkhE4NNRmgNqUJ3wV8asVNCV6RheyfUEe15xBKNjZkbNsyYfCBAfW3xBBBJNAkQUb4F9OSiBK5IlURmEqyqX+pPuNrjjkeYQtZImkmp56TN8xLpBE9XALlaLB/DBLHkVshr7txYAuRVOn9YKOeY7vu9xEhTaZpFAaVE9d/a/fSgPnHMxk9cYfUoH9x/8DD91aOCOttz62LV5Pu9eK3kQ+MgvzYVr7F+/HtqwrD/HPN8OYS6yOqufoY7hpDUddShCGmUQfseLazFQQK42ox+ndYDJggaMCcIu6x9qqRy1bQxhl7p4QXVUP+3sSTAPm1v5WlFkWgjsnG1YlvxNe4+qMpMwZMYwLre3Ao0BjJ99sz19GMH9icsof83iaC6ATePTQpC9cpfovzqxMvgWqaDZHot25IvjGyD3fPEFRZfr/7wnfRK6inPbJ2IYKZkqC6ia78eRHZQ73VouSieLUa4HOhd21elYA2JSEL7z6WqzjXjOEK9RlUuBOFOVcC+c5m6uyNToZ19VAWI7TJG3dvR+XvsiEWnpHFiOD3b9ZYd2+n9PCWa0dVnUl28aiMeXGFEXA4ANk+JE2Keyv05OVHHDgPCARehe9CONlNeIOhkU8m/cfKzlFYhUzkVZce+ZT8Q+0Cy7ENkBfDwwoULHNiRU3xAB9He+afftw90BKeynWM15SxRqKWTNfskxYwy3XpB5N+uV7mSmoV0qePzBFVq35BQCjzkfV32RrWtsjJ7UGoqRjaOxonvr9/8Q3X1e7vtHXEYAd0+4hnpY39gzCoWimkuMqT9CPTleooXRg2xjPr/PMCJxbebYs9zC7hiB2lQ==,iv:ZuWQ8v8nJXxGDcGVI2ew0fg2UO+/hB+30UIA72JLQUc=,tag:dNn6mtDKKjIxH/QSHZlAvw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRWVzTWZzRmpWWkJodzJi
            c2l3dnltc0p1NVhrbDhmRTB1SmYxYnpqZkQ4CmRwRklSZXFTNTYzV0NFblR6ZkN1
            TGdBenE2VzlMU3dsWEVobUNUaVFPU00KLS0tIHZra3BmcTlyQWFUNi9tckZDNDJo
            M1FzWmFaT0c1S3k4dzF0YUJWZjhrajgKhJv5UxnYnNleXUU2JmNy7nWyiO7x1SeB
            FT6tG72emUEyBCw3jh6/JG/voXTxUScyIKw1FK7suAbQ64KzPnsAbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVHA3dHk4MWFLWGxwdElP
            NVEyMnN5SDNBbE9sNEptK3ljbEtDRXBhUlZNCkFIVUMxcC92QjVhSUJzeSt1U3FY
            c2N6MnAyOUJjak9WeHpscUhrQ1BDd3cKLS0tIDVlNnZ0dzV5ZGE5amNQYlptV0k2
            dHFKeHUzaFdIbldBaWc0bHFROFRkbWsK3rwmSf0wplSoVBbTQ+lSQRtA9G3GKMtp
            wq+MYlzmxviuSXC3lwLHaT/etxHWAL142WMNOhfk0Pr7PMhWXMNnhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T08:55:56Z"
    mac: ENC[AES256_GCM,data:zTpdJqV8So3VqQ/EejhOHLSLliA3KN+9TrMox34ed5+sQX4OgLU5RR5KCwUpKlCDDjhNK7I5AqBC3KNel0tsLx1kd02jX9jn2DWrpJDyrhp8MjpwCmpjDDZbq4YDnCI9AGGDffWvkaFc91x68xo6xvnaUpjZkLNm9LsWlAvmFoU=,iv:s23ANo+U5Nq9ZDfedK4SytMy1UjKVKVuLf9/9ABhj6Q=,tag:9m8typilYBrc/tWP5pR+Vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
