load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "kubespanlib",
    testonly = True,
    srcs = [
        "kubespanlib.go",
    ],
    importpath = "github.com/agentydragon/ducktape/cluster/kubespand/qemu_tests/vms/kubespanlib",
    visibility = ["//cluster/kubespand:__subpackages__"],
    deps = [
        "//cluster/kubespand/qemu_tests/vms/initlib",
    ],
)
