"""Emit a TS module exporting one or more files' contents as base64 data: URIs.

Turns checked-in or Bazel-fetched binary assets (e.g. `http_file` repos) into constants a
frontend module can import, instead of hand-pasting the base64 into source. Driven by the
`//devinfra/js:data_uri.bzl` macro's genrule.
"""

from __future__ import annotations

import argparse
import base64
import mimetypes
from pathlib import Path


def _entry(value: str) -> tuple[str, Path]:
    const_name, sep, path = value.partition("=")
    if not sep:
        raise argparse.ArgumentTypeError(f"expected NAME=path, got {value!r}")
    return const_name, Path(path)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "entries", nargs="+", type=_entry, metavar="NAME=path", help="One exported constant name and its source file."
    )
    parser.add_argument("-o", "--out", type=Path, required=True, help="Output .ts file path.")
    args = parser.parse_args()

    lines = ["// Generated by util/data_uri.py — do not edit.\n"]
    for const_name, path in args.entries:
        mime_type, _ = mimetypes.guess_type(path.name)
        if mime_type is None:
            raise ValueError(f"Could not guess a MIME type for {path.name}")
        encoded = base64.b64encode(path.read_bytes()).decode("ascii")
        lines.append(f'export const {const_name} = "data:{mime_type};base64,{encoded}";\n')

    args.out.write_text("".join(lines))


if __name__ == "__main__":
    main()
