"""Generates the separate Tana-backed LiteLLM proxy config.

Run to regenerate the committed file:
    bazel run //cluster/k8s/litellm/tana:generate_tana_litellm_bin

Parity enforced by:
    bazel test //cluster/k8s/litellm/tana:test_generate_tana_litellm
"""

from __future__ import annotations

import yaml

from devinfra.prettier import prettier_format_in_place
from tana.litellm_proxy.model_registry import TANA_LLM_PROXY_RESPONDING_MODELS
from util.bazel.workspace import get_build_workspace_directory

_CUSTOM_HANDLER = "custom_handler.tana_handler"


def _model_entry(model_id: str) -> dict:
    return {
        "model_name": model_id,
        "litellm_params": {"model": f"tana/{model_id}"},
        "model_info": {"mode": "chat", "supports_function_calling": True},
    }


def generate() -> str:
    proxy_config = {
        "model_list": [_model_entry(model.model_id) for model in TANA_LLM_PROXY_RESPONDING_MODELS],
        "custom_provider_map": [{"provider": "tana", "custom_handler": _CUSTOM_HANDLER}],
        "litellm_settings": {"drop_params": True, "callbacks": ["langfuse_otel"]},
    }
    header = "# Generated by //cluster/k8s/litellm/tana:generate_tana_litellm_bin - do not edit by hand.\n"
    return header + yaml.dump(proxy_config, default_flow_style=False, sort_keys=False, allow_unicode=True)


def main() -> None:
    out_path = get_build_workspace_directory() / "cluster/k8s/litellm/tana/proxy-config.yaml"
    out_path.write_text(generate())
    prettier_format_in_place(out_path)
    print(f"Generated {out_path}")


if __name__ == "__main__":
    main()
