load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "manager",
    srcs = [
        "manager.go",
        "mcp.go",
        "tunnel_register.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/manager",
    visibility = ["//claude_web_env/re/environment_manager/6b49f1ca/src:__subpackages__"],
    deps = [
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/config",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/envtype",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/mcp",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/o11y",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/o11y/diag",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/tunnel/actions",
        "//claude_web_env/re/environment_manager/6b49f1ca/src/internal/tunnel/actions/deploy",
    ],
)
