load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

exports_files(
    [
        "cilium-values.yaml",
        "ovh-nodes.tf",
    ],
    visibility = ["//cluster:__subpackages__"],
)

tf_providers_versions(
    name = "providers",
    providers = {
        "proxmox": "bpg/proxmox:~>0.113.0",
        "talos": "siderolabs/talos:~>0.11.0",
        "kubernetes": "hashicorp/kubernetes:~>3.2.0",
        "helm": "hashicorp/helm:~>3.3.0",
        "local": "hashicorp/local:~>2.9.0",
        "null": "hashicorp/null:~>3.3.0",
        "sops": "carlpett/sops:~>1.4.0",
        "tls": "hashicorp/tls:~>4.4.0",
        "ovh": "ovh/ovh:~>2.0",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "main",
    data = [
        "//:nebula-mesh.json",
        "//cluster/k8s:flux_bootstrap_files",
        "//cluster/k8s/talos-cloud-controller-manager:helmrelease.yaml",
    ],
    providers = [
        "proxmox",
        "talos",
        "kubernetes",
        "helm",
        "local",
        "null",
        "sops",
        "tls",
        "ovh",
    ],
    providers_versions = ":providers",
    tflint_config = "//cluster:.tflint.hcl",
    deps = [
        "//terraform/modules/nixos-image",
    ],
)
