load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

exports_files(
    ["cilium-values.yaml"],
    visibility = ["//cluster:__subpackages__"],
)

tf_providers_versions(
    name = "providers",
    providers = {
        "external": "hashicorp/external:~>2.3.0",
        "proxmox": "bpg/proxmox:~>0.91.0",
        "hcloud": "hetznercloud/hcloud:~>1.45",
        "talos": "siderolabs/talos:~>0.10.0",
        "kubernetes": "hashicorp/kubernetes:~>2.38.0",
        "flux": "fluxcd/flux:~>1.7.0",
        "helm": "hashicorp/helm:~>3.1.0",
        "local": "hashicorp/local:~>2.5.0",
        "null": "hashicorp/null:~>3.2.0",
        "random": "hashicorp/random:~>3.7.0",
        "tls": "hashicorp/tls:~>4.1.0",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "main",
    data = ["//:nebula-mesh.json"],
    providers = [
        "external",
        "proxmox",
        "hcloud",
        "talos",
        "kubernetes",
        "flux",
        "helm",
        "local",
        "null",
        "random",
        "tls",
    ],
    providers_versions = ":providers",
    tflint_config = "//cluster:.tflint.hcl",
    deps = [
        "//terraform/modules/nixos-image",
        "//terraform/modules/proxmox-vm",
    ],
)
