apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-images-creds
  namespace: squid-egress-spike
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-flux-system-secret-store
    kind: ClusterSecretStore
  target:
    name: forgejo-images-creds
    template:
      type: kubernetes.io/dockerconfigjson
      mergePolicy: Merge
  dataFrom:
    - extract:
        key: forgejo-images-creds
