load("//devinfra/python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "execution",
    srcs = ["execution.py"],
    deps = [
        "//finance/augur/model:asset_key",
        "//finance/augur/model:series",
        "//finance/augur/sim:bonds",
        "//finance/augur/sim:books",
        "//finance/augur/sim:external_series",
        "//finance/augur/sim:fixed_point",
        "//finance/augur/sim:ids",
        "//finance/augur/sim:income",
        "//finance/augur/sim:jurisdictions",
        "//finance/augur/sim:locations",
        "//finance/augur/sim:prepared",
        "//finance/augur/sim:property",
        "//finance/augur/sim:scenario",
        "//finance/augur/sim:tlh",
    ],
)
