apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
  name: attic
  namespace: seaweedfs
spec:
  seaweedRef:
    name: seaweedfs
  reclaimPolicy: Retain
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: attic
  namespace: seaweedfs
spec:
  seaweedRef:
    name: seaweedfs
  identityRef:
    name: attic
  secretRef:
    name: attic-s3-credentials
    namespace: nix-cache
    accessKeyField: AWS_ACCESS_KEY_ID
    secretKeyField: AWS_SECRET_ACCESS_KEY
  reclaimPolicy: Retain
