# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "flux_grafana_secrets",
    srcs = ["flux_grafana_secrets.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s:manifest_roots",
        "//cluster/cdk8s:metadata",
        "//cluster/cdk8s/providers/flux:kustomization",
        "//cluster/cdk8s/providers/grafana_operator:grafana_operator_grafana",
        "//cluster/cdk8s/providers/grafana_operator:grafanaserviceaccount",
        "//cluster/cdk8s/providers/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
    ],
)
