apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: loki
  annotations:
    description: MinIO credentials for Loki chunk/index storage
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qqh8hA06OqBW9+umqnlgQg==,iv:W+riwDKKz5SalGlr21tT0iBzTIJ/GIeczwQu7tJE5Qw=,tag:vqDE/6IAzVkdbytRT4SX0w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NBkphjN9vuXlRmGPtrdcyrraFhwtbbFAf6+7EJQS42A20NdBDuUnFJiEzA==,iv:Qola12GT4iZnwnS5O/AsNhzXpa9f0kx6UV3tVo5MxEM=,tag:iUcRJ2qB99bN/bJe8ZYWNg==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SkVxMzJoUjN0SDVRUkp6
        STlhNCtvaVZTRlRUQnAzRS9QR0NBWHE0bkE4Ckl1R3NUV1MwOG05eEdUS2ZySFg2
        cFc0aVBEaFNCajlIeDd4Z2FNYVhxTlUKLS0tIE9tYzN1NFBVdjBJdFppQXo0NUhz
        MGpKV1hGMDQ5OFRZUWcxdzJobGRmR0kK6HyY7LV9gihQDIrXNk4Jb5VRTgmLKtLX
        fkvbdbNknz30Q4by6REu/lNTadmdfLZhYxZwNGy10Cae+Dsey/0kQg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS2xzWTdVdzk5QjFrYld4
        b3BIa0l4STZoT3VxZ1NuRmlXbFJHMnFpY2o0CmU2VWkrYWpZS1N6clFqclo2VEpn
        d1NkOWVXc2JsaXB3ZFVGNm5TZkp0SHcKLS0tIGI1bldiYkkzbmxUdEZuWFR6eXMw
        aFUyT1NYWkZqZUtkSEhtcElUd2s5VWsKqplqhoHK4tvU84HAXS+0hF4wFsEm6rlZ
        tpOqTQzY3MSJbEJzu8AgL464AW5nmapK485BvM4FZkIzAHX2+dhPAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T05:12:58Z"
  mac: ENC[AES256_GCM,data:iAQ2Ah8d6yadzp9bktVgUZjU5eqspKAcWuaFKE0CMERuYU1yzg2Mw+QtmIdy87EJ10ykXgidSjKBlmzFnB80fNpRBLzRmy+RQPDVLBOdv6OkS+hNr4/MJAMRd9dcmmsGu2nWlzBr2uc3RKRujwISwvfCnt0GnF8eMHM0nClrzbg=,iv:OC+EnP7FxrJ0b5LbjWQce4Jfdfi6Yz9K9uBf3DVQGac=,tag:pPzM88ABpHVGkswVDBYfnA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
