"""The Attic Nix binary cache (`cache.allegedly.works`): the server and its Postgres, its
SeaweedFS bucket and credentials, the cache bootstrap Job, and the hourly JWT rotation.

Hand-written beside the output: `server.toml` and `rotators.yaml` (the directory's
`kustomization.yaml` generates ConfigMaps from them), the SOPS Secrets, and
`image-pins/kustomization.yaml`, which pins the rotator image's tag over the placeholder
here (cluster/cdk8s/AGENTS.md § image-pins).
"""

from __future__ import annotations

from pathlib import Path

from cdk8s import App, Chart
from cdk8s_plus_34 import k8s
from cnpg_cluster_crds.io.cnpg.postgresql import ClusterSpecBootstrapInitdb
from constructs import Construct
from external_secrets_crds.io.external_secrets import (
    ExternalSecret,
    ExternalSecretSpec,
    ExternalSecretSpecData,
    ExternalSecretSpecDataRemoteRef,
    ExternalSecretSpecSecretStoreRef,
    ExternalSecretSpecSecretStoreRefKind,
    ExternalSecretSpecTarget,
    ExternalSecretSpecTargetCreationPolicy,
    ExternalSecretSpecTargetDeletionPolicy,
    ExternalSecretSpecTargetTemplate,
)
from seaweed_bucket_crds.com.seaweedfs.seaweed import (
    Bucket,
    BucketSpec,
    BucketSpecAccess,
    BucketSpecAccessActions,
    BucketSpecClusterRef,
)
from seaweed_resourcereferencegrant_crds.com.seaweedfs.seaweed import (
    ResourceReferenceGrant,
    ResourceReferenceGrantSpec,
    ResourceReferenceGrantSpecFrom,
    ResourceReferenceGrantSpecTo,
)
from seaweed_s3credentials_crds.com.seaweedfs.seaweed import (
    S3Credentials,
    S3CredentialsSpec,
    S3CredentialsSpecIdentityRef,
    S3CredentialsSpecReclaimPolicy,
    S3CredentialsSpecSeaweedRef,
    S3CredentialsSpecSecretRef,
)
from seaweed_s3identity_crds.com.seaweedfs.seaweed import (
    S3Identity,
    S3IdentitySpec,
    S3IdentitySpecReclaimPolicy,
    S3IdentitySpecSeaweedRef,
)

from cluster.cdk8s import cnpg, forgejo_images
from cluster.cdk8s.gateway import https_route
from cluster.cdk8s.generation import write_charts
from cluster.cdk8s.metadata import metadata
from cluster.cdk8s.seaweedfs import cluster as seaweedfs_cluster, namespace as seaweedfs_namespace

NAME = "attic"
NAMESPACE = "nix-cache"
OUTPUT_DIR = "cluster/k8s/nix-cache"
_PORT = 8080
_SELECTOR = {"app.kubernetes.io/name": NAME}
_DB = "attic-db"
# The operator mints the S3 key pair straight into this namespace (S3Credentials below).
_S3_SECRET = "attic-s3-credentials"
_GITHUB_PAT_SECRET = "github-secrets-sync-pat"
_ROTATOR = "attic-jwt-rotator"
# Placeholder tag; image-pins/kustomization.yaml sets the real one.
_ROTATOR_IMAGE = "git.allegedly.works/ducktape-ci/attic-jwt-rotation:unset"
# Generated by the directory's kustomization.yaml from rotators.yaml and server.toml.
_ROTATORS_CONFIG_MAP = "attic-rotators-config"
_SERVER_CONFIG_MAP = "attic-config"
_CONTROL_PLANE_TOLERATION = k8s.Toleration(
    key="node-role.kubernetes.io/control-plane", operator="Exists", effect="NoSchedule"
)
_ZONE_SELECTOR = {"topology.kubernetes.io/zone": "hil-ovh"}


def _secret_env(name: str, secret: str, key: str) -> k8s.EnvVar:
    return k8s.EnvVar(
        name=name, value_from=k8s.EnvVarSource(secret_key_ref=k8s.SecretKeySelector(name=secret, key=key))
    )


def _database(scope: Construct) -> None:
    cnpg.cluster(
        scope,
        "db",
        name=_DB,
        namespace=NAMESPACE,
        image_name=None,
        affinity=cnpg.affinity(node_selector=_ZONE_SELECTOR, tolerate_control_plane=True),
        storage_class="local-path-ovh",
        size="2Gi",
        # CNPG generates the credentials in Secret attic-db-app.
        initdb=ClusterSpecBootstrapInitdb(database="attic", owner="attic"),
    )


def _storage(scope: Construct) -> None:
    # attic's NAR chunks. Replication is per-volume (the SeaweedFS cluster's
    # defaultReplication), so the bucket is backed by replicated storage.
    Bucket(
        scope,
        "bucket",
        metadata=metadata(NAME, NAMESPACE),
        spec=BucketSpec(
            name=NAME,
            # Handing the existing (freshly emptied) bucket to this tenant-local CR -- same
            # precedent as seaweedfs/registry_cache_bucket.py.
            adopt_existing=True,
            cluster_ref=BucketSpecClusterRef(name=seaweedfs_cluster.NAME, namespace=seaweedfs_namespace.NAME),
            access=[
                BucketSpecAccess(
                    user=NAME,
                    actions=[
                        BucketSpecAccessActions.READ,
                        BucketSpecAccessActions.WRITE,
                        BucketSpecAccessActions.LIST,
                        BucketSpecAccessActions.TAGGING,
                    ],
                )
            ],
        ),
    )
    S3Identity(
        scope,
        "identity",
        metadata=metadata(NAME, seaweedfs_namespace.NAME),
        spec=S3IdentitySpec(
            seaweed_ref=S3IdentitySpecSeaweedRef(name=seaweedfs_cluster.NAME),
            reclaim_policy=S3IdentitySpecReclaimPolicy.RETAIN,
        ),
    )
    # Tenant-local S3Credentials (upstream's default topology): the identity stays
    # centralized in seaweedfs, but credentials mint straight into this namespace, so the
    # resulting Secret needs no cross-namespace write/grant.
    S3Credentials(
        scope,
        "credentials",
        metadata=metadata(NAME, NAMESPACE),
        spec=S3CredentialsSpec(
            seaweed_ref=S3CredentialsSpecSeaweedRef(name=seaweedfs_cluster.NAME, namespace=seaweedfs_namespace.NAME),
            identity_ref=S3CredentialsSpecIdentityRef(name=NAME),
            secret_ref=S3CredentialsSpecSecretRef(
                name=_S3_SECRET, access_key_field="AWS_ACCESS_KEY_ID", secret_key_field="AWS_SECRET_ACCESS_KEY"
            ),
            reclaim_policy=S3CredentialsSpecReclaimPolicy.RETAIN,
        ),
    )
    # Permit the tenant-local Bucket and S3Credentials to reference the SeaweedFS cluster in
    # its namespace.
    ResourceReferenceGrant(
        scope,
        "grant",
        metadata=metadata(NAMESPACE, seaweedfs_namespace.NAME),
        spec=ResourceReferenceGrantSpec(
            from_=[
                ResourceReferenceGrantSpecFrom(group="seaweed.seaweedfs.com", kind="Bucket", namespace=NAMESPACE),
                ResourceReferenceGrantSpecFrom(
                    group="seaweed.seaweedfs.com", kind="S3Credentials", namespace=NAMESPACE
                ),
            ],
            to=[
                ResourceReferenceGrantSpecTo(group="seaweed.seaweedfs.com", kind="Seaweed", name=seaweedfs_cluster.NAME)
            ],
        ),
    )


def _server(scope: Construct) -> None:
    k8s.KubeDeployment(
        scope,
        "deployment",
        metadata=k8s.ObjectMeta(name=NAME, namespace=NAMESPACE, annotations={"reloader.stakater.com/auto": "true"}),
        spec=k8s.DeploymentSpec(
            replicas=1,
            selector=k8s.LabelSelector(match_labels=_SELECTOR),
            template=k8s.PodTemplateSpec(
                metadata=k8s.ObjectMeta(labels=_SELECTOR),
                spec=k8s.PodSpec(
                    # Co-located with SeaweedFS and attic-db on OVH kimsufi workers.
                    node_selector=_ZONE_SELECTOR,
                    # Stateless S3-backed service; allow control-plane nodes as overflow capacity.
                    tolerations=[_CONTROL_PLANE_TOLERATION],
                    containers=[
                        k8s.Container(
                            name=NAME,
                            # TODO: Pin to a versioned tag once attic publishes semver releases.
                            image="ghcr.io/zhaofengli/attic:latest",
                            image_pull_policy="Always",
                            security_context=k8s.SecurityContext(
                                run_as_user=1000,
                                run_as_group=1000,
                                run_as_non_root=True,
                                allow_privilege_escalation=False,
                                capabilities=k8s.Capabilities(drop=["ALL"]),
                                seccomp_profile=k8s.SeccompProfile(type="RuntimeDefault"),
                            ),
                            env=[
                                _secret_env("ATTIC_SERVER_DATABASE_URL", f"{_DB}-app", "uri"),
                                _secret_env("ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64", "attic-jwt-token", "jwt-token"),
                                _secret_env("AWS_ACCESS_KEY_ID", _S3_SECRET, "AWS_ACCESS_KEY_ID"),
                                _secret_env("AWS_SECRET_ACCESS_KEY", _S3_SECRET, "AWS_SECRET_ACCESS_KEY"),
                            ],
                            args=["-f", "/config/server.toml", "--mode", "monolithic"],
                            ports=[k8s.ContainerPort(name="http", container_port=_PORT, protocol="TCP")],
                            volume_mounts=[
                                k8s.VolumeMount(name="config", mount_path="/config", read_only=True),
                                k8s.VolumeMount(name="tmp", mount_path="/tmp"),
                            ],
                            liveness_probe=k8s.Probe(
                                http_get=k8s.HttpGetAction(path="/", port=k8s.IntOrString.from_string("http")),
                                initial_delay_seconds=10,
                                period_seconds=30,
                                timeout_seconds=5,
                            ),
                            readiness_probe=k8s.Probe(
                                http_get=k8s.HttpGetAction(path="/", port=k8s.IntOrString.from_string("http")),
                                initial_delay_seconds=5,
                                period_seconds=10,
                                timeout_seconds=3,
                            ),
                        )
                    ],
                    volumes=[
                        k8s.Volume(name="config", config_map=k8s.ConfigMapVolumeSource(name=_SERVER_CONFIG_MAP)),
                        k8s.Volume(name="tmp", empty_dir=k8s.EmptyDirVolumeSource()),
                    ],
                ),
            ),
        ),
    )
    k8s.KubeService(
        scope,
        "service",
        metadata=k8s.ObjectMeta(name=NAME, namespace=NAMESPACE),
        spec=k8s.ServiceSpec(
            type="ClusterIP",
            ports=[
                k8s.ServicePort(
                    port=_PORT, target_port=k8s.IntOrString.from_string("http"), protocol="TCP", name="http"
                )
            ],
            selector=_SELECTOR,
        ),
    )
    https_route(
        scope,
        "route",
        metadata=metadata(NAMESPACE, NAMESPACE),
        hostname="cache.allegedly.works",
        backend=NAME,
        port=_PORT,
        hsts=False,
        listener=None,
    )


def _rotation(scope: Construct) -> None:
    k8s.KubeServiceAccount(
        scope, "external-creds-reader", metadata=k8s.ObjectMeta(name="external-creds-reader", namespace=NAMESPACE)
    )
    # The rotator's GitHub PAT, copied from the canonical external-creds source
    # (external_creds.py approves nix-cache as a consumer).
    ExternalSecret(
        scope,
        "github-pat",
        metadata=metadata(_GITHUB_PAT_SECRET, NAMESPACE),
        spec=ExternalSecretSpec(
            refresh_interval="1h",
            secret_store_ref=ExternalSecretSpecSecretStoreRef(
                kind=ExternalSecretSpecSecretStoreRefKind.CLUSTER_SECRET_STORE,
                name="kubernetes-external-creds-secret-store",
            ),
            target=ExternalSecretSpecTarget(
                name=_GITHUB_PAT_SECRET,
                creation_policy=ExternalSecretSpecTargetCreationPolicy.OWNER,
                deletion_policy=ExternalSecretSpecTargetDeletionPolicy.RETAIN,
                template=ExternalSecretSpecTargetTemplate(type="Opaque"),
            ),
            data=[
                ExternalSecretSpecData(
                    secret_key="token",
                    remote_ref=ExternalSecretSpecDataRemoteRef(key="github-agentydragon-2", property="token"),
                )
            ],
        ),
    )
    k8s.KubeServiceAccount(
        scope,
        "rotator",
        metadata=k8s.ObjectMeta(
            name=_ROTATOR,
            namespace=NAMESPACE,
            annotations={
                "description": (
                    "Runs the Attic JWT rotation CronJobs. RBAC is `pods/exec` scoped to the nix-cache namespace so"
                    " the rotator can `kubectl exec deploy/attic -- atticadm make-token …` without ever holding the"
                    " HS256 signing secret."
                )
            },
        ),
        image_pull_secrets=[k8s.LocalObjectReference(name=forgejo_images.SECRET_NAME)],
    )
    k8s.KubeRole(
        scope,
        "rotator-role",
        metadata=k8s.ObjectMeta(name=_ROTATOR, namespace=NAMESPACE),
        rules=[
            # `kubectl exec` requires get on pods (to resolve deploy/attic to a Pod name) plus
            # create on pods/exec (to open the exec stream).
            k8s.PolicyRule(api_groups=[""], resources=["pods"], verbs=["get", "list"]),
            k8s.PolicyRule(api_groups=[""], resources=["pods/exec"], verbs=["create"]),
            # Resolving `deploy/attic` to a pod first reads the Deployment.
            k8s.PolicyRule(api_groups=["apps"], resources=["deployments"], verbs=["get"]),
        ],
    )
    k8s.KubeRoleBinding(
        scope,
        "rotator-binding",
        metadata=k8s.ObjectMeta(name=_ROTATOR, namespace=NAMESPACE),
        role_ref=k8s.RoleRef(api_group="rbac.authorization.k8s.io", kind="Role", name=_ROTATOR),
        subjects=[k8s.Subject(kind="ServiceAccount", name=_ROTATOR, namespace=NAMESPACE)],
    )
    k8s.KubeCronJob(
        scope,
        "rotation",
        metadata=k8s.ObjectMeta(
            name="attic-jwt-rotation",
            namespace=NAMESPACE,
            annotations={
                "description": (
                    "Rotates all Attic JWTs (per-host readers, claude-web reader, ducktape and gaffer CI writer"
                    " tokens) defined in rotators.yaml. Hourly cron; per-token freshness check skips entries with"
                    " >24h remaining, so a real mint runs ~once per token per year. See rotate.py."
                )
            },
        ),
        spec=k8s.CronJobSpec(
            schedule="30 * * * *",
            successful_jobs_history_limit=3,
            failed_jobs_history_limit=3,
            job_template=k8s.JobTemplateSpec(
                spec=k8s.JobSpec(
                    # A Job whose pod can never start (e.g. it pins a kustomize-hashed ConfigMap
                    # that a newer generation pruned) stays active forever -- history limits and
                    # TTL apply only to finished Jobs. The deadline fails it; the TTL then
                    # garbage-collects it.
                    active_deadline_seconds=1800,
                    ttl_seconds_after_finished=86400,
                    backoff_limit=2,
                    template=k8s.PodTemplateSpec(
                        spec=k8s.PodSpec(
                            service_account_name=_ROTATOR,
                            restart_policy="OnFailure",
                            volumes=[
                                k8s.Volume(
                                    name="rotators-config",
                                    config_map=k8s.ConfigMapVolumeSource(name=_ROTATORS_CONFIG_MAP),
                                )
                            ],
                            security_context=k8s.PodSecurityContext(
                                run_as_non_root=True,
                                run_as_user=65534,
                                seccomp_profile=k8s.SeccompProfile(type="RuntimeDefault"),
                            ),
                            containers=[
                                k8s.Container(
                                    name="rotate",
                                    image=_ROTATOR_IMAGE,
                                    args=["rotate", "--config", "/config/rotators.yaml"],
                                    env=[_secret_env("GIT_TOKEN", _GITHUB_PAT_SECRET, "token")],
                                    security_context=k8s.SecurityContext(
                                        allow_privilege_escalation=False, capabilities=k8s.Capabilities(drop=["ALL"])
                                    ),
                                    volume_mounts=[
                                        k8s.VolumeMount(name="rotators-config", mount_path="/config", read_only=True)
                                    ],
                                    resources=k8s.ResourceRequirements(
                                        requests={
                                            "cpu": k8s.Quantity.from_string("100m"),
                                            "memory": k8s.Quantity.from_string("256Mi"),
                                        },
                                        limits={"memory": k8s.Quantity.from_string("512Mi")},
                                    ),
                                )
                            ],
                        )
                    ),
                )
            ),
        ),
    )
    k8s.KubeJob(
        scope,
        "bootstrap-caches",
        metadata=k8s.ObjectMeta(
            name="attic-bootstrap-caches",
            namespace=NAMESPACE,
            annotations={
                "description": (
                    "Idempotently ensure required Attic caches (main, gaffer, public) exist and print their"
                    " public keys."
                ),
                # Force Flux to recreate the Job when its hash (image or args) changes.
                "kustomize.toolkit.fluxcd.io/force": "enabled",
            },
        ),
        spec=k8s.JobSpec(
            backoff_limit=5,
            template=k8s.PodTemplateSpec(
                metadata=k8s.ObjectMeta(labels={"app": "attic-bootstrap-caches"}),
                spec=k8s.PodSpec(
                    # Reuses the rotator's ServiceAccount -- same pods/exec RBAC for invoking
                    # atticadm against deploy/attic. The bootstrap subcommand doesn't touch SOPS
                    # or git, so it doesn't need the rotator's GitHub PAT.
                    service_account_name=_ROTATOR,
                    # Keep the registry credential explicit on the Pod. The Secret is reflected
                    # into nix-cache; this avoids relying on ServiceAccount admission timing for
                    # the image pull.
                    image_pull_secrets=[k8s.LocalObjectReference(name=forgejo_images.SECRET_NAME)],
                    restart_policy="OnFailure",
                    security_context=k8s.PodSecurityContext(
                        run_as_non_root=True,
                        run_as_user=65534,
                        seccomp_profile=k8s.SeccompProfile(type="RuntimeDefault"),
                    ),
                    containers=[
                        k8s.Container(
                            name="bootstrap",
                            image=_ROTATOR_IMAGE,
                            args=[
                                "bootstrap-caches",
                                "--cache=main",
                                "--cache=gaffer",
                                "--public-cache=public",
                                "--keypair-dir=/secrets/cache-keys",
                            ],
                            security_context=k8s.SecurityContext(
                                allow_privilege_escalation=False, capabilities=k8s.Capabilities(drop=["ALL"])
                            ),
                            resources=k8s.ResourceRequirements(
                                requests={
                                    "cpu": k8s.Quantity.from_string("100m"),
                                    "memory": k8s.Quantity.from_string("128Mi"),
                                },
                                limits={"memory": k8s.Quantity.from_string("256Mi")},
                            ),
                            volume_mounts=[
                                k8s.VolumeMount(name="cache-keys", mount_path="/secrets/cache-keys", read_only=True)
                            ],
                        )
                    ],
                    volumes=[
                        k8s.Volume(name="cache-keys", secret=k8s.SecretVolumeSource(secret_name="attic-cache-keys"))
                    ],
                ),
            ),
        ),
    )


def chart(app: App) -> Chart:
    chart = Chart(app, NAME, disable_resource_name_hashes=True)
    k8s.KubeNamespace(
        chart,
        "namespace",
        metadata=k8s.ObjectMeta(
            name=NAMESPACE,
            labels={
                "goldilocks.fairwinds.com/enabled": "true",
                "goldilocks.fairwinds.com/vpa-update-mode": "auto",
                "rbac.ducktape.io/agent-readable-metadata": "true",
            },
        ),
    )
    forgejo_images.forgejo_images_creds_external_secret(chart, "forgejo-images-creds", namespace=NAMESPACE)
    _database(chart)
    _storage(chart)
    _server(chart)
    _rotation(chart)
    return chart


def write_manifests(root: Path) -> None:
    write_charts(root, OUTPUT_DIR, chart)
