apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: aw-server
  namespace: flux-system
spec:
  image: git.allegedly.works/ducktape-ci/aw-server
  interval: 5m
  secretRef:
    name: forgejo-images-creds
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: aw-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: aw-server
  filterTags:
    pattern: '^devel-\d{14}-[0-9a-f]{7}$'
  policy:
    alphabetical:
      order: asc
