# CLEANUP(added 2026-08-10): delete with cluster/images/squid-ssl when the
#   egress-proxy spike concludes.
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: squid-ssl
  namespace: flux-system
spec:
  image: git.allegedly.works/ducktape-ci/squid-ssl
  interval: 5m
  secretRef:
    name: forgejo-images-creds
