apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: tana-mcp
  namespace: flux-system
spec:
  image: git.allegedly.works/ducktape-ci/tana-desktop
  interval: 5m
  secretRef:
    name: forgejo-images-creds
