apiVersion: v1
kind: Secret
metadata:
    name: bsc-client-credentials
    namespace: airlock
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:oj4qZl1lNQ+CJWfqKQsD8LQBUmNn5PrYt+miyhINvPs=,iv:7Vxh7KbDOoh7T0KF4ZU+IoVIgr+K9DAu/lUN7T79B+M=,tag:CVvuIAMJ80mrXNrOJ7b4/A==,type:str]
    client_secret: ENC[AES256_GCM,data:/hLRTn0uXqCU3rNtgEcHxE61I3y7uhxOilqhJrOWH0s=,iv:UnXLixsIMOJ2G81mhZGyGgWz2MFJ5sHF9ayzW821dAQ=,tag:bWPoopPgGYRi4yqEiYD6pA==,type:str]
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVkpuUlhrajlvZjdEbDI1
            Wks0eUJRNlNJdTBsWWtjdGZhWkVRcEdOZjNNCjc5c2RWTmNsQ0NZcHNKWXpGSkxX
            QlU0UEZnQjUxeDAvSEZESU5ZYTNmOGMKLS0tICtQaE81R2kvZWNsNmFvbGMzcjJq
            YTBkN1ZEUjR4NHJyS24rYmh0NlQ3SkkKwQ7zXZgQV+Dlelg4CDqkIJKbQwPx6dNN
            rWpdWceUioi07FPy22nw1Tx6LTUiPrV/94zPV2jjiX0LJqOCOwRLGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRzN6TUh4Rjd5SkRuN29O
            Y2VhOFhySGdqV0FONklwMFhqV2xwQWFTVHhVCkpyOU5iWTdvVk41cnVpSzF1UzBF
            MGxIYkxnRVVBNkR4czhZTWFzS2U0c00KLS0tIFJOaUNLd0dtR21NSHUwU0dEeXQ3
            TnVlQ0s5aXVhQUJDQkdjSmx3UHJ0K00K06hu/7xX9Ooqkx9ogRdJpIDvoG/7bNXy
            fQWowzBQTlQ6wNw1nrgVhw+g5ks30H5YEJcBUU/Znr7piqksVusbeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T19:10:07Z"
    mac: ENC[AES256_GCM,data:shh3JUML1IIURuDTmhxAHSwxjGlmdE/5YyGpJ7Z8qEMIzrCICsYiu4ILVMBVPrWtd31FyHZayyu0l5BLTm8bwxPIezAYbDTqXTcdCjLtLn+/nQk7QkC+2dOZ0fvK8kkyUYgim+z9YMUp99hNaO2laULgHDfGKp1/FceEHhvhrFA=,iv:71mGgNoi+i4kdFhtWPkfxVRz02UayivrDt/WLff6xqg=,tag:rCw6sdxVUz+5AS+xtytQAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
