apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
  name: vm-images-ci-writer
  namespace: seaweedfs
spec:
  seaweedRef:
    name: seaweedfs
  reclaimPolicy: Retain
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: vm-images-ci-writer
  namespace: vm-images-publisher
spec:
  seaweedRef:
    name: seaweedfs
    namespace: seaweedfs
  identityRef:
    name: vm-images-ci-writer
  secretRef:
    name: vm-images-ci-writer-s3-credentials
  reclaimPolicy: Retain
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
  name: vm-images-cdi-reader
  namespace: seaweedfs
spec:
  seaweedRef:
    name: seaweedfs
  reclaimPolicy: Retain
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: vm-images-cdi-reader
  namespace: vm-images-publisher
spec:
  seaweedRef:
    name: seaweedfs
    namespace: seaweedfs
  identityRef:
    name: vm-images-cdi-reader
  secretRef:
    name: vm-images-cdi-reader-s3-credentials
  reclaimPolicy: Retain
