"""Props core package."""

load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("//tools/lint:linters.bzl", "ruff_test")

py_library(
    name = "core",
    srcs = glob(
        ["**/*.py"],
        exclude = [
            ".*/**",
            "tests/**",
        ],
    ),
    data = glob([
        "docs/**/*.md",
        "docs/**/*.j2",
        "agent_defs/**/*",
        "noop_classifier/**/*.md",
    ]),
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//agent_core",
        "//agent_pkg/host",
        "//agent_pkg/runtime",
        "//cli_util",
        "//mcp_infra",
        "//net_util",
        "//openai_utils",
        "@pypi//aiodocker",
        "@pypi//alembic",
        "@pypi//asyncpg",
        "@pypi//canonicaljson",
        "@pypi//docker",
        "@pypi//jinja2",
        "@pypi//plotext",
        "@pypi//psycopg",
        "@pypi//psycopg2_binary",
        "@pypi//pydantic",
        "@pypi//pygit2",
        "@pypi//pyyaml",
        "@pypi//requests",
        "@pypi//rich",
        "@pypi//sqlalchemy",
        "@pypi//tiktoken",
        "@pypi//typer",
        "@pypi//typer_di",
        "@pypi//uvicorn",
    ],
)

py_binary(
    name = "props",
    srcs = ["cli/main.py"],
    main = "cli/main.py",
    deps = [":core"],
)

py_test(
    name = "test_core",
    srcs = glob(["tests/**/*.py"]),
    main = "tests/test_agent_types.py",
    deps = [
        ":core",
        "//agent_core_testing",
        "@pypi//pytest",
        "@pypi//pytest_asyncio",
        "@pypi//pytest_env",
        "@pypi//pytest_mock",
        "@pypi//pytest_timeout",
        "@pypi//pytest_xdist",
    ],
)

ruff_test(
    name = "ruff",
    srcs = [":core"],
)
