load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("//cluster/kubespand/qemu_tests:initramfs.bzl", "initramfs")

go_library(
    name = "doublenat_lib",
    testonly = True,
    srcs = ["main.go"],
    importpath = "github.com/agentydragon/ducktape/cluster/kubespand/qemu_tests/vms/doublenat",
    deps = [
        "//cluster/kubespand/qemu_tests/vms/initlib",
        "//cluster/kubespand/qemu_tests/vms/kubespanlib",
    ],
)

go_binary(
    name = "doublenat",
    testonly = True,
    embed = [":doublenat_lib"],
    goarch = "amd64",
    goos = "linux",
    static = "on",
    visibility = ["//cluster/kubespand:__subpackages__"],
)

initramfs(
    name = "initramfs",
    testonly = True,
    extra_binaries = {
        "//cluster/kubespand": "/kubespand",
    },
    extra_dirs = [
        "/var/lib/kubespan",
        "/etc/kubespan",
    ],
    init = ":doublenat",
    visibility = ["//cluster/kubespand:__subpackages__"],
)
