load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "clusterctrl",
    srcs = [
        "discovery_service.go",
        "kubernetes_node.go",
    ],
    importpath = "github.com/agentydragon/ducktape/cluster/kubespand/controllers/cluster",
    visibility = ["//cluster/kubespand:__subpackages__"],
    deps = [
        "//cluster/kubespand/agentconfig",
        "//cluster/kubespand/discovery",
        "@com_github_cosi_project_runtime//pkg/controller",
        "@com_github_cosi_project_runtime//pkg/resource",
        "@com_github_cosi_project_runtime//pkg/safe",
        "@com_github_cosi_project_runtime//pkg/state",
        "@com_github_siderolabs_discovery_api//api/v1alpha1/client/pb",
        "@com_github_siderolabs_discovery_client//pkg/client",
        "@com_github_siderolabs_gen//optional",
        "@com_github_siderolabs_talos_pkg_machinery//resources/cluster",
        "@com_github_siderolabs_talos_pkg_machinery//resources/k8s",
        "@com_github_siderolabs_talos_pkg_machinery//resources/kubespan",
        "@com_github_siderolabs_talos_pkg_machinery//resources/network",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/fields",
        "@io_k8s_client_go//informers",
        "@io_k8s_client_go//kubernetes",
        "@io_k8s_client_go//rest",
        "@io_k8s_client_go//tools/cache",
        "@io_k8s_client_go//tools/clientcmd",
        "@org_uber_go_zap//:zap",
    ],
)
