apiVersion: v2
name: traefik
description: Traefik ingress controller for Ducktape clusters
version: 0.1.0
appVersion: "3.0"
type: application

dependencies:
  - name: common-lib
    version: ^0.1.1
    repository: file://../common-lib
