load("//devinfra/python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "benchmark_ollama",
    srcs = ["benchmark_ollama.py"],
    deps = [
        "//util/bazel:workspace",
        "@pypi//openai",
    ],
)

py_binary(
    name = "benchmark_ollama_bin",
    main_module = "hack.benchmark_ollama.benchmark_ollama",
    deps = [":benchmark_ollama"],
)
