apiVersion: v1
kind: Secret
metadata:
    name: tofu-state-ollama-bearer-token-credentials
    namespace: tofu-state
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ollama
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ollama
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xpGzSt4+4n1Ifna4VFXBWh9xMU7jYWGQnuWL,iv:xJx0FmSnam/Kob8rjN5Ps3SE/Ddl/V4Y42oCfjyWgu4=,tag:BJnCPiRUFeLTjAz9GzLyAA==,type:str]
    password: ENC[AES256_GCM,data:LX8IHk7lkm9gvh4/hnNSoHd92rO5g4eCUwF+K9tFtUsMbtb09O7I6FRqr+t/BG7bHe+jPP0RuTHDZtFf7v18tA==,iv:fXUYxSFgzxBPwQN1nJwlE3jJtFsMA4iHsHpvBQvEzeQ=,tag:O2OEbyH9/SlCLA+hsRridQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdHpxUCtDV05vSFhvQjJU
            ZHgxb2RzbDBuWUNxQ21FaytBcEg0MnhuMXljCnc1Yy9sZGRuRWhDNml6Vk9udE80
            U3daS2NUNVlNbXBxNVhRSGswYkhEME0KLS0tIFhCdjViU3I2RXhpTmQwVDVWU3dY
            QWpweVhoOGluRCtDNCtoOG1JSWlxTFkKPXy5eqTT+XEq93YAZbgCpr6QyLiZAVcj
            AkMxhzroKkS1rGT4f+5SqpMr8P8x05EWZsiv4aLPh+Z/Qm5h/ubuzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSGxuTkxDNTJUS1I4NDdh
            QjZ5eFh4allFWXp1dUw1Wi9VMkhZL1J4aGlrCkVkUnpSb2piakdlbTg4Z0Y1N3pv
            c2V3M2dQbHFkeTlMaVpoNmtKQjExNDgKLS0tIHYyVVUwUzFNZXpCZkRPNlhYblRq
            b0tqeUFjSURVMU42cmpid3VDR3lYVlEKIe0PYsEskxSAwMS3/tsTqEQ35OurR/IB
            +Yl4y3XUTPK0dZx6qj+TwlVPpz1kfz3lUwjDlkowO5/7II82bLx7aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T20:57:31Z"
    mac: ENC[AES256_GCM,data:zY7HbPX6HNlH3VvWeY+O4sAakV+COTuaSWS5DNJvg445n4iv1jTrhnlv4g59nIHsXFjKkg/OHWci22aZCzwX+6Ztt8hw9SRdtc+c77tObLQKSCj96ei9Fpu/ajfheD5/ff0VrzxiucTl3HkxxMCBVE+ubyAP2l1Hrga39BNsFr0=,iv:b24D8QSVqwIdANf6uZBZFoaxR2KynA1YX0uMpRXuW6k=,tag:LgA8zWIPa2Oz2ERh/GtUJg==,type:str]
    version: 3.13.3
