# Per-session Bazel configuration (auto-generated by Claude Code session hook)
# Platform: ${platform.platform.value} (${platform.root_fstype})
# See devinfra/claude/web_env/docs/container_spec.md for environment details.
% if bazel_cache_dir:
startup --output_user_root=${bazel_cache_dir | sh}
% endif
## JVM heap sizing: full-monorepo `bazel query` loads 6000+ packages into
## Skyframe analysis cache. On Firecracker (16Gi RAM, ext4 disk), 8Gi heap
## is needed; the default ~4Gi auto-sized heap causes OOM.
## On gVisor with tmpfs, use a smaller heap to leave room for tmpfs.
## See container_spec.md "Bazel JVM Heap" and debug/bazel-bench-2026-03-24.md.
% if platform.is_firecracker:
startup --host_jvm_args=-Xmx8g
% elif platform.is_gvisor:
startup --host_jvm_args=-Xmx4g
% endif
% if system_java_cacerts:
# Bazel's bundled JDK uses its own cacerts which lacks Anthropic's TLS
# inspection CA, so direct BCR fetches (e.g. bcr.bazel.build) fail with
# PKIX path building failed under the transparent MITM proxy. Pointing the
# JVM at /etc/ssl/certs/java/cacerts picks up the system-wide truststore,
# which ca-certificates-java populates from /etc/ssl/certs/ca-certificates.crt
# (and therefore contains the Anthropic CA on web containers). Emitted after
# the setup_auth_proxy block so it overrides any session-local truststore.
startup --host_jvm_args=-Djavax.net.ssl.trustStore=${system_java_cacerts | sh}
startup --host_jvm_args=-Djavax.net.ssl.trustStorePassword=changeit
% endif
% if setup_auth_proxy:
startup --host_jvm_args=-Djavax.net.ssl.trustStore=${truststore_path | sh}
startup --host_jvm_args=-Djavax.net.ssl.trustStorePassword=${truststore_password | sh}
# BCR fetches use the native JVM proxy settings from Anthropic's
# JAVA_TOOL_OPTIONS (proxyHost/proxyPort/proxyUser/proxyPassword). Only gRPC
# traffic (remote execution, cache, BES) needs the UDS proxy.
startup --host_jvm_args=-Djdk.http.auth.tunneling.disabledSchemes=

# Pass proxy + TLS CA to repository rules (for Go modules in gazelle, etc.)
# GONOPROXY=* forces all Go module downloads through HTTP proxy.
# Explicitly NOT passing NO_PROXY since it excludes *.googleapis.com
# (see also _strip_no_proxy_google in env_file.py which fixes this globally).
common --repo_env=HTTP_PROXY
common --repo_env=HTTPS_PROXY
common --repo_env=http_proxy
common --repo_env=https_proxy
common --repo_env=GONOPROXY=*
common --repo_env=GOPRIVATE=
common --repo_env=GOSUMDB=sum.golang.org
# TLS inspection CA: the egress proxy MITMs HTTPS, so git and Go need the
# proxy CA in their trust stores.  GIT_SSL_CAINFO covers git-ls-remote
# (used by Gazelle fetch_repo), SSL_CERT_FILE covers Go's net/http and most
# other tools that repo rules shell out to.  These are --repo_env so they
# only affect the Bazel host (repo rules); RBE workers are unaffected.
common --repo_env=GIT_SSL_CAINFO=${combined_ca_path | sh}
common --repo_env=SSL_CERT_FILE=${combined_ca_path | sh}

# Skip live OpenAI tests in wildcard expansion (no API key available)
test --test_tag_filters=-live_openai_api
% endif
% if bazel_remote_proxy_sock:
# Route gRPC remote execution/cache through a UDS proxy (direct on CLI,
# CONNECT tunnel through egress proxy on web). Uses Bazel's native --remote_proxy,
# bypassing gRPC-Java's proxy auth timing issue.
# On CLI: socket accessible inside bwrap sandbox (--ro-bind / / exposes host fs;
# no seccomp on most Linux machines means AF_UNIX is not blocked).
build --remote_proxy=unix:${bazel_remote_proxy_sock}
% endif
% if bazel_bes_proxy_sock:
# Route BES to the local interceptor which inspects events and forwards to BuildBuddy.
# The interceptor runs as a gRPC service, so we point --bes_backend (not --bes_proxy)
# at it — Bazel speaks BES directly to our service on UDS.
build --bes_backend=unix:${bazel_bes_proxy_sock}
build --bes_results_url=https://app.buildbuddy.io/invocation/
% endif

% if buildbuddy_bazelrc:
# BuildBuddy remote cache (API key written to per-session bazelrc)
try-import ${buildbuddy_bazelrc}
% endif
% if bbr_bazelrc:
# bbr metadata (ROLE, session TAGS) — also read by bbr for bb remote invocations
try-import ${bbr_bazelrc}
% endif

# AI agent quiet mode (suppress verbose progress for agent transcript)
# Bazel 7.6+ reads workspace and user RC files in addition to --bazelrc=,
# so the config definition in the workspace .bazelrc is available here.
common --config=ai_agent
