# Per-session Bazel configuration (auto-generated by Claude Code session hook)
% if bazel_cache_dir:
startup --output_user_root=${bazel_cache_dir | sh}
% endif
% if web_proxy:
# Route Bazel's JVM through the local auth proxy (localhost:${proxy_port}).
# The auth proxy adds Proxy-Authorization credentials when forwarding to the
# egress proxy. This is needed because gRPC-Java's ProxyDetectorImpl reads
# proxy settings from ProxySelector (via these system properties) but cannot
# reliably authenticate — Bazel's ProxyHelper installs the Authenticator only
# when a repository rule triggers a download, which may be after the gRPC
# remote execution channel is already established.
startup --host_jvm_args=-Dhttps.proxyHost=127.0.0.1
startup --host_jvm_args=-Dhttps.proxyPort=${proxy_port}
startup --host_jvm_args=-Djavax.net.ssl.trustStore=${truststore_path | sh}
startup --host_jvm_args=-Djavax.net.ssl.trustStorePassword=${truststore_password | sh}

# Pass proxy + TLS CA to repository rules (for Go modules in gazelle, etc.)
# GONOPROXY=* forces all Go module downloads through HTTP proxy.
# Explicitly NOT passing NO_PROXY since it excludes *.googleapis.com
# (see also _strip_no_proxy_google in env_file.py which fixes this globally).
common --repo_env=HTTP_PROXY
common --repo_env=HTTPS_PROXY
common --repo_env=http_proxy
common --repo_env=https_proxy
common --repo_env=GONOPROXY=*
common --repo_env=GOPRIVATE=
common --repo_env=GOSUMDB=sum.golang.org
# TLS inspection CA: the egress proxy MITMs HTTPS, so git and Go need the
# proxy CA in their trust stores.  GIT_SSL_CAINFO covers git-ls-remote
# (used by Gazelle fetch_repo), SSL_CERT_FILE covers Go's net/http and most
# other tools that repo rules shell out to.  These are --repo_env so they
# only affect the Bazel host (repo rules); RBE workers are unaffected.
common --repo_env=GIT_SSL_CAINFO=${combined_ca_path | sh}
common --repo_env=SSL_CERT_FILE=${combined_ca_path | sh}

# Tag invocations for BuildBuddy filtering
build --build_metadata=ROLE=claude-code

# Skip live OpenAI tests in wildcard expansion (no API key available)
test --test_tag_filters=-live_openai_api
% endif

# BuildBuddy remote cache (API key in separate bazelrc, no-op if absent)
try-import ${buildbuddy_bazelrc}

# AI agent quiet mode (suppress verbose progress for agent transcript)
# Bazel 7.6+ reads workspace and user RC files in addition to --bazelrc=,
# so the config definition in the workspace .bazelrc is available here.
common --config=ai_agent
