apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - synapse-signing-key.sops.yaml
  - synapse-registration-secret.sops.yaml
  - synapse-macaroon-secret.sops.yaml
  - synapse-redis-password.sops.yaml
  - synapse-admin-credentials.sops.yaml
  - haku-matrix-bot-password.sops.yaml
  - public-coder-agent-matrix-bot-password.sops.yaml
