apiVersion: v1
kind: Secret
metadata:
    name: openclaw-matrix-bot-password
    namespace: matrix
    annotations: {}
stringData:
    password: ENC[AES256_GCM,data:BOZe4IqaIrR7YGrDiioBIR59Qwy6vBQR5bt1mqh6O/s=,iv:ZKB9r5UGPh/zUbTRO+RujjtNwTl5HrMAyABCYYyBFPc=,tag:pImJtAHC9kwbVB+2vbPuCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVUhiem5MaDBicmFBenNl
            ZzVtNzJNRmNTMWJJWi9zTzJ0R09CWkZ1QzM0CkRkZ1FkV2ErbFUyUEdHSDBSR3Uz
            N0Q2ck1RSTBqNnZIWWJPMmpBVEdYWUkKLS0tIHpoMHFwQ1phQnFFRGoxdzh0bElG
            YVNYTDEwWDZCSGdQWS9wWG1vZms5azgKbx/SysFz9Fqc0SHzLiECSdtfcqccA8cn
            dZi0eO55iIkuYmeipoYHC20g3AMS/s8sGqLNn3ULnxCDIvUx3Zd3eA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMGtGeFFOL0s5c1o0dStr
            N1Fta1dKOCsrS2tvVXB2R2poN2R6NWZSSERvCnpNaTVNbm96bFR1eUNqS042Q0py
            dFlOVXlMNGhGbXVCTHJPTEFkZFVqbzQKLS0tIDcyeGZHMU5waEN4cGZQdEhUVUgw
            dHlOdTBYeWtBMkNpYjdoaFpKNkVOSDQKizMAGoq3DCvQRTaz8VkaasTg+iKCEh9M
            8c890Kc/F/p5Le4F/NtLAB0TppWVOTXg3zW2rgQX0vCEpW4ombbX9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T22:07:26Z"
    mac: ENC[AES256_GCM,data:tis1B40FzEtpctdW3l+yuE6AGpIP91yTCTm+C8aCbXaiU7Z0ybBUxaphJ0HiR44e98tJfiF1N/iss7XZLnnRhEC9tx0dpCxAArYQzTiM6swhSfglRlFUmKnHUVb3LBSPDFql4JKtAWeVplcQBq7YuRdO77V3nhyI2BH2hrL8OaQ=,iv:dSiSOaIBjWpoWxPJaqdx9TIxut7j0DHqhvJCKG34Xgk=,tag:rs8a9MGMpVPwvQ3d8uD85w==,type:str]
    version: 3.12.1
