apiVersion: v1
kind: Secret
metadata:
  name: synapse-signing-key
  namespace: matrix
stringData:
  signing.key: ENC[AES256_GCM,data:dLsb0joy/nzLb82dvp7zEd4E3prfvVZtzieGiQn1/Tyq5ohMTJMhWJYxbbnUonDETs+PXQE=,iv:l+rwqLtZXTkv9ikmXLMOudd6mot37fhOqBWzqN7+rz8=,tag:R3R8Rc6EkAI47UGPgKJ9OA==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOW04Sk40NVFISGlIU2NI
        RzYxV1NaZk4zL1AxWlRMR0Z5Mlo4UEZ6TGtnCjRmTkVaT0tPWml6UkRPMC81R0dQ
        eUFpR29OakJFNjMyb1VjNVNOL1MvalEKLS0tIHFkN2FrS1lzK2VKclZ5S29aUVl0
        Nks2MXR6VW9qNEpyVTc2b094Wi96c3MKawVCdKTMgtbQ7D3MkIUJzF63Ye9BEZPr
        jrQ6e3UH33qMhP2vLS7E/h2iPpchR05ANUvNSFjjhgLHssnAklmdlw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUy9VRStXUGl3VTlzNVRT
        LzdsUml4UkwvYW5oSTh3LzREbU90Q3RvNTI0Ck0raDJXZUlRN0UxY002Y0t2eUY2
        OHBZQlVsYzBqTDJGL2IzS1I2RFdZTUEKLS0tIDVrSjZlclptSDNuaW1aNUlFYW9C
        SytxSEVoNlcwTS8rOTRpbGNwVU1qa1EKzIvpTZeJSEPjgelN/PYgBCOb6RzqaIQF
        ccMNHiAYMMVlvUV2+l+Ga2by9ZOw36GHsuIlRf7ACHFFddjli0QbEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T05:27:17Z"
  mac: ENC[AES256_GCM,data:/yXLsYtfxkg69TRL42yiI2F+Km/TlWUYSi4WbZTCdrvf41TVR/VLwrYZuLb+DV6yEPcbIiCsU1ak8zO6hjnKsInzRuLE+cns7xoMTDZH2b2hGi5GYwv833NiSqD8pCr6B+83vduqZ5mLSbNmLf7PVhaMQK3VMJkllGIq0PPg/yE=,iv:VKzTEDaBvpOS1DKgOAYLfD+7t+/lGtK+G84d5v/RiH8=,tag:QSIYA3Y8BucF32sOmO55aQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
