apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: git.allegedly.works/ducktape-ci/plaid-mcp-server
    newTag: devel-20260929025739-c4ba0a9 # {"$imagepolicy": "flux-system:plaid-mcp-server:tag"}
  - name: git.allegedly.works/ducktape-ci/plaid-mcp-sync
    newTag: devel-20260929025744-c4ba0a9 # {"$imagepolicy": "flux-system:plaid-mcp-sync:tag"}
