# SeaweedFS s3 identity for "mimir".
apiVersion: v1
kind: Secret
metadata:
    name: s3-identity-mimir
    namespace: seaweedfs
    labels:
        seaweedfs.io/role: s3-identity
type: Opaque
stringData:
    name: mimir
    actions: Admin
    accessKey: ENC[AES256_GCM,data:dTlSe6WRmyPKRHV9WdTPbedn0FA=,iv:DGHzcic0PVYzpD3lCcxbpxHdsM/mA0rndousFvbAD8Y=,tag:Ezo2SpuRK0co6OMw/QPojw==,type:str]
    secretKey: ENC[AES256_GCM,data:8UEQdZIK3+TKUljlgsQAkDBND35Fd3KvlaMBjx5nXkHHSmeAH9jJxQ==,iv:zktT5i6QB7FmqR2tObxvmVQGFCgd87oDWA/kqJNzlcA=,tag:Vuo/QvsNGBxucBca/t811Q==,type:str]
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR1gzOXQ4SHJEeFErSjhV
            QkpDUm5JeFZ1KzFuczNVdEtId1J2aUI4MGtNClBTSndBMy9wbWx2MkhHUHp1ZXM1
            cEdTcEZGaG1TUG16T2FrR0RIS0NjRjAKLS0tIGwyMi9OUnNFNnVtWEMrTHVhbHUy
            SXVUQlVHOFJhSXZHcmUzQVo0VmVmNWMK9K8JHYavmM8bmSE5NFnnPN6p4/dnn2/S
            xWU6HpARzLdQytXirwHq1rJcE4vYsPe9MhHZr+P9AQdfWbHnypO1/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVlVnMTJMbVV0eVM3cmI3
            VDBTMnRyTmI4eFp1WU5jZG1GVEVpeXZxMTJ3ClBrbU53SWp3SWFZSFFSbnA3OWlh
            SWpVNlFtNFFKVEVhWXl2WDlVNWNpaGMKLS0tIDNNV3pzaUtyanBmOW9xLys4dEJB
            TTJ5ZGUyZFdEbDJiM1JKaUJjME0wNTQKKXV9TcqmFLF9qDUBLIgCGzFj66EZGkti
            QEKh08OIWL3345GXFkLojdqcqX0R78zmIa1wrf5lAaK0HpZAG53Bbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T23:50:43Z"
    mac: ENC[AES256_GCM,data:cNL4/+MOIvKLLOCvMZMeW9TMcMpXBwAoJl256omJL0HmUOMTiXwnzFKwQdkvupm2sB7ve8Ft3unab4otkO47dinv4rzmCE2aCPBcLEThKXK38/TNTTdV3mC80zmElRUGL468u1zAkNHPSe01JHMG5oP3kO4WJt8XDOGBgkoo8Aw=,iv:fmuR0MvquwqohyKusDE/kQPjG2KpLA0LgKBmR72Rjt0=,tag:qVti3UP6e/5kNnfawOL2AA==,type:str]
    encrypted_regex: ^(accessKey|secretKey)$
    version: 3.12.1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: s3-identity-mimir-json
    namespace: seaweedfs
    labels:
        seaweedfs.io/role: s3-identity-json
spec:
    refreshInterval: 1m
    secretStoreRef:
        kind: SecretStore
        name: seaweedfs-identities
    target:
        name: s3-identity-mimir-json
        template:
            type: Opaque
            data:
                identity: |
                    {"name":"{{ .name }}",
                     "credentials":[{"accessKey":"{{ .accessKey }}","secretKey":"{{ .secretKey }}"}],
                     "actions":[{{- $first := true -}}
                       {{- range splitList "," .actions -}}
                       {{- if not $first }},{{ end -}}"{{ . }}"{{- $first = false -}}
                       {{- end }}]}
    dataFrom:
        - extract:
            key: s3-identity-mimir
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR1gzOXQ4SHJEeFErSjhV
            QkpDUm5JeFZ1KzFuczNVdEtId1J2aUI4MGtNClBTSndBMy9wbWx2MkhHUHp1ZXM1
            cEdTcEZGaG1TUG16T2FrR0RIS0NjRjAKLS0tIGwyMi9OUnNFNnVtWEMrTHVhbHUy
            SXVUQlVHOFJhSXZHcmUzQVo0VmVmNWMK9K8JHYavmM8bmSE5NFnnPN6p4/dnn2/S
            xWU6HpARzLdQytXirwHq1rJcE4vYsPe9MhHZr+P9AQdfWbHnypO1/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVlVnMTJMbVV0eVM3cmI3
            VDBTMnRyTmI4eFp1WU5jZG1GVEVpeXZxMTJ3ClBrbU53SWp3SWFZSFFSbnA3OWlh
            SWpVNlFtNFFKVEVhWXl2WDlVNWNpaGMKLS0tIDNNV3pzaUtyanBmOW9xLys4dEJB
            TTJ5ZGUyZFdEbDJiM1JKaUJjME0wNTQKKXV9TcqmFLF9qDUBLIgCGzFj66EZGkti
            QEKh08OIWL3345GXFkLojdqcqX0R78zmIa1wrf5lAaK0HpZAG53Bbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T23:50:43Z"
    mac: ENC[AES256_GCM,data:cNL4/+MOIvKLLOCvMZMeW9TMcMpXBwAoJl256omJL0HmUOMTiXwnzFKwQdkvupm2sB7ve8Ft3unab4otkO47dinv4rzmCE2aCPBcLEThKXK38/TNTTdV3mC80zmElRUGL468u1zAkNHPSe01JHMG5oP3kO4WJt8XDOGBgkoo8Aw=,iv:fmuR0MvquwqohyKusDE/kQPjG2KpLA0LgKBmR72Rjt0=,tag:qVti3UP6e/5kNnfawOL2AA==,type:str]
    encrypted_regex: ^(accessKey|secretKey)$
    version: 3.12.1
