load("@aspect_rules_js//js:defs.bzl", "js_library", "js_test")

_BABEL_DEPS = [
    "//:node_modules/@babel/generator",
    "//:node_modules/@babel/parser",
    "//:node_modules/@babel/traverse",
    "//:node_modules/@babel/types",
]

js_library(
    name = "libs",
    srcs = [
        "chunk.mjs",
        "function_parts.mjs",
        "function_parts_worker.mjs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//devinfra/js/debundle/common:libs",
    ] + _BABEL_DEPS,
)

js_test(
    name = "chunk_test",
    data = [
        "chunk.mjs",
        "//devinfra/js/debundle/common:sources",
        "//devinfra/js/debundle/test_support:sources",
    ] + _BABEL_DEPS,
    entry_point = "chunk_test.mjs",
)

js_test(
    name = "function_parts_test",
    data = [
        "chunk.mjs",
        "function_parts.mjs",
        "function_parts_worker.mjs",
        "//devinfra/js/debundle/common:sources",
        "//devinfra/js/debundle/test_support:sources",
        "//devinfra/js/debundle/transforms:libs",
    ] + _BABEL_DEPS,
    entry_point = "function_parts_test.mjs",
)
