apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ember.configName" . }}
  labels:
    {{- include "common.labelsWith" (dict "context" . "extra" (dict "app.kubernetes.io/component" "runtime")) | nindent 4 }}
data:
  ember.toml: |
{{ tpl (.Files.Get "files/ember.toml.tpl") . | indent 4 }}
