# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "app",
    srcs = ["app.py"],
    data = ["dashboard.json"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:grafana_dashboards",
        "//cluster/cdk8s:manifest_roots",
        "//cluster/cdk8s/clickhouse:client",
        "//cluster/cdk8s/providers/grafana_operator:grafana_dashboard",
        "//cluster/cdk8s/providers/grafana_operator:grafana_datasource",
        "//cluster/cdk8s/providers/grafana_operator:grafanadashboard",
        "//cluster/cdk8s/providers/grafana_operator:grafanadatasource",
        "@pypi//cdk8s",
    ],
)
