load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "o11y",
    srcs = [
        "discard_o11y_service.go",
        "metric_types.go",
        "metrics.go",
        "otel_logger.go",
        "otel_metrics.go",
        "service.go",
        "util.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/o11y",
    visibility = ["//claude_web_env/re/environment_manager/6b49f1ca/src:__subpackages__"],
    deps = [
        "@io_opentelemetry_go_contrib_bridges_otelslog//:otelslog",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//semconv/v1.24.0:v1_24_0",
        "@io_opentelemetry_go_otel_exporters_otlp_otlplog_otlploghttp//:otlploghttp",
        "@io_opentelemetry_go_otel_exporters_otlp_otlpmetric_otlpmetrichttp//:otlpmetrichttp",
        "@io_opentelemetry_go_otel_exporters_stdout_stdoutmetric//:stdoutmetric",
        "@io_opentelemetry_go_otel_metric//:metric",
        "@io_opentelemetry_go_otel_sdk//resource",
        "@io_opentelemetry_go_otel_sdk_log//:log",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
        "@io_opentelemetry_go_otel_sdk_metric//metricdata",
    ],
)
