# gazelle:python_generation_mode off

load("@rules_python//python:defs.bzl", "py_binary")

# Export generic test file and conftest for specimen_targets to reference
exports_files([
    "test_specimen.py",
    "conftest.py",
])

py_binary(
    name = "create_code_tar",
    srcs = ["create_code_tar.py"],
    main = "create_code_tar.py",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "create_data_blob",
    srcs = ["create_data_blob.py"],
    main = "create_data_blob.py",
    visibility = ["//visibility:public"],
    deps = [
        "//props/db/sync",
        "@pypi//pyyaml",
    ],
)
