apiVersion: v1
kind: Secret
metadata:
  name: docker-ci-server-tls
  namespace: docker-ci
type: Opaque
stringData:
  server-key.pem: ENC[AES256_GCM,data:9R+HmDK/4m7V+7Tu1+7vz5WF0+yiqQFEsyQlPJv20mVUsfQlePZtdaBcPYidx2kBZEMBThe/XaFQ293v030IC9c0j4Tgxns4YTg2MclAqS+VifcqYYNvtPimVcwG8ErCgfiyFiN9RV+zzvtL39XlwRbiyZ0hdWGcu2+nNrrGtmlwhOKNiche9u5Yvlj0vEccbThf9rFZM+oM1EF5GdiUtmVY/m5l9G81adGAE+vEx2cH2GhGWYKB73woGjF0Ycytpj1l7bDT5hmDr4brbXmAkmVzl7eUv64VsUmLyridERPbZLU=,iv:WjIXHT1Gi9V/JC/ipo6mIKdcByZbKKnMCLawBinw9pI=,tag:U3kWpnU0sMh6WHdIaeELBg==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R0dJWmM5NHY3dVJVTjFn
        ak1zbW5tWWtGODhJTnY1MTRwOW9OTnNTR0FnCmxtMm81dnRFQUdFL2ZGUFZmdHFo
        VG9xZm5nb3dPZWhqWXc0K2xyRmpLK2sKLS0tIHBVU3JES0xSTUQvNEZidzdRQk1y
        bDJyMk43bERXNm5YekVMeUIybnlsZncK3yJUOKlonxdqRkrCEJccXB/I8wTp22Da
        EeqMb5JKbkB8tVkPmvnOHFhCfSZYlxLdAwx3IEWq8voO2RCxzHfplA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYnFvNXBOOC9iNXNvdzdl
        SHl6SXVRWnhxUHVpY3RVS3d1TXpweDlYN0ZnCng5Zi8yZmY5WW9id3ZWSHJVajlw
        eENTWjE4c2JVOEhTY0VRZHVMd1hkS0UKLS0tIC91dHlzeWdEcFFPWHpvR05hNitq
        SXpRNVhMWVBKNEw5VEVBRjNyenVCdzQKEFEa5RMAH1AZcFiUhqgGFq0cn8C+t9OL
        mwb3N+upyGcO4YdTXp12cb1kpxmpnMTam85oI3gDw+3tjDp82c8D4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T02:07:39Z"
  mac: ENC[AES256_GCM,data:aH5kMOkMjA2fnr9Lu6sUAc7IIQM+54TbeSIN2v7eP8i9AcAEo+GdWXQYN5+Vc2idezFwyGxv8/LCqalFyP7yypszn9ZPgiBCYm1FDV0NMsqy1nrHVhyTEs1RmL0cXFxXUd5F7Uql5V7c11I8XPtBBq0hQ9pFLZlDzYb+m2VrBSE=,iv:/2LSjpECHGVLD21tYobS8t+1xhAnDAnTIe43iIrqlZo=,tag:dEXHHs8lmJl7eCvag2JbnA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
