load("//props/specimens:defs.bzl", "specimen_targets")

# Snapshot of ducktape at 167e3901.
# Included: adgn/, wt/
# Excluded: adgn/src/adgn/agent/web/, adgn/src/adgn/props/specimens/
specimen_targets(
    name = "specimen",
    code_srcs = glob(["code/**/*"]),
    slug = "ducktape/2025-11-21-00",
    split = "valid",
)
