"""Stakater Reloader (https://github.com/stakater/Reloader), which restarts pods when a
Secret or ConfigMap they reference changes, so secret rotation needs no manual restart."""

from __future__ import annotations

from pathlib import Path

from cdk8s import App, Chart
from flux_helm.io.fluxcd.toolkit.helm import (
    HelmRelease,
    HelmReleaseSpec,
    HelmReleaseSpecChart,
    HelmReleaseSpecChartSpec,
    HelmReleaseSpecChartSpecSourceRef,
    HelmReleaseSpecChartSpecSourceRefKind,
    HelmReleaseSpecInstall,
    HelmReleaseSpecInstallRemediation,
)
from flux_kustomize.io.fluxcd.toolkit.kustomize import KustomizationSpecHealthChecks
from flux_source.io.fluxcd.toolkit.source import HelmRepository, HelmRepositorySpec
from source_watcher_crds.io.fluxcd.extensions.source import ArtifactGeneratorSpecArtifacts

from cluster.cdk8s.flux import Kustomization, flux_kustomization, flux_kustomization_depends_on
from cluster.cdk8s.generation import write_charts
from cluster.cdk8s.metadata import metadata

NAME = "reloader"
NAMESPACE = "kube-system"
OUTPUT_DIR = "cluster/k8s/reloader"


def _values() -> dict[str, object]:
    return {
        "reloader": {
            # Watch all namespaces
            "watchGlobally": True,
            "enableHA": False,
            # By default Reloader only fires on Update events to a watched ConfigMap/Secret.
            # A delete-then-recreate sequence (e.g. tofu-controller re-creating an Authentik or
            # Forgejo credential secret as part of recovery -- see the 2026-06-03 forgejo-props
            # incident in <../docs/troubleshooting.md> § "Resource ID Desync After Wiping a
            # Backing Datastore") would otherwise be silently ignored, leaving consumer pods on
            # stale env values. These flags map to --reload-on-create / --reload-on-delete on
            # the operator.
            "reloadOnCreate": True,
            "reloadOnDelete": True,
            # Reload on ANY referenced ConfigMap/Secret change without requiring a per-workload
            # `reloader.stakater.com/auto` annotation. Required because operator-managed
            # Deployments -- notably seaweedfs-s3, generated by the SeaweedFS operator from the
            # Seaweed CR -- can only carry the annotation on the *pod template*
            # (spec.s3.annotations), which Reloader ignores: it reads the annotation off the
            # workload's own metadata. Without this, ESO reassembling `seaweedfs-s3-config`
            # when a tenant is added/rotated leaves the s3 gateway on stale identities until a
            # manual restart (the 2026-06-08 attic `InvalidAccessKeyId` incident). Opt a
            # workload out with `reloader.stakater.com/auto: "false"`.
            "autoReloadAll": True,
            # The Altinity operator hot-reloads its generated ClickHouse user config. Watching
            # clickhouse causes a feedback loop: each generated users ConfigMap update restarts
            # ClickHouse, the new Pod IP changes the next generated config, and Reloader
            # restarts it again. Operator-managed ClickHouse workloads therefore stay outside
            # cluster-wide auto reloads.
            "ignoreNamespaces": "clickhouse",
            # Use pod-template annotations, not Reloader's default env-var patch, to force
            # rollouts. The default mutates the container spec; operator-owned workloads can
            # reconcile that drift away. SeaweedFS proved this with `seaweedfs-s3`: the operator
            # reverted Reloader's env-var patch, leaving stale S3 identities loaded. Annotation
            # mode changes the pod-template hash without touching the container spec, and a
            # throwaway Seaweed experiment confirmed the operator preserves that annotation
            # across reconcile. Full RCA:
            # <../docs/lessons_learned/2026_07_04_seaweedfs_s3_identity_stale_after_tenant_add.md>.
            "reloadStrategy": "annotations",
            "deployment": {
                "resources": {
                    "limits": {"cpu": "100m", "memory": "128Mi"},
                    "requests": {"cpu": "10m", "memory": "64Mi"},
                }
            },
        }
    }


def chart(app: App) -> Chart:
    chart = Chart(app, NAME, disable_resource_name_hashes=True)
    repository = HelmRepository(
        chart,
        "repository",
        metadata=metadata("stakater", "flux-system"),
        spec=HelmRepositorySpec(interval="24h", url="https://stakater.github.io/stakater-charts"),
    )
    HelmRelease(
        chart,
        "release",
        metadata=metadata(NAME, NAMESPACE),
        spec=HelmReleaseSpec(
            interval="30m",
            install=HelmReleaseSpecInstall(remediation=HelmReleaseSpecInstallRemediation(retries=3)),
            chart=HelmReleaseSpecChart(
                spec=HelmReleaseSpecChartSpec(
                    chart=NAME,
                    version="2.*",
                    source_ref=HelmReleaseSpecChartSpecSourceRef(
                        kind=HelmReleaseSpecChartSpecSourceRefKind.HELM_REPOSITORY,
                        name=repository.name,
                        namespace=repository.metadata.namespace,
                    ),
                )
            ),
            values=_values(),
        ),
    )
    return chart


def write_manifests(root: Path) -> None:
    write_charts(root, OUTPUT_DIR, chart)


def reloader(chart: Chart, artifact: ArtifactGeneratorSpecArtifacts, kyverno: Kustomization) -> Kustomization:
    return flux_kustomization(
        chart,
        NAME,
        artifact,
        interval="10m0s",
        timeout="5m",
        health_checks=[
            KustomizationSpecHealthChecks(
                api_version="helm.toolkit.fluxcd.io/v2", kind="HelmRelease", name=NAME, namespace=NAMESPACE
            )
        ],
        depends_on=[flux_kustomization_depends_on(kyverno)],
    )
