# Per-session Bazel configuration (auto-generated by Claude Code session hook)
% if web_proxy:
# JVM proxy settings for Bazel server (BCR access, etc.)
startup --host_jvm_args=-Dhttps.proxyHost=127.0.0.1
startup --host_jvm_args=-Dhttps.proxyPort=${proxy_port}
startup --host_jvm_args=-Djavax.net.ssl.trustStore=${truststore_path | sh}
startup --host_jvm_args=-Djavax.net.ssl.trustStorePassword=${truststore_password | sh}

# Pass proxy + TLS CA to repository rules (for Go modules in gazelle, etc.)
# GONOPROXY=* forces all Go module downloads through HTTP proxy.
# Explicitly NOT passing NO_PROXY since it excludes *.googleapis.com
# (see also _strip_no_proxy_google in env_file.py which fixes this globally).
common --repo_env=HTTP_PROXY
common --repo_env=HTTPS_PROXY
common --repo_env=http_proxy
common --repo_env=https_proxy
common --repo_env=GONOPROXY=*
common --repo_env=GOPRIVATE=
common --repo_env=GOSUMDB=sum.golang.org
# TLS inspection CA: the egress proxy MITMs HTTPS, so git and Go need the
# proxy CA in their trust stores.  GIT_SSL_CAINFO covers git-ls-remote
# (used by Gazelle fetch_repo), SSL_CERT_FILE covers Go's net/http and most
# other tools that repo rules shell out to.  These are --repo_env so they
# only affect the Bazel host (repo rules); RBE workers are unaffected.
common --repo_env=GIT_SSL_CAINFO=${combined_ca_path | sh}
common --repo_env=SSL_CERT_FILE=${combined_ca_path | sh}

# Tag invocations for BuildBuddy filtering
build --build_metadata=ROLE=claude-code

# Skip live OpenAI tests in wildcard expansion (no API key available)
test --test_tag_filters=-live_openai_api
% if local_registry_path:

# Local registry with patched ape module (native ELF instead of APE binaries)
# This avoids binfmt_misc requirement in Claude Code web containers
# Note: Local registry is checked first, then BCR as fallback
common --registry=file://${local_registry_path | sh}
common --registry=https://bcr.bazel.build
% endif
% endif

# AI agent quiet mode (suppress verbose progress for agent transcript)
# Bazel 7.6+ reads workspace and user RC files in addition to --bazelrc=,
# so the config definition in the workspace .bazelrc is available here.
common --config=ai_agent
