load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "orchestrator",
    srcs = [
        "hooks.go",
        "orchestrator.go",
        "poll_hook.go",
        "poller.go",
        "whoami.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/orchestrator",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/o11y",
        "//internal/sandbox",
        "//internal/util",
    ],
)
