load("@rules_oci//oci:defs.bzl", "oci_load")
load("//devinfra/testing:defs.bzl", "py_test")

oci_load(
    name = "e2e_container_load",
    testonly = True,
    image = "@e2e_container_linux_amd64",
    repo_tags = ["e2e-container:pinned"],
)

filegroup(
    name = "e2e_container_tarball",
    testonly = True,
    srcs = [":e2e_container_load"],
    output_group = "tarball",
)

py_test(
    name = "test_container_e2e",
    size = "large",
    srcs = ["test_container_e2e.py"],
    data = [
        ":e2e_container_tarball",
        "//:claude_hooks_wheel",
        "//devinfra/claude/testdata/test_workspace:workspace_files",
        "//devinfra/claude/testing:mock_egress_proxy_tarball",
    ],
    env_inherit = [
        "DOCKER_HOST",
    ],
    imports = ["../../../.."],
    tags = [
        "e2e",
        "external",
    ],
    deps = [
        "//devinfra/claude:conftest",
        "//devinfra/claude/auth_proxy:setup",
        "//devinfra/claude/auth_proxy:vars",
        "//devinfra/claude/testing:conftest",
        "//devinfra/claude/testing:mock_egress_proxy",
        "//util:oci",
        "//util/bazel:runfiles",
        "//util/testing:undeclared_outputs",
        "@pypi//aiodocker",
        "@pypi//aiohttp",
        "@pypi//pytest",
        "@pypi//pytest_asyncio",
        "@pypi//pytest_bazel",
        "@pypi//tenacity",
        "@pypi//yarl",
    ],
)
