apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sandboxtemplate-zai.yaml
  - sandboxwarmpool-zai.yaml
  - sandboxtemplate-codex.yaml
  - sandboxwarmpool-codex.yaml
  - cleanuppolicy-workspace-janitor.yaml
