load("//devinfra/python:defs.bzl", "py_binary", "py_library", "py_test")

exports_files(
    ["kubeconfig.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "kubeconfig",
    srcs = ["kubeconfig.py"],
    visibility = ["//visibility:public"],
    deps = ["@pypi//pyyaml"],
)

py_binary(
    name = "kubeconfig_bin",
    main_module = "devinfra.k8s.kubeconfig",
    deps = [":kubeconfig"],
)

py_binary(
    name = "extract_crd_bin",
    main_module = "devinfra.k8s.extract_crd",
    visibility = ["//visibility:public"],
    deps = [":extract_crd"],
)

py_test(
    name = "test_extract_crd",
    srcs = ["test_extract_crd.py"],
    deps = [
        ":extract_crd",
        "//:conftest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_kubeconfig",
    srcs = ["test_kubeconfig.py"],
    deps = [
        ":kubeconfig",
        "//:conftest",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
        "@pypi//pyyaml",
    ],
)

py_library(
    name = "extract_crd",
    srcs = ["extract_crd.py"],
    deps = ["@pypi//pyyaml"],
)
