apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: haku-mitmproxy-root-ca
  namespace: haku-mitmproxy
spec:
  isCA: true
  commonName: haku-mitmproxy-root-ca
  secretName: haku-mitmproxy-ca
  duration: 87600h # 10 years
  renewBefore: 8760h # 1 year
  privateKey:
    algorithm: ECDSA
    size: 256
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: cert-manager
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: cert-manager
  issuerRef:
    name: cluster-ca-bootstrap
    kind: ClusterIssuer
