apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mitmproxy-ca-key.sops.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - cnp-haku-cloud-api-egress.yaml
  - ccnp-haku-proxy-egress.yaml
configMapGenerator:
  - name: haku-mitmproxy-ca-cert
    namespace: haku-mitmproxy
    files:
      - ca-cert.pem
    options:
      disableNameSuffixHash: true
      annotations:
        description: haku-mitmproxy CA cert for haku-sandbox HTTPS inspection
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: haku-sandbox
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: haku-sandbox
