load("//devinfra/python:defs.bzl", "py_library")

package(default_visibility = ["//agentplane/notification_service:__subpackages__"])

py_library(
    name = "actions",
    srcs = ["actions.py"],
    deps = [
        "//agentplane:subjects",
        "//agentplane/action_service:models",
        "@pypi//httpx",
        "@pypi//pydantic",
    ],
)
