apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-trial-loop-devices
  namespace: flux-system
spec:
  suspend: true # rook-ceph storage trial complete (2026-07-17); winding down, see debug/distributed_storage_and_tiny_rook_ceph.md
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  path: ./cluster/k8s/rook-ceph-trial/loop-devices
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: rook-ceph-trial-namespace
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: rook-ceph-trial-loop-device-ssd
      namespace: rook-ceph
