load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "input",
    srcs = [
        "parser.go",
        "secret.go",
        "v0_parser.go",
        "v1_parser.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/input",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/api",
        "//internal/auth",
        "//internal/claude",
        "//internal/config",
        "//internal/o11y",
    ],
)
