load("//devinfra/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//x/agentplane:__subpackages__"])

py_library(
    name = "binding",
    srcs = ["binding.py"],
    deps = ["@pypi//pydantic"],
)

py_library(
    name = "inventory",
    srcs = ["inventory.py"],
    deps = [
        ":binding",
        ":models",
        "//mcp_infra/exec:kubernetes",
        "//util:kubernetes",
        "//x/agentplane:subjects",
        "@pypi//kubernetes_asyncio",
    ],
)

py_library(
    name = "models",
    srcs = ["models.py"],
    deps = [
        "//mcp_infra/exec:models",
        "@pypi//pydantic",
    ],
)

py_test(
    name = "test_inventory",
    srcs = ["test_inventory.py"],
    deps = [
        ":binding",
        ":inventory",
        ":models",
        "//:conftest",
        "//mcp_infra/exec:kubernetes",
        "//mcp_infra/exec:models",
        "//x/agentplane:subjects",
        "@pypi//kubernetes_asyncio",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
