load("//devinfra/python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "scenarios",
    srcs = ["scenarios.py"],
    deps = [
        "//augur/model:series",
        "@pypi//numpy",
    ],
)

py_library(
    name = "_density",
    srcs = ["_density.py"],
    deps = ["@pypi//numpy"],
)
