load("//devinfra/python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "profile",
    srcs = ["profile.py"],
    deps = [
        ":run",
        "//finance/augur/rust:invocation",
    ],
)

py_binary(
    name = "profile_bin",
    main_module = "finance.augur.x.monthly_actions.profile",
    deps = [":profile"],
)

py_binary(
    name = "run_bin",
    main_module = "finance.augur.x.monthly_actions.run",
    deps = [":run"],
)

py_library(
    name = "run",
    srcs = ["run.py"],
    deps = [
        ":policy",
        "//finance/augur/model:series",
        "//finance/augur/rust:invocation",
        "//finance/augur/rust:simulator_ext",
        "//finance/augur/sim:backend",
        "//finance/augur/sim:external_series",
        "//finance/augur/sim:jurisdictions",
        "//finance/augur/sim:scenario",
        "@pypi//numpy",
    ],
)

py_test(
    name = "test_run",
    srcs = ["test_run.py"],
    data = [
        ":profile_bin",
        ":run_bin",
    ],
    deps = [
        ":run",
        "//:conftest",
        "//finance/augur:conftest",
        "//util/bazel:runfiles",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "policy",
    srcs = ["policy.py"],
    deps = [
        "//finance/augur/policy:cash_band",
        "//finance/augur/rust:simulator_ext",
        "//finance/augur/sim:fixed_point",
    ],
)

py_test(
    name = "test_policy",
    srcs = ["test_policy.py"],
    deps = [
        ":policy",
        "//:conftest",
        "//finance/augur:conftest",
        "//finance/augur/model:series",
        "//finance/augur/rust:simulator_ext",
        "//finance/augur/sim:scenario",
        "//finance/augur/sim/testing:case",
        "//finance/augur/sim/testing:fixtures",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
