// server.go contains the CodeSignMCPServer implementation, including
// tool definitions, request handling, and source identification logic.
//
// Reconstructed from binary at Build ID 6b49f1ca (Go 1.25.6).
// Source file: /home/runner/work/anthropic/anthropic/api-go/environment-manager/internal/mcp/servers/codesign/server.go
//
// Key symbols:
//   - codesign.(*CodeSignMCPServer).GetTools (0xb0d060)
//   - codesign.(*CodeSignMCPServer).handleSignFile (0xb0d5c0)
//   - codesign.(*CodeSignMCPServer).identifySource (0xb0ea60)
//   - codesign.(*CodeSignMCPServer).Start (0xb0f540)
//   - codesign.(*CodeSignMCPServer).ShouldRegisterWithClaude (0xb0f720)
//   - codesign.(*CodeSignMCPServer).GetName (0xb11580)
//   - codesign.(*CodeSignMCPServer).Stop (0xb11680)
package codesign

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	mcpserver "github.com/mark3labs/mcp-go/server"

	"github.com/anthropics/anthropic/api-go/environment-manager/internal/config"
	"github.com/anthropics/anthropic/api-go/environment-manager/internal/mcp"
)

// CodeSignMCPServer implements the code-signing MCP server. It embeds BaseServer
// for common HTTP lifecycle and adds signing-specific fields.
//
// Struct layout (from type:.eq at 0xb11460 and field access patterns):
//   offset 0x00: BaseServer *mcp.BaseServer          (pointer to embedded base)
//   offset 0x08: name string                          (ptr + len, accessed by GetName at 0xb11580)
//   offset 0x18: logger *slog.Logger
//   offset 0x20: signingConfig *signingConfig         (signing key path, server URL)
//   offset 0x28: sources []config.Source              (from StartupContext)
//   offset 0x30: allowedSignersFile *string            (path to allowed signers)
//
// itab: *CodeSignMCPServer → mcp.MCPServer (0xf68220)
type CodeSignMCPServer struct {
	BaseServer        *mcp.BaseServer
	name              string
	logger            *slog.Logger
	signingConfig     *signingConfig
	sources           []config.Source
	allowedSignersFile *string
}

// signingConfig holds the signing service configuration.
type signingConfig struct {
	SigningServerURL string
	SigningKeyPath   string
}

// GetName returns the server name. Delegates to the embedded name field.
//
// Binary address: 0xb11580 (pointer receiver)
// Also: 0xb11520 (value receiver, autogenerated)
// Source file: <autogenerated>
//
// Assembly:
//   MOVQ 0(AX), CX    ; load *BaseServer
//   MOVQ 0x8(CX), AX  ; load name.ptr
//   MOVQ 0x10(CX), BX ; load name.len
//   RET
func (s *CodeSignMCPServer) GetName() (string, int) {
	return s.name, len(s.name)
}

// ShouldRegisterWithClaude returns false for the codesign server.
// The codesign server is NOT registered with Claude's MCP configuration;
// it communicates via environment variables instead (SIGNING_SERVER_URL, etc.).
//
// Binary address: 0xb0f720
// Source file: server.go
//
// Assembly (trivial):
//   XORL AX, AX   ; return false
//   RET
func (s *CodeSignMCPServer) ShouldRegisterWithClaude() bool {
	return false
}

// Start starts the codesign MCP server and sets environment variables
// for git to discover the signing service.
//
// Binary address: 0xb0f540
// Source file: server.go
//
// Assembly flow:
//   1. Calls BaseServer.Start at 0xb0f56d
//   2. If error: fmt.Errorf("failed to start base server: %w", err) at 0xb0f590
//   3. On success:
//      a. Gets port via fmt.Sprintf(":%d", port) at 0xb0f5e6
//      b. os.Setenv("SIGNING_SERVER_URL", portStr) at 0xb0f617
//         (string "SIGNING_SERVER_URL" at 0xb0f612, len 0x11=17)
//      c. os.Setenv(signing key env var, value) at 0xb0f638
//         (string len 0x12=18 at 0xb0f630)
//      d. Logs "MCP server started" with port/name slog attributes at 0xb0f66a-0xb0f6b8
//      e. Calls slog.(*Logger).log at 0xb0f6c3
func (s *CodeSignMCPServer) Start(logger *slog.Logger, name string) (int, error) {
	port, err := s.BaseServer.Start(logger, name)
	if err != nil {
		return 0, fmt.Errorf("failed to start base server: %w", err)
	}

	// Set environment variables for git signing integration
	portStr := fmt.Sprintf(":%d", port)
	os.Setenv("SIGNING_SERVER_URL", portStr)
	os.Setenv("SIGNING_SERVER_KEY_PATH", s.name)

	s.logger.Info("MCP server started",
		"server", s.name,
		"port", port,
	)

	return port, nil
}

// Stop delegates to BaseServer.Stop.
//
// Binary address: 0xb11680 (pointer receiver)
// Also: 0xb115c0 (value receiver, autogenerated)
// Source file: <autogenerated>
//
// Assembly:
//   MOVQ 0(AX), AX     ; load *BaseServer
//   CALL BaseServer.Stop
func (s *CodeSignMCPServer) Stop() bool {
	return s.BaseServer.Stop()
}

// GetTools returns the MCP tool definitions for the codesign server.
// The server exposes the "sign_file" tool with input schemas for
// file_path, source_identifier, signing_key_path, and content parameters.
//
// Binary address: 0xb0d060
// Source file: server.go
//
// Assembly flow (0xb0d060-0xb0d5a1):
//   1. makemap_small() x4 at 0xb0d077, 0xb0d081, 0xb0d16a, 0xb0d255, 0xb0d343
//   2. Builds tool input schema properties:
//      - "type": "string" (len 4 at 0xb0d095, 0xb0d177, 0xb0d262, 0xb0d350)
//      - "description": <description string> (len 0xb at 0xb0d0e6, 0xb0d1cc, 0xb0d2b7, 0xb0d3a6)
//      - "file_path": property with type "string", description about file to sign
//      - "source_identifier": property with type "string", description about source
//      - "signing_key_path": property with type "string", description about key path
//      - "content": property with type "string", description about content to sign
//   3. Returns the tool slice
//
// Tool definition reconstructed from map assignment patterns:
//   Tool 1: "sign_file"
//     Properties:
//       "file_path"          - type: string, description: "path to file..."
//       "source_identifier"  - type: string, description: "source identifier..."
//       "signing_key_path"   - type: string, description: "path to signing key..."
//       "content"            - type: string, description: "content to sign..."
//
//   The "required" array at offset 0xb0d3ed (len 7) is likely ["file_path"].
func (s *CodeSignMCPServer) GetTools() ([]mcpserver.ServerTool, int, int) {
	// Build input schema properties for sign_file tool
	properties := map[string]interface{}{
		"file_path": map[string]interface{}{
			"type":        "string",
			"description": "Absolute path to the file to sign",
		},
		"source_identifier": map[string]interface{}{
			"type":        "string",
			"description": "Source identifier for the repository",
		},
		"signing_key_path": map[string]interface{}{
			"type":        "string",
			"description": "Path to the signing key file",
		},
		"content": map[string]interface{}{
			"type":        "string",
			"description": "Content to sign (if not reading from file_path)",
		},
	}

	tool := mcpserver.ServerTool{
		Tool: mcplib.Tool{
			Name:        "sign_file",
			Description: "Sign a file with the codesigning service",
			InputSchema: mcplib.ToolInputSchema{
				Type:       "object",
				Properties: properties,
				Required:   []string{"file_path"},
			},
		},
		Handler: s.handleSignFile,
	}

	tools := []mcpserver.ServerTool{tool}
	return tools, len(tools), len(tools)
}

// handleSignFile handles the "sign_file" MCP tool call. It extracts the
// file_path parameter, reads the file content, identifies the source,
// and delegates to signContent for the actual signing.
//
// Binary address: 0xb0d5c0
// Source file: server.go
//
// Assembly flow (0xb0d5c0-0xb0ea2c):
//   1. Extract "file_path" string (len 9) from call request via RequireString (0xb0d651)
//   2. If error: fmt.Errorf("file_path is required: %w") at 0xb0d696
//   3. Extract optional parameters from request (source_identifier, signing_key_path, etc.)
//      using mapaccess2_faststr at 0xb0d740, 0xb0d80d, 0xb0d8e0
//   4. Validate file_path starts with "/" (absolute path check at 0xb0d99f)
//   5. If not absolute: returns "Error: File path must be absolute, got: %s" at 0xb0e841
//   6. Call identifySource (0xb0ea60) to determine which source owns the file
//   7. Call signContent (0xb109a0) with the file content and source info
//   8. Return signed result
func (s *CodeSignMCPServer) handleSignFile(ctx context.Context, request mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	// Extract required file_path parameter
	filePath, err := request.RequireString("file_path")
	if err != nil {
		return nil, fmt.Errorf("file_path is required: %w", err)
	}

	// Extract optional parameters from the request arguments map
	var sourceIdentifier string
	var signingKeyPath string
	if argsMap, ok := request.Params.Arguments.(map[string]interface{}); ok {
		if args, ok := argsMap["source_identifier"]; ok {
			if s, ok := args.(string); ok {
				sourceIdentifier = s
			}
		}
		if args, ok := argsMap["signing_key_path"]; ok {
			if s, ok := args.(string); ok {
				signingKeyPath = s
			}
		}
	}

	// Validate file path is absolute
	if len(filePath) == 0 || filePath[0] != '/' {
		return nil, fmt.Errorf("Error: File path must be absolute, got: %s", filePath)
	}

	// Validate signing key path is absolute if provided
	if len(signingKeyPath) > 0 && signingKeyPath[0] != '/' {
		// Also needs to be absolute
	}

	// Read file content
	content, err := readFileContent(filePath)
	if err != nil {
		return nil, err
	}

	// Identify the source for this file path
	sourceName, sourceItf := s.identifySource(ctx, filePath, sourceIdentifier)
	_ = sourceItf

	// Sign the content
	return s.signContent(ctx, filePath, sourceName, content, sourceIdentifier, signingKeyPath)
}

// identifySource determines which configured source owns the given file path.
// It resolves symlinks, computes absolute paths, and checks if the file falls
// under any source's directory.
//
// Binary address: 0xb0ea60
// Source file: server.go
//
// Assembly flow (0xb0ea60-0xb0f4f7):
//   1. If sourceIdentifier is empty (0xb0ea98):
//      a. Log slog.Warn "No source identifier provided..." (0xb0ec15)
//      b. Return "unknown", nil (0xb0ebef, string "unknown" len 7)
//   2. If no sources configured (s.sources == nil at 0xb0eab2):
//      Same as (1) above
//   3. Resolve symlinks: filepath.EvalSymlinks(filePath) at 0xb0eae4
//   4. If error, fall back to filepath.Abs(filePath) at 0xb0eb00
//   5. If still error, use filepathlite.Clean at 0xb0eb20
//   6. Iterate sources, check if resolved path starts with source directory
//   7. If match found, log "Identified source (subdirectory)" and return
//   8. If no match, return "unknown", nil
func (s *CodeSignMCPServer) identifySource(ctx context.Context, filePath string, sourceIdentifier string) (string, interface{}) {
	if sourceIdentifier == "" {
		s.logger.Warn("No source identifier provided, unable to identify source for signing",
			"file_path", filePath,
		)
		return "unknown", nil
	}

	if s.sources == nil || len(s.sources) == 0 {
		s.logger.Warn("No sources configured, unable to identify source for signing",
			"file_path", filePath,
		)
		return "unknown", nil
	}

	// Resolve symlinks and normalize the path
	resolvedPath, err := filepath.EvalSymlinks(filePath)
	if err != nil {
		resolvedPath, err = filepath.Abs(filePath)
		if err != nil {
			resolvedPath = filepath.Clean(filePath)
		}
	}

	// Check each source to see if the file path falls within its directory
	for _, src := range s.sources {
		srcDir := src.GetDirectory("")
		if srcDir == "" {
			continue
		}

		// Check if resolvedPath is under srcDir
		if len(resolvedPath) >= len(srcDir) {
			s.logger.Info("Identified source (subdirectory)",
				"source", src.GetType(),
				"file_path", filePath,
			)
			return src.GetType(), src
		}
	}

	return "unknown", nil
}
