"""Render classified budget transactions as a Beancount ledger.

This module is a *pure* projection: it turns already-classified transactions
(one bucket per txn, produced by the SQL read model) into deterministic
Beancount text. It does no I/O — fetching rows from the Plaid mirror and
committing the result to a git repo live in the exporter runner.

Double-entry handles signs, reversals and transfers for free: each Plaid txn
becomes one balanced two-posting entry. Plaid signs outflows positive and
inflows negative, so the bucket's *contra* leg takes ``+amount`` and the
transaction's own *funding* account (a Plaid account) takes ``-amount``. An
expense (amount > 0) thus debits Expenses and credits the asset/liability; an
income deposit (amount < 0) does the reverse. The same rule covers credit-card
charges (a Liabilities funding leg) without special-casing.

Output is byte-stable for a fixed input (entries ordered by ``(date,
transaction_id)``, accounts opened once at the earliest date, fixed-precision
amounts) so re-running the exporter produces no spurious git commits.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import date

from augur.budget.schema import BucketDef, BucketKind

# Default Beancount root for each bucket kind when a bucket has no explicit
# ``account``. INFLOW (refunds / insurance payouts) lands in Income as negative
# income; TRANSFER (movement between the user's own accounts) routes through a
# holding account since the other real leg isn't modelled here.
_KIND_ROOT: dict[BucketKind, str] = {
    BucketKind.EXPENSE: "Expenses",
    BucketKind.INCOME: "Income",
    BucketKind.INFLOW: "Income",
    BucketKind.TRANSFER: "Equity:Transfers",
}


@dataclass(frozen=True, slots=True)
class ClassifiedTxn:
    """One live Plaid transaction with its assigned bucket.

    The funding leg is keyed by ``account_id`` (resolved against the funding-account
    map passed to :func:`render_ledger`); the contra leg comes from the bucket. The
    Plaid fields are carried through as ledger metadata for additive reconciliation.
    """

    transaction_id: str
    date: date
    # Plaid sign convention: outflows positive, inflows negative.
    amount: float
    name: str
    account_id: str
    bucket_id: str
    merchant_name: str | None = None
    pfc_primary: str | None = None
    pfc_detailed: str | None = None
    iso_currency_code: str | None = None


def _segment(bucket_id: str) -> str:
    """Turn a snake_case bucket id into a CapWords Beancount account segment.

    Beancount segments forbid underscores, so ``bay_area_psychiatric`` becomes
    ``BayAreaPsychiatric``. Ids are already lowercased ([a-z0-9_]) by the schema.
    """
    return "".join(part.capitalize() for part in bucket_id.split("_"))


def default_account(bucket: BucketDef) -> str:
    """Derive a Beancount account path for a bucket that has no explicit ``account``."""
    return f"{_KIND_ROOT[bucket.kind]}:{_segment(bucket.id)}"


def contra_account(bucket: BucketDef) -> str:
    """The bucket's category leg: its explicit ``account`` or a derived default."""
    return bucket.account or default_account(bucket)


def _escape(value: str) -> str:
    """Escape a string for a Beancount double-quoted literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _amount(value: float) -> str:
    text = f"{value:.2f}"
    return "0.00" if text == "-0.00" else text


def _posting(account: str, value: float, currency: str) -> str:
    return f"  {account}  {_amount(value)} {currency}"


def render_ledger(
    txns: Sequence[ClassifiedTxn],
    buckets: Mapping[str, BucketDef],
    funding_accounts: Mapping[str, str],
    *,
    title: str = "Budget",
    operating_currency: str = "USD",
) -> str:
    """Render classified transactions as a deterministic Beancount ledger.

    Args:
        txns: live classified transactions (one bucket each).
        buckets: bucket id -> definition (supplies the contra account path).
        funding_accounts: Plaid account id -> Beancount funding account path.
        title: ledger title (``option "title"``).
        operating_currency: fallback currency and ``option "operating_currency"``.

    Raises:
        KeyError: a txn references a bucket id or account id not in the maps.
    """
    ordered = sorted(txns, key=lambda t: (t.date, t.transaction_id))

    lines: list[str] = [
        ";; Generated by the augur budget exporter. Do not edit by hand.",
        "",
        f'option "title" "{_escape(title)}"',
        f'option "operating_currency" "{operating_currency}"',
        "",
    ]

    if ordered:
        open_date = ordered[0].date
        used: set[str] = set()
        for txn in ordered:
            used.add(funding_accounts[txn.account_id])
            used.add(contra_account(buckets[txn.bucket_id]))
        lines.extend(f"{open_date.isoformat()} open {account}" for account in sorted(used))
        lines.append("")

    for txn in ordered:
        funding = funding_accounts[txn.account_id]
        contra = contra_account(buckets[txn.bucket_id])
        currency = txn.iso_currency_code or operating_currency

        narration = _escape(txn.name)
        if txn.merchant_name:
            header = f'{txn.date.isoformat()} * "{_escape(txn.merchant_name)}" "{narration}"'
        else:
            header = f'{txn.date.isoformat()} * "{narration}"'
        lines.append(header)

        lines.append(f'  plaid-id: "{_escape(txn.transaction_id)}"')
        lines.append(f'  bucket: "{_escape(txn.bucket_id)}"')
        if txn.pfc_primary:
            pfc = txn.pfc_primary + (f" / {txn.pfc_detailed}" if txn.pfc_detailed else "")
            lines.append(f'  plaid-pfc: "{_escape(pfc)}"')

        # Contra (category) leg takes +amount; funding leg takes -amount.
        lines.append(_posting(contra, txn.amount, currency))
        lines.append(_posting(funding, -txn.amount, currency))
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"
