apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - serviceaccount-haku.yaml
  - role.yaml
  - rolebinding.yaml
  - rolebinding-haku.yaml
  - rolebinding-oidc.yaml
  - resourcequota.yaml
  - limitrange.yaml
