# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "app",
    srcs = ["app.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:manifest_roots",
        "//cluster/cdk8s:node_scheduling",
        "//cluster/cdk8s/providers/kubevirt",
        "@pypi//cdk8s",
    ],
)

py_library(
    name = "cdi",
    srcs = ["cdi.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:manifest_roots",
        "//cluster/cdk8s:node_scheduling",
        "//cluster/cdk8s/providers/flux:kustomization",
        "//cluster/cdk8s/providers/kubevirt:cdi",
        "//cluster/cdk8s/providers/kubevirt:storageprofile",
        "@pypi//cdk8s",
    ],
)

py_library(
    name = "flux_kustomizations",
    srcs = ["flux_kustomizations.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s/providers/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
    ],
)

py_library(
    name = "virtual_machine",
    srcs = ["virtual_machine.py"],
    visibility = ["//cluster/cdk8s:__subpackages__"],
    deps = [
        "//cluster/cdk8s/providers/kubevirt:virtual_machine",
        "//cluster/cdk8s/providers/kubevirt:virtualmachine",
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
        "@pypi//constructs",
    ],
)
