# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "app",
    srcs = ["app.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s:metadata",
        "//cluster/cdk8s/crd_bindings/kubevirt",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
    ],
)

py_library(
    name = "cdi",
    srcs = ["cdi.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s/crd_bindings/kubevirt:cdi",
        "@pypi//cdk8s",
    ],
)

py_library(
    name = "flux_kustomizations",
    srcs = ["flux_kustomizations.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
    ],
)
