load("//devinfra/python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "discovery_to_mcp_lib",
    srcs = ["discovery_to_mcp.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//google_api_python_client"],
)

py_binary(
    name = "discovery_to_mcp",
    main_module = "haku.console.x.discovery_mcp.discovery_to_mcp",
    deps = [":discovery_to_mcp_lib"],
)

py_library(
    name = "tool_factory_lib",
    srcs = ["tool_factory.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":discovery_to_mcp_lib",
        "@pypi//fastmcp",
        "@pypi//pydantic",
    ],
)

py_binary(
    name = "tool_factory",
    main_module = "haku.console.x.discovery_mcp.tool_factory",
    deps = [":tool_factory_lib"],
)
