"""Spike part 2: turn a `GenTool` spec into a live FastMCP tool.

Builds the *first set* of autogenerated tools — the batch-1 gmail reads — as real FastMCP
tools, and drives them through an in-memory MCP client end to end. Each tool is:

- **schema** — discovery params → JSON Schema (`discovery_to_mcp`), then the curation overlay
  (allowlist `expose`, drop `pin`ned constants, recompute `required`);
- **execution** — one generic executor that walks the dotted method id against a `googleapiclient`
  Resource (`service.users().labels().list(userId="me").execute()`), merging the pinned constants.

No credentials and no network: the demo injects a fake Resource that records the call chain, so
`bb run //haku/console/x/discovery_mcp:tool_factory` both prints the advertised `tools/list`
schemas (what the agent + the frontend Zod pipeline see) and proves the executor dispatches
correctly. Inline asserts make it self-checking.
"""

from __future__ import annotations

import asyncio
import json
from dataclasses import dataclass, field
from typing import Any

from fastmcp import Client, FastMCP
from fastmcp.tools.tool import Tool, ToolResult
from pydantic import ConfigDict, Field

from haku.console.x.discovery_mcp.discovery_to_mcp import find_method, load, to_json_schema

# api -> pinned version, so a GenTool only names the method id.
_API_VERSION = {"gmail": "v1", "drive": "v3", "tasks": "v1", "calendar": "v3", "docs": "v1", "sheets": "v4"}


@dataclass(frozen=True)
class GenTool:
    """A tier-1/2 spec: a discovery method + a curation overlay."""

    method_id: str  # e.g. "gmail.users.labels.list"
    name: str  # advertised MCP tool name
    pin: dict[str, str] = field(default_factory=dict)  # constants injected by the executor, hidden from the agent
    expose: tuple[str, ...] | None = None  # param allowlist; None = all params

    @property
    def api_version(self) -> str:
        api = self.method_id.split(".", 1)[0]
        return f"{api}.{_API_VERSION[api]}"


def build_input_schema(spec: GenTool, doc: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
    """Generated JSON Schema for a spec's exposed params (pinned constants removed). Returns (schema, method)."""
    method = find_method(doc, spec.method_id)
    schemas = doc.get("schemas", {})
    params = method.get("parameters") or {}
    names = spec.expose if spec.expose is not None else tuple(params)

    props: dict[str, Any] = {}
    required: list[str] = []
    for n in names:
        if n in spec.pin:
            continue
        if n not in params:
            raise KeyError(f"{spec.name}: exposed param {n!r} not in {spec.method_id} (Google changed the API?)")
        props[n] = to_json_schema(params[n], schemas)
        if params[n].get("required"):
            required.append(n)

    schema: dict[str, Any] = {"type": "object", "properties": props}
    if required:
        schema["required"] = required
    return schema, method


def _execute(service: Any, method_id: str, args: dict[str, Any]) -> Any:
    """Generic googleapiclient dispatch: gmail.users.labels.list -> service.users().labels().list(**args)."""
    _api, *path, method = method_id.split(".")
    node = service
    for segment in path:
        node = getattr(node, segment)()
    return getattr(node, method)(**args).execute()


class GeneratedGoogleTool(Tool):
    """A FastMCP tool whose schema is discovery-generated and whose handler is the generic executor."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    method_id: str
    pinned: dict[str, str] = Field(default_factory=dict)
    service: Any = None  # a googleapiclient Resource (or, in the spike, a fake that records calls)

    async def run(self, arguments: dict[str, Any], **_: Any) -> ToolResult:
        merged = {**self.pinned, **arguments}
        raw = _execute(self.service, self.method_id, merged)
        return self.convert_result(raw)


def build_server(specs: list[GenTool], service: Any) -> FastMCP:
    mcp: FastMCP = FastMCP(name="gmail")
    for spec in specs:
        schema, method = build_input_schema(spec, load(spec.api_version))
        mcp.add_tool(
            GeneratedGoogleTool(
                name=spec.name,
                description=(method.get("description") or "").strip(),
                parameters=schema,
                method_id=spec.method_id,
                pinned=spec.pin,
                service=service,
            )
        )
    return mcp


# Batch-1: gmail verbatim reads. `userId` is pinned to "me" (never exposed to the agent).
BATCH_1 = [
    GenTool("gmail.users.labels.list", name="labels_list", pin={"userId": "me"}),
    GenTool("gmail.users.labels.get", name="labels_get", pin={"userId": "me"}, expose=("id",)),
    GenTool("gmail.users.messages.get", name="messages_get", pin={"userId": "me"}, expose=("id", "format")),
    GenTool(
        "gmail.users.threads.list",
        name="threads_list",
        pin={"userId": "me"},
        expose=("q", "maxResults", "pageToken", "labelIds"),
    ),
]


class _FakeGoogle:
    """Records the chained call and returns a canned result on .execute() — stands in for a Resource."""

    def __init__(self, result: Any, log: list[tuple[str, dict[str, Any]]]) -> None:
        self._result = result
        self._log = log

    def __getattr__(self, name: str) -> Any:
        def call(**kwargs: Any) -> _FakeGoogle:
            self._log.append((name, kwargs))
            return self

        return call

    def execute(self) -> Any:
        return self._result


async def _demo() -> None:
    calls: list[tuple[str, dict[str, Any]]] = []
    service = _FakeGoogle({"labels": [{"id": "INBOX", "name": "INBOX"}]}, calls)
    mcp = build_server(BATCH_1, service)

    async with Client(mcp) as client:
        tools = {t.name: t for t in await client.list_tools()}
        print(f"advertised {len(tools)} tools: {', '.join(sorted(tools))}\n")
        for name in ("labels_list", "labels_get", "messages_get", "threads_list"):
            print(f"--- {name} inputSchema ---")
            print(json.dumps(tools[name].inputSchema, indent=2))
            print()

        # Schema overlay: userId is pinned -> never advertised; required/enums survive.
        assert "userId" not in tools["labels_list"].inputSchema["properties"], "pinned param leaked into schema"
        assert tools["labels_get"].inputSchema["required"] == ["id"], "required not derived"
        assert "enum" in tools["messages_get"].inputSchema["properties"]["format"], "enum dropped"

        # Executor: calling the tool dispatches the right googleapiclient chain with the pinned constant.
        result = await client.call_tool("labels_list", {})
        assert calls[-3:] == [("users", {}), ("labels", {}), ("list", {"userId": "me"})], calls
        print("executor dispatched:", " -> ".join(f"{n}({a})" for n, a in calls))
        print("call_tool result:", result.data)

    print("\nOK — batch-1 gmail reads generate, advertise, and dispatch correctly.")


def main() -> None:
    asyncio.run(_demo())


if __name__ == "__main__":
    main()
