# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "chart",
    srcs = ["chart.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:artifact_generators",
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:gateway",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s:metadata",
        "//cluster/cdk8s:ntfy",
        "//cluster/cdk8s/crd_bindings/external_secrets:externalsecret",
        "//cluster/cdk8s/crd_bindings/flux:alert",
        "//cluster/cdk8s/crd_bindings/flux:kustomization",
        "//cluster/cdk8s/crd_bindings/flux:provider",
        "//cluster/cdk8s/crd_bindings/flux:receiver",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
    ],
)
