set -euo pipefail

runtime_path=$PATH
set +u
# Generated by the booted NixOS system.
# shellcheck disable=SC1091
source /etc/set-environment
set -u
PATH="$runtime_path:$PATH"

workspace=/workspace
execution_log=/tmp/rbe-execution.json

mkdir -p "$workspace"
cp -a /source/. "$workspace/"
cp /rbe.bazelrc "$workspace/.bazelrc"
cat "$workspace/workspace.bazelrc" >>"$workspace/.bazelrc"

if [[ "${1:-}" == "--prepare-only" ]]; then
  exit 0
fi

cd "$workspace"

echo "=== NixOS filesystem checks ==="
echo "/bin/bash exists: $(test -e /bin/bash && echo YES || echo NO)"
echo "Bash location: $(command -v bash)"
echo "NIX_LD=${NIX_LD:-unset}"
echo "NIX_LD_LIBRARY_PATH=${NIX_LD_LIBRARY_PATH:-unset}"
echo ""

echo "=== Credentialed Ducktape RBE build + local run ==="
set +e
output="$(bazelisk run \
  --noremote_accept_cached \
  --execution_log_json_file="$execution_log" \
  //:remote_smoke 2>&1)"
bazel_status=$?
set -e
printf "%s\n" "$output"
if ((bazel_status != 0)); then
  exit "$bazel_status"
fi

grep -Fq "ducktape-nixos-rbe-smoke-ok" <<<"$output"
if ! grep -Fq '"runner": "remote"' "$execution_log"; then
  echo "execution log did not record remote execution:" >&2
  cat "$execution_log" >&2
  exit 1
fi
grep -Fq '"mnemonic": "AspectRulesLintRuff"' "$execution_log"
if grep -F '"runner":' "$execution_log" | grep -Fvq '"runner": "remote"'; then
  echo "execution log contains a non-remote action:" >&2
  grep -F '"runner":' "$execution_log" >&2
  exit 1
fi
if grep -Fq 'processwrapper-sandbox' <<<"$output"; then
  echo "eligible action unexpectedly fell back to local execution" >&2
  exit 1
fi

echo "=== NixOS configured Bazel executed the Ruff action remotely and ran its output locally ==="
