set -euo pipefail

runtime_path=$PATH
if [[ -f /etc/set-environment ]]; then
  set +u
  # Generated by the booted NixOS system.
  # shellcheck disable=SC1091
  source /etc/set-environment
  set -u
  PATH="$runtime_path:$PATH"
fi

client_name=${CLIENT_NAME:-NixOS}
source_workspace=${SOURCE_WORKSPACE:-/source}
rbe_bazelrc=${RBE_BAZELRC:-/rbe.bazelrc}
workspace=${WORKSPACE:-/workspace}
execution_log_dir=${EXECUTION_LOG_DIR:-/tmp}
run_execution_log="$execution_log_dir/rbe-run-execution.json"
remote_test_execution_log="$execution_log_dir/rbe-remote-test-execution.json"
local_test_execution_log="$execution_log_dir/rbe-local-test-execution.json"

mkdir -p "$workspace"
mkdir -p "$execution_log_dir"
cp -a "$source_workspace/." "$workspace/"
cp "$rbe_bazelrc" "$workspace/.bazelrc"
cat "$workspace/workspace.bazelrc" >>"$workspace/.bazelrc"

if [[ "${1:-}" == "--prepare-only" ]]; then
  exit 0
fi

cd "$workspace"

echo "=== $client_name filesystem checks ==="
echo "/bin/bash exists: $(test -e /bin/bash && echo YES || echo NO)"
echo "Bash location: $(command -v bash)"
echo "NIX_LD=${NIX_LD:-unset}"
echo "NIX_LD_LIBRARY_PATH=${NIX_LD_LIBRARY_PATH:-unset}"
echo ""

assert_all_remote() {
  local execution_log=$1
  if ! jq -s -e 'all(.[]; .runner == "remote")' "$execution_log" >/dev/null; then
    echo "$execution_log contains a non-remote action:" >&2
    jq -s -r '.[] | [.mnemonic, .runner] | @tsv' "$execution_log" >&2
    exit 1
  fi
}

assert_remote_mnemonic() {
  local execution_log=$1
  local mnemonic=$2
  if ! jq -s -e --arg mnemonic "$mnemonic" 'any(.[]; .mnemonic == $mnemonic and .runner == "remote")' "$execution_log" >/dev/null; then
    echo "$execution_log did not run $mnemonic remotely:" >&2
    jq -s -r '.[] | [.mnemonic, .runner] | @tsv' "$execution_log" >&2
    exit 1
  fi
}

echo "=== $client_name: credentialed RBE build + client-local bazel run ==="
set +e
output="$(bazelisk run \
  --disk_cache= \
  --noremote_accept_cached \
  --execution_log_json_file="$run_execution_log" \
  //:remote_smoke 2>&1)"
bazel_status=$?
set -e
printf "%s\n" "$output"
if ((bazel_status != 0)); then
  exit "$bazel_status"
fi

grep -Fq "ducktape-rbe-run-smoke-ok" <<<"$output"
assert_remote_mnemonic "$run_execution_log" "AspectRulesLintRuff"
assert_all_remote "$run_execution_log"
if grep -Fq 'processwrapper-sandbox' <<<"$output"; then
  echo "eligible action unexpectedly fell back to local execution" >&2
  exit 1
fi

echo "=== $client_name: regular TestRunner on RBE ==="
bazelisk test \
  --disk_cache= \
  --noremote_accept_cached \
  --execution_log_json_file="$remote_test_execution_log" \
  --test_output=all \
  //:remote_test_smoke
assert_remote_mnemonic "$remote_test_execution_log" "SmokeTestExecutable"
assert_remote_mnemonic "$remote_test_execution_log" "TestRunner"
assert_all_remote "$remote_test_execution_log"

echo "=== $client_name: local-only TestRunner with remote build and aspect actions ==="
bazelisk test \
  --disk_cache= \
  --noremote_accept_cached \
  --execution_log_json_file="$local_test_execution_log" \
  --test_output=all \
  //:local_test_smoke
assert_remote_mnemonic "$local_test_execution_log" "SmokeTestExecutable"
if ! jq -s -e 'any(.[]; .mnemonic == "TestRunner" and .runner != "remote")' "$local_test_execution_log" >/dev/null; then
  echo "$local_test_execution_log did not run TestRunner locally:" >&2
  jq -s -r '.[] | [.mnemonic, .runner] | @tsv' "$local_test_execution_log" >&2
  exit 1
fi
if ! jq -s -e 'all(.[]; .mnemonic == "TestRunner" or .runner == "remote")' "$local_test_execution_log" >/dev/null; then
  echo "$local_test_execution_log ran a non-TestRunner action locally:" >&2
  jq -s -r '.[] | [.mnemonic, .runner] | @tsv' "$local_test_execution_log" >&2
  exit 1
fi

echo "=== $client_name execution contract passed ==="
