apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: homeassistant-proxy
  namespace: flux-system
spec:
  image: ghcr.io/agentydragon/homeassistant-proxy
  interval: 5m
