apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: grafana-flux-token
  namespace: flux-system
spec:
  interval: 15m
  approvePlan: "auto"
  path: ./cluster/terraform/gitops/grafana-flux-token
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  serviceAccountName: tf-runner
  backendConfig:
    customConfiguration: |
      backend "kubernetes" {
        secret_suffix    = "grafana-flux-token"
        namespace        = "flux-system"
      }
  vars:
    - name: grafana_url
      value: "https://grafana.allegedly.works"
