apiVersion: cilium.io/v2
kind: CiliumNode
metadata:
  creationTimestamp: "2026-05-16T04:35:50Z"
  generation: 3
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    extensions.talos.dev/nebula: 1.10.2
    feature.node.kubernetes.io/cpu-cpuid.ADX: "true"
    feature.node.kubernetes.io/cpu-cpuid.AESNI: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX2: "true"
    feature.node.kubernetes.io/cpu-cpuid.CMPXCHG8: "true"
    feature.node.kubernetes.io/cpu-cpuid.FLUSH_L1D: "true"
    feature.node.kubernetes.io/cpu-cpuid.FMA3: "true"
    feature.node.kubernetes.io/cpu-cpuid.FXSR: "true"
    feature.node.kubernetes.io/cpu-cpuid.FXSROPT: "true"
    feature.node.kubernetes.io/cpu-cpuid.IA32_ARCH_CAP: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBPB: "true"
    feature.node.kubernetes.io/cpu-cpuid.LAHF: "true"
    feature.node.kubernetes.io/cpu-cpuid.MD_CLEAR: "true"
    feature.node.kubernetes.io/cpu-cpuid.MOVBE: "true"
    feature.node.kubernetes.io/cpu-cpuid.MPX: "true"
    feature.node.kubernetes.io/cpu-cpuid.OSXSAVE: "true"
    feature.node.kubernetes.io/cpu-cpuid.PMU_FIXEDCOUNTER_CYCLES: "true"
    feature.node.kubernetes.io/cpu-cpuid.PMU_FIXEDCOUNTER_INSTRUCTIONS: "true"
    feature.node.kubernetes.io/cpu-cpuid.PMU_FIXEDCOUNTER_REFCYCLES: "true"
    feature.node.kubernetes.io/cpu-cpuid.RTM_ALWAYS_ABORT: "true"
    feature.node.kubernetes.io/cpu-cpuid.SPEC_CTRL_SSBD: "true"
    feature.node.kubernetes.io/cpu-cpuid.SRBDS_CTRL: "true"
    feature.node.kubernetes.io/cpu-cpuid.STIBP: "true"
    feature.node.kubernetes.io/cpu-cpuid.SYSCALL: "true"
    feature.node.kubernetes.io/cpu-cpuid.SYSEE: "true"
    feature.node.kubernetes.io/cpu-cpuid.VMX: "true"
    feature.node.kubernetes.io/cpu-cpuid.X87: "true"
    feature.node.kubernetes.io/cpu-cpuid.XGETBV1: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVE: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVEC: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVEOPT: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVES: "true"
    feature.node.kubernetes.io/cpu-cstate.enabled: "true"
    feature.node.kubernetes.io/cpu-hardware_multithreading: "true"
    feature.node.kubernetes.io/cpu-model.family: "6"
    feature.node.kubernetes.io/cpu-model.id: "158"
    feature.node.kubernetes.io/cpu-model.vendor_id: Intel
    feature.node.kubernetes.io/cpu-pstate.scaling_governor: powersave
    feature.node.kubernetes.io/cpu-pstate.status: active
    feature.node.kubernetes.io/cpu-pstate.turbo: "true"
    feature.node.kubernetes.io/cpu-security.sev.enabled: "true"
    feature.node.kubernetes.io/cpu-security.sev.es.enabled: "true"
    feature.node.kubernetes.io/cpu-security.sev.snp.enabled: "true"
    feature.node.kubernetes.io/kernel-config.NO_HZ: "true"
    feature.node.kubernetes.io/kernel-config.NO_HZ_IDLE: "true"
    feature.node.kubernetes.io/kernel-version.full: 6.18.8-talos
    feature.node.kubernetes.io/kernel-version.major: "6"
    feature.node.kubernetes.io/kernel-version.minor: "18"
    feature.node.kubernetes.io/kernel-version.revision: "8"
    feature.node.kubernetes.io/pci-102b.present: "true"
    feature.node.kubernetes.io/pci-8086.present: "true"
    feature.node.kubernetes.io/storage-nonrotationaldisk: "true"
    feature.node.kubernetes.io/system-os_release.ID: talos
    feature.node.kubernetes.io/system-os_release.VERSION_ID: v1.12.3
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: talos-kimsufi-worker-1
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
    node.kubernetes.io/exclude-from-external-load-balancers: ""
    topology.kubernetes.io/region: hil
    topology.kubernetes.io/zone: hil-ovh
  name: talos-kimsufi-worker-1
  ownerReferences:
    - apiVersion: v1
      kind: Node
      name: talos-kimsufi-worker-1
      uid: b0b3be2b-bf8e-4ecd-9635-258e885c4316
  resourceVersion: "79225217"
  uid: ae33e4f5-d90c-492e-b231-d3c5b1d4cdc4
spec:
  addresses:
    - ip: 10.42.0.14
      type: InternalIP
    - ip: 10.244.8.18
      type: CiliumInternalIP
  alibaba-cloud: {}
  azure: {}
  bootid: f077fd20-44ea-4497-b340-3d3c0960c653
  encryption: {}
  eni: {}
  health:
    ipv4: 10.244.8.95
  ingress:
    ipv4: 10.244.8.100
  ipam:
    podCIDRs:
      - 10.244.8.0/24
    pools: {}
