load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cmd",
    srcs = [
        "cmd_code_sign.go",
        "cmd_orchestrator.go",
        "cmd_poll.go",
        "cmd_print_sandbox.go",
        "cmd_setup.go",
        "cmd_task_run.go",
        "types.go",
        "utils.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/cmd",
    visibility = ["//devinfra/claude/web_env/re/environment_manager/495ea204/src:__subpackages__"],
    deps = [
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/api",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/auth",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/claude",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/config",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/input",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/logger",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/manager",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/o11y",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/o11y/diag",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/orchestrator",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/sandbox",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/session",
        "//devinfra/claude/web_env/re/environment_manager/495ea204/src/internal/util",
        "@com_github_spf13_cobra//:cobra",
    ],
)
