load("//devinfra/python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "cli",
    srcs = ["cli.py"],
    visibility = ["//:__subpackages__"],
    deps = [":convert"],
)

py_library(
    name = "convert",
    srcs = ["convert.py"],
    deps = [
        "//tana/domain:constants",
        "//tana/domain:nodes",
        "//tana/domain:types",
        "//tana/graph",
        "//tana/graph:loader",
        "//tana/graph:wrappers",
        "//tana/query:nodes",
        "//tana/render:html_utils",
        "//tana/render:inline_refs",
    ],
)

py_binary(
    name = "convert_bin",
    main_module = "tana.export.convert",
    visibility = ["//:__subpackages__"],
    deps = [":convert"],
)

py_library(
    name = "export_node_subset",
    srcs = ["export_node_subset.py"],
    deps = [
        ":convert",
        "//tana/domain:constants",
        "//tana/domain:nodes",
        "//tana/domain:types",
        "//tana/graph",
        "//tana/graph:wrappers",
    ],
)

py_binary(
    name = "export_node_subset_bin",
    main_module = "tana.export.export_node_subset",
    visibility = ["//:__subpackages__"],
    deps = [":export_node_subset"],
)

py_library(
    name = "materialize_searches",
    srcs = ["materialize_searches.py"],
    deps = [
        "//tana:workspace",
        "//tana/domain:types",
        "//tana/graph",
        "//tana/query/search:materializer",
        "//tana/query/search:parser",
    ],
)

py_binary(
    name = "materialize_searches_bin",
    main_module = "tana.export.materialize_searches",
    visibility = ["//:__subpackages__"],
    deps = [":materialize_searches"],
)

py_library(
    name = "download_images",
    srcs = ["download_images.py"],
    deps = [
        "//tana/domain:nodes",
        "//tana/graph",
        "//tana/graph:loader",
        "//tana/query:nodes",
    ],
)

py_binary(
    name = "download_images_bin",
    main_module = "tana.export.download_images",
    visibility = ["//:__subpackages__"],
    deps = [":download_images"],
)

py_library(
    name = "sample",
    srcs = ["sample.py"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "tana_issues_to_tanapaste",
    srcs = ["tana_issues_to_tanapaste.py"],
    deps = [
        ":convert",
        "//tana:workspace",
        "//tana/query:filters",
    ],
)

py_binary(
    name = "tana_issues_to_tanapaste_bin",
    main_module = "tana.export.tana_issues_to_tanapaste",
    visibility = ["//:__subpackages__"],
    deps = [":tana_issues_to_tanapaste"],
)
