load("//devinfra/python:defs.bzl", "py_binary")

py_binary(
    name = "ultra_long_cot",
    srcs = ["ultra_long_cot.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//openai",
        "@pypi//tiktoken",
    ],
)

py_binary(
    name = "ultra_long_cot_o4",
    srcs = ["ultra_long_cot_o4.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//openai",
        "@pypi//pydantic",
        "@pypi//tiktoken",
    ],
)
