load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "cpio_tool",
    srcs = ["cpio_tool.py"],
    deps = ["@rules_pkg//pkg/private:manifest"],
)

py_binary(
    name = "cpio_tool_bin",
    main_module = "devinfra.cpio.cpio_tool",
    visibility = ["//visibility:public"],
    deps = [":cpio_tool"],
)
