load("@rules_python//python:defs.bzl", "py_library")
load("//tools/lint:linters.bzl", "ruff_test")

# Gazelle will create per-file py_library targets

ruff_test(
    name = "ruff",
    srcs = [
        ":mcp",
        ":output",
    ],
)

py_library(
    name = "mcp",
    srcs = ["mcp.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//mcp_utils",
        "@pypi//fastmcp",
        "@pypi//mcp",
    ],
)

py_library(
    name = "output",
    srcs = ["output.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//jinja2"],
)
