// Shared mount for per-server preview screenshots. Each server's `preview_harness.tsx` imports
// this and passes its fixtures; the sweep loads one page per fixture × variant × color scheme
// (scenarios generated by emit_scenarios.mjs) and screenshots the card.
//
// Each server harness imports its own `preview_mock.ts` before this module, so the widget graph
// sees only that server's canned MCP responses.

import { MantineProvider } from "@mantine/core";
import { createRoot } from "react-dom/client";

import { hakuTheme } from "../../theme";
import type { PreviewVariant } from "../vocabulary";
import { PreviewCard, type PreviewFixture } from "./card";

// Which card to render, set by the page before this script runs: the scenario's `windowGlobals`.
const PREVIEW_WINDOW = window as unknown as {
  __FIXTURE__?: number;
  __VARIANT__?: PreviewVariant;
};

export function mountPreviewCards(fixtures: PreviewFixture[]): void {
  const fixtureIndex = PREVIEW_WINDOW.__FIXTURE__ ?? 0;
  const variant = PREVIEW_WINDOW.__VARIANT__ ?? "compact";
  // The scenario's emulated `prefers-color-scheme` is its color scheme.
  const colorScheme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
  const fixture = fixtures[fixtureIndex];
  if (!fixture) throw new Error(`no preview fixture at index ${fixtureIndex}`);

  const container = document.getElementById("app");
  if (!container) throw new Error("missing #app");
  createRoot(container).render(
    <MantineProvider forceColorScheme={colorScheme} theme={hakuTheme}>
      <PreviewCard fixture={fixture} variant={variant} />
    </MantineProvider>
  );
}
