load("//devinfra/js:ts_library.bzl", "ts_library")

package(default_visibility = [
    "//props/frontend:__pkg__",
    "//props/frontend:__subpackages__",
])

ts_library(
    name = "CreditBadge",
    srcs = ["CreditBadge.tsx"],
    tsconfig = "//props/frontend:tsconfig",
    deps = [
        "//props/frontend:node_modules/@mantine/core",
        "//props/frontend:node_modules/@types/react",
        "//props/frontend:node_modules/react",
    ],
)

ts_library(
    name = "OccurrenceStats",
    srcs = ["OccurrenceStats.tsx"],
    tsconfig = "//props/frontend:tsconfig",
    deps = [
        "//props/frontend:node_modules/@mantine/core",
        "//props/frontend:node_modules/@types/react",
        "//props/frontend:node_modules/react",
    ],
)

ts_library(
    name = "DistributionChart",
    srcs = ["DistributionChart.tsx"],
    tsconfig = "//props/frontend:tsconfig",
    deps = [
        "//props/frontend:node_modules/@mantine/core",
        "//props/frontend:node_modules/@types/react",
        "//props/frontend:node_modules/chart.js",
        "//props/frontend:node_modules/react",
    ],
)

ts_library(
    name = "CoverageHeatmap",
    srcs = ["CoverageHeatmap.tsx"],
    tsconfig = "//props/frontend:tsconfig",
    deps = [
        "//props/frontend:node_modules/@mantine/core",
        "//props/frontend:node_modules/@types/react",
        "//props/frontend:node_modules/chart.js",
        "//props/frontend:node_modules/chartjs-chart-matrix",
        "//props/frontend:node_modules/react",
        "//props/frontend/src/lib:formatters",
    ],
)

ts_library(
    name = "SummaryCards",
    srcs = ["SummaryCards.tsx"],
    tsconfig = "//props/frontend:tsconfig",
    deps = [
        "//props/frontend:node_modules/@mantine/core",
        "//props/frontend:node_modules/@types/react",
        "//props/frontend:node_modules/react",
        "//props/frontend/src/lib:DefinitionIdLink",
        "//props/frontend/src/lib:formatters",
        "//props/frontend/src/lib:types",
    ],
)

ts_library(
    name = "DefinitionsTable",
    srcs = ["DefinitionsTable.tsx"],
    tsconfig = "//props/frontend:tsconfig",
    deps = [
        "//props/frontend:node_modules/@mantine/core",
        "//props/frontend:node_modules/@types/react",
        "//props/frontend:node_modules/react",
        "//props/frontend/src/lib:DefinitionIdLink",
        "//props/frontend/src/lib:colors",
        "//props/frontend/src/lib:formatters",
        "//props/frontend/src/lib:types",
    ],
)
