apiVersion: v1
kind: Secret
metadata:
    name: public-coder-devbox-hostexecd-token
    namespace: public-coder-agent
    annotations:
        description: Same value as ../../../haku/console/node-daemon-public-coder-devbox.sops.yaml, reflected here so KubeVirt can attach it as a guest disk. Update both if rotated.
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:D/mB5trwIlDD8hp1ifwggWr7LJcgDYCLy5H0vrl1llLKKOQTgDbHUz/QN5xUTC2EDcNjrc5TxpyiqevtZZDzBA==,iv:bbtcGGhzIAGTN1vBoQgRUak7yVwS4efFbqK4H0M9NQ4=,tag:Cm5WMy1Ks0vCWdWADfx+dA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d1hrUUhQTFIzQTZDK2Mz
            ellUQUFjZmxCdHFCdU9PTDFVbFlveXdsZVRnClBTbnBOWkFvcWJOYm81R3pzWE0x
            Nm5nWGpFd3p6VFFOblpVUzVxK1NkbncKLS0tIHJ3aVRDNVQzeUcxbDJVREMvTjJI
            aE9odGNJcHF2eWIvUlZWZzZaNTRKeFkKwkLBY8Pghh8KHIjrBUk/XOPUqC3cWwR1
            9Z8/xD9Von2qQT7Y4yGvELqYJEt2sHSIN8AWACxGx2dSrtZcU/1F2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTU41RzBoVE5ZTzc5dWZE
            UHdFU24zSktuUzZLQWJGT3RvcHlxSlpFQndJCnZuQVVpNFBaV3lMb0FvaXEzT0d2
            L0VKaEVDVGdYRXM2RC9QaEpWSktRM28KLS0tIGM5Q0J6VSs2R0ZlemNOTjJFZzVn
            Qy9hMTFUMXNOSWlvTmNFR1gxeGZxaUUKS1ZDOt6gAvQ9WPyw3eFYN1Bv0KFEn9io
            3oULkIMbbDg5twTOWApLwwWfrckIQm1DF9s7GW9mq6O5DxjkVQL1Og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T00:53:55Z"
    mac: ENC[AES256_GCM,data:/5sLHxxBSJPDBBYDmdML/dBLkDJyntOEUPBC89RjPQFCd3R7VLVDaz6yaNWt1MdHmSVNiBrmn4UslEpZyk0JaMoUvDpEX/T+K8keoggkJWxLwSOrS3dhH79/z4IckF7rG+w0uX0V4q4DNOm5WvkgNuqSaKfRWVq6ljdIGH42l/U=,iv:LrVZK+uF4LlryOElSNJhMZnrj5Fq3gWnUtQ34zVSOLo=,tag:tn3RddzHZ2/cslSqllSk8A==,type:str]
    version: 3.13.3
