load("@rules_oci//oci:defs.bzl", "oci_image")
load("//devinfra/oci:defs.bzl", "oci_layout_rloc")

package(
    default_testonly = True,
    default_visibility = ["//devinfra/github_proxy/host:__pkg__"],
)

oci_image(
    name = "squid_test_image",
    base = "@debian_trixie_slim_linux_amd64",
    tars = ["@github_relay_squid//:flat"],
)

oci_layout_rloc(
    name = "squid_image",
    testonly = True,
    image = ":squid_test_image",
)
