load("//devinfra/python:defs.bzl", "py_library", "py_test")

py_library(
    name = "auth",
    srcs = ["auth.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//authlib",
        "@pypi//fastmcp",
        "@pypi//httpx",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    deps = [
        "@pypi//pytest",
        "@pypi//pytest_asyncio",
    ],
)

py_test(
    name = "test_auth",
    srcs = ["test_auth.py"],
    deps = [
        ":auth",
        ":conftest",
        "@pypi//authlib",
        "@pypi//pytest",
        "@pypi//pytest_asyncio",
        "@pypi//pytest_bazel",
    ],
)
