apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aiquota-api-bearer.sops.yaml
  - public-coder-bearer-eso.yaml
  - haku-claude-bearer-eso.yaml
  - haku-console-bearer-eso.yaml
  - haku-sandbox-bearer-eso.yaml
  - deployment.yaml
  - httproute.yaml
  - service.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: aiquota-api-config
    namespace: cli-proxy-api
    files:
      - config.toml=config.toml
