apiVersion: v1
kind: Namespace
metadata:
  name: oci-cache
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    goldilocks.fairwinds.com/vpa-update-mode: "auto"
    rbac.ducktape.io/agent-logs-configmaps-reader: "true"
    rbac.ducktape.io/agent-namespace-diagnostics-reader: "true"
