load("//devinfra/python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "gen",
    srcs = ["gen.py"],
    deps = [
        "@pypi//fonttools",
        "@pypi//qrcode",
        "@pypi//svg_py",
    ],
)

py_binary(
    name = "gen_bin",
    main_module = "qr_codes.gen",
    deps = [":gen"],
)
