load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "peerstate",
    srcs = ["peerstate.go"],
    importpath = "github.com/agentydragon/ducktape/cluster/kubespan_agent/peerstate",
    visibility = ["//cluster/kubespan_agent:__subpackages__"],
    deps = [
        "@com_github_siderolabs_talos_pkg_machinery//resources/kubespan",
        "@com_zx2c4_golang_wireguard_wgctrl//wgtypes",
    ],
)

go_test(
    name = "peerstate_test",
    srcs = ["peerstate_test.go"],
    deps = [
        ":peerstate",
        "@com_github_siderolabs_talos_pkg_machinery//resources/kubespan",
    ],
)
