# Haskell website builder (DISABLED - rules_haskell incompatible with Bazel 9)
# TODO: Re-enable when rules_haskell supports Bazel 9.
# See MODULE.bazel for details on the incompatibility.
#
# load("@rules_haskell//haskell:defs.bzl", "haskell_binary")
#
# haskell_binary(
#     name = "site",
#     srcs = ["site.hs"],
#     tags = ["manual"],
#     deps = [
#         "@stackage//:base",
#         "@stackage//:hakyll",
#     ],
# )
