# gazelle:ignore
load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "external_system",
    srcs = ["external_system.py"],
    deps = [
    ],
)

py_library(
    name = "splitwise_lib",
    srcs = ["splitwise_lib.py"],
    deps = [
        ":external_system",
        "@pypi//absl_py",
        "@pypi//fastapi",
        "@pypi//platformdirs",
        "@pypi//splitwise",
        "@pypi//uvicorn",
    ],
)

py_library(
    name = "cli",
    srcs = ["cli.py"],
    deps = [
        ":splitwise_lib",
        "//finance:gnucash_util",
        "@pypi//absl_py",
        "@pypi//platformdirs",
        "@pypi//pyyaml",
        "@pypi//types_pyyaml",
    ],
)

py_binary(
    name = "reconcile",
    main_module = "finance.reconcile.cli",
    visibility = ["//visibility:public"],
    deps = [":cli"],
)
