"""Settings for the Authentik MCP POC.

Pure environment-variable config — intentionally minimal. The POC runs two
separate processes via separate entrypoints: the FastMCP server (`server.py`)
and the FastAPI whoami backend (`backend.py`). Server settings use the
`AUTHENTIK_MCP_POC_` prefix; backend settings use the
`AUTHENTIK_MCP_POC_BACKEND_` prefix.
"""

from __future__ import annotations

from urllib.parse import urlparse, urlunparse

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class ServerSettings(BaseSettings):
    """Config for the FastMCP server (the client-facing side)."""

    model_config = SettingsConfigDict(env_prefix="AUTHENTIK_MCP_POC_")

    oidc_issuer: str = Field(
        description="Authentik OIDC issuer URL, e.g. https://auth.allegedly.works/application/o/authentik-mcp-poc/"
    )
    oidc_client_id: str = Field(description="OAuth2 client_id for the Authentik OAuth2 provider")
    oidc_client_secret: str = Field(description="OAuth2 client_secret for the Authentik OAuth2 provider")
    public_base_url: str = Field(
        description="Public URL at which this MCP server is reachable, e.g. https://authentik-mcp-poc.allegedly.works"
    )
    backend_url: str = Field(
        description="Public URL of the Authentik-proxy-protected whoami backend, e.g. "
        "https://authentik-mcp-poc-backend.allegedly.works"
    )
    # For the RFC 7521 JWT-bearer client_credentials token exchange the tool
    # handler performs before calling the backend (see server.py and
    # <NOTES.md> §5). The MCP server authenticates as the backend's own
    # OAuth2 client, presenting the user's upstream token as the
    # `client_assertion` — Authentik validates it against the proxy
    # provider's `jwt_federation_providers` and mints a NEW token scoped to
    # the backend provider, which the outpost's introspection then accepts.
    backend_oidc_client_id: str = Field(
        description=(
            "client_id of the backend's Authentik Proxy Provider (the inner "
            "OAuth2 client auto-generated by `authentik_provider_proxy`). "
            "Used as the `client_id` in the JWT-bearer token exchange."
        )
    )
    host: str = "0.0.0.0"
    port: int = 8765

    def normalized_public_base_url(self) -> str:
        return self.public_base_url.rstrip("/")

    def normalized_issuer(self) -> str:
        return self.oidc_issuer.rstrip("/")

    def authentik_token_endpoint(self) -> str:
        """Global Authentik `/application/o/token/` URL derived from `oidc_issuer`.

        Authentik's token endpoint is NOT per-provider — every OAuth2 provider
        dispatches off the `client_id` parameter in the request body, so a
        single URL like `https://auth.allegedly.works/application/o/token/`
        handles both our MCP user-login provider AND the backend's proxy
        provider. We derive it from `oidc_issuer` (which points at our
        provider's per-provider issuer URL) by stripping the trailing
        `/<slug>/` segment.
        """
        parsed = urlparse(self.oidc_issuer.rstrip("/"))
        # Issuer path looks like `/application/o/authentik-mcp-poc`; we want `/application/o/token/`.
        return urlunparse(parsed._replace(path="/application/o/token/"))


class BackendSettings(BaseSettings):
    """Config for the whoami backend (the outpost-protected side)."""

    model_config = SettingsConfigDict(env_prefix="AUTHENTIK_MCP_POC_BACKEND_")

    host: str = "0.0.0.0"
    port: int = 8080
