load("//devinfra/python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "kind",
    srcs = ["kind.py"],
)

py_library(
    name = "environment",
    srcs = ["environment.py"],
    deps = [
        "//util:env",
        "@pypi//pydantic",
    ],
)
