# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "config",
    srcs = ["config.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s/crd_bindings/external_secrets:clustersecretstore",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
    ],
)

py_library(
    name = "flux_kustomizations",
    srcs = ["flux_kustomizations.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s/crd_bindings/flux:kustomization",
        "@pypi//cdk8s",
    ],
)

py_library(
    name = "operator",
    srcs = ["operator.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s:helm",
        "//cluster/cdk8s:metadata",
        "//cluster/cdk8s/crd_bindings/cert_manager:issuer",
        "//cluster/cdk8s/crd_bindings/flux:helmrepository",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
    ],
)

py_library(
    name = "external_secret",
    srcs = ["external_secret.py"],
    visibility = ["//cluster/cdk8s:__subpackages__"],
    deps = [
        "//cluster/cdk8s:metadata",
        "//cluster/cdk8s/crd_bindings/external_secrets:externalsecret",
        "@pypi//constructs",
    ],
)
