use anyhow::{Context, Result};

use crate::artifact::{
    ArtifactChunkRecord, ArtifactCounts, ArtifactManifest, CANONICAL_CHUNK_ENTRY_FILE,
    ChunkMetadata, FileMetadata, JsChunk, JsFile, JsPipelineArtifact,
};
use crate::program_analysis::{analyze_program_shallow, build_chunk_manifest_from_analysis};

const NORMALIZE_HEADER_LINES: &[&str] = &[
    "// Generated by //devinfra/js/debundle/common:normalize.",
    "// Executable chunk entry.",
];

pub fn normalize_js_chunks(
    artifact: JsPipelineArtifact,
) -> Result<(JsPipelineArtifact, ArtifactManifest)> {
    let mut next = JsPipelineArtifact::default();
    let mut chunk_manifests = Vec::new();
    let mut artifact = artifact;
    for chunk_id in artifact.list_chunk_ids() {
        let mut chunk = artifact
            .chunks
            .remove(&chunk_id)
            .with_context(|| format!("normalizeJsChunks missing ordered chunk: {chunk_id}"))?;
        let source_path = chunk
            .metadata
            .source_path
            .clone()
            .unwrap_or_else(|| format!("{chunk_id}.js"));
        let entry_file = chunk.entry_file.clone();
        let mut entry_artifact_file = chunk.files.remove(&entry_file).with_context(|| {
            format!("normalizeJsChunks requires entry file for chunk: {chunk_id}/{entry_file}")
        })?;
        let parsed = entry_artifact_file.ast.take().with_context(|| {
            format!("normalizeJsChunks requires AST for chunk: {chunk_id}/{entry_file}")
        })?;
        let analysis = analyze_program_shallow(&parsed);
        let manifest = build_chunk_manifest_from_analysis(
            &chunk_id,
            CANONICAL_CHUNK_ENTRY_FILE,
            &source_path,
            &analysis,
        );
        let normalized_file = JsFile {
            path: CANONICAL_CHUNK_ENTRY_FILE.to_string(),
            content: None,
            ast: Some(parsed),
            header_lines: NORMALIZE_HEADER_LINES
                .iter()
                .map(|line| (*line).to_string())
                .collect(),
            metadata: FileMetadata {
                chunk_id: Some(chunk_id.clone()),
                chunk_file: Some(CANONICAL_CHUNK_ENTRY_FILE.to_string()),
                role: Some("entry".to_string()),
                source_path: Some(source_path.clone()),
                ..Default::default()
            },
        };
        let mut files = std::collections::BTreeMap::new();
        files.insert(CANONICAL_CHUNK_ENTRY_FILE.to_string(), normalized_file);
        next.chunk_order.push(chunk_id.clone());
        next.chunk_manifests
            .insert(chunk_id.clone(), manifest.clone());
        next.chunks.insert(
            chunk_id.clone(),
            JsChunk {
                entry_file: CANONICAL_CHUNK_ENTRY_FILE.to_string(),
                files,
                metadata: ChunkMetadata {
                    source_path: Some(source_path),
                    module_extraction_state: None,
                },
            },
        );
        chunk_manifests.push(manifest);
    }
    let manifest = build_artifact_manifest(&chunk_manifests);
    next.root_manifest = Some(manifest.clone());
    Ok((next, manifest))
}

fn build_artifact_manifest(chunk_manifests: &[crate::artifact::ChunkManifest]) -> ArtifactManifest {
    ArtifactManifest {
        schema_version: 1,
        counts: ArtifactCounts {
            chunks: chunk_manifests.len(),
            parts: 0,
            split_function_declarations: 0,
            kept_top_level_declaration_owners: chunk_manifests
                .iter()
                .map(|manifest| manifest.counts.kept_top_level_declaration_owners)
                .sum(),
            top_level_side_effects: chunk_manifests
                .iter()
                .map(|manifest| manifest.counts.top_level_side_effects)
                .sum(),
            export_aliases: chunk_manifests
                .iter()
                .map(|manifest| manifest.counts.export_aliases)
                .sum(),
            unresolved_exports: chunk_manifests
                .iter()
                .map(|manifest| manifest.counts.unresolved_exports)
                .sum(),
            selected_module_lowerings: None,
            extra: Default::default(),
        },
        chunks: chunk_manifests
            .iter()
            .map(|manifest| ArtifactChunkRecord {
                chunk_id: manifest.chunk_id.clone(),
                source_path: manifest.source_path.clone(),
            })
            .collect(),
        logical_modules: None,
        selected_module_lowerings: None,
        extra: Default::default(),
    }
}
