use std::collections::{BTreeMap, BTreeSet};
use std::time::Instant;

use anyhow::{Context, Result, bail};
use rayon::prelude::*;
use serde::Serialize;

use analysis::ChunkId;
use artifact::{
    ArtifactChunkRecord, ArtifactCounts, ArtifactManifest, CANONICAL_CHUNK_ENTRY_FILE,
    ChunkArtifact, ChunkManifest, ChunkMetadata, FileMetadata, FileRole, JsChunk, JsFile,
    JsFileBody, JsPipelineArtifact, LoadedJsChunks, ParsedJsFileRecord,
};
use js_ast::{ParsedJsModule, parse_js_module_consuming};
use program_analysis::{
    ProgramAnalysis, analyze_program_shallow, build_chunk_manifest_from_analysis,
};
use rewrite_specifiers::ast_has_rewritable_specifier;
use spec::TransformSpec;

const CANONICALIZE_HEADER_LINES: &[&str] = &[
    "// Generated by //devinfra/js/debundle:prepare_chunks.",
    "// Executable chunk entry.",
];

pub struct PrepareJsChunksResult {
    pub artifact: JsPipelineArtifact,
    pub manifest: ArtifactManifest,
    pub parsed_js_files: ParsedJsFilesManifest,
}

#[derive(Debug, Clone, Serialize)]
pub struct ParsedJsFilesManifest {
    pub counts: ParsedJsFilesCounts,
    pub parsed_files: Vec<ParsedJsFileRecord>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ParsedJsFilesCounts {
    pub parsed: usize,
    pub files: usize,
}

pub fn prepare_js_chunks(
    spec: &TransformSpec,
    mut loaded: LoadedJsChunks,
) -> Result<PrepareJsChunksResult> {
    // Move chunk_table out of loaded; it will be placed on the artifact.
    let chunk_table = std::mem::take(&mut loaded.chunk_table);

    // Collect (ChunkId, name) pairs preserving load order.
    let ordered_ids: Vec<(ChunkId, String)> = loaded
        .chunk_order
        .iter()
        .map(|id| (*id, chunk_table.name(*id).to_string()))
        .collect();
    let jobs = ordered_ids
        .iter()
        .map(|(chunk_id, chunk_name)| {
            let mut chunk = loaded.take_chunk(*chunk_id).with_context(|| {
                format!("prepare_js_chunks missing ordered chunk: {chunk_name}")
            })?;
            let entry_file = chunk.entry_file.clone();
            let entry_artifact_file = chunk.remove_file(&entry_file).with_context(|| {
                format!(
                    "prepare_js_chunks requires entry file for chunk: {chunk_name}/{entry_file}"
                )
            })?;
            // Source text is taken ownership of here; it will be moved into
            // the SourceMap via parse_js_module_consuming inside prepare_chunk.
            let source = entry_artifact_file.into_source().with_context(|| {
                format!("prepare_js_chunks requires content for chunk: {chunk_name}/{entry_file}")
            })?;
            Ok(PrepareChunkJob {
                chunk_id: *chunk_id,
                chunk_name: chunk_name.clone(),
                chunk: JsChunk {
                    entry_file: entry_file.clone(),
                    files: vec![JsFile {
                        path: entry_file.clone(),
                        body: JsFileBody::Source(source),
                        header_lines: Vec::new(),
                        metadata: FileMetadata::default(),
                    }],
                    metadata: chunk.metadata,
                },
            })
        })
        .collect::<Result<Vec<_>>>()?;
    let file_count = jobs.iter().map(|job| job.chunk.files.len()).sum();

    // First pass: parse all chunks and collect imports for vendor caller detection.
    // Source text moves into the SourceMap; no extra copy.
    let parsed_chunks = jobs
        .into_par_iter()
        .map(|job| {
            let chunk_id = job.chunk_id;
            let chunk_name = job.chunk_name.clone();
            let parsed = prepare_chunk(job)?;
            Ok((chunk_id, chunk_name, parsed))
        })
        .collect::<Result<Vec<_>>>()?;

    // Build import index to detect vendor callers
    let import_index = build_import_index(&parsed_chunks);

    // Build set of vendor target chunk ids
    let vendor_target_chunk_ids: BTreeSet<String> = spec
        .vendor
        .keys()
        .filter_map(|chunk_path| {
            // Vendor marks use .js paths, convert to chunk ids
            chunk_path.strip_suffix(".js").map(|s| s.to_string())
        })
        .collect();

    // Second pass: replace ASTs with original source for chunks that don't need them.
    //
    // A chunk needs to keep its AST if any downstream stage will read it. The
    // predicates below cover spec-driven stages (logical modules, residual
    // modules, renames, vendor); on top of those, `rewrite_chunk_entry_specifiers`
    // runs unconditionally for every chunk, so we must also keep the AST whenever
    // that stage would actually rewrite anything in this chunk's entry. The
    // unified predicate `ast_has_rewritable_specifier` mirrors `rewrite_source`
    // exactly — both treat a specifier as rewriteable iff it is a relative path
    // (`.` or `/` prefix). Sharing the predicate prevents drift if either side
    // grows.
    let prepared_chunks = parsed_chunks
        .into_iter()
        .map(|(chunk_id, chunk_name, mut prepared)| {
            let needs_ast =
                needs_ast_for_chunk(&chunk_name, spec, &import_index, &vendor_target_chunk_ids)
                    || entry_has_rewritable_specifier(&prepared);

            if !needs_ast {
                // Clone the source text from the SourceMap. We need an owned
                // String because the AST (which owns the SourceMap) is being
                // dropped. This is one copy instead of the previous three:
                // load → JsFileBody::Source clone → SourceMap clone.
                let source = prepared
                    .files
                    .iter()
                    .find(|f| f.path == prepared.entry_file)
                    .and_then(|f| f.ast())
                    .map(|parsed| parsed.source_text());
                if let Some(source) = source {
                    if let Some(entry_file) = prepared
                        .files
                        .iter_mut()
                        .find(|f| f.path == prepared.entry_file)
                    {
                        entry_file.body = JsFileBody::Source(source);
                    }
                }
            }

            Ok((chunk_id, chunk_name, prepared))
        })
        .collect::<Result<Vec<_>>>()?;

    let (mut next, manifests, parsed_files) = ordered_ids.into_iter().zip(prepared_chunks).try_fold(
        (
            JsPipelineArtifact::default(),
            Vec::<ChunkManifest>::new(),
            Vec::<ParsedJsFileRecord>::new(),
        ),
        |(mut next, mut manifests, mut parsed_files), ((_expected_chunk_id, expected_chunk_name), (actual_chunk_id, actual_chunk_name, prepared))| {
            if actual_chunk_name != expected_chunk_name {
                bail!(
                    "prepare_js_chunks reordered prepared chunks: expected {expected_chunk_name}, got {actual_chunk_name}"
                );
            }
            let manifest = prepared.manifest.clone();
            next.chunks.push(ChunkArtifact {
                chunk_id: actual_chunk_id,
                js: JsChunk {
                    entry_file: prepared.entry_file,
                    files: prepared.files,
                    metadata: prepared.metadata,
                },
                manifest: manifest.clone(),
            });
            parsed_files.extend(prepared.parsed_files);
            manifests.push(manifest);
            Ok::<_, anyhow::Error>((next, manifests, parsed_files))
        },
    )?;

    next.chunk_table = chunk_table;
    let manifest = build_artifact_manifest(&manifests);
    next.root_manifest = manifest.clone();
    Ok(PrepareJsChunksResult {
        artifact: next,
        manifest,
        parsed_js_files: ParsedJsFilesManifest {
            counts: ParsedJsFilesCounts {
                parsed: parsed_files.len(),
                files: file_count,
            },
            parsed_files,
        },
    })
}

struct PrepareChunkJob {
    chunk_id: ChunkId,
    chunk_name: String,
    chunk: JsChunk,
}

struct PreparedChunk {
    entry_file: String,
    files: Vec<JsFile>,
    metadata: ChunkMetadata,
    manifest: ChunkManifest,
    parsed_files: Vec<ParsedJsFileRecord>,
}

fn prepare_chunk(job: PrepareChunkJob) -> Result<PreparedChunk> {
    let PrepareChunkJob {
        chunk_id: _,
        chunk_name,
        mut chunk,
    } = job;
    let source_path = chunk
        .metadata
        .source_path
        .clone()
        .unwrap_or_else(|| format!("{chunk_name}.js"));
    let entry_file = chunk.entry_file.clone();
    let entry_artifact_file = chunk.remove_file(&entry_file).with_context(|| {
        format!("prepare_js_chunks requires entry file for chunk: {chunk_name}/{entry_file}")
    })?;
    let (manifest, prepared_file, prepared_entry_file, parsed_files) =
        prepare_parsed_entry(&chunk_name, &entry_file, &source_path, entry_artifact_file)?;
    Ok(PreparedChunk {
        entry_file: prepared_entry_file,
        files: vec![prepared_file],
        metadata: ChunkMetadata {
            source_path: Some(source_path),
            module_extraction_state: None,
        },
        manifest,
        parsed_files,
    })
}

fn prepare_parsed_entry(
    chunk_id: &str,
    entry_file: &str,
    source_path: &str,
    entry_artifact_file: JsFile,
) -> Result<(ChunkManifest, JsFile, String, Vec<ParsedJsFileRecord>)> {
    let content = entry_artifact_file.into_source().with_context(|| {
        format!("prepare_js_chunks requires content for parsed chunk: {chunk_id}/{entry_file}")
    })?;
    let source_bytes = content.len();
    let source_name = format!("{chunk_id}/{entry_file}");

    let parse_started = Instant::now();
    // Takes ownership of content — zero extra copies into the SourceMap.
    let parsed = parse_js_module_consuming(&source_name, content)?;
    let parse_duration = parse_started.elapsed();

    let analysis_started = Instant::now();
    let analysis = analyze_program_shallow(&parsed);
    let analysis_duration = analysis_started.elapsed();

    let manifest = build_parsed_chunk_manifest(chunk_id, source_path, &analysis);
    let file = canonical_parsed_file(chunk_id, source_path, parsed);
    Ok((
        manifest,
        file,
        CANONICAL_CHUNK_ENTRY_FILE.to_string(),
        vec![ParsedJsFileRecord {
            chunk_id: chunk_id.to_string(),
            file: entry_file.to_string(),
            source_bytes,
            parse_duration,
            analysis_duration,
        }],
    ))
}

fn build_parsed_chunk_manifest(
    chunk_id: &str,
    source_path: &str,
    analysis: &ProgramAnalysis,
) -> ChunkManifest {
    build_chunk_manifest_from_analysis(chunk_id, CANONICAL_CHUNK_ENTRY_FILE, source_path, analysis)
}

fn canonical_parsed_file(chunk_id: &str, source_path: &str, parsed: ParsedJsModule) -> JsFile {
    JsFile {
        path: CANONICAL_CHUNK_ENTRY_FILE.to_string(),
        body: JsFileBody::Ast(parsed),
        header_lines: CANONICALIZE_HEADER_LINES
            .iter()
            .map(|line| (*line).to_string())
            .collect(),
        metadata: FileMetadata {
            chunk_id: Some(chunk_id.to_string()),
            chunk_file: Some(CANONICAL_CHUNK_ENTRY_FILE.to_string()),
            role: Some(FileRole::Entry),
            source_path: Some(source_path.to_string()),
            ..Default::default()
        },
    }
}

fn build_artifact_manifest(manifests: &[ChunkManifest]) -> ArtifactManifest {
    ArtifactManifest {
        counts: ArtifactCounts {
            chunks: manifests.len(),
            kept_top_level_declaration_owners: manifests
                .iter()
                .map(|manifest| manifest.counts.kept_top_level_declaration_owners)
                .sum(),
            top_level_side_effects: manifests
                .iter()
                .map(|manifest| manifest.counts.top_level_side_effects)
                .sum(),
            export_aliases: manifests
                .iter()
                .map(|manifest| manifest.counts.export_aliases)
                .sum(),
            unresolved_exports: manifests
                .iter()
                .map(|manifest| manifest.counts.unresolved_exports)
                .sum(),
            selected_module_lowerings: None,
        },
        chunks: manifests
            .iter()
            .map(|manifest| ArtifactChunkRecord {
                chunk_id: manifest.chunk_id.clone(),
                source_path: manifest.source_path.clone(),
            })
            .collect(),
        logical_modules: None,
        selected_module_lowerings: None,
        identifier_rename_queue: None,
        output_metrics: None,
    }
}

/// Build an index of imports by target chunk for vendor caller detection.
fn build_import_index(
    chunks: &[(ChunkId, String, PreparedChunk)],
) -> BTreeMap<String, Vec<String>> {
    chunks
        .iter()
        .flat_map(|(_chunk_id, chunk_name, prepared)| {
            prepared.manifest.imports.iter().filter_map(move |import| {
                let target_chunk_id = import
                    .source
                    .strip_prefix("./")
                    .and_then(|s| s.strip_suffix(".js").or(Some(s)))?;
                Some((target_chunk_id.to_string(), chunk_name.clone()))
            })
        })
        .fold(
            BTreeMap::new(),
            |mut acc, (target_chunk_id, caller_chunk_id)| {
                acc.entry(target_chunk_id)
                    .or_default()
                    .push(caller_chunk_id);
                acc
            },
        )
}

/// True iff this chunk's entry-file AST contains any specifier that
/// `rewrite_chunk_entry_specifiers` could rewrite. Looking at the actual
/// AST (rather than the manifest's static-import list) is what makes this
/// coherent with the rewrite phase: we cover dynamic `import(...)` and
/// `new Worker(...)` shapes too, and we apply the same relative-path
/// gate (`.` / `/` prefix) that `rewrite_source` uses.
fn entry_has_rewritable_specifier(prepared: &PreparedChunk) -> bool {
    let Some(entry) = prepared
        .files
        .iter()
        .find(|f| f.path == prepared.entry_file)
    else {
        return false;
    };
    let JsFileBody::Ast(parsed) = &entry.body else {
        return false;
    };
    ast_has_rewritable_specifier(parsed)
}

/// Determine if a chunk needs to keep its AST based on the spec and import index.
fn needs_ast_for_chunk(
    chunk_id: &str,
    spec: &TransformSpec,
    import_index: &BTreeMap<String, Vec<String>>,
    vendor_target_chunk_ids: &BTreeSet<String>,
) -> bool {
    // Chunk with logical modules needs AST
    if spec.logical_modules.contains_key(chunk_id) {
        return true;
    }

    // Chunk with a non-default unassigned-mode policy needs AST
    // (CatchallFile emits a residual logical module; MiniFactors
    // synthesizes mini-factor modules — both require the chunk
    // body parsed for materialisation).
    if spec.unassigned_mode.contains_key(chunk_id) {
        return true;
    }

    // Chunk with renames needs AST
    if spec.chunk_renames.contains_key(chunk_id) {
        return true;
    }

    // Vendor target needs AST
    if vendor_target_chunk_ids.contains(chunk_id) {
        return true;
    }

    // Chunk that imports a vendor target needs AST
    if let Some(callers) = import_index.get(chunk_id) {
        for caller in callers {
            if vendor_target_chunk_ids.contains(caller) {
                return true;
            }
        }
    }

    // Check if this chunk imports a vendor target
    for vendor_target in vendor_target_chunk_ids {
        if let Some(callers) = import_index.get(vendor_target) {
            if callers.iter().any(|caller| caller == chunk_id) {
                return true;
            }
        }
    }

    false
}
