use std::collections::{BTreeMap, BTreeSet};

use anyhow::{Context, Result};
use rayon::prelude::*;
use swc_common::GLOBALS;

use analysis::ChunkId;
use artifact::{
    ArtifactChunkRecord, ArtifactCounts, CANONICAL_CHUNK_ENTRY_FILE, ChunkAnalysisReport,
    ChunkArtifact, ChunkBundle, ChunkMetadata, FileMetadata, FileRole, JsChunk, JsFile, JsFileBody,
    LoadedJsChunks,
};
use js_ast::{ParsedJsModule, parse_js_module_consuming};
use program_analysis::{analyze_program_shallow, build_chunk_manifest_from_analysis};
use spec::TransformSpec;

const CANONICALIZE_HEADER_LINES: &[&str] = &[
    "// Generated by //devinfra/js/debundle:prepare_chunks.",
    "// Executable chunk entry.",
];

pub struct PrepareJsChunksResult {
    pub artifact: ChunkBundle,
    pub counts: ArtifactCounts,
    pub chunk_records: Vec<ArtifactChunkRecord>,
}

pub fn prepare_js_chunks(
    spec: &TransformSpec,
    loaded: LoadedJsChunks,
) -> Result<PrepareJsChunksResult> {
    let LoadedJsChunks {
        chunks,
        chunk_table,
    } = loaded;

    let jobs = chunks
        .into_iter()
        .enumerate()
        .map(|(index, mut chunk)| {
            let chunk_id = ChunkId(index);
            let chunk_name = chunk_table.name(chunk_id).to_string();
            let entry_file = chunk.entry_file.clone();
            let entry_artifact_file = chunk.remove_file(&entry_file).with_context(|| {
                format!(
                    "prepare_js_chunks requires entry file for chunk: {chunk_name}/{entry_file}"
                )
            })?;
            let entry_source = entry_artifact_file.into_source().with_context(|| {
                format!("prepare_js_chunks requires content for chunk: {chunk_name}/{entry_file}")
            })?;
            Ok(PrepareChunkJob {
                chunk_id,
                chunk_name,
                entry_file,
                source_path: chunk.metadata.source_path.clone(),
                entry_source,
            })
        })
        .collect::<Result<Vec<_>>>()?;

    // First pass: parse all chunks and collect imports for vendor caller detection.
    // Source text moves into the SourceMap; no extra copy.
    // Rayon workers don't inherit the caller's `swc_common::GLOBALS` scope
    // (it's `scoped_tls`, per-thread), so we re-set it inside each worker
    // closure to give `Mark::new()` an arena to mint into.
    let parsed_chunks = GLOBALS.with(|globals| {
        jobs.into_par_iter()
            .map(|job| {
                GLOBALS.set(globals, || {
                    let chunk_id = job.chunk_id;
                    let chunk_name = job.chunk_name.clone();
                    let parsed = prepare_chunk(job)?;
                    Ok((chunk_id, chunk_name, parsed))
                })
            })
            .collect::<Result<Vec<_>>>()
    })?;

    // Build import index to detect vendor callers
    let import_index = build_import_index(&parsed_chunks);

    // Build set of vendor target chunk ids
    let vendor_target_chunk_ids: BTreeSet<String> = spec
        .vendor
        .keys()
        .filter_map(|chunk_path| {
            // Vendor marks use .js paths, convert to chunk ids
            chunk_path.strip_suffix(".js").map(|s| s.to_string())
        })
        .collect();

    // Second pass: replace ASTs with original source for chunks that don't need them.
    //
    // A chunk needs to keep its AST if any downstream stage will read it. The
    // predicates below cover spec-driven stages (logical modules, residual
    // modules, renames, vendor); on top of those, the pass-through emission
    // rewriter canonicalizes specifiers in every emitted non-module file, so
    // we must also keep the AST whenever it would rewrite anything in this
    // chunk's entry. The `has_rewritable_specifier` fact mirrors the
    // canonicalizer's relative-path gate (`.` or `/` prefix) exactly and is
    // computed during the first-pass `analyze_program_shallow` walk, so this
    // second pass does not need to re-visit the AST.
    let prepared_chunks = parsed_chunks
        .into_iter()
        .map(|(chunk_id, chunk_name, mut prepared)| {
            let needs_ast =
                needs_ast_for_chunk(&chunk_name, spec, &import_index, &vendor_target_chunk_ids)
                    || prepared.has_rewritable_specifier;

            if !needs_ast
                && let Some(pos) = prepared
                    .files
                    .iter()
                    .position(|f| f.path == CANONICAL_CHUNK_ENTRY_FILE)
            {
                let file = prepared.files.remove(pos);
                if let Some(rendered) = file.into_rendered_source() {
                    prepared.files.insert(pos, rendered);
                }
            }

            Ok((chunk_id, chunk_name, prepared))
        })
        .collect::<Result<Vec<_>>>()?;

    let artifact = ChunkBundle {
        chunks: prepared_chunks
            .into_iter()
            .map(|(chunk_id, _, prepared)| ChunkArtifact {
                chunk_id,
                js: JsChunk {
                    entry_file: CANONICAL_CHUNK_ENTRY_FILE.to_string(),
                    files: prepared.files,
                    metadata: prepared.metadata,
                },
                analysis: prepared.analysis,
            })
            .collect(),
        chunk_table,
    };

    let manifests: Vec<ChunkAnalysisReport> = artifact
        .chunks
        .iter()
        .map(|chunk| chunk.analysis.clone())
        .collect();
    let (counts, chunk_records) = build_prepare_output(&manifests);
    Ok(PrepareJsChunksResult {
        artifact,
        counts,
        chunk_records,
    })
}

struct PrepareChunkJob {
    chunk_id: ChunkId,
    chunk_name: String,
    entry_file: String,
    source_path: String,
    entry_source: String,
}

struct PreparedChunk {
    files: Vec<JsFile>,
    metadata: ChunkMetadata,
    analysis: ChunkAnalysisReport,
    /// Captured from the fused `analyze_program_shallow` walk so the
    /// second pass can decide AST retention without re-visiting the
    /// AST.
    has_rewritable_specifier: bool,
}

fn prepare_chunk(job: PrepareChunkJob) -> Result<PreparedChunk> {
    let parsed = parse_js_module_consuming(
        &format!("{}/{}", job.chunk_name, job.entry_file),
        job.entry_source,
    )?;
    let analysis = analyze_program_shallow(&parsed);
    Ok(PreparedChunk {
        files: vec![canonical_parsed_file(
            &job.chunk_name,
            &job.source_path,
            parsed,
        )],
        analysis: build_chunk_manifest_from_analysis(
            &job.chunk_name,
            CANONICAL_CHUNK_ENTRY_FILE,
            &job.source_path,
            &analysis,
        ),
        has_rewritable_specifier: analysis.has_rewritable_specifier,
        metadata: ChunkMetadata {
            source_path: job.source_path,
        },
    })
}

fn canonical_parsed_file(chunk_id: &str, source_path: &str, parsed: ParsedJsModule) -> JsFile {
    JsFile {
        path: CANONICAL_CHUNK_ENTRY_FILE.to_string(),
        body: JsFileBody::Ast(parsed),
        header_lines: CANONICALIZE_HEADER_LINES
            .iter()
            .map(|line| (*line).to_string())
            .collect(),
        binding_comments: BTreeMap::new(),
        leading_item_comments: BTreeMap::new(),
        metadata: FileMetadata {
            chunk_id: chunk_id.to_string(),
            chunk_file: CANONICAL_CHUNK_ENTRY_FILE.to_string(),
            role: FileRole::Entry,
            source_path: source_path.to_string(),
        },
    }
}

fn build_prepare_output(
    manifests: &[ChunkAnalysisReport],
) -> (ArtifactCounts, Vec<ArtifactChunkRecord>) {
    let counts = ArtifactCounts {
        kept_top_level_declaration_owners: manifests
            .iter()
            .map(|manifest| manifest.counts.kept_top_level_declaration_owners)
            .sum(),
        top_level_side_effects: manifests
            .iter()
            .map(|manifest| manifest.counts.top_level_side_effects)
            .sum(),
        export_aliases: manifests
            .iter()
            .map(|manifest| manifest.counts.export_aliases)
            .sum(),
        unresolved_exports: manifests
            .iter()
            .map(|manifest| manifest.counts.unresolved_exports)
            .sum(),
    };
    let chunk_records = manifests
        .iter()
        .map(|manifest| ArtifactChunkRecord {
            chunk_id: manifest.chunk_id.clone(),
            source_path: manifest.source_path.clone(),
        })
        .collect();
    (counts, chunk_records)
}

/// Build an index of imports by target chunk for vendor caller detection.
fn build_import_index(
    chunks: &[(ChunkId, String, PreparedChunk)],
) -> BTreeMap<String, Vec<String>> {
    chunks
        .iter()
        .flat_map(|(_chunk_id, chunk_name, prepared)| {
            prepared.analysis.imports.iter().filter_map(move |import| {
                let target_chunk_id = import
                    .source
                    .strip_prefix("./")
                    .and_then(|s| s.strip_suffix(".js").or(Some(s)))?;
                Some((target_chunk_id.to_string(), chunk_name.clone()))
            })
        })
        .fold(
            BTreeMap::new(),
            |mut acc, (target_chunk_id, caller_chunk_id)| {
                acc.entry(target_chunk_id)
                    .or_default()
                    .push(caller_chunk_id);
                acc
            },
        )
}

/// Determine if a chunk needs to keep its AST based on the spec and import index.
fn needs_ast_for_chunk(
    chunk_id: &str,
    spec: &TransformSpec,
    import_index: &BTreeMap<String, Vec<String>>,
    vendor_target_chunk_ids: &BTreeSet<String>,
) -> bool {
    // Chunk with logical modules needs AST
    if spec.logical_modules.contains_key(chunk_id) {
        return true;
    }

    // Chunk with a non-default unassigned-mode policy needs AST
    // (CatchallFile emits a residual logical module; MiniFactors
    // synthesizes mini-factor modules — both require the chunk
    // body parsed for materialisation).
    if spec.unassigned_mode.contains_key(chunk_id) {
        return true;
    }

    // Chunk with renames needs AST
    if spec.chunk_renames.contains_key(chunk_id) {
        return true;
    }

    // Vendor target needs AST
    if vendor_target_chunk_ids.contains(chunk_id) {
        return true;
    }

    // Chunk that imports a vendor target needs AST
    if let Some(callers) = import_index.get(chunk_id) {
        for caller in callers {
            if vendor_target_chunk_ids.contains(caller) {
                return true;
            }
        }
    }

    // Check if this chunk imports a vendor target
    for vendor_target in vendor_target_chunk_ids {
        if let Some(callers) = import_index.get(vendor_target)
            && callers.iter().any(|caller| caller == chunk_id)
        {
            return true;
        }
    }

    false
}
