//! Selector debt report: rank the spec's most rebuild-fragile selectors.
//!
//! Powers `debundle spec selector-debt`. A spec author targets minified
//! top-level statements two ways: by **name** (`selector.binding.name`,
//! cheap but unstable — a rebuild can reassign the token) or by
//! **structure** (`selector.source_match`, robust but verbose and prone
//! to copy-paste). This report surfaces the debt that accrues from the
//! cheap path, so authors can see what rests on fragile name-only
//! selection and which structural selectors have been copied:
//!
//! - **name-only selectors**, scored by how minified the bound name
//!   looks (`minified_score`). Short / vowel-poor tokens rank highest
//!   because they are the most likely to move under a rebuild.
//! - **repeated `source_match` bodies** — identical structural selector
//!   text reused across members / anonymous statements / binding groups.
//!   These are the copy-paste the contextual-selector and matcher-core
//!   work is meant to replace.
//! - **drifted minified bindings** (with `--against <other spec>`) —
//!   members whose readable `name:` is stable across two spec versions
//!   but whose `selector.binding.name` changed. A name-only selector
//!   that has *already* required updating is proven rebuild-fragile.
//!
//! By default this reads only the on-disk modules tree (same walk as
//! `spec stats` / `modules list`). With [`SourceAwareSelectorDebtConfig`],
//! callers may also supply the current chunk source to flag structural
//! selectors that resolve uniquely today but have close non-matching
//! siblings in that chunk.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use anyhow::{Context, Result};
use serde::Serialize;
use spec::{AnonymousStatementSelector, MemberSelectorSpec};
use spec_modules::{ModuleFile, collect_module_files, module_path_from_file, read_module_file};
use swc_ecma_ast::{
    Expr, Lit, Module as SwcModule, ModuleDecl, ModuleItem, Pat, Stmt, VarDecl, VarDeclKind,
    VarDeclarator,
};

/// Minified-score at or above which a name-only selector is counted as
/// rebuild-fragile in [`SelectorDebtSummary::name_only_fragile`]. The
/// score scale is coarse (see [`minified_score`]); every positive score
/// clears this threshold, so "fragile" means "did not look like a
/// readable word."
pub const FRAGILE_THRESHOLD: u8 = 60;

/// Heuristic `0..=100` estimate of how minified / autogenerated an
/// identifier looks. Higher means more likely a bundler-assigned token,
/// and therefore a more rebuild-fragile thing to select by name.
///
/// This is triage guidance, not a classifier: the score only has to
/// *rank* selectors so the most fragile ones surface first. Shortness
/// and vowel-poverty are the load-bearing signals — base-54 minifier
/// output is dominated by 1-3 character tokens and consonant clusters,
/// while hand-written identifiers tend to be longer and word-shaped.
pub fn minified_score(name: &str) -> u8 {
    let len = name.chars().count();
    if len == 0 {
        return 0;
    }
    let vowels = name.chars().filter(|c| "aeiouAEIOU".contains(*c)).count();
    match len {
        1 => 100,
        2 => 90,
        // A vowel-less three-letter token (`Rng`, `Wbt`) is almost
        // always minified; one with a vowel (`XOe`, `iRe`) is still
        // short enough to be collision-prone but slightly less certain.
        3 if vowels == 0 => 85,
        3 => 70,
        // Four or more characters with no vowel at all is consonant
        // soup — overwhelmingly minified. Longer names that contain a
        // vowel read as words and score zero (not flagged).
        _ if vowels == 0 => 60,
        _ => 0,
    }
}

/// Which selector construct an occurrence came from.
#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum SelectorSite {
    Member,
    AnonymousStatement,
    BindingGroup,
}

#[derive(Debug, Clone, Serialize)]
pub struct NameOnlySelector {
    /// Module path that owns the member.
    pub module: String,
    /// The bound minified name the selector matches on.
    pub binding_name: String,
    /// Readable export `name:`, when the member has one.
    pub export_name: Option<String>,
    /// Heuristic minified-ness of `binding_name` (see [`minified_score`]).
    pub minified_score: u8,
}

#[derive(Debug, Clone, Serialize)]
pub struct NameOnlyModuleGroup {
    /// First `module_prefix_depth` slash-separated path components.
    pub module_prefix: String,
    pub module_prefix_depth: usize,
    /// Name-only selectors in this group after any caller-side filtering.
    pub name_only_count: usize,
    /// Rows in this group with `minified_score >= FRAGILE_THRESHOLD`.
    pub fragile_count: usize,
    /// Distinct modules contributing rows to the group.
    pub module_count: usize,
    /// Highest minified score seen in the group.
    pub max_minified_score: u8,
}

#[derive(Debug, Clone, Serialize)]
pub struct SourceMatchOccurrence {
    pub module: String,
    pub site: SelectorSite,
    /// Readable export `name:` for `Member`-site occurrences.
    pub export_name: Option<String>,
    /// The original (un-normalized) `match` body, for display.
    pub match_source: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct RepeatedSourceMatch {
    /// Whitespace-normalized body shared by every occurrence; the key
    /// the occurrences were grouped on.
    pub normalized: String,
    pub occurrences: Vec<SourceMatchOccurrence>,
}

#[derive(Debug, Clone, Serialize)]
pub struct SourceAwareRepeatedExactSourceMatch {
    /// Whitespace-normalized body shared by every occurrence.
    pub normalized: String,
    /// Exact top-level body indices every occurrence resolves to today.
    pub exact_body_indices: Vec<usize>,
    pub occurrences: Vec<SourceMatchOccurrence>,
}

#[derive(Debug, Clone, Serialize)]
pub struct SourceAwareNearMiss {
    /// Top-level body index of the near-matching candidate in the current chunk.
    pub body_idx: usize,
    /// Binding names declared by that candidate, if any.
    pub declared_bindings: Vec<String>,
    /// Existing source_match mismatch-score heuristic. Higher means closer.
    pub score: usize,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct SourceAwareStructuralSelector {
    pub module: String,
    pub site: SelectorSite,
    /// Readable export `name:` for `Member`-site occurrences.
    pub export_name: Option<String>,
    /// The exact top-level body indices matched by this selector today.
    pub exact_body_indices: Vec<usize>,
    pub near_misses: Vec<SourceAwareNearMiss>,
}

#[derive(Debug, Clone, Serialize)]
pub struct SourceMatchBindingGroupSelector {
    pub module: String,
    pub export_name: Option<String>,
    pub target_binding: String,
    pub declarator_idx: usize,
}

#[derive(Debug, Clone, Serialize)]
pub struct SourceAwareBindingGroupSuggestion {
    pub module: String,
    pub body_idx: usize,
    pub declaration_kind: String,
    pub selectors: Vec<SourceMatchBindingGroupSelector>,
    /// Pasteable YAML sketch for replacing repeated member-form
    /// `source_match` selectors with one `binding_groups` entry.
    pub candidate_yaml: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct DriftedBinding {
    pub module: String,
    pub export_name: String,
    /// `selector.binding.name` in the `--against` spec.
    pub previous_binding: String,
    /// `selector.binding.name` in the current spec.
    pub current_binding: String,
}

/// Spec-wide totals. These count the whole spec; the lists in
/// [`SelectorDebtReport`] may be filtered (`--min-score`) or truncated
/// (`--limit`) by the CLI, so the summary is not derivable from the
/// printed rows.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SelectorDebtSummary {
    pub name_only_total: usize,
    /// Name-only selectors scoring `>= FRAGILE_THRESHOLD`.
    pub name_only_fragile: usize,
    /// Every `source_match` occurrence (repeated or not).
    pub source_match_total: usize,
    pub repeated_source_match_groups: usize,
    pub drifted_binding_total: usize,
    /// Source-aware structural selectors checked against a chunk source.
    /// Zero when source-aware mode was not requested.
    pub source_aware_checked: usize,
    /// Checked selectors with exactly one exact top-level body match.
    pub source_aware_unique: usize,
    /// Unique structural selectors that also had near-matching siblings.
    pub source_aware_near_ambiguous: usize,
    /// Repeated structural selector bodies that resolve to the same exact
    /// top-level body index set in source-aware mode.
    pub source_aware_repeated_exact: usize,
    /// Source-aware member-form `source_match` groups that can be consolidated
    /// into one `binding_groups` entry.
    pub source_aware_binding_group_suggestions: usize,
    /// Member-form `source_match` rows covered by those suggestions.
    pub source_aware_binding_group_suggested_selectors: usize,
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct SelectorDebtReport {
    /// Every name-only (`selector.binding`) selector, sorted most
    /// rebuild-fragile first.
    pub name_only: Vec<NameOnlySelector>,
    /// `source_match` bodies that appear two or more times, sorted by
    /// occurrence count (descending).
    pub repeated_source_match: Vec<RepeatedSourceMatch>,
    /// Populated only when `--against` is supplied.
    pub drifted_bindings: Vec<DriftedBinding>,
    /// Populated only when source-aware mode is supplied.
    pub source_aware_near_ambiguous: Vec<SourceAwareStructuralSelector>,
    /// Populated only when source-aware mode is supplied.
    pub source_aware_repeated_exact: Vec<SourceAwareRepeatedExactSourceMatch>,
    /// Populated only when source-aware mode is supplied.
    pub source_aware_binding_group_suggestions: Vec<SourceAwareBindingGroupSuggestion>,
    /// Populated by the CLI when `--group-module-depth` is requested.
    /// Derived from the already-computed and caller-filtered `name_only` rows.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub name_only_module_groups: Vec<NameOnlyModuleGroup>,
    pub summary: SelectorDebtSummary,
}

#[derive(Debug, Clone)]
pub struct SourceAwareSelectorDebtConfig<'a> {
    /// Current chunk source to parse and compare `source_match` bodies against.
    pub source_file: &'a Path,
    /// Minimum near-miss score to report. See `source_match` mismatch scoring.
    pub near_match_min_score: usize,
    /// Maximum near-matches retained per selector. Zero means unlimited.
    pub near_match_limit: usize,
}

/// Normalize a `match` body for copy-paste grouping: collapse every run
/// of whitespace to a single space. Copy-paste produces byte-identical
/// (modulo reindentation) bodies, so whitespace-insensitive textual
/// identity is exactly the right grain — no need to parse the JS.
fn normalize_match(source: &str) -> String {
    source.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn module_prefix_at_depth(module: &str, depth: usize) -> String {
    module.split('/').take(depth).collect::<Vec<_>>().join("/")
}

#[derive(Debug, Default)]
struct NameOnlyModuleGroupBuilder {
    name_only_count: usize,
    fragile_count: usize,
    modules: BTreeSet<String>,
    max_minified_score: u8,
}

/// Group already-computed name-only selector rows by module path prefix.
///
/// Callers should apply any row filters first. This keeps grouping cheap and
/// source-independent: it is a single pass over the in-memory report rows.
pub fn group_name_only_by_module_depth(
    name_only: &[NameOnlySelector],
    module_prefix_depth: usize,
) -> Vec<NameOnlyModuleGroup> {
    let mut groups = BTreeMap::<String, NameOnlyModuleGroupBuilder>::new();
    for entry in name_only {
        let prefix = module_prefix_at_depth(&entry.module, module_prefix_depth);
        let group = groups.entry(prefix).or_default();
        group.name_only_count += 1;
        group.modules.insert(entry.module.clone());
        group.max_minified_score = group.max_minified_score.max(entry.minified_score);
        if entry.minified_score >= FRAGILE_THRESHOLD {
            group.fragile_count += 1;
        }
    }
    let mut rows: Vec<NameOnlyModuleGroup> = groups
        .into_iter()
        .map(|(module_prefix, group)| NameOnlyModuleGroup {
            module_prefix,
            module_prefix_depth,
            name_only_count: group.name_only_count,
            fragile_count: group.fragile_count,
            module_count: group.modules.len(),
            max_minified_score: group.max_minified_score,
        })
        .collect();
    rows.sort_by(|a, b| {
        b.name_only_count
            .cmp(&a.name_only_count)
            .then_with(|| b.fragile_count.cmp(&a.fragile_count))
            .then_with(|| b.max_minified_score.cmp(&a.max_minified_score))
            .then_with(|| a.module_prefix.cmp(&b.module_prefix))
    });
    rows
}

pub fn populate_name_only_module_groups(
    report: &mut SelectorDebtReport,
    module_prefix_depth: usize,
) {
    report.name_only_module_groups =
        group_name_only_by_module_depth(&report.name_only, module_prefix_depth);
}

/// (module path, readable export name) -> minified `selector.binding.name`.
/// Only members that carry both a readable `name:` and a name-only
/// binding selector can be tracked across spec versions, so only those
/// land in the map.
type DriftMap = BTreeMap<(String, String), String>;

fn collect_drift_map(modules_root: &Path) -> Result<DriftMap> {
    let mut map = DriftMap::new();
    for file in collect_module_files(modules_root)
        .with_context(|| format!("walking {}", modules_root.display()))?
    {
        let module_path = module_path_from_file(&file, modules_root);
        let module = read_module_file(&file)?;
        for member in &module.members {
            let (Some(export_name), Some(binding)) = (&member.name, &member.selector.binding)
            else {
                continue;
            };
            map.insert(
                (module_path.clone(), export_name.clone()),
                binding.name.clone(),
            );
        }
    }
    Ok(map)
}

pub fn compute_selector_debt(
    modules_root: &Path,
    against: Option<&Path>,
) -> Result<SelectorDebtReport> {
    compute_selector_debt_with_source(modules_root, against, None)
}

pub fn compute_selector_debt_with_source(
    modules_root: &Path,
    against: Option<&Path>,
    source_aware: Option<&SourceAwareSelectorDebtConfig<'_>>,
) -> Result<SelectorDebtReport> {
    if source_aware.is_some() {
        return js_ast::with_swc_globals(|| {
            compute_selector_debt_impl(modules_root, against, source_aware)
        });
    }
    compute_selector_debt_impl(modules_root, against, source_aware)
}

fn compute_selector_debt_impl(
    modules_root: &Path,
    against: Option<&Path>,
    source_aware: Option<&SourceAwareSelectorDebtConfig<'_>>,
) -> Result<SelectorDebtReport> {
    let files = collect_module_files(modules_root)
        .with_context(|| format!("walking {}", modules_root.display()))?;

    let mut name_only: Vec<NameOnlySelector> = Vec::new();
    // normalized body -> every occurrence of it.
    let mut by_normalized: BTreeMap<String, Vec<SourceMatchOccurrence>> = BTreeMap::new();
    let mut source_match_total = 0usize;
    let mut current_drift: DriftMap = DriftMap::new();
    let runtime_module = source_aware
        .map(|config| {
            let source = std::fs::read_to_string(config.source_file)
                .with_context(|| format!("reading {}", config.source_file.display()))?;
            js_ast::parse_js_module_ast(&config.source_file.display().to_string(), &source)
                .with_context(|| format!("parsing {}", config.source_file.display()))
        })
        .transpose()?;
    let mut source_aware_checked = 0usize;
    let mut source_aware_unique = 0usize;
    let mut source_aware_near_ambiguous = Vec::new();
    let mut source_aware_exact_by_key =
        BTreeMap::<(String, Vec<usize>), Vec<SourceMatchOccurrence>>::new();
    let mut binding_group_suggestion_candidates = Vec::new();

    for file in &files {
        let module_path = module_path_from_file(file, modules_root);
        let module: ModuleFile = read_module_file(file)?;

        for member in &module.members {
            match member
                .selector
                .selected()
                .with_context(|| format!("module {module_path}: member selector"))?
            {
                MemberSelectorSpec::Binding(binding) => {
                    if let Some(export_name) = &member.name {
                        current_drift.insert(
                            (module_path.clone(), export_name.clone()),
                            binding.name.clone(),
                        );
                    }
                    name_only.push(NameOnlySelector {
                        module: module_path.clone(),
                        minified_score: minified_score(&binding.name),
                        binding_name: binding.name,
                        export_name: member.name.clone(),
                    });
                }
                MemberSelectorSpec::SourceMatch(selector) => {
                    source_match_total += 1;
                    let exact_body_indices = collect_source_aware_debt(
                        &mut source_aware_checked,
                        &mut source_aware_unique,
                        &mut source_aware_near_ambiguous,
                        source_aware,
                        runtime_module.as_ref(),
                        &module_path,
                        SelectorSite::Member,
                        member.name.clone(),
                        &selector,
                    )?;
                    if let Some(candidate) = collect_binding_group_suggestion_candidate(
                        runtime_module.as_ref(),
                        &module_path,
                        member.name.clone(),
                        &selector,
                        exact_body_indices.as_deref(),
                    )? {
                        binding_group_suggestion_candidates.push(candidate);
                    }
                    let normalized = normalize_match(&selector.match_source);
                    let occurrence = SourceMatchOccurrence {
                        module: module_path.clone(),
                        site: SelectorSite::Member,
                        export_name: member.name.clone(),
                        match_source: selector.match_source,
                    };
                    if let Some(exact_body_indices) = exact_body_indices {
                        source_aware_exact_by_key
                            .entry((normalized.clone(), exact_body_indices))
                            .or_default()
                            .push(occurrence.clone());
                    }
                    by_normalized
                        .entry(normalized)
                        .or_default()
                        .push(occurrence);
                }
                MemberSelectorSpec::CrossRef(_) => {
                    // A cross-ref selector is re-minify-proof by construction —
                    // the debt solution, not name-pin debt — so it contributes
                    // nothing to the debt tallies.
                }
            }
        }

        for group in &module.binding_groups {
            source_match_total += 1;
            let selector = group.source_match.selector();
            let exact_body_indices = collect_source_aware_debt(
                &mut source_aware_checked,
                &mut source_aware_unique,
                &mut source_aware_near_ambiguous,
                source_aware,
                runtime_module.as_ref(),
                &module_path,
                SelectorSite::BindingGroup,
                None,
                &selector,
            )?;
            let normalized = normalize_match(&group.source_match.match_source);
            let occurrence = SourceMatchOccurrence {
                module: module_path.clone(),
                site: SelectorSite::BindingGroup,
                export_name: None,
                match_source: group.source_match.match_source.clone(),
            };
            if let Some(exact_body_indices) = exact_body_indices {
                source_aware_exact_by_key
                    .entry((normalized.clone(), exact_body_indices))
                    .or_default()
                    .push(occurrence.clone());
            }
            by_normalized
                .entry(normalized)
                .or_default()
                .push(occurrence);
        }

        for statement in &module.anonymous_statements {
            let selector = statement
                .selector()
                .with_context(|| format!("module {module_path}: anonymous statement selector"))?;
            source_match_total += 1;
            let exact_body_indices = collect_source_aware_debt(
                &mut source_aware_checked,
                &mut source_aware_unique,
                &mut source_aware_near_ambiguous,
                source_aware,
                runtime_module.as_ref(),
                &module_path,
                SelectorSite::AnonymousStatement,
                None,
                &selector,
            )?;
            let normalized = normalize_match(&selector.match_source);
            let occurrence = SourceMatchOccurrence {
                module: module_path.clone(),
                site: SelectorSite::AnonymousStatement,
                export_name: None,
                match_source: selector.match_source,
            };
            if let Some(exact_body_indices) = exact_body_indices {
                source_aware_exact_by_key
                    .entry((normalized.clone(), exact_body_indices))
                    .or_default()
                    .push(occurrence.clone());
            }
            by_normalized
                .entry(normalized)
                .or_default()
                .push(occurrence);
        }
    }

    // Most rebuild-fragile first; ties broken by module then bound name
    // for a stable order.
    name_only.sort_by(|a, b| {
        b.minified_score
            .cmp(&a.minified_score)
            .then_with(|| a.module.cmp(&b.module))
            .then_with(|| a.binding_name.cmp(&b.binding_name))
    });

    let mut repeated_source_match: Vec<RepeatedSourceMatch> = by_normalized
        .into_iter()
        .filter(|(_, occurrences)| occurrences.len() >= 2)
        .map(|(normalized, mut occurrences)| {
            occurrences.sort_by(|a, b| {
                a.module
                    .cmp(&b.module)
                    .then_with(|| a.site.cmp(&b.site))
                    .then_with(|| a.export_name.cmp(&b.export_name))
            });
            RepeatedSourceMatch {
                normalized,
                occurrences,
            }
        })
        .collect();
    repeated_source_match.sort_by(|a, b| {
        b.occurrences
            .len()
            .cmp(&a.occurrences.len())
            .then_with(|| a.normalized.cmp(&b.normalized))
    });

    let mut source_aware_repeated_exact: Vec<SourceAwareRepeatedExactSourceMatch> =
        source_aware_exact_by_key
            .into_iter()
            .filter(|(_, occurrences)| occurrences.len() >= 2)
            .map(|((normalized, exact_body_indices), mut occurrences)| {
                sort_occurrences(&mut occurrences);
                SourceAwareRepeatedExactSourceMatch {
                    normalized,
                    exact_body_indices,
                    occurrences,
                }
            })
            .collect();
    source_aware_repeated_exact.sort_by(|a, b| {
        b.occurrences
            .len()
            .cmp(&a.occurrences.len())
            .then_with(|| a.normalized.cmp(&b.normalized))
            .then_with(|| a.exact_body_indices.cmp(&b.exact_body_indices))
    });

    let drifted_bindings = match against {
        None => Vec::new(),
        Some(against_root) => {
            let against_drift = collect_drift_map(against_root)?;
            let mut drifted: Vec<DriftedBinding> = current_drift
                .iter()
                .filter_map(|((module, export_name), current_binding)| {
                    let previous = against_drift.get(&(module.clone(), export_name.clone()))?;
                    (previous != current_binding).then(|| DriftedBinding {
                        module: module.clone(),
                        export_name: export_name.clone(),
                        previous_binding: previous.clone(),
                        current_binding: current_binding.clone(),
                    })
                })
                .collect();
            drifted.sort_by(|a, b| {
                a.module
                    .cmp(&b.module)
                    .then_with(|| a.export_name.cmp(&b.export_name))
            });
            drifted
        }
    };
    let source_aware_binding_group_suggestions =
        collect_binding_group_suggestions(binding_group_suggestion_candidates);
    let source_aware_binding_group_suggested_selectors = source_aware_binding_group_suggestions
        .iter()
        .map(|group| group.selectors.len())
        .sum();

    let summary = SelectorDebtSummary {
        name_only_total: name_only.len(),
        name_only_fragile: name_only
            .iter()
            .filter(|n| n.minified_score >= FRAGILE_THRESHOLD)
            .count(),
        source_match_total,
        repeated_source_match_groups: repeated_source_match.len(),
        drifted_binding_total: drifted_bindings.len(),
        source_aware_checked,
        source_aware_unique,
        source_aware_near_ambiguous: source_aware_near_ambiguous.len(),
        source_aware_repeated_exact: source_aware_repeated_exact.len(),
        source_aware_binding_group_suggestions: source_aware_binding_group_suggestions.len(),
        source_aware_binding_group_suggested_selectors,
    };

    Ok(SelectorDebtReport {
        name_only,
        repeated_source_match,
        drifted_bindings,
        source_aware_near_ambiguous,
        source_aware_repeated_exact,
        source_aware_binding_group_suggestions,
        name_only_module_groups: Vec::new(),
        summary,
    })
}

fn sort_occurrences(occurrences: &mut [SourceMatchOccurrence]) {
    occurrences.sort_by(|a, b| {
        a.module
            .cmp(&b.module)
            .then_with(|| a.site.cmp(&b.site))
            .then_with(|| a.export_name.cmp(&b.export_name))
    });
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
struct BindingGroupSuggestionKey {
    module: String,
    body_idx: usize,
    selector_key: String,
}

#[derive(Debug, Clone)]
struct BindingGroupSuggestionCandidate {
    key: BindingGroupSuggestionKey,
    module: String,
    export_name: Option<String>,
    target_binding: String,
    declarator_idx: usize,
    declarator: VarDeclarator,
    declaration_kind: VarDeclKind,
    identifiers: spec::SourceMatchIdentifierMode,
    wildcard_string_literals: Vec<String>,
}

fn collect_binding_group_suggestion_candidate(
    runtime_module: Option<&SwcModule>,
    module_path: &str,
    export_name: Option<String>,
    selector: &AnonymousStatementSelector,
    exact_body_indices: Option<&[usize]>,
) -> Result<Option<BindingGroupSuggestionCandidate>> {
    let (Some(runtime_module), Some([body_idx])) = (runtime_module, exact_body_indices) else {
        return Ok(None);
    };
    let Some(runtime_var) = runtime_module
        .body
        .get(*body_idx)
        .and_then(module_item_var_decl)
    else {
        return Ok(None);
    };
    if runtime_var.decls.len() < 2 {
        return Ok(None);
    }
    let Some(target_binding) = selector.target_binding.as_deref() else {
        return Ok(None);
    };
    let parsed = js_ast::parse_js_module_ast(
        "<member source_match consolidation>",
        &selector.match_source,
    )
    .with_context(
        || "parsing member source_match while building selector-debt binding group suggestion",
    )?;
    let [needle] = parsed.body.as_slice() else {
        return Ok(None);
    };
    let Some(needle_var) = module_item_var_decl(needle) else {
        return Ok(None);
    };
    if needle_var.decls.len() < 2 {
        return Ok(None);
    }
    let Some((declarator_idx, declarator)) = selector_target_declarator(needle_var, target_binding)
    else {
        return Ok(None);
    };
    Ok(Some(BindingGroupSuggestionCandidate {
        key: BindingGroupSuggestionKey {
            module: module_path.to_owned(),
            body_idx: *body_idx,
            selector_key: selector_group_key(selector),
        },
        module: module_path.to_owned(),
        export_name,
        target_binding: target_binding.to_owned(),
        declarator_idx,
        declarator: declarator.clone(),
        declaration_kind: needle_var.kind,
        identifiers: selector.identifiers,
        wildcard_string_literals: selector.wildcard_string_literals.iter().cloned().collect(),
    }))
}

fn collect_binding_group_suggestions(
    candidates: Vec<BindingGroupSuggestionCandidate>,
) -> Vec<SourceAwareBindingGroupSuggestion> {
    let mut by_key =
        BTreeMap::<BindingGroupSuggestionKey, Vec<BindingGroupSuggestionCandidate>>::new();
    for candidate in candidates {
        by_key
            .entry(candidate.key.clone())
            .or_default()
            .push(candidate);
    }
    let mut groups = by_key
        .into_values()
        .filter(|candidates| candidates.len() >= 2)
        .map(build_binding_group_suggestion)
        .collect::<Vec<_>>();
    groups.sort_by(|a, b| {
        b.selectors
            .len()
            .cmp(&a.selectors.len())
            .then_with(|| a.body_idx.cmp(&b.body_idx))
            .then_with(|| a.declaration_kind.cmp(&b.declaration_kind))
            .then_with(|| a.module.cmp(&b.module))
    });
    groups
}

fn build_binding_group_suggestion(
    mut candidates: Vec<BindingGroupSuggestionCandidate>,
) -> SourceAwareBindingGroupSuggestion {
    candidates.sort_by(|a, b| {
        a.declarator_idx
            .cmp(&b.declarator_idx)
            .then_with(|| a.module.cmp(&b.module))
            .then_with(|| a.export_name.cmp(&b.export_name))
    });
    let first = &candidates[0];
    let match_source = render_var_source_match_template(first.declaration_kind, &candidates);
    let selectors = candidates
        .iter()
        .map(|candidate| SourceMatchBindingGroupSelector {
            module: candidate.module.clone(),
            export_name: candidate.export_name.clone(),
            target_binding: candidate.target_binding.clone(),
            declarator_idx: candidate.declarator_idx,
        })
        .collect::<Vec<_>>();
    let candidate_yaml = render_binding_group_candidate_yaml(
        &selectors,
        &match_source,
        first.identifiers,
        &first.wildcard_string_literals,
    );
    SourceAwareBindingGroupSuggestion {
        module: first.key.module.clone(),
        body_idx: first.key.body_idx,
        declaration_kind: var_decl_kind_label(first.declaration_kind).to_string(),
        selectors,
        candidate_yaml,
    }
}

fn selector_group_key(selector: &AnonymousStatementSelector) -> String {
    format!(
        "{:?}\0{:?}\0{}",
        selector.identifiers,
        selector.wildcard_string_literals,
        normalize_match(&selector.match_source),
    )
}

fn selector_target_declarator<'a>(
    var: &'a VarDecl,
    target_binding: &str,
) -> Option<(usize, &'a VarDeclarator)> {
    var.decls.iter().enumerate().find(|(_, declarator)| {
        simple_declarator_binding_name(declarator).as_deref() == Some(target_binding)
    })
}

fn render_var_source_match_template(
    kind: VarDeclKind,
    targets: &[BindingGroupSuggestionCandidate],
) -> String {
    let mut lines = vec![format!(
        "{} DECLARATORS_BEFORE = null,",
        var_decl_kind_label(kind)
    )];
    let mut previous_declarator_idx = None;
    for (target_idx, target) in targets.iter().enumerate() {
        if let Some(previous) = previous_declarator_idx
            && target.declarator_idx > previous + 1
        {
            lines.push(format!("  DECLARATORS_BETWEEN_{target_idx} = null,"));
        }
        let initializer = selector_initializer_template(
            &target.target_binding,
            target.declarator.init.as_deref(),
        );
        lines.push(format!("  {} = {initializer},", target.target_binding));
        previous_declarator_idx = Some(target.declarator_idx);
    }
    lines.push("  DECLARATORS_AFTER = null;".to_string());
    lines.join("\n")
}

fn render_binding_group_candidate_yaml(
    selectors: &[SourceMatchBindingGroupSelector],
    match_source: &str,
    identifiers: spec::SourceMatchIdentifierMode,
    wildcard_string_literals: &[String],
) -> String {
    let mut lines = vec![
        "binding_groups:".to_string(),
        "  - source_match:".to_string(),
    ];
    if identifiers != spec::SourceMatchIdentifierMode::Exact {
        lines.push(format!(
            "      identifiers: {}",
            source_match_identifier_mode_label(identifiers),
        ));
    }
    if !wildcard_string_literals.is_empty() {
        lines.push(format!(
            "      wildcard_string_literals: [{}]",
            wildcard_string_literals
                .iter()
                .map(|value| yaml_single_quoted(value))
                .collect::<Vec<_>>()
                .join(", "),
        ));
    }
    lines.push("      match: |".to_string());
    lines.extend(indent_lines(match_source, 8));
    lines.push("    exports:".to_string());
    for selector in selectors {
        let export_name = selector
            .export_name
            .as_deref()
            .unwrap_or(selector.target_binding.as_str());
        lines.push(format!(
            "      {}: {}",
            selector.target_binding, export_name
        ));
    }
    lines.join("\n")
}

fn indent_lines(source: &str, spaces: usize) -> Vec<String> {
    let prefix = " ".repeat(spaces);
    source
        .lines()
        .map(|line| format!("{prefix}{line}"))
        .collect()
}

fn selector_initializer_template(selector_local_name: &str, init: Option<&Expr>) -> String {
    match init {
        Some(Expr::Lit(Lit::Str(value))) => format!(
            "STR_LITERAL_MATCHING_RE(\"^{}$\")",
            js_string_escape(&regex_escape(&value.value.to_string_lossy()))
        ),
        Some(Expr::Lit(Lit::Bool(value))) => value.value.to_string(),
        Some(Expr::Lit(Lit::Null(_))) => "null".to_string(),
        Some(Expr::Lit(Lit::Num(value))) => value.value.to_string(),
        Some(_) => format!("EXPR_{selector_local_name}"),
        None => format!("EXPR_{selector_local_name}"),
    }
}

fn regex_escape(value: &str) -> String {
    let mut escaped = String::new();
    for ch in value.chars() {
        if matches!(
            ch,
            '\\' | '.' | '+' | '*' | '?' | '(' | ')' | '|' | '[' | ']' | '{' | '}' | '^' | '$'
        ) {
            escaped.push('\\');
        }
        escaped.push(ch);
    }
    escaped
}

fn js_string_escape(value: &str) -> String {
    let mut escaped = String::new();
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            c if c.is_control() => escaped.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => escaped.push(c),
        }
    }
    escaped
}

fn yaml_single_quoted(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn source_match_identifier_mode_label(mode: spec::SourceMatchIdentifierMode) -> &'static str {
    match mode {
        spec::SourceMatchIdentifierMode::Exact => "exact",
        spec::SourceMatchIdentifierMode::AlphaAll => "alpha_all",
    }
}

fn module_item_var_decl(item: &ModuleItem) -> Option<&VarDecl> {
    match item {
        ModuleItem::Stmt(Stmt::Decl(swc_ecma_ast::Decl::Var(var))) => Some(var),
        ModuleItem::ModuleDecl(ModuleDecl::ExportDecl(export)) => match &export.decl {
            swc_ecma_ast::Decl::Var(var) => Some(var),
            _ => None,
        },
        _ => None,
    }
}

fn simple_declarator_binding_name(declarator: &VarDeclarator) -> Option<String> {
    match &declarator.name {
        Pat::Ident(ident) => Some(ident.id.sym.to_string()),
        _ => None,
    }
}

fn var_decl_kind_label(kind: VarDeclKind) -> &'static str {
    match kind {
        VarDeclKind::Var => "var",
        VarDeclKind::Let => "let",
        VarDeclKind::Const => "const",
    }
}

#[allow(clippy::too_many_arguments)]
fn collect_source_aware_debt(
    checked: &mut usize,
    unique: &mut usize,
    rows: &mut Vec<SourceAwareStructuralSelector>,
    config: Option<&SourceAwareSelectorDebtConfig<'_>>,
    runtime_module: Option<&swc_ecma_ast::Module>,
    module_path: &str,
    site: SelectorSite,
    export_name: Option<String>,
    selector: &AnonymousStatementSelector,
) -> Result<Option<Vec<usize>>> {
    let (Some(config), Some(runtime_module)) = (config, runtime_module) else {
        return Ok(None);
    };
    *checked += 1;
    let debt = source_match::source_match_body_debt(
        runtime_module,
        module_path,
        selector,
        config.near_match_min_score,
        config.near_match_limit,
    )?;
    let [exact_group] = debt.exact_groups.as_slice() else {
        return Ok(None);
    };
    *unique += 1;
    let exact_body_indices = exact_group.iter().flatten().copied().collect::<Vec<_>>();
    if exact_body_indices.is_empty() {
        return Ok(None);
    }
    if debt.near_misses.is_empty() {
        return Ok(Some(exact_body_indices));
    }
    rows.push(SourceAwareStructuralSelector {
        module: module_path.to_owned(),
        site,
        export_name,
        exact_body_indices: exact_body_indices.clone(),
        near_misses: debt
            .near_misses
            .into_iter()
            .map(|near| SourceAwareNearMiss {
                body_idx: near.body_idx,
                declared_bindings: near.declared_bindings,
                score: near.score,
                reason: near.reason,
            })
            .collect(),
    });
    Ok(Some(exact_body_indices))
}

/// Compact two-section-plus-summary text rendering.
pub fn render_selector_debt_text(report: &SelectorDebtReport, out: &mut String) {
    let s = &report.summary;
    out.push_str(&format!(
        "name-only selectors: {} ({} fragile)  source_match: {} ({} repeated group(s))  drifted: {}  source-aware near-ambiguous: {}/{} unique checked  source-aware repeated exact: {}  source-aware binding_groups suggestions: {} selector(s) in {} group(s)\n",
        s.name_only_total,
        s.name_only_fragile,
        s.source_match_total,
        s.repeated_source_match_groups,
        s.drifted_binding_total,
        s.source_aware_near_ambiguous,
        s.source_aware_unique,
        s.source_aware_repeated_exact,
        s.source_aware_binding_group_suggested_selectors,
        s.source_aware_binding_group_suggestions,
    ));

    if !report.name_only_module_groups.is_empty() {
        out.push_str("name-only groups by module prefix:\n");
        for group in &report.name_only_module_groups {
            out.push_str(&format!(
                "  {:>4} selector(s)  {:>4} fragile  {:>4} module(s)  max={}  depth={}  {}\n",
                group.name_only_count,
                group.fragile_count,
                group.module_count,
                group.max_minified_score,
                group.module_prefix_depth,
                group.module_prefix,
            ));
        }
    }

    if !report.name_only.is_empty() {
        out.push_str("name-only (most fragile first):\n");
        for entry in &report.name_only {
            let readable = entry.export_name.as_deref().unwrap_or("-");
            out.push_str(&format!(
                "  {:>3}  {}  {}  [{}]\n",
                entry.minified_score, entry.binding_name, entry.module, readable,
            ));
        }
    }

    if !report.repeated_source_match.is_empty() {
        out.push_str("repeated source_match bodies:\n");
        for group in &report.repeated_source_match {
            out.push_str(&format!(
                "  {}x  {}\n",
                group.occurrences.len(),
                group.normalized,
            ));
            for occurrence in &group.occurrences {
                out.push_str(&format!(
                    "      {:?} {}\n",
                    occurrence.site, occurrence.module,
                ));
            }
        }
    }

    if !report.drifted_bindings.is_empty() {
        out.push_str("drifted minified bindings:\n");
        for drift in &report.drifted_bindings {
            out.push_str(&format!(
                "  {} ({})  {} -> {}\n",
                drift.export_name, drift.module, drift.previous_binding, drift.current_binding,
            ));
        }
    }

    if !report.source_aware_near_ambiguous.is_empty() {
        out.push_str("source-aware near-ambiguous structural selectors:\n");
        for selector in &report.source_aware_near_ambiguous {
            let readable = selector.export_name.as_deref().unwrap_or("-");
            out.push_str(&format!(
                "  {:?} {} [{}] exact={:?}\n",
                selector.site, selector.module, readable, selector.exact_body_indices,
            ));
            for near in &selector.near_misses {
                let declared = if near.declared_bindings.is_empty() {
                    "-".to_owned()
                } else {
                    near.declared_bindings.join(",")
                };
                out.push_str(&format!(
                    "      score={} body={} declared=[{}] {}\n",
                    near.score, near.body_idx, declared, near.reason,
                ));
            }
        }
    }

    if !report.source_aware_repeated_exact.is_empty() {
        out.push_str("source-aware repeated exact structural selectors:\n");
        for group in &report.source_aware_repeated_exact {
            out.push_str(&format!(
                "  {}x exact={:?}  {}\n",
                group.occurrences.len(),
                group.exact_body_indices,
                group.normalized,
            ));
            for occurrence in &group.occurrences {
                let readable = occurrence.export_name.as_deref().unwrap_or("-");
                out.push_str(&format!(
                    "      {:?} {} [{}]\n",
                    occurrence.site, occurrence.module, readable,
                ));
            }
        }
    }

    if !report.source_aware_binding_group_suggestions.is_empty() {
        out.push_str("source-aware binding_groups suggestions:\n");
        for group in &report.source_aware_binding_group_suggestions {
            out.push_str(&format!(
                "  {} body={} kind={} selectors={}\n",
                group.module,
                group.body_idx,
                group.declaration_kind,
                group.selectors.len(),
            ));
            for selector in &group.selectors {
                let readable = selector.export_name.as_deref().unwrap_or("-");
                out.push_str(&format!(
                    "      target_binding={} [{}] {} decl#{}\n",
                    selector.target_binding, readable, selector.module, selector.declarator_idx,
                ));
            }
            out.push_str("      candidate:\n");
            for line in group.candidate_yaml.lines() {
                out.push_str(&format!("        {line}\n"));
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn write(root: &Path, rel: &str, body: &str) {
        let p = root.join(rel);
        fs::create_dir_all(p.parent().unwrap()).unwrap();
        fs::write(p, body).unwrap();
    }

    #[test]
    fn minified_score_ranks_short_and_vowelless_above_words() {
        // Single/double-char tokens are maximal; readable words are zero.
        assert_eq!(minified_score("a"), 100);
        assert_eq!(minified_score("$"), 100);
        assert_eq!(minified_score("aQ"), 90);
        assert!(minified_score("XOe") >= FRAGILE_THRESHOLD);
        // A vowel-less 3-char beats a voweled 3-char.
        assert!(minified_score("Rng") > minified_score("XOe"));
        // Real words score zero regardless of length / single vowel.
        assert_eq!(minified_score("registry"), 0);
        assert_eq!(minified_score("parseConfig"), 0);
        assert_eq!(minified_score("Test"), 0);
        assert_eq!(minified_score("List"), 0);
        // Longer consonant soup is still flagged.
        assert!(minified_score("wXyz") >= FRAGILE_THRESHOLD);
    }

    #[test]
    fn name_only_selectors_ranked_most_fragile_first() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "ui/widgets.yaml",
            "members:\n  - name: WidgetRegistry\n    selector: { binding: { name: registry } }\n  - selector: { binding: { name: a } }\n",
        );
        let report = compute_selector_debt(root, None).unwrap();
        assert_eq!(report.summary.name_only_total, 2);
        assert_eq!(report.summary.name_only_fragile, 1);
        // `a` (score 100) ranks before `registry` (score 0).
        assert_eq!(report.name_only[0].binding_name, "a");
        assert_eq!(report.name_only[0].minified_score, 100);
        assert_eq!(report.name_only[1].binding_name, "registry");
        assert_eq!(
            report.name_only[1].export_name.as_deref(),
            Some("WidgetRegistry")
        );
    }

    #[test]
    fn name_only_module_groups_use_filtered_rows_and_prefix_depth() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "app/panel/core.yaml",
            "members:\n  - name: PanelEntry\n    selector: { binding: { name: a } }\n  - name: ReadablePanelEntry\n    selector: { binding: { name: readableName } }\n",
        );
        write(
            root,
            "app/panel/menu.yaml",
            "members:\n  - name: PanelMenu\n    selector: { binding: { name: bQ } }\n",
        );
        write(
            root,
            "app/search/index.yaml",
            "members:\n  - name: SearchEntry\n    selector: { binding: { name: sRx } }\n",
        );
        write(
            root,
            "runtime/init.yaml",
            "members:\n  - name: Startup\n    selector: { binding: { name: c } }\n",
        );

        let mut report = compute_selector_debt(root, None).unwrap();
        report
            .name_only
            .retain(|entry| entry.minified_score >= FRAGILE_THRESHOLD);
        populate_name_only_module_groups(&mut report, 2);
        // Detail limits should not change the already-derived group counts.
        report.name_only.truncate(1);

        assert_eq!(report.name_only_module_groups.len(), 3);
        assert_eq!(report.name_only_module_groups[0].module_prefix, "app/panel");
        assert_eq!(report.name_only_module_groups[0].module_prefix_depth, 2);
        assert_eq!(report.name_only_module_groups[0].name_only_count, 2);
        assert_eq!(report.name_only_module_groups[0].fragile_count, 2);
        assert_eq!(report.name_only_module_groups[0].module_count, 2);
        assert_eq!(report.name_only_module_groups[0].max_minified_score, 100);
        assert_eq!(
            report.name_only_module_groups[1].module_prefix,
            "runtime/init"
        );
        assert_eq!(
            report.name_only_module_groups[2].module_prefix,
            "app/search"
        );

        let mut text = String::new();
        render_selector_debt_text(&report, &mut text);
        assert!(text.contains("name-only groups by module prefix:"));
        assert!(
            text.contains(
                "2 selector(s)     2 fragile     2 module(s)  max=100  depth=2  app/panel"
            )
        );
        assert!(!text.contains("readableName"));
    }

    #[test]
    fn default_json_omits_name_only_module_groups() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "app/panel/core.yaml",
            "members:\n  - name: PanelEntry\n    selector: { binding: { name: a } }\n",
        );

        let json = serde_json::to_string(&compute_selector_debt(root, None).unwrap()).unwrap();

        assert!(!json.contains("name_only_module_groups"));
    }

    #[test]
    fn repeated_source_match_bodies_grouped_across_sites() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        // Same decorator-helper body copied into a member source_match
        // and an anonymous statement, modulo whitespace.
        write(
            root,
            "a.yaml",
            "members:\n  - name: Foo\n    selector:\n      source_match:\n        target_binding: x\n        match: 'var x = decorate(y);'\n",
        );
        write(
            root,
            "b.yaml",
            "anonymous_statements:\n  - match: |\n      var   x =   decorate(y);\n",
        );
        // A body that appears only once must not be reported.
        write(
            root,
            "c.yaml",
            "anonymous_statements:\n  - match: 'register(z);'\n",
        );
        let report = compute_selector_debt(root, None).unwrap();
        assert_eq!(report.summary.source_match_total, 3);
        assert_eq!(report.repeated_source_match.len(), 1);
        let group = &report.repeated_source_match[0];
        assert_eq!(group.normalized, "var x = decorate(y);");
        assert_eq!(group.occurrences.len(), 2);
        assert_eq!(group.occurrences[0].site, SelectorSite::Member);
        assert_eq!(group.occurrences[1].site, SelectorSite::AnonymousStatement);
    }

    #[test]
    fn drift_detected_only_when_minified_binding_changes_under_stable_name() {
        let dir = TempDir::new().unwrap();
        let current = dir.path().join("current");
        let against = dir.path().join("against");
        // `Foo`'s minified binding moved XOe -> XPq; `Bar` is unchanged.
        write(
            &current,
            "m.yaml",
            "members:\n  - name: Foo\n    selector: { binding: { name: XPq } }\n  - name: Bar\n    selector: { binding: { name: YY } }\n",
        );
        write(
            &against,
            "m.yaml",
            "members:\n  - name: Foo\n    selector: { binding: { name: XOe } }\n  - name: Bar\n    selector: { binding: { name: YY } }\n",
        );
        let report = compute_selector_debt(&current, Some(&against)).unwrap();
        assert_eq!(report.summary.drifted_binding_total, 1);
        let drift = &report.drifted_bindings[0];
        assert_eq!(drift.export_name, "Foo");
        assert_eq!(drift.previous_binding, "XOe");
        assert_eq!(drift.current_binding, "XPq");
    }

    #[test]
    fn drift_section_empty_without_against() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "m.yaml",
            "members:\n  - name: Foo\n    selector: { binding: { name: XOe } }\n",
        );
        let report = compute_selector_debt(root, None).unwrap();
        assert!(report.drifted_bindings.is_empty());
        assert_eq!(report.summary.drifted_binding_total, 0);
    }

    #[test]
    fn source_aware_mode_reports_unique_selector_with_near_matching_sibling() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "classes.yaml",
            "members:\n  - name: PickedClass\n    selector:\n      source_match:\n        identifiers: alpha_all\n        match: |\n          class PickedClass {\n            important() {\n              return 1;\n            }\n          }\n",
        );
        let source_file = root.join("chunk.js");
        fs::write(
            &source_file,
            "class a { important() { return 1; } }\nclass b { important() { return 2; } }\n",
        )
        .unwrap();
        let config = SourceAwareSelectorDebtConfig {
            source_file: &source_file,
            near_match_min_score: 55,
            near_match_limit: 3,
        };

        let report = compute_selector_debt_with_source(root, None, Some(&config)).unwrap();

        assert_eq!(report.summary.source_aware_checked, 1);
        assert_eq!(report.summary.source_aware_unique, 1);
        assert_eq!(report.summary.source_aware_near_ambiguous, 1);
        let row = &report.source_aware_near_ambiguous[0];
        assert_eq!(row.module, "classes");
        assert_eq!(row.site, SelectorSite::Member);
        assert_eq!(row.export_name.as_deref(), Some("PickedClass"));
        assert_eq!(row.exact_body_indices, vec![0]);
        assert_eq!(row.near_misses.len(), 1);
        assert_eq!(row.near_misses[0].body_idx, 1);
        assert_eq!(row.near_misses[0].declared_bindings, vec!["b".to_owned()]);
    }

    #[test]
    fn source_aware_mode_does_not_report_ambiguous_exact_matches_as_unique_near_misses() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "classes.yaml",
            "members:\n  - name: PickedClass\n    selector:\n      source_match:\n        identifiers: alpha_all\n        match: |\n          class PickedClass {\n            important() {\n              return 1;\n            }\n          }\n",
        );
        let source_file = root.join("chunk.js");
        fs::write(
            &source_file,
            "class a { important() { return 1; } }\nclass b { important() { return 1; } }\n",
        )
        .unwrap();
        let config = SourceAwareSelectorDebtConfig {
            source_file: &source_file,
            near_match_min_score: 55,
            near_match_limit: 3,
        };

        let report = compute_selector_debt_with_source(root, None, Some(&config)).unwrap();

        assert_eq!(report.summary.source_aware_checked, 1);
        assert_eq!(report.summary.source_aware_unique, 0);
        assert_eq!(report.summary.source_aware_near_ambiguous, 0);
        assert!(report.source_aware_near_ambiguous.is_empty());
    }

    #[test]
    fn source_aware_mode_reports_repeated_exact_body_index_matches() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        let selector = "members:\n  - name: SelectedFormatter\n    selector:\n      source_match:\n        identifiers: alpha_all\n        match: |\n          function selectedFormatter(value) {\n            return value.trim().toUpperCase();\n          }\n";
        write(root, "format/primary.yaml", selector);
        write(root, "format/duplicate.yaml", selector);
        let source_file = root.join("chunk.js");
        fs::write(
            &source_file,
            "function runtimeFormatter(value) { return value.trim().toUpperCase(); }\n\
             function otherFormatter(value) { return value.trim().toLowerCase(); }\n",
        )
        .unwrap();
        let config = SourceAwareSelectorDebtConfig {
            source_file: &source_file,
            near_match_min_score: 55,
            near_match_limit: 3,
        };

        let report = compute_selector_debt_with_source(root, None, Some(&config)).unwrap();

        assert_eq!(report.summary.source_match_total, 2);
        assert_eq!(report.summary.repeated_source_match_groups, 1);
        assert_eq!(report.summary.source_aware_checked, 2);
        assert_eq!(report.summary.source_aware_unique, 2);
        assert_eq!(report.summary.source_aware_repeated_exact, 1);
        let group = &report.source_aware_repeated_exact[0];
        assert_eq!(group.exact_body_indices, vec![0]);
        assert_eq!(group.occurrences.len(), 2);
        assert_eq!(group.occurrences[0].module, "format/duplicate");
        assert_eq!(group.occurrences[1].module, "format/primary");

        let mut text = String::new();
        render_selector_debt_text(&report, &mut text);
        assert!(text.contains("source-aware repeated exact: 1"));
        assert!(text.contains("source-aware repeated exact structural selectors:"));
        assert!(text.contains("2x exact=[0]"));
    }

    #[test]
    fn source_aware_mode_suggests_binding_group_for_repeated_multideclarator_member_selectors() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "styles.yaml",
            r#"members:
  - name: PrimaryStyle
    selector:
      source_match:
        identifiers: alpha_all
        target_binding: primaryStyle
        match: |
          const primaryStyle = "WidgetShell-42",
            ignoredValue = EXPR_IGNORED,
            secondaryReader = computeReader(EXPR_INPUT);
  - name: SecondaryReader
    selector:
      source_match:
        identifiers: alpha_all
        target_binding: secondaryReader
        match: |
          const primaryStyle = "WidgetShell-42",
            ignoredValue = EXPR_IGNORED,
            secondaryReader = computeReader(EXPR_INPUT);
"#,
        );
        let source_file = root.join("chunk.js");
        fs::write(
            &source_file,
            r#"const a = "WidgetShell-42", b = makeIgnored(), c = computeReader(1);
const stableName = 1;
"#,
        )
        .unwrap();
        let config = SourceAwareSelectorDebtConfig {
            source_file: &source_file,
            near_match_min_score: 55,
            near_match_limit: 3,
        };

        let report = compute_selector_debt_with_source(root, None, Some(&config)).unwrap();

        assert_eq!(report.summary.source_match_total, 2);
        assert_eq!(report.summary.source_aware_checked, 2);
        assert_eq!(report.summary.source_aware_unique, 2);
        assert_eq!(report.summary.source_aware_binding_group_suggestions, 1);
        assert_eq!(
            report
                .summary
                .source_aware_binding_group_suggested_selectors,
            2,
        );
        let group = &report.source_aware_binding_group_suggestions[0];
        assert_eq!(group.module, "styles");
        assert_eq!(group.body_idx, 0);
        assert_eq!(group.declaration_kind, "const");
        assert_eq!(group.selectors.len(), 2);
        assert_eq!(group.selectors[0].target_binding, "primaryStyle");
        assert_eq!(
            group.selectors[0].export_name.as_deref(),
            Some("PrimaryStyle")
        );
        assert_eq!(group.selectors[0].declarator_idx, 0);
        assert_eq!(group.selectors[1].target_binding, "secondaryReader");
        assert_eq!(
            group.selectors[1].export_name.as_deref(),
            Some("SecondaryReader")
        );
        assert_eq!(group.selectors[1].declarator_idx, 2);
        assert!(group.candidate_yaml.contains("binding_groups:"));
        assert!(group.candidate_yaml.contains("identifiers: alpha_all"));
        assert!(
            group
                .candidate_yaml
                .contains("const DECLARATORS_BEFORE = null,")
        );
        assert!(
            group
                .candidate_yaml
                .contains("DECLARATORS_BETWEEN_1 = null,")
        );
        assert!(group.candidate_yaml.contains("DECLARATORS_AFTER = null;"));
        assert!(group.candidate_yaml.contains("primaryStyle: PrimaryStyle"));
        assert!(
            group
                .candidate_yaml
                .contains("secondaryReader: SecondaryReader")
        );
        assert!(
            group
                .candidate_yaml
                .contains("STR_LITERAL_MATCHING_RE(\"^WidgetShell-42$\")")
        );
        assert!(
            group
                .candidate_yaml
                .contains("secondaryReader = EXPR_secondaryReader")
        );

        let mut text = String::new();
        render_selector_debt_text(&report, &mut text);
        assert!(
            text.contains("source-aware binding_groups suggestions: 2 selector(s) in 1 group(s)")
        );
        assert!(text.contains("source-aware binding_groups suggestions:"));
        assert!(text.contains("styles body=0 kind=const selectors=2"));
        assert!(text.contains("target_binding=primaryStyle [PrimaryStyle] styles decl#0"));
    }

    #[test]
    fn source_aware_mode_keeps_binding_group_suggestions_same_module() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        let first_selector = r#"members:
  - name: PrimaryStyle
    selector:
      source_match:
        identifiers: alpha_all
        target_binding: primaryStyle
        match: |
          const primaryStyle = "WidgetShell-42",
            secondaryReader = computeReader(EXPR_INPUT);
"#;
        let second_selector = r#"members:
  - name: SecondaryReader
    selector:
      source_match:
        identifiers: alpha_all
        target_binding: secondaryReader
        match: |
          const primaryStyle = "WidgetShell-42",
            secondaryReader = computeReader(EXPR_INPUT);
"#;
        write(root, "styles/primary.yaml", first_selector);
        write(root, "readers/secondary.yaml", second_selector);
        let source_file = root.join("chunk.js");
        fs::write(
            &source_file,
            r#"const a = "WidgetShell-42", c = computeReader(1);
"#,
        )
        .unwrap();
        let config = SourceAwareSelectorDebtConfig {
            source_file: &source_file,
            near_match_min_score: 55,
            near_match_limit: 3,
        };

        let report = compute_selector_debt_with_source(root, None, Some(&config)).unwrap();

        assert_eq!(report.summary.source_aware_binding_group_suggestions, 0);
        assert!(report.source_aware_binding_group_suggestions.is_empty());
    }

    #[test]
    fn source_aware_mode_skips_single_member_multideclarator_source_match_suggestions() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "values.yaml",
            r#"members:
  - name: SelectedValue
    selector:
      source_match:
        identifiers: alpha_all
        target_binding: selectedValue
        match: |
          let skippedValue = EXPR_SKIPPED,
            selectedValue = computeValue();
"#,
        );
        let source_file = root.join("chunk.js");
        fs::write(&source_file, "let p = ignored(), q = computeValue();\n").unwrap();
        let config = SourceAwareSelectorDebtConfig {
            source_file: &source_file,
            near_match_min_score: 55,
            near_match_limit: 3,
        };

        let report = compute_selector_debt_with_source(root, None, Some(&config)).unwrap();

        assert_eq!(report.summary.source_aware_binding_group_suggestions, 0,);
        assert!(report.source_aware_binding_group_suggestions.is_empty());
    }

    #[test]
    fn deterministic_same_spec_same_output() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "a.yaml",
            "members:\n  - selector: { binding: { name: a } }\n  - selector: { binding: { name: bQ } }\n",
        );
        write(
            root,
            "b/c.yaml",
            "anonymous_statements:\n  - match: 'foo();'\n",
        );
        let j1 = serde_json::to_string(&compute_selector_debt(root, None).unwrap()).unwrap();
        let j2 = serde_json::to_string(&compute_selector_debt(root, None).unwrap()).unwrap();
        assert_eq!(j1, j2);
    }
}
