//! OR-Tools CP-SAT implementation of the selector backend contract.
//!
//! The Rust side owns the backend-neutral `CompiledSelectorProblem`; the C++
//! sidecar owns OR-Tools. Both sides share `selector_cp_sat.proto`, with Rust
//! bindings generated by `rules_rust`/Prost.

use std::collections::BTreeMap;
use std::error::Error;
use std::fmt;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus, Stdio};
use std::sync::atomic::{AtomicUsize, Ordering};

use prost::Message;
use selector_constraint_backend::{
    AllDifferentReason, BinaryConstraintKind, ConstraintVariableId, TargetBindingProjection,
};
use selector_constraint_backend::{
    BackendAssignment, BackendAssignmentCoverage, BackendSolveResult, BackendSolveStatus,
    BackendValueId, BackendVariableAssignment, CompiledAllDifferentConstraint,
    CompiledAllowedTupleConstraint, CompiledBinaryConstraint, CompiledSelectorProblem,
    CompiledVariable, CompiledVariableDomain, SelectorProblemBackend, TargetProjection,
};
use selector_cp_sat_proto::ducktape::debundle::solver_backends::ortools_cpsat as wire;
use selector_ir::VariableDomain;

const REQUEST_PROTO_ENV: &str = "DUCKTAPE_DEBUNDLE_ORTOOLS_CPSAT_REQUEST_PROTO";
const SUMMARY_JSON_ENV: &str = "DUCKTAPE_DEBUNDLE_ORTOOLS_CPSAT_SUMMARY_JSON";
const REQUEST_PROTO_DIR_ENV: &str = "DUCKTAPE_DEBUNDLE_ORTOOLS_CPSAT_REQUEST_PROTO_DIR";
const SUMMARY_JSON_DIR_ENV: &str = "DUCKTAPE_DEBUNDLE_ORTOOLS_CPSAT_SUMMARY_JSON_DIR";
const DUMP_ONLY_ENV: &str = "DUCKTAPE_DEBUNDLE_ORTOOLS_CPSAT_DUMP_ONLY";
static DUMP_SEQUENCE: AtomicUsize = AtomicUsize::new(0);

#[derive(Debug, Clone)]
pub struct OrToolsCpSatBackend {
    solver_path: PathBuf,
}

impl OrToolsCpSatBackend {
    pub fn new(solver_path: impl Into<PathBuf>) -> Self {
        Self {
            solver_path: solver_path.into(),
        }
    }

    pub fn solver_path(&self) -> &Path {
        &self.solver_path
    }
}

impl SelectorProblemBackend for OrToolsCpSatBackend {
    type Error = OrToolsCpSatBackendError;

    fn solve(&self, problem: &CompiledSelectorProblem) -> Result<BackendSolveResult, Self::Error> {
        let request = request_from_problem(problem)?;
        let request_bytes = request.encode_to_vec();
        let dumped_request_path = dump_request_if_requested(problem, &request, &request_bytes)?;
        if dump_only_requested() {
            return Err(OrToolsCpSatBackendError::DumpOnly {
                path: dumped_request_path,
            });
        }
        let output = run_sidecar(&self.solver_path, request_bytes.as_slice())?;
        let response = wire::SelectorCpSatResponse::decode(output.as_slice())
            .map_err(OrToolsCpSatBackendError::DecodeResponse)?;
        response_into_backend_result(response)
    }
}

fn run_sidecar(
    solver_path: &Path,
    request_bytes: &[u8],
) -> Result<Vec<u8>, OrToolsCpSatBackendError> {
    let mut child = Command::new(solver_path)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(OrToolsCpSatBackendError::Spawn)?;
    let mut stdin = child
        .stdin
        .take()
        .ok_or(OrToolsCpSatBackendError::MissingChildStdin)?;
    stdin
        .write_all(request_bytes)
        .map_err(OrToolsCpSatBackendError::WriteRequest)?;
    drop(stdin);

    let output = child
        .wait_with_output()
        .map_err(OrToolsCpSatBackendError::Wait)?;
    if !output.status.success() {
        return Err(OrToolsCpSatBackendError::SidecarFailed {
            status: output.status,
            stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
        });
    }
    Ok(output.stdout)
}

#[derive(Debug)]
pub enum OrToolsCpSatBackendError {
    IdOutOfRange {
        field: &'static str,
        value: usize,
    },
    Spawn(io::Error),
    MissingChildStdin,
    WriteRequest(io::Error),
    Wait(io::Error),
    SidecarFailed {
        status: ExitStatus,
        stderr: String,
    },
    DecodeResponse(prost::DecodeError),
    DumpSummaryJson {
        path: PathBuf,
        source: serde_json::Error,
    },
    DumpIo {
        path: PathBuf,
        source: io::Error,
    },
    DumpOnly {
        path: Option<PathBuf>,
    },
    InvalidStatus {
        status: i32,
    },
    InvalidAssignmentCoverage {
        coverage: i32,
    },
}

impl fmt::Display for OrToolsCpSatBackendError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::IdOutOfRange { field, value } => {
                write!(
                    f,
                    "CP-SAT protobuf field {field} cannot represent id {value}"
                )
            }
            Self::Spawn(err) => write!(f, "failed to spawn CP-SAT sidecar: {err}"),
            Self::MissingChildStdin => write!(f, "CP-SAT sidecar stdin was unavailable"),
            Self::WriteRequest(err) => write!(f, "failed to write CP-SAT request: {err}"),
            Self::Wait(err) => write!(f, "failed to wait for CP-SAT sidecar: {err}"),
            Self::SidecarFailed { status, stderr } => {
                write!(f, "CP-SAT sidecar exited with {status}: {stderr}")
            }
            Self::DecodeResponse(err) => {
                write!(f, "failed to decode CP-SAT response protobuf: {err}")
            }
            Self::DumpSummaryJson { path, source } => {
                write!(
                    f,
                    "failed to serialize CP-SAT summary JSON at {}: {source}",
                    path.display()
                )
            }
            Self::DumpIo { path, source } => {
                write!(
                    f,
                    "failed to write CP-SAT diagnostic artifact at {}: {source}",
                    path.display()
                )
            }
            Self::DumpOnly { path: Some(path) } => {
                write!(
                    f,
                    "dumped CP-SAT request at {}; stopping before sidecar because {DUMP_ONLY_ENV}=1",
                    path.display()
                )
            }
            Self::DumpOnly { path: None } => {
                write!(
                    f,
                    "{DUMP_ONLY_ENV}=1 requires {REQUEST_PROTO_ENV} or {SUMMARY_JSON_ENV} to point at an output file"
                )
            }
            Self::InvalidStatus { status } => {
                write!(f, "CP-SAT sidecar returned invalid status {status}")
            }
            Self::InvalidAssignmentCoverage { coverage } => {
                write!(
                    f,
                    "CP-SAT sidecar returned invalid assignment coverage {coverage}"
                )
            }
        }
    }
}

impl Error for OrToolsCpSatBackendError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Spawn(err) | Self::WriteRequest(err) | Self::Wait(err) => Some(err),
            Self::DecodeResponse(err) => Some(err),
            Self::DumpSummaryJson { source, .. } => Some(source),
            Self::DumpIo { source, .. } => Some(source),
            Self::IdOutOfRange { .. }
            | Self::MissingChildStdin
            | Self::SidecarFailed { .. }
            | Self::DumpOnly { .. }
            | Self::InvalidStatus { .. }
            | Self::InvalidAssignmentCoverage { .. } => None,
        }
    }
}

fn dump_request_if_requested(
    problem: &CompiledSelectorProblem,
    request: &wire::SelectorCpSatRequest,
    request_bytes: &[u8],
) -> Result<Option<PathBuf>, OrToolsCpSatBackendError> {
    let request_proto_path = env_path(REQUEST_PROTO_ENV);
    let summary_json_path = env_path(SUMMARY_JSON_ENV);
    let request_proto_dir = env_path(REQUEST_PROTO_DIR_ENV);
    let summary_json_dir = env_path(SUMMARY_JSON_DIR_ENV);
    if request_proto_path.is_none()
        && summary_json_path.is_none()
        && request_proto_dir.is_none()
        && summary_json_dir.is_none()
    {
        return Ok(None);
    }

    let dump_sequence = (request_proto_dir.is_some() || summary_json_dir.is_some())
        .then(|| DUMP_SEQUENCE.fetch_add(1, Ordering::Relaxed));
    if let Some(path) = &request_proto_path {
        write_request_proto(path, request_bytes)?;
    }
    if let Some(path) = &summary_json_path {
        write_summary_json(path, problem, request, request_bytes.len(), dump_sequence)?;
    }
    if let Some(dir) = &request_proto_dir {
        write_request_proto(
            &dump_dir_path(dir, "selector-cpsat", dump_sequence.unwrap(), "pb"),
            request_bytes,
        )?;
    }
    if let Some(dir) = &summary_json_dir {
        write_summary_json(
            &dump_dir_path(dir, "selector-cpsat", dump_sequence.unwrap(), "json"),
            problem,
            request,
            request_bytes.len(),
            dump_sequence,
        )?;
    }
    Ok(request_proto_path
        .or(summary_json_path)
        .or(request_proto_dir)
        .or(summary_json_dir))
}

fn env_path(env: &str) -> Option<PathBuf> {
    std::env::var_os(env)
        .map(PathBuf::from)
        .filter(|path| !path.as_os_str().is_empty())
}

fn write_request_proto(path: &Path, request_bytes: &[u8]) -> Result<(), OrToolsCpSatBackendError> {
    create_parent_dir(path)?;
    let temp_path = path.with_extension("pb.tmp");
    fs::write(&temp_path, request_bytes).map_err(|source| OrToolsCpSatBackendError::DumpIo {
        path: temp_path.clone(),
        source,
    })?;
    fs::rename(&temp_path, path).map_err(|source| OrToolsCpSatBackendError::DumpIo {
        path: path.to_path_buf(),
        source,
    })
}

fn write_summary_json(
    path: &Path,
    problem: &CompiledSelectorProblem,
    request: &wire::SelectorCpSatRequest,
    request_encoded_bytes: usize,
    dump_sequence: Option<usize>,
) -> Result<(), OrToolsCpSatBackendError> {
    create_parent_dir(path)?;
    let temp_path = path.with_extension("json.tmp");
    let mut file =
        fs::File::create(&temp_path).map_err(|source| OrToolsCpSatBackendError::DumpIo {
            path: temp_path.clone(),
            source,
        })?;
    let summary = problem_summary(problem, request, request_encoded_bytes, dump_sequence);
    serde_json::to_writer_pretty(&mut file, &summary).map_err(|source| {
        OrToolsCpSatBackendError::DumpSummaryJson {
            path: temp_path.clone(),
            source,
        }
    })?;
    file.write_all(b"\n")
        .map_err(|source| OrToolsCpSatBackendError::DumpIo {
            path: temp_path.clone(),
            source,
        })?;
    file.flush()
        .map_err(|source| OrToolsCpSatBackendError::DumpIo {
            path: temp_path.clone(),
            source,
        })?;
    drop(file);
    fs::rename(&temp_path, path).map_err(|source| OrToolsCpSatBackendError::DumpIo {
        path: path.to_path_buf(),
        source,
    })
}

fn create_parent_dir(path: &Path) -> Result<(), OrToolsCpSatBackendError> {
    if let Some(parent) = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        fs::create_dir_all(parent).map_err(|source| OrToolsCpSatBackendError::DumpIo {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    Ok(())
}

fn dump_dir_path(dir: &Path, stem: &str, sequence: usize, extension: &str) -> PathBuf {
    dir.join(format!("{stem}-{sequence:06}.{extension}"))
}

fn dump_only_requested() -> bool {
    std::env::var_os(DUMP_ONLY_ENV)
        .map(|value| !value.is_empty() && value != "0")
        .unwrap_or(false)
}

fn problem_summary(
    problem: &CompiledSelectorProblem,
    request: &wire::SelectorCpSatRequest,
    request_encoded_bytes: usize,
    dump_sequence: Option<usize>,
) -> serde_json::Value {
    let total_domain_values = problem
        .variables
        .iter()
        .map(|variable| problem.variable_domain_values(variable).len())
        .sum::<usize>();
    let max_domain_values = problem
        .variables
        .iter()
        .map(|variable| problem.variable_domain_values(variable).len())
        .max()
        .unwrap_or(0);
    let allowed_row_count = problem
        .allowed_tuples
        .iter()
        .map(|constraint| constraint.tuples.len())
        .sum::<usize>();
    let allowed_cell_count = problem
        .allowed_tuples
        .iter()
        .map(|constraint| {
            constraint
                .tuples
                .iter()
                .map(|tuple| tuple.len())
                .sum::<usize>()
        })
        .sum::<usize>();
    let max_allowed_rows = problem
        .allowed_tuples
        .iter()
        .map(|constraint| constraint.tuples.len())
        .max()
        .unwrap_or(0);
    let max_allowed_arity = problem
        .allowed_tuples
        .iter()
        .map(|constraint| constraint.variables.len())
        .max()
        .unwrap_or(0);
    let binary_equal_count = problem
        .binary_constraints
        .iter()
        .filter(|constraint| matches!(constraint.kind, BinaryConstraintKind::Equal))
        .count();
    let binary_not_equal_count = problem
        .binary_constraints
        .iter()
        .filter(|constraint| matches!(constraint.kind, BinaryConstraintKind::NotEqual))
        .count();
    let binary_ordinal_before_count = problem
        .binary_constraints
        .iter()
        .filter(|constraint| matches!(constraint.kind, BinaryConstraintKind::OrdinalBefore))
        .count();
    let variable_count_by_domain = keyed_count(
        problem
            .variables
            .iter()
            .map(|variable| variable_domain_name(variable.domain)),
    );
    let domain_size_histogram = usize_histogram(
        problem
            .variables
            .iter()
            .map(|variable| problem.variable_domain_values(variable).len()),
    );
    let domain_size_histogram_by_domain =
        grouped_usize_histogram(problem.variables.iter().map(|variable| {
            (
                variable_domain_name(variable.domain),
                problem.variable_domain_values(variable).len(),
            )
        }));
    let allowed_table_arity_histogram = usize_histogram(
        problem
            .allowed_tuples
            .iter()
            .map(|constraint| constraint.variables.len()),
    );
    let allowed_table_row_count_histogram = usize_histogram(
        problem
            .allowed_tuples
            .iter()
            .map(|constraint| constraint.tuples.len()),
    );
    let allowed_table_cell_count_histogram =
        usize_histogram(problem.allowed_tuples.iter().map(|constraint| {
            constraint
                .tuples
                .iter()
                .map(|tuple| tuple.len())
                .sum::<usize>()
        }));
    let binary_constraint_count_by_kind = keyed_count(
        problem
            .binary_constraints
            .iter()
            .map(|constraint| binary_constraint_kind_name(constraint.kind)),
    );
    let all_different_arity_histogram = usize_histogram(
        problem
            .all_different
            .iter()
            .map(|constraint| constraint.variables.len()),
    );
    let all_different_count_by_reason = keyed_count(
        problem
            .all_different
            .iter()
            .map(|constraint| all_different_reason_name(&constraint.reason)),
    );
    let variable_domain_representation_count_by_kind = keyed_count(problem.variables.iter().map(
        |variable| match &variable.values {
            CompiledVariableDomain::Full(_) => "full",
            CompiledVariableDomain::Sparse(_) => "sparse",
        },
    ));
    let domain_sharing = variable_domain_sharing_summary(problem);

    serde_json::json!({
        "all_different_count": problem.all_different.len(),
        "all_different_count_by_reason": all_different_count_by_reason,
        "all_different_arity_histogram": all_different_arity_histogram,
        "allowed_cell_count": allowed_cell_count,
        "allowed_table_arity_histogram": allowed_table_arity_histogram,
        "allowed_table_cell_count_histogram": allowed_table_cell_count_histogram,
        "allowed_table_row_count_histogram": allowed_table_row_count_histogram,
        "allowed_row_count": allowed_row_count,
        "allowed_table_count": problem.allowed_tuples.len(),
        "binary_constraint_count": problem.binary_constraints.len(),
        "binary_constraint_count_by_kind": binary_constraint_count_by_kind,
        "binary_equal_count": binary_equal_count,
        "binary_not_equal_count": binary_not_equal_count,
        "binary_ordinal_before_count": binary_ordinal_before_count,
        "domain_size_histogram": domain_size_histogram,
        "domain_size_histogram_by_domain": domain_size_histogram_by_domain,
        "dump_sequence": dump_sequence,
        "max_allowed_arity": max_allowed_arity,
        "max_allowed_rows": max_allowed_rows,
        "max_domain_values": max_domain_values,
        "request_encoded_bytes": request_encoded_bytes,
        "target_projection_count": problem.target_projections.len(),
        "total_domain_values": total_domain_values,
        "variable_domain_representation_count_by_kind": variable_domain_representation_count_by_kind,
        "variable_domain_sharing": domain_sharing,
        "value_dictionary_count": problem.value_dictionary.len(),
        "variable_count": problem.variables.len(),
        "variable_count_by_domain": variable_count_by_domain,
        "wire_all_different_count": request.all_different.len(),
        "wire_allowed_table_count": request.allowed_tables.len(),
        "wire_binary_constraint_count": request.binary_constraints.len(),
        "wire_target_projection_count": request.target_projections.len(),
        "wire_variable_count": request.variables.len(),
    })
}

fn variable_domain_sharing_summary(problem: &CompiledSelectorProblem) -> serde_json::Value {
    let mut domain_use_counts: BTreeMap<Vec<BackendValueId>, usize> = BTreeMap::new();
    for variable in &problem.variables {
        *domain_use_counts
            .entry(problem.variable_domain_values(variable))
            .or_insert(0) += 1;
    }
    let unique_domain_value_count = domain_use_counts
        .keys()
        .map(|values| values.len())
        .sum::<usize>();
    let total_variable_domain_values = domain_use_counts
        .iter()
        .map(|(values, use_count)| values.len() * use_count)
        .sum::<usize>();
    let shared_domain_group_count = domain_use_counts
        .values()
        .filter(|use_count| **use_count > 1)
        .count();
    let max_variables_sharing_domain = domain_use_counts.values().copied().max().unwrap_or(0);
    let variables_per_unique_domain_histogram =
        usize_histogram(domain_use_counts.values().copied());

    serde_json::json!({
        "current_encoded_value_count": total_variable_domain_values,
        "deduplicated_encoded_value_count": unique_domain_value_count,
        "encoded_value_savings_if_deduplicated": total_variable_domain_values.saturating_sub(unique_domain_value_count),
        "max_variables_sharing_domain": max_variables_sharing_domain,
        "shared_domain_group_count": shared_domain_group_count,
        "unique_domain_count": domain_use_counts.len(),
        "variables_per_unique_domain_histogram": variables_per_unique_domain_histogram,
    })
}

fn usize_histogram(values: impl IntoIterator<Item = usize>) -> BTreeMap<String, usize> {
    let mut histogram = BTreeMap::new();
    for value in values {
        *histogram.entry(value.to_string()).or_insert(0) += 1;
    }
    histogram
}

fn grouped_usize_histogram(
    values: impl IntoIterator<Item = (&'static str, usize)>,
) -> BTreeMap<&'static str, BTreeMap<String, usize>> {
    let mut grouped = BTreeMap::new();
    for (key, value) in values {
        *grouped
            .entry(key)
            .or_insert_with(BTreeMap::new)
            .entry(value.to_string())
            .or_insert(0) += 1;
    }
    grouped
}

fn keyed_count(keys: impl IntoIterator<Item = &'static str>) -> BTreeMap<&'static str, usize> {
    let mut counts = BTreeMap::new();
    for key in keys {
        *counts.entry(key).or_insert(0) += 1;
    }
    counts
}

fn variable_domain_name(domain: VariableDomain) -> &'static str {
    match domain {
        VariableDomain::Owner => "owner",
        VariableDomain::AstNode => "ast_node",
        VariableDomain::String => "string",
        VariableDomain::StatementOrdinal => "statement_ordinal",
    }
}

fn binary_constraint_kind_name(kind: BinaryConstraintKind) -> &'static str {
    match kind {
        BinaryConstraintKind::Equal => "equal",
        BinaryConstraintKind::NotEqual => "not_equal",
        BinaryConstraintKind::OrdinalBefore => "ordinal_before",
    }
}

fn all_different_reason_name(reason: &AllDifferentReason) -> &'static str {
    match reason {
        AllDifferentReason::TargetInjectivity { .. } => "target_injectivity",
        AllDifferentReason::SelectorSemantics { .. } => "selector_semantics",
    }
}

fn request_from_problem(
    problem: &CompiledSelectorProblem,
) -> Result<wire::SelectorCpSatRequest, OrToolsCpSatBackendError> {
    Ok(wire::SelectorCpSatRequest {
        variables: problem
            .variables
            .iter()
            .map(|variable| variable_from_backend(problem, variable))
            .collect::<Result<Vec<_>, _>>()?,
        allowed_tables: problem
            .allowed_tuples
            .iter()
            .map(table_from_backend)
            .collect::<Result<Vec<_>, _>>()?,
        binary_constraints: problem
            .binary_constraints
            .iter()
            .map(binary_constraint_from_backend)
            .collect::<Result<Vec<_>, _>>()?,
        all_different: problem
            .all_different
            .iter()
            .map(all_different_from_backend)
            .collect::<Result<Vec<_>, _>>()?,
        target_projections: problem
            .target_projections
            .iter()
            .map(target_projection_from_backend)
            .collect::<Result<Vec<_>, _>>()?,
    })
}

fn variable_from_backend(
    problem: &CompiledSelectorProblem,
    variable: &CompiledVariable,
) -> Result<wire::Variable, OrToolsCpSatBackendError> {
    Ok(wire::Variable {
        id: constraint_variable_id(variable.id)?,
        values: problem
            .variable_domain_values(variable)
            .iter()
            .map(|value| value.0)
            .collect(),
        debug_name: variable.debug_name.clone().unwrap_or_default(),
    })
}

fn table_from_backend(
    constraint: &CompiledAllowedTupleConstraint,
) -> Result<wire::TableConstraint, OrToolsCpSatBackendError> {
    Ok(wire::TableConstraint {
        id: u32_id("allowed_tables.id", constraint.id.0)?,
        variable_ids: constraint
            .variables
            .iter()
            .copied()
            .map(constraint_variable_id)
            .collect::<Result<Vec<_>, _>>()?,
        allowed_rows: constraint
            .tuples
            .iter()
            .map(|values| wire::Tuple {
                values: values.iter().map(|value| value.0).collect(),
            })
            .collect(),
    })
}

fn binary_constraint_from_backend(
    constraint: &CompiledBinaryConstraint,
) -> Result<wire::BinaryConstraint, OrToolsCpSatBackendError> {
    Ok(wire::BinaryConstraint {
        left_variable_id: constraint_variable_id(constraint.left)?,
        right_variable_id: constraint_variable_id(constraint.right)?,
        kind: match constraint.kind {
            BinaryConstraintKind::Equal => wire::BinaryConstraintKind::Equal,
            BinaryConstraintKind::NotEqual => wire::BinaryConstraintKind::NotEqual,
            BinaryConstraintKind::OrdinalBefore => wire::BinaryConstraintKind::OrdinalBefore,
        } as i32,
    })
}

fn all_different_from_backend(
    constraint: &CompiledAllDifferentConstraint,
) -> Result<wire::AllDifferent, OrToolsCpSatBackendError> {
    Ok(wire::AllDifferent {
        id: u32_id("all_different.id", constraint.id.0)?,
        variable_ids: constraint
            .variables
            .iter()
            .copied()
            .map(constraint_variable_id)
            .collect::<Result<Vec<_>, _>>()?,
    })
}

fn target_projection_from_backend(
    projection: &TargetProjection,
) -> Result<wire::TargetProjection, OrToolsCpSatBackendError> {
    let binding_projection = match &projection.binding_projection {
        Some(TargetBindingProjection::Variable(variable)) => Some(
            wire::target_projection::BindingProjection::BindingVariableId(constraint_variable_id(
                *variable,
            )?),
        ),
        Some(TargetBindingProjection::Const(binding)) => Some(
            wire::target_projection::BindingProjection::BindingConst(binding.clone()),
        ),
        None => None,
    };
    Ok(wire::TargetProjection {
        target_id: u32_id("target_projections.target_id", projection.target.0)?,
        owner_variable_id: constraint_variable_id(projection.owner_variable)?,
        binding_projection,
    })
}

fn response_into_backend_result(
    response: wire::SelectorCpSatResponse,
) -> Result<BackendSolveResult, OrToolsCpSatBackendError> {
    let status = match wire::SolverStatus::try_from(response.status).map_err(|_| {
        OrToolsCpSatBackendError::InvalidStatus {
            status: response.status,
        }
    })? {
        wire::SolverStatus::Unsatisfiable => BackendSolveStatus::Unsatisfiable,
        wire::SolverStatus::Satisfiable => BackendSolveStatus::Satisfiable,
        wire::SolverStatus::Ambiguous => BackendSolveStatus::Ambiguous,
        wire::SolverStatus::Unknown => BackendSolveStatus::Unknown,
        wire::SolverStatus::Invalid | wire::SolverStatus::Unspecified => {
            return Err(OrToolsCpSatBackendError::InvalidStatus {
                status: response.status,
            });
        }
    };
    let assignment_coverage = match wire::AssignmentCoverage::try_from(response.assignment_coverage)
        .map_err(|_| OrToolsCpSatBackendError::InvalidAssignmentCoverage {
            coverage: response.assignment_coverage,
        })? {
        wire::AssignmentCoverage::Unspecified | wire::AssignmentCoverage::Sample => {
            BackendAssignmentCoverage::Sample
        }
        wire::AssignmentCoverage::TargetSupportComplete => {
            BackendAssignmentCoverage::TargetSupportComplete
        }
    };
    Ok(BackendSolveResult {
        status,
        assignment_coverage,
        assignments: response
            .assignments
            .into_iter()
            .map(assignment_row_into_backend)
            .collect(),
        diagnostic: (!response.diagnostic.is_empty()).then_some(response.diagnostic),
    })
}

fn assignment_row_into_backend(row: wire::AssignmentRow) -> BackendAssignment {
    BackendAssignment {
        values: row
            .values
            .into_iter()
            .map(|assignment| BackendVariableAssignment {
                variable: ConstraintVariableId(assignment.variable_id as usize),
                value: BackendValueId(assignment.value),
            })
            .collect(),
    }
}

fn constraint_variable_id(id: ConstraintVariableId) -> Result<u32, OrToolsCpSatBackendError> {
    u32_id("variable id", id.0)
}

fn u32_id(field: &'static str, value: usize) -> Result<u32, OrToolsCpSatBackendError> {
    value
        .try_into()
        .map_err(|_| OrToolsCpSatBackendError::IdOutOfRange { field, value })
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::path::{Path, PathBuf};

    use analysis::{AnalysisHints, ChunkId, OwnerId, StatementOrdinal};
    use selector_backend_solver::solve_with_backend;
    use selector_ir::{
        ClaimKind, ClaimOrigin, ClaimOutcome, OwnerTerm, ResolvedClaim, SelectorAtom, SelectorFact,
        SelectorFactStore, SelectorProgram, SelectorTargetId, StringTerm, VariableDomain,
    };
    use selector_ir_lowering::{MemberSelectorLoweringContext, MemberSelectorProgramBuilder};
    use spec::{AnonymousStatementSelector, MemberSelectorSpec, SourceMatchIdentifierMode};

    use super::*;

    fn owner_fact(owner: usize, ordinal: usize, kind: &str) -> SelectorFact {
        SelectorFact::Owner {
            chunk_id: ChunkId(0),
            owner: OwnerId(owner),
            statement_ordinal: StatementOrdinal(ordinal),
            statement_kind: kind.to_string(),
        }
    }

    fn declared_binding(owner: usize, binding: &str) -> SelectorFact {
        SelectorFact::DeclaredBinding {
            chunk_id: ChunkId(0),
            owner: OwnerId(owner),
            binding: binding.to_string(),
            export_name: None,
        }
    }

    fn owner_references_binding(owner: usize, binding: &str) -> SelectorFact {
        SelectorFact::OwnerReferencesBinding {
            chunk_id: ChunkId(0),
            owner: OwnerId(owner),
            binding: binding.to_string(),
            edge_kind: "eager_use".to_string(),
        }
    }

    fn member_read(ordinal: usize, object: Option<&str>, member: &str) -> SelectorFact {
        SelectorFact::MemberRead {
            chunk_id: ChunkId(0),
            statement_ordinal: StatementOrdinal(ordinal),
            object: object.map(str::to_string),
            member: member.to_string(),
        }
    }

    fn module_member_use(ordinal: usize, module: &str, member: &str) -> SelectorFact {
        SelectorFact::ModuleMemberUse {
            chunk_id: ChunkId(0),
            statement_ordinal: StatementOrdinal(ordinal),
            module: module.to_string(),
            member: member.to_string(),
        }
    }

    fn call_argument_use(
        argument: &str,
        callee_object: Option<&str>,
        callee_member: &str,
        arg_index: usize,
    ) -> SelectorFact {
        SelectorFact::CallArgumentUse {
            chunk_id: ChunkId(0),
            argument: argument.to_string(),
            callee_object: callee_object.map(str::to_string),
            callee_member: callee_member.to_string(),
            arg_index,
        }
    }

    fn sidecar_path() -> PathBuf {
        let rlocation = std::env::var("ORTOOLS_CPSAT_SOLVER")
            .expect("ORTOOLS_CPSAT_SOLVER must be set by Bazel");
        let path = Path::new(&rlocation);
        if path.is_absolute() {
            return path.to_path_buf();
        }
        for root_env in ["RUNFILES_DIR", "TEST_SRCDIR"] {
            if let Ok(root) = std::env::var(root_env) {
                let candidate = Path::new(&root).join(path);
                if candidate.exists() {
                    return candidate;
                }
            }
        }
        panic!("could not resolve sidecar runfile {rlocation}");
    }

    #[test]
    fn request_preserves_constant_binding_projection() {
        let projection = TargetProjection {
            target: SelectorTargetId(7),
            owner_variable: ConstraintVariableId(0),
            binding_projection: Some(TargetBindingProjection::Const("minA".to_string())),
        };

        let wire_projection = target_projection_from_backend(&projection).unwrap();

        assert_eq!(wire_projection.target_id, 7);
        assert_eq!(wire_projection.owner_variable_id, 0);
        assert_eq!(
            wire_projection.binding_projection,
            Some(wire::target_projection::BindingProjection::BindingConst(
                "minA".to_string()
            ))
        );
    }

    #[test]
    fn cpsat_sidecar_resolves_broad_specific_target_injectivity() {
        let mut program = SelectorProgram::default();
        let broad_owner = program.add_variable(VariableDomain::Owner, Some("broad".to_string()));
        let strict_owner = program.add_variable(VariableDomain::Owner, Some("strict".to_string()));
        let broad_target = program.add_target(
            ChunkId(0),
            broad_owner,
            "module",
            ClaimKind::Binding {
                export_name: Some("Broad".to_string()),
            },
            ClaimOrigin::Synthetic,
        );
        let strict_target = program.add_target(
            ChunkId(0),
            strict_owner,
            "module",
            ClaimKind::Binding {
                export_name: Some("Strict".to_string()),
            },
            ClaimOrigin::Synthetic,
        );
        program.add_atom(SelectorAtom::OwnerDeclaresBinding {
            owner: OwnerTerm::Var { id: broad_owner },
            binding: StringTerm::Const {
                value: "shared".to_string(),
            },
        });
        program.add_atom(SelectorAtom::OwnerDeclaresBinding {
            owner: OwnerTerm::Var { id: strict_owner },
            binding: StringTerm::Const {
                value: "specific".to_string(),
            },
        });
        program.require_all_different(vec![broad_target, strict_target]);

        let mut facts = SelectorFactStore::default();
        facts.push(owner_fact(10, 0, "var"));
        facts.push(owner_fact(20, 1, "var"));
        facts.push(declared_binding(10, "shared"));
        facts.push(declared_binding(20, "shared"));
        facts.push(declared_binding(20, "specific"));

        let backend = OrToolsCpSatBackend::new(sidecar_path());
        let result = solve_with_backend(&program, &facts, &backend).unwrap();

        assert_eq!(
            result.outcome_for(broad_target),
            Some(&ClaimOutcome::Unique {
                claim: ResolvedClaim {
                    chunk_id: ChunkId(0),
                    owner: OwnerId(10),
                    statement_ordinal: StatementOrdinal(0),
                    binding: Some("shared".to_string()),
                    provenance: Vec::new(),
                }
            })
        );
        assert_eq!(
            result.outcome_for(strict_target),
            Some(&ClaimOutcome::Unique {
                claim: ResolvedClaim {
                    chunk_id: ChunkId(0),
                    owner: OwnerId(20),
                    statement_ordinal: StatementOrdinal(1),
                    binding: Some("specific".to_string()),
                    provenance: Vec::new(),
                }
            })
        );
    }

    #[test]
    fn cpsat_sidecar_resolves_alpha_all_binding_group_multideclarator() {
        js_ast::with_swc_globals(|| {
            let mut group_selector = AnonymousStatementSelector::exact(
                "const primary = EXPR_PRIMARY, secondary = EXPR_SECONDARY;",
            );
            group_selector.identifiers = SourceMatchIdentifierMode::AlphaAll;
            let mut primary_selector = group_selector.clone();
            primary_selector.target_binding = Some("primary".to_string());
            let mut secondary_selector = group_selector.clone();
            secondary_selector.target_binding = Some("secondary".to_string());

            let mut builder = MemberSelectorProgramBuilder::new(
                MemberSelectorLoweringContext::new(ChunkId(0), "static/app::settings"),
            );
            let primary_target = builder
                .declare_member_target_in_module(
                    "static/app::settings",
                    "primary",
                    &MemberSelectorSpec::SourceMatch(primary_selector),
                )
                .unwrap();
            let secondary_target = builder
                .declare_member_target_in_module(
                    "static/app::settings",
                    "secondary",
                    &MemberSelectorSpec::SourceMatch(secondary_selector),
                )
                .unwrap();
            assert!(
                builder
                    .try_lower_native_source_match_group(
                        "static/app::settings",
                        &group_selector,
                        &BTreeMap::from([
                            ("primary".to_string(), "primary".to_string()),
                            ("secondary".to_string(), "secondary".to_string()),
                        ]),
                    )
                    .unwrap()
            );
            let program = builder.into_program().unwrap();

            let module = js_ast::parse_js_module_ast(
                "<chunk>",
                "const primary = 10, secondary = 20;\n\
                 console.log(primary + secondary);\n\
                 export { primary, secondary };\n",
            )
            .unwrap();
            let chunk_facts = chunk_facts::extract_facts(&module).unwrap();
            let analysis =
                analysis::facts::analyze_chunk(&module, &AnalysisHints::default(), None, |_| None);
            let owner_graph = analysis::graph::build_owner_graph(&analysis.facts).unwrap();
            let mut facts = SelectorFactStore::default();
            facts.extend_chunk_facts(ChunkId(0), &chunk_facts);
            for node in owner_graph.iter_nodes() {
                facts.push(SelectorFact::Owner {
                    chunk_id: ChunkId(0),
                    owner: node.id,
                    statement_ordinal: node.statement_ordinal,
                    statement_kind: node.kind.to_string(),
                });
                for binding in &node.declared {
                    facts.push(SelectorFact::DeclaredBinding {
                        chunk_id: ChunkId(0),
                        owner: node.id,
                        binding: binding.0.as_str().to_string(),
                        export_name: None,
                    });
                }
            }
            for edge in owner_graph.iter_edges() {
                if let Some(binding) = edge.reason.binding() {
                    facts.push(SelectorFact::OwnerReferencesBinding {
                        chunk_id: ChunkId(0),
                        owner: edge.from,
                        binding: binding.0.as_str().to_string(),
                        edge_kind: edge.reason.kind().to_string(),
                    });
                }
            }

            let backend = OrToolsCpSatBackend::new(sidecar_path());
            let result = solve_with_backend(&program, &facts, &backend).unwrap();

            assert_eq!(
                result.outcome_for(primary_target),
                Some(&ClaimOutcome::Unique {
                    claim: ResolvedClaim {
                        chunk_id: ChunkId(0),
                        owner: OwnerId(0),
                        statement_ordinal: StatementOrdinal(0),
                        binding: Some("primary".to_string()),
                        provenance: Vec::new(),
                    }
                })
            );
            assert_eq!(
                result.outcome_for(secondary_target),
                Some(&ClaimOutcome::Unique {
                    claim: ResolvedClaim {
                        chunk_id: ChunkId(0),
                        owner: OwnerId(1),
                        statement_ordinal: StatementOrdinal(1),
                        binding: Some("secondary".to_string()),
                        provenance: Vec::new(),
                    }
                })
            );
        });
    }

    #[test]
    fn cpsat_sidecar_solves_cross_ref_anchor_in_one_program() {
        let mut program = SelectorProgram::default();
        let anchor_owner = program.add_variable(VariableDomain::Owner, Some("anchor".to_string()));
        let delegator_owner =
            program.add_variable(VariableDomain::Owner, Some("delegator".to_string()));
        let anchor_target = program.add_target(
            ChunkId(0),
            anchor_owner,
            "module",
            ClaimKind::Binding {
                export_name: Some("Anchor".to_string()),
            },
            ClaimOrigin::Synthetic,
        );
        let delegator_target = program.add_target(
            ChunkId(0),
            delegator_owner,
            "module",
            ClaimKind::Binding {
                export_name: Some("Delegator".to_string()),
            },
            ClaimOrigin::Synthetic,
        );
        program.add_atom(SelectorAtom::OwnerDeclaresBinding {
            owner: OwnerTerm::Var { id: anchor_owner },
            binding: StringTerm::Const {
                value: "a".to_string(),
            },
        });
        program.add_atom(SelectorAtom::OwnerReferencesOwner {
            owner: OwnerTerm::Var {
                id: delegator_owner,
            },
            referenced: OwnerTerm::Var { id: anchor_owner },
        });
        program.add_atom(SelectorAtom::OwnerKind {
            owner: OwnerTerm::Var {
                id: delegator_owner,
            },
            statement_kind: StringTerm::Const {
                value: "fn_decl".to_string(),
            },
        });
        program.require_all_different(vec![anchor_target, delegator_target]);

        let mut facts = SelectorFactStore::default();
        facts.push(owner_fact(1, 1, "var_decl"));
        facts.push(declared_binding(1, "a"));
        facts.push(owner_fact(2, 2, "fn_decl"));
        facts.push(declared_binding(2, "b"));
        facts.push(owner_references_binding(2, "a"));
        facts.push(owner_fact(3, 3, "fn_decl"));
        facts.push(declared_binding(3, "other"));
        facts.push(owner_references_binding(3, "missing"));

        let backend = OrToolsCpSatBackend::new(sidecar_path());
        let result = solve_with_backend(&program, &facts, &backend).unwrap();

        assert_eq!(
            result.outcome_for(anchor_target),
            Some(&ClaimOutcome::Unique {
                claim: ResolvedClaim {
                    chunk_id: ChunkId(0),
                    owner: OwnerId(1),
                    statement_ordinal: StatementOrdinal(1),
                    binding: Some("a".to_string()),
                    provenance: Vec::new(),
                }
            })
        );
        assert_eq!(
            result.outcome_for(delegator_target),
            Some(&ClaimOutcome::Unique {
                claim: ResolvedClaim {
                    chunk_id: ChunkId(0),
                    owner: OwnerId(2),
                    statement_ordinal: StatementOrdinal(2),
                    binding: Some("b".to_string()),
                    provenance: Vec::new(),
                }
            })
        );
    }

    #[test]
    fn cpsat_sidecar_solves_object_constrained_reads_member_jointly() {
        let mut program = SelectorProgram::default();
        let object_owner = program.add_variable(VariableDomain::Owner, Some("object".to_string()));
        let reader_owner = program.add_variable(VariableDomain::Owner, Some("reader".to_string()));
        let object_target = program.add_target(
            ChunkId(0),
            object_owner,
            "module",
            ClaimKind::Binding {
                export_name: Some("Context".to_string()),
            },
            ClaimOrigin::Synthetic,
        );
        let reader_target = program.add_target(
            ChunkId(0),
            reader_owner,
            "module",
            ClaimKind::Binding {
                export_name: Some("ReadId".to_string()),
            },
            ClaimOrigin::Synthetic,
        );
        program.add_atom(SelectorAtom::OwnerDeclaresBinding {
            owner: OwnerTerm::Var { id: object_owner },
            binding: StringTerm::Const {
                value: "ctx".to_string(),
            },
        });
        program.add_atom(SelectorAtom::ReadsMemberOfOwner {
            owner: OwnerTerm::Var { id: reader_owner },
            object: OwnerTerm::Var { id: object_owner },
            member: StringTerm::Const {
                value: "id".to_string(),
            },
        });
        program.add_atom(SelectorAtom::OwnerKind {
            owner: OwnerTerm::Var { id: reader_owner },
            statement_kind: StringTerm::Const {
                value: "fn_decl".to_string(),
            },
        });
        program.require_all_different(vec![object_target, reader_target]);

        let mut facts = SelectorFactStore::default();
        facts.push(owner_fact(1, 1, "var_decl"));
        facts.push(declared_binding(1, "ctx"));
        facts.push(owner_fact(2, 2, "fn_decl"));
        facts.push(declared_binding(2, "readId"));
        facts.push(member_read(2, Some("ctx"), "id"));
        facts.push(owner_fact(3, 3, "fn_decl"));
        facts.push(declared_binding(3, "other"));
        facts.push(member_read(3, Some("otherCtx"), "id"));

        let backend = OrToolsCpSatBackend::new(sidecar_path());
        let result = solve_with_backend(&program, &facts, &backend).unwrap();

        assert_eq!(
            result.outcome_for(object_target),
            Some(&ClaimOutcome::Unique {
                claim: ResolvedClaim {
                    chunk_id: ChunkId(0),
                    owner: OwnerId(1),
                    statement_ordinal: StatementOrdinal(1),
                    binding: Some("ctx".to_string()),
                    provenance: Vec::new(),
                }
            })
        );
        assert_eq!(
            result.outcome_for(reader_target),
            Some(&ClaimOutcome::Unique {
                claim: ResolvedClaim {
                    chunk_id: ChunkId(0),
                    owner: OwnerId(2),
                    statement_ordinal: StatementOrdinal(2),
                    binding: Some("readId".to_string()),
                    provenance: Vec::new(),
                }
            })
        );
    }

    #[test]
    fn cpsat_sidecar_solves_consumes_module_member_allowed_tuple() {
        let mut program = SelectorProgram::default();
        let consumer_owner =
            program.add_variable(VariableDomain::Owner, Some("consumer".to_string()));
        let consumer_target = program.add_target(
            ChunkId(0),
            consumer_owner,
            "module",
            ClaimKind::Binding {
                export_name: Some("WidgetConsumer".to_string()),
            },
            ClaimOrigin::Synthetic,
        );
        program.add_atom(SelectorAtom::ConsumesModuleMember {
            owner: OwnerTerm::Var { id: consumer_owner },
            module: StringTerm::Const {
                value: "./accessors".to_string(),
            },
            member: StringTerm::Const {
                value: "Widget".to_string(),
            },
        });

        let mut facts = SelectorFactStore::default();
        facts.push(owner_fact(65, 55, "function"));
        facts.push(declared_binding(65, "useWidget"));
        facts.push(module_member_use(55, "./accessors", "Widget"));
        facts.push(owner_fact(66, 56, "function"));
        facts.push(declared_binding(66, "useOther"));
        facts.push(module_member_use(56, "./accessors", "Other"));
        facts.push(owner_fact(67, 57, "function"));
        facts.push(declared_binding(67, "useOtherModule"));
        facts.push(module_member_use(57, "./other", "Widget"));

        let backend = OrToolsCpSatBackend::new(sidecar_path());
        let result = solve_with_backend(&program, &facts, &backend).unwrap();

        assert_eq!(
            result.outcome_for(consumer_target),
            Some(&ClaimOutcome::Unique {
                claim: ResolvedClaim {
                    chunk_id: ChunkId(0),
                    owner: OwnerId(65),
                    statement_ordinal: StatementOrdinal(55),
                    binding: Some("useWidget".to_string()),
                    provenance: Vec::new(),
                }
            })
        );
    }

    #[test]
    fn cpsat_sidecar_solves_passed_to_call_of_owner_allowed_tuple() {
        let mut program = SelectorProgram::default();
        let registry_owner =
            program.add_variable(VariableDomain::Owner, Some("registry".to_string()));
        let widget_owner = program.add_variable(VariableDomain::Owner, Some("widget".to_string()));
        let registry_target = program.add_target(
            ChunkId(0),
            registry_owner,
            "module",
            ClaimKind::Binding {
                export_name: Some("Registry".to_string()),
            },
            ClaimOrigin::Synthetic,
        );
        let widget_target = program.add_target(
            ChunkId(0),
            widget_owner,
            "module",
            ClaimKind::Binding {
                export_name: Some("RegisteredWidget".to_string()),
            },
            ClaimOrigin::Synthetic,
        );
        program.add_atom(SelectorAtom::OwnerDeclaresBinding {
            owner: OwnerTerm::Var { id: registry_owner },
            binding: StringTerm::Const {
                value: "registry".to_string(),
            },
        });
        program.add_atom(SelectorAtom::PassedToCallOfOwner {
            owner: OwnerTerm::Var { id: widget_owner },
            callee_object: OwnerTerm::Var { id: registry_owner },
            callee_member: StringTerm::Const {
                value: "register".to_string(),
            },
            arg_index: Some(1),
        });
        program.require_all_different(vec![registry_target, widget_target]);

        let mut facts = SelectorFactStore::default();
        facts.push(owner_fact(10, 0, "var_decl"));
        facts.push(declared_binding(10, "registry"));
        facts.push(owner_fact(20, 1, "class"));
        facts.push(declared_binding(20, "Widget"));
        facts.push(call_argument_use("Widget", Some("registry"), "register", 1));
        facts.push(owner_fact(30, 2, "class"));
        facts.push(declared_binding(30, "WrongIndex"));
        facts.push(call_argument_use(
            "WrongIndex",
            Some("registry"),
            "register",
            0,
        ));
        facts.push(owner_fact(40, 3, "class"));
        facts.push(declared_binding(40, "WrongObject"));
        facts.push(call_argument_use(
            "WrongObject",
            Some("otherRegistry"),
            "register",
            1,
        ));

        let backend = OrToolsCpSatBackend::new(sidecar_path());
        let result = solve_with_backend(&program, &facts, &backend).unwrap();

        assert_eq!(
            result.outcome_for(registry_target),
            Some(&ClaimOutcome::Unique {
                claim: ResolvedClaim {
                    chunk_id: ChunkId(0),
                    owner: OwnerId(10),
                    statement_ordinal: StatementOrdinal(0),
                    binding: Some("registry".to_string()),
                    provenance: Vec::new(),
                }
            })
        );
        assert_eq!(
            result.outcome_for(widget_target),
            Some(&ClaimOutcome::Unique {
                claim: ResolvedClaim {
                    chunk_id: ChunkId(0),
                    owner: OwnerId(20),
                    statement_ordinal: StatementOrdinal(1),
                    binding: Some("Widget".to_string()),
                    provenance: Vec::new(),
                }
            })
        );
    }
}
