//! Selector debt report: rank the spec's most rebuild-fragile selectors.
//!
//! Powers `debundle spec selector-debt`. A spec author targets minified
//! top-level statements two ways: by **name** (`selector.binding.name`,
//! cheap but unstable — a rebuild can reassign the token) or by
//! **structure** (`selector.source_match`, robust but verbose and prone
//! to copy-paste). This report surfaces the debt that accrues from the
//! cheap path, so authors can see what rests on fragile name-only
//! selection and which structural selectors have been copied:
//!
//! - **name-only selectors**, scored by how minified the bound name
//!   looks (`minified_score`). Short / vowel-poor tokens rank highest
//!   because they are the most likely to move under a rebuild.
//! - **repeated `source_match` bodies** — identical structural selector
//!   text reused across members / anonymous statements / binding groups.
//!   These are the copy-paste the contextual-selector and matcher-core
//!   work is meant to replace.
//! - **drifted minified bindings** (with `--against <other spec>`) —
//!   members whose readable `name:` is stable across two spec versions
//!   but whose `selector.binding.name` changed. A name-only selector
//!   that has *already* required updating is proven rebuild-fragile.
//!
//! By default this reads only the on-disk modules tree (same walk as
//! `spec stats` / `modules list`). With [`SourceAwareSelectorDebtConfig`],
//! callers may also supply the current chunk source to flag structural
//! selectors that resolve uniquely today but have close non-matching
//! siblings in that chunk.

use std::collections::BTreeMap;
use std::path::Path;

use anyhow::{Context, Result};
use serde::Serialize;
use spec::{AnonymousStatementSelector, MemberSelectorSpec};
use spec_modules::{ModuleFile, collect_module_files, module_path_from_file, read_module_file};

/// Minified-score at or above which a name-only selector is counted as
/// rebuild-fragile in [`SelectorDebtSummary::name_only_fragile`]. The
/// score scale is coarse (see [`minified_score`]); every positive score
/// clears this threshold, so "fragile" means "did not look like a
/// readable word."
pub const FRAGILE_THRESHOLD: u8 = 60;

/// Heuristic `0..=100` estimate of how minified / autogenerated an
/// identifier looks. Higher means more likely a bundler-assigned token,
/// and therefore a more rebuild-fragile thing to select by name.
///
/// This is triage guidance, not a classifier: the score only has to
/// *rank* selectors so the most fragile ones surface first. Shortness
/// and vowel-poverty are the load-bearing signals — base-54 minifier
/// output is dominated by 1-3 character tokens and consonant clusters,
/// while hand-written identifiers tend to be longer and word-shaped.
pub fn minified_score(name: &str) -> u8 {
    let len = name.chars().count();
    if len == 0 {
        return 0;
    }
    let vowels = name.chars().filter(|c| "aeiouAEIOU".contains(*c)).count();
    match len {
        1 => 100,
        2 => 90,
        // A vowel-less three-letter token (`Rng`, `Wbt`) is almost
        // always minified; one with a vowel (`XOe`, `iRe`) is still
        // short enough to be collision-prone but slightly less certain.
        3 if vowels == 0 => 85,
        3 => 70,
        // Four or more characters with no vowel at all is consonant
        // soup — overwhelmingly minified. Longer names that contain a
        // vowel read as words and score zero (not flagged).
        _ if vowels == 0 => 60,
        _ => 0,
    }
}

/// Which selector construct an occurrence came from.
#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum SelectorSite {
    Member,
    AnonymousStatement,
    BindingGroup,
}

#[derive(Debug, Clone, Serialize)]
pub struct NameOnlySelector {
    /// Module path that owns the member.
    pub module: String,
    /// The bound minified name the selector matches on.
    pub binding_name: String,
    /// Readable export `name:`, when the member has one.
    pub export_name: Option<String>,
    /// Heuristic minified-ness of `binding_name` (see [`minified_score`]).
    pub minified_score: u8,
}

#[derive(Debug, Clone, Serialize)]
pub struct SourceMatchOccurrence {
    pub module: String,
    pub site: SelectorSite,
    /// Readable export `name:` for `Member`-site occurrences.
    pub export_name: Option<String>,
    /// The original (un-normalized) `match` body, for display.
    pub match_source: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct RepeatedSourceMatch {
    /// Whitespace-normalized body shared by every occurrence; the key
    /// the occurrences were grouped on.
    pub normalized: String,
    pub occurrences: Vec<SourceMatchOccurrence>,
}

#[derive(Debug, Clone, Serialize)]
pub struct SourceAwareNearMiss {
    /// Top-level body index of the near-matching candidate in the current chunk.
    pub body_idx: usize,
    /// Binding names declared by that candidate, if any.
    pub declared_bindings: Vec<String>,
    /// Existing source_match mismatch-score heuristic. Higher means closer.
    pub score: usize,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct SourceAwareStructuralSelector {
    pub module: String,
    pub site: SelectorSite,
    /// Readable export `name:` for `Member`-site occurrences.
    pub export_name: Option<String>,
    /// The exact top-level body indices matched by this selector today.
    pub exact_body_indices: Vec<usize>,
    pub near_misses: Vec<SourceAwareNearMiss>,
}

#[derive(Debug, Clone, Serialize)]
pub struct DriftedBinding {
    pub module: String,
    pub export_name: String,
    /// `selector.binding.name` in the `--against` spec.
    pub previous_binding: String,
    /// `selector.binding.name` in the current spec.
    pub current_binding: String,
}

/// Spec-wide totals. These count the whole spec; the lists in
/// [`SelectorDebtReport`] may be filtered (`--min-score`) or truncated
/// (`--limit`) by the CLI, so the summary is not derivable from the
/// printed rows.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SelectorDebtSummary {
    pub name_only_total: usize,
    /// Name-only selectors scoring `>= FRAGILE_THRESHOLD`.
    pub name_only_fragile: usize,
    /// Every `source_match` occurrence (repeated or not).
    pub source_match_total: usize,
    pub repeated_source_match_groups: usize,
    pub drifted_binding_total: usize,
    /// Source-aware structural selectors checked against a chunk source.
    /// Zero when source-aware mode was not requested.
    pub source_aware_checked: usize,
    /// Checked selectors with exactly one exact top-level body match.
    pub source_aware_unique: usize,
    /// Unique structural selectors that also had near-matching siblings.
    pub source_aware_near_ambiguous: usize,
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct SelectorDebtReport {
    /// Every name-only (`selector.binding`) selector, sorted most
    /// rebuild-fragile first.
    pub name_only: Vec<NameOnlySelector>,
    /// `source_match` bodies that appear two or more times, sorted by
    /// occurrence count (descending).
    pub repeated_source_match: Vec<RepeatedSourceMatch>,
    /// Populated only when `--against` is supplied.
    pub drifted_bindings: Vec<DriftedBinding>,
    /// Populated only when source-aware mode is supplied.
    pub source_aware_near_ambiguous: Vec<SourceAwareStructuralSelector>,
    pub summary: SelectorDebtSummary,
}

#[derive(Debug, Clone)]
pub struct SourceAwareSelectorDebtConfig<'a> {
    /// Current chunk source to parse and compare `source_match` bodies against.
    pub source_file: &'a Path,
    /// Minimum near-miss score to report. See `source_match` mismatch scoring.
    pub near_match_min_score: usize,
    /// Maximum near-matches retained per selector. Zero means unlimited.
    pub near_match_limit: usize,
}

/// Normalize a `match` body for copy-paste grouping: collapse every run
/// of whitespace to a single space. Copy-paste produces byte-identical
/// (modulo reindentation) bodies, so whitespace-insensitive textual
/// identity is exactly the right grain — no need to parse the JS.
fn normalize_match(source: &str) -> String {
    source.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// (module path, readable export name) -> minified `selector.binding.name`.
/// Only members that carry both a readable `name:` and a name-only
/// binding selector can be tracked across spec versions, so only those
/// land in the map.
type DriftMap = BTreeMap<(String, String), String>;

fn collect_drift_map(modules_root: &Path) -> Result<DriftMap> {
    let mut map = DriftMap::new();
    for file in collect_module_files(modules_root)
        .with_context(|| format!("walking {}", modules_root.display()))?
    {
        let module_path = module_path_from_file(&file, modules_root);
        let module = read_module_file(&file)?;
        for member in &module.members {
            let (Some(export_name), Some(binding)) = (&member.name, &member.selector.binding)
            else {
                continue;
            };
            map.insert(
                (module_path.clone(), export_name.clone()),
                binding.name.clone(),
            );
        }
    }
    Ok(map)
}

pub fn compute_selector_debt(
    modules_root: &Path,
    against: Option<&Path>,
) -> Result<SelectorDebtReport> {
    compute_selector_debt_with_source(modules_root, against, None)
}

pub fn compute_selector_debt_with_source(
    modules_root: &Path,
    against: Option<&Path>,
    source_aware: Option<&SourceAwareSelectorDebtConfig<'_>>,
) -> Result<SelectorDebtReport> {
    if source_aware.is_some() {
        return js_ast::with_swc_globals(|| {
            compute_selector_debt_impl(modules_root, against, source_aware)
        });
    }
    compute_selector_debt_impl(modules_root, against, source_aware)
}

fn compute_selector_debt_impl(
    modules_root: &Path,
    against: Option<&Path>,
    source_aware: Option<&SourceAwareSelectorDebtConfig<'_>>,
) -> Result<SelectorDebtReport> {
    let files = collect_module_files(modules_root)
        .with_context(|| format!("walking {}", modules_root.display()))?;

    let mut name_only: Vec<NameOnlySelector> = Vec::new();
    // normalized body -> every occurrence of it.
    let mut by_normalized: BTreeMap<String, Vec<SourceMatchOccurrence>> = BTreeMap::new();
    let mut source_match_total = 0usize;
    let mut current_drift: DriftMap = DriftMap::new();
    let runtime_module = source_aware
        .map(|config| {
            let source = std::fs::read_to_string(config.source_file)
                .with_context(|| format!("reading {}", config.source_file.display()))?;
            js_ast::parse_js_module_ast(&config.source_file.display().to_string(), &source)
                .with_context(|| format!("parsing {}", config.source_file.display()))
        })
        .transpose()?;
    let mut source_aware_checked = 0usize;
    let mut source_aware_unique = 0usize;
    let mut source_aware_near_ambiguous = Vec::new();

    for file in &files {
        let module_path = module_path_from_file(file, modules_root);
        let module: ModuleFile = read_module_file(file)?;

        for member in &module.members {
            match member
                .selector
                .selected()
                .with_context(|| format!("module {module_path}: member selector"))?
            {
                MemberSelectorSpec::Binding(binding) => {
                    if let Some(export_name) = &member.name {
                        current_drift.insert(
                            (module_path.clone(), export_name.clone()),
                            binding.name.clone(),
                        );
                    }
                    name_only.push(NameOnlySelector {
                        module: module_path.clone(),
                        minified_score: minified_score(&binding.name),
                        binding_name: binding.name,
                        export_name: member.name.clone(),
                    });
                }
                MemberSelectorSpec::SourceMatch(selector) => {
                    source_match_total += 1;
                    collect_source_aware_debt(
                        &mut source_aware_checked,
                        &mut source_aware_unique,
                        &mut source_aware_near_ambiguous,
                        source_aware,
                        runtime_module.as_ref(),
                        &module_path,
                        SelectorSite::Member,
                        member.name.clone(),
                        &selector,
                    )?;
                    by_normalized
                        .entry(normalize_match(&selector.match_source))
                        .or_default()
                        .push(SourceMatchOccurrence {
                            module: module_path.clone(),
                            site: SelectorSite::Member,
                            export_name: member.name.clone(),
                            match_source: selector.match_source,
                        });
                }
            }
        }

        for group in &module.binding_groups {
            source_match_total += 1;
            let selector = group.source_match.selector();
            collect_source_aware_debt(
                &mut source_aware_checked,
                &mut source_aware_unique,
                &mut source_aware_near_ambiguous,
                source_aware,
                runtime_module.as_ref(),
                &module_path,
                SelectorSite::BindingGroup,
                None,
                &selector,
            )?;
            by_normalized
                .entry(normalize_match(&group.source_match.match_source))
                .or_default()
                .push(SourceMatchOccurrence {
                    module: module_path.clone(),
                    site: SelectorSite::BindingGroup,
                    export_name: None,
                    match_source: group.source_match.match_source.clone(),
                });
        }

        for statement in &module.anonymous_statements {
            let selector = statement
                .selector()
                .with_context(|| format!("module {module_path}: anonymous statement selector"))?;
            source_match_total += 1;
            collect_source_aware_debt(
                &mut source_aware_checked,
                &mut source_aware_unique,
                &mut source_aware_near_ambiguous,
                source_aware,
                runtime_module.as_ref(),
                &module_path,
                SelectorSite::AnonymousStatement,
                None,
                &selector,
            )?;
            by_normalized
                .entry(normalize_match(&selector.match_source))
                .or_default()
                .push(SourceMatchOccurrence {
                    module: module_path.clone(),
                    site: SelectorSite::AnonymousStatement,
                    export_name: None,
                    match_source: selector.match_source,
                });
        }
    }

    // Most rebuild-fragile first; ties broken by module then bound name
    // for a stable order.
    name_only.sort_by(|a, b| {
        b.minified_score
            .cmp(&a.minified_score)
            .then_with(|| a.module.cmp(&b.module))
            .then_with(|| a.binding_name.cmp(&b.binding_name))
    });

    let mut repeated_source_match: Vec<RepeatedSourceMatch> = by_normalized
        .into_iter()
        .filter(|(_, occurrences)| occurrences.len() >= 2)
        .map(|(normalized, mut occurrences)| {
            occurrences.sort_by(|a, b| {
                a.module
                    .cmp(&b.module)
                    .then_with(|| a.site.cmp(&b.site))
                    .then_with(|| a.export_name.cmp(&b.export_name))
            });
            RepeatedSourceMatch {
                normalized,
                occurrences,
            }
        })
        .collect();
    repeated_source_match.sort_by(|a, b| {
        b.occurrences
            .len()
            .cmp(&a.occurrences.len())
            .then_with(|| a.normalized.cmp(&b.normalized))
    });

    let drifted_bindings = match against {
        None => Vec::new(),
        Some(against_root) => {
            let against_drift = collect_drift_map(against_root)?;
            let mut drifted: Vec<DriftedBinding> = current_drift
                .iter()
                .filter_map(|((module, export_name), current_binding)| {
                    let previous = against_drift.get(&(module.clone(), export_name.clone()))?;
                    (previous != current_binding).then(|| DriftedBinding {
                        module: module.clone(),
                        export_name: export_name.clone(),
                        previous_binding: previous.clone(),
                        current_binding: current_binding.clone(),
                    })
                })
                .collect();
            drifted.sort_by(|a, b| {
                a.module
                    .cmp(&b.module)
                    .then_with(|| a.export_name.cmp(&b.export_name))
            });
            drifted
        }
    };

    let summary = SelectorDebtSummary {
        name_only_total: name_only.len(),
        name_only_fragile: name_only
            .iter()
            .filter(|n| n.minified_score >= FRAGILE_THRESHOLD)
            .count(),
        source_match_total,
        repeated_source_match_groups: repeated_source_match.len(),
        drifted_binding_total: drifted_bindings.len(),
        source_aware_checked,
        source_aware_unique,
        source_aware_near_ambiguous: source_aware_near_ambiguous.len(),
    };

    Ok(SelectorDebtReport {
        name_only,
        repeated_source_match,
        drifted_bindings,
        source_aware_near_ambiguous,
        summary,
    })
}

#[allow(clippy::too_many_arguments)]
fn collect_source_aware_debt(
    checked: &mut usize,
    unique: &mut usize,
    rows: &mut Vec<SourceAwareStructuralSelector>,
    config: Option<&SourceAwareSelectorDebtConfig<'_>>,
    runtime_module: Option<&swc_ecma_ast::Module>,
    module_path: &str,
    site: SelectorSite,
    export_name: Option<String>,
    selector: &AnonymousStatementSelector,
) -> Result<()> {
    let (Some(config), Some(runtime_module)) = (config, runtime_module) else {
        return Ok(());
    };
    *checked += 1;
    let debt = source_match::source_match_body_debt(
        runtime_module,
        module_path,
        selector,
        config.near_match_min_score,
        config.near_match_limit,
    )?;
    let [exact_group] = debt.exact_groups.as_slice() else {
        return Ok(());
    };
    *unique += 1;
    if debt.near_misses.is_empty() {
        return Ok(());
    }
    rows.push(SourceAwareStructuralSelector {
        module: module_path.to_owned(),
        site,
        export_name,
        exact_body_indices: exact_group.iter().flatten().copied().collect(),
        near_misses: debt
            .near_misses
            .into_iter()
            .map(|near| SourceAwareNearMiss {
                body_idx: near.body_idx,
                declared_bindings: near.declared_bindings,
                score: near.score,
                reason: near.reason,
            })
            .collect(),
    });
    Ok(())
}

/// Compact two-section-plus-summary text rendering.
pub fn render_selector_debt_text(report: &SelectorDebtReport, out: &mut String) {
    let s = &report.summary;
    out.push_str(&format!(
        "name-only selectors: {} ({} fragile)  source_match: {} ({} repeated group(s))  drifted: {}  source-aware near-ambiguous: {}/{} unique checked\n",
        s.name_only_total,
        s.name_only_fragile,
        s.source_match_total,
        s.repeated_source_match_groups,
        s.drifted_binding_total,
        s.source_aware_near_ambiguous,
        s.source_aware_unique,
    ));

    if !report.name_only.is_empty() {
        out.push_str("name-only (most fragile first):\n");
        for entry in &report.name_only {
            let readable = entry.export_name.as_deref().unwrap_or("-");
            out.push_str(&format!(
                "  {:>3}  {}  {}  [{}]\n",
                entry.minified_score, entry.binding_name, entry.module, readable,
            ));
        }
    }

    if !report.repeated_source_match.is_empty() {
        out.push_str("repeated source_match bodies:\n");
        for group in &report.repeated_source_match {
            out.push_str(&format!(
                "  {}x  {}\n",
                group.occurrences.len(),
                group.normalized,
            ));
            for occurrence in &group.occurrences {
                out.push_str(&format!(
                    "      {:?} {}\n",
                    occurrence.site, occurrence.module,
                ));
            }
        }
    }

    if !report.drifted_bindings.is_empty() {
        out.push_str("drifted minified bindings:\n");
        for drift in &report.drifted_bindings {
            out.push_str(&format!(
                "  {} ({})  {} -> {}\n",
                drift.export_name, drift.module, drift.previous_binding, drift.current_binding,
            ));
        }
    }

    if !report.source_aware_near_ambiguous.is_empty() {
        out.push_str("source-aware near-ambiguous structural selectors:\n");
        for selector in &report.source_aware_near_ambiguous {
            let readable = selector.export_name.as_deref().unwrap_or("-");
            out.push_str(&format!(
                "  {:?} {} [{}] exact={:?}\n",
                selector.site, selector.module, readable, selector.exact_body_indices,
            ));
            for near in &selector.near_misses {
                let declared = if near.declared_bindings.is_empty() {
                    "-".to_owned()
                } else {
                    near.declared_bindings.join(",")
                };
                out.push_str(&format!(
                    "      score={} body={} declared=[{}] {}\n",
                    near.score, near.body_idx, declared, near.reason,
                ));
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn write(root: &Path, rel: &str, body: &str) {
        let p = root.join(rel);
        fs::create_dir_all(p.parent().unwrap()).unwrap();
        fs::write(p, body).unwrap();
    }

    #[test]
    fn minified_score_ranks_short_and_vowelless_above_words() {
        // Single/double-char tokens are maximal; readable words are zero.
        assert_eq!(minified_score("a"), 100);
        assert_eq!(minified_score("$"), 100);
        assert_eq!(minified_score("aQ"), 90);
        assert!(minified_score("XOe") >= FRAGILE_THRESHOLD);
        // A vowel-less 3-char beats a voweled 3-char.
        assert!(minified_score("Rng") > minified_score("XOe"));
        // Real words score zero regardless of length / single vowel.
        assert_eq!(minified_score("registry"), 0);
        assert_eq!(minified_score("parseConfig"), 0);
        assert_eq!(minified_score("Test"), 0);
        assert_eq!(minified_score("List"), 0);
        // Longer consonant soup is still flagged.
        assert!(minified_score("wXyz") >= FRAGILE_THRESHOLD);
    }

    #[test]
    fn name_only_selectors_ranked_most_fragile_first() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "ui/widgets.yaml",
            "members:\n  - name: WidgetRegistry\n    selector: { binding: { name: registry } }\n  - selector: { binding: { name: a } }\n",
        );
        let report = compute_selector_debt(root, None).unwrap();
        assert_eq!(report.summary.name_only_total, 2);
        assert_eq!(report.summary.name_only_fragile, 1);
        // `a` (score 100) ranks before `registry` (score 0).
        assert_eq!(report.name_only[0].binding_name, "a");
        assert_eq!(report.name_only[0].minified_score, 100);
        assert_eq!(report.name_only[1].binding_name, "registry");
        assert_eq!(
            report.name_only[1].export_name.as_deref(),
            Some("WidgetRegistry")
        );
    }

    #[test]
    fn repeated_source_match_bodies_grouped_across_sites() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        // Same decorator-helper body copied into a member source_match
        // and an anonymous statement, modulo whitespace.
        write(
            root,
            "a.yaml",
            "members:\n  - name: Foo\n    selector:\n      source_match:\n        target_binding: x\n        match: 'var x = decorate(y);'\n",
        );
        write(
            root,
            "b.yaml",
            "anonymous_statements:\n  - match: |\n      var   x =   decorate(y);\n",
        );
        // A body that appears only once must not be reported.
        write(
            root,
            "c.yaml",
            "anonymous_statements:\n  - match: 'register(z);'\n",
        );
        let report = compute_selector_debt(root, None).unwrap();
        assert_eq!(report.summary.source_match_total, 3);
        assert_eq!(report.repeated_source_match.len(), 1);
        let group = &report.repeated_source_match[0];
        assert_eq!(group.normalized, "var x = decorate(y);");
        assert_eq!(group.occurrences.len(), 2);
        assert_eq!(group.occurrences[0].site, SelectorSite::Member);
        assert_eq!(group.occurrences[1].site, SelectorSite::AnonymousStatement);
    }

    #[test]
    fn drift_detected_only_when_minified_binding_changes_under_stable_name() {
        let dir = TempDir::new().unwrap();
        let current = dir.path().join("current");
        let against = dir.path().join("against");
        // `Foo`'s minified binding moved XOe -> XPq; `Bar` is unchanged.
        write(
            &current,
            "m.yaml",
            "members:\n  - name: Foo\n    selector: { binding: { name: XPq } }\n  - name: Bar\n    selector: { binding: { name: YY } }\n",
        );
        write(
            &against,
            "m.yaml",
            "members:\n  - name: Foo\n    selector: { binding: { name: XOe } }\n  - name: Bar\n    selector: { binding: { name: YY } }\n",
        );
        let report = compute_selector_debt(&current, Some(&against)).unwrap();
        assert_eq!(report.summary.drifted_binding_total, 1);
        let drift = &report.drifted_bindings[0];
        assert_eq!(drift.export_name, "Foo");
        assert_eq!(drift.previous_binding, "XOe");
        assert_eq!(drift.current_binding, "XPq");
    }

    #[test]
    fn drift_section_empty_without_against() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "m.yaml",
            "members:\n  - name: Foo\n    selector: { binding: { name: XOe } }\n",
        );
        let report = compute_selector_debt(root, None).unwrap();
        assert!(report.drifted_bindings.is_empty());
        assert_eq!(report.summary.drifted_binding_total, 0);
    }

    #[test]
    fn source_aware_mode_reports_unique_selector_with_near_matching_sibling() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "classes.yaml",
            "members:\n  - name: PickedClass\n    selector:\n      source_match:\n        identifiers: alpha_all\n        match: |\n          class PickedClass {\n            important() {\n              return 1;\n            }\n          }\n",
        );
        let source_file = root.join("chunk.js");
        fs::write(
            &source_file,
            "class a { important() { return 1; } }\nclass b { important() { return 2; } }\n",
        )
        .unwrap();
        let config = SourceAwareSelectorDebtConfig {
            source_file: &source_file,
            near_match_min_score: 55,
            near_match_limit: 3,
        };

        let report = compute_selector_debt_with_source(root, None, Some(&config)).unwrap();

        assert_eq!(report.summary.source_aware_checked, 1);
        assert_eq!(report.summary.source_aware_unique, 1);
        assert_eq!(report.summary.source_aware_near_ambiguous, 1);
        let row = &report.source_aware_near_ambiguous[0];
        assert_eq!(row.module, "classes");
        assert_eq!(row.site, SelectorSite::Member);
        assert_eq!(row.export_name.as_deref(), Some("PickedClass"));
        assert_eq!(row.exact_body_indices, vec![0]);
        assert_eq!(row.near_misses.len(), 1);
        assert_eq!(row.near_misses[0].body_idx, 1);
        assert_eq!(row.near_misses[0].declared_bindings, vec!["b".to_owned()]);
    }

    #[test]
    fn source_aware_mode_does_not_report_ambiguous_exact_matches_as_unique_near_misses() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "classes.yaml",
            "members:\n  - name: PickedClass\n    selector:\n      source_match:\n        identifiers: alpha_all\n        match: |\n          class PickedClass {\n            important() {\n              return 1;\n            }\n          }\n",
        );
        let source_file = root.join("chunk.js");
        fs::write(
            &source_file,
            "class a { important() { return 1; } }\nclass b { important() { return 1; } }\n",
        )
        .unwrap();
        let config = SourceAwareSelectorDebtConfig {
            source_file: &source_file,
            near_match_min_score: 55,
            near_match_limit: 3,
        };

        let report = compute_selector_debt_with_source(root, None, Some(&config)).unwrap();

        assert_eq!(report.summary.source_aware_checked, 1);
        assert_eq!(report.summary.source_aware_unique, 0);
        assert_eq!(report.summary.source_aware_near_ambiguous, 0);
        assert!(report.source_aware_near_ambiguous.is_empty());
    }

    #[test]
    fn deterministic_same_spec_same_output() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();
        write(
            root,
            "a.yaml",
            "members:\n  - selector: { binding: { name: a } }\n  - selector: { binding: { name: bQ } }\n",
        );
        write(
            root,
            "b/c.yaml",
            "anonymous_statements:\n  - match: 'foo();'\n",
        );
        let j1 = serde_json::to_string(&compute_selector_debt(root, None).unwrap()).unwrap();
        let j2 = serde_json::to_string(&compute_selector_debt(root, None).unwrap()).unwrap();
        assert_eq!(j1, j2);
    }
}
