apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guacamole.guacamoleServiceName" . }}
  labels:
    {{- include "common.labelsWith" (dict "context" . "extra" (dict "app.kubernetes.io/component" "guacamole")) | nindent 4 }}
spec:
  replicas: {{ .Values.guacamole.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabelsWith" (dict "context" . "extra" (dict "app.kubernetes.io/component" "guacamole")) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabelsWith" (dict "context" . "extra" (dict "app.kubernetes.io/component" "guacamole")) | nindent 8 }}
        {{- range $k, $v := .Values.guacamole.podLabels }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      {{- if .Values.guacamole.podAnnotations }}
      annotations:
        {{- range $k, $v := .Values.guacamole.podAnnotations }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "guacamole.serviceAccountName" . }}
      containers:
        - name: guacamole
          image: "{{ .Values.guacamole.image.repository }}:{{ .Values.guacamole.image.tag }}"
          imagePullPolicy: {{ .Values.guacamole.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GUACD_HOSTNAME
              value: {{ include "guacamole.guacdServiceName" . }}
            - name: GUACD_PORT
              value: {{ .Values.guacd.service.port | quote }}
            - name: POSTGRES_HOSTNAME
              value: {{ .Values.postgres.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "guacamole.dbSecretName" . }}
                  key: {{ include "guacamole.envSecretKey" . }}
          {{- if .Values.guacamole.extraEnv }}
          {{- range .Values.guacamole.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.guacamole.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
