load("//devinfra/python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "models",
    srcs = ["models.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//pydantic",
    ],
)

py_library(
    name = "loaders",
    srcs = ["loaders.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":models",
    ],
)

py_library(
    name = "matcher",
    srcs = ["matcher.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":models",
    ],
)

py_library(
    name = "main",
    srcs = ["main.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":loaders",
        ":matcher",
        ":models",
    ],
)

py_library(
    name = "pdf_utils",
    srcs = ["pdf_utils.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//more_itertools",
    ],
)

py_library(
    name = "extract_pdfs",
    srcs = ["extract_pdfs.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":models",
        ":pdf_utils",
        "@pypi//httpx",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "parse_eob_listing",
    srcs = ["parse_eob_listing.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//beautifulsoup4"],
)

py_binary(
    name = "parse_eob_listing_bin",
    main_module = "x.eob_matching.parse_eob_listing",
    visibility = ["//visibility:public"],
    deps = [":parse_eob_listing"],
)

py_binary(
    name = "eob_matching",
    main_module = "x.eob_matching.main",
    visibility = ["//visibility:public"],
    deps = [":main"],
)

py_binary(
    name = "extract_pdfs_bin",
    main_module = "x.eob_matching.extract_pdfs",
    visibility = ["//visibility:public"],
    deps = [":extract_pdfs"],
)

py_library(
    name = "eval_extraction",
    srcs = ["eval_extraction.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":extract_pdfs",
        ":models",
        ":pdf_utils",
        "@pypi//pydantic",
    ],
)

py_binary(
    name = "eval_extraction_bin",
    main_module = "x.eob_matching.eval_extraction",
    visibility = ["//visibility:public"],
    deps = [":eval_extraction"],
)
