load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "mcp",
    srcs = [
        "registry.go",
        "server.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/internal/mcp",
    visibility = ["//devinfra/claude/web_env/re/environment_manager/a6f96673/src:__subpackages__"],
    deps = [
        "@com_github_mark3labs_mcp_go//mcp",
        "@com_github_mark3labs_mcp_go//server",
    ],
)
