// Package mcp provides the MCP (Model Context Protocol) server registry and
// base server implementation. MCP servers are registered at init time and
// started/registered with Claude Code at runtime.
//
// Reconstructed from binary at Build ID a6f96673 (Go 1.25.6).
// Source path: /home/runner/work/anthropic/anthropic/api-go/environment-manager/internal/mcp/registry.go
//
// Key symbols:
//   - mcp.RegisterServer (0xace1c0)
//   - mcp.NewRegistration (0xace340)
//   - mcp.GetMCPRegistrations (0xacedc0)
//   - mcp.RegisterWithClaude (0xacf0a0)
//   - mcp.registry (0x15ade00) - package-level slice
//   - mcp.registryMu (0x15d2500) - package-level RWMutex
//   - mcp.debugHardcodedToken (0x15d1af2) - package-level bool
//   - mcp.init (0xace180)
package mcp

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"strings"
	"sync"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
)

// ToolConfig holds a tool definition and its handler function.
// This is the mcp package's own tool type used by the MCPServer interface.
//
// DWARF type: github.com/anthropics/anthropic/api-go/environment-manager/internal/mcp.ToolConfig
//
//	field: Tool -> mcp.Tool (github.com/mark3labs/mcp-go/mcp)
//	field: Handler -> func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error)
type ToolConfig struct {
	Tool    mcplib.Tool
	Handler func(context.Context, mcplib.CallToolRequest) (*mcplib.CallToolResult, error)
}

// MCPServer is the interface that all MCP servers must implement.
// Implementations include BaseServer (embedded default) and concrete servers
// like codesign.CodeSignMCPServer.
//
// Interface reconstructed from itab:
//
//	go:itab.*codesign.CodeSignMCPServer,mcp.MCPServer (0xf68220)
type MCPServer interface {
	// GetName returns the server's display name.
	GetName() string

	// GetTools returns the server tool definitions for the MCP protocol.
	GetTools() []ToolConfig

	// Start starts the MCP server, binding to a port and serving requests.
	// It returns the listening port and any error.
	Start(logger *slog.Logger, name string) (int, error)

	// Stop gracefully stops the MCP server.
	Stop() bool

	// ShouldRegisterWithClaude returns whether this server should be registered
	// with the Claude Code MCP configuration.
	ShouldRegisterWithClaude() bool
}

// ServerRegistration holds a registered MCP server's metadata and lifecycle hooks.
//
// Struct layout (from NewRegistration assembly at 0xace340):
//
//	offset 0x00: name string (ptr + len)
//	offset 0x10: configureServer func(...) (MCPServer, error)
//	offset 0x18: shouldRegister func() bool
//	offset 0x20: server MCPServer (interface)
//	offset 0x28: enabled func() bool (closure from NewRegistration.func1)
//	offset 0x38: disable func() (closure from NewRegistration.func2)
type ServerRegistration struct {
	name            string
	command         string
	configureServer func(*slog.Logger, string, interface{}, interface{}, interface{}) (MCPServer, error)
	shouldRegister  func() bool
	server          MCPServer
	enabled         func() bool
	disable         func()
}

// Name returns the registration's server name.
func (r *ServerRegistration) Name() string {
	return r.name
}

// Command returns the registration's command string.
func (r *ServerRegistration) Command() string {
	return r.command
}

// Setup calls the registration's configureServer function and starts the server.
// Returns the MCPServer, the socket directory path, and any error.
func (r *ServerRegistration) Setup(ctx context.Context, logger *slog.Logger) (MCPServer, string, error) {
	srv, err := r.configureServer(logger, r.name, nil, nil, nil)
	if err != nil {
		return nil, "", err
	}
	r.server = srv
	return srv, "", nil
}

// registry is the global slice of registered MCP server registrations.
// Protected by registryMu.
// Symbol: mcp.registry (0x15ade00) - []interface{} (slice header: ptr, len, cap)
var registry []*ServerRegistration

// registryMu protects concurrent access to the registry slice.
// Symbol: mcp.registryMu (0x15d2500)
var registryMu sync.RWMutex

// debugHardcodedToken controls whether a hardcoded bearer token is used instead
// of randomly generated tokens. Set to true when MCP_DEBUG_TOKEN env var is non-empty.
// Symbol: mcp.debugHardcodedToken (0x15d1af2)
var debugHardcodedToken bool

// heartbeatDuration is the interval for MCP server heartbeat checks.
// Symbol: mcp.heartbeatDuration (0x152dae8)
var heartbeatDuration time.Duration

// init checks for the MCP_DEBUG_TOKEN environment variable and sets
// debugHardcodedToken accordingly.
//
// Binary address: 0xace180
// Source file: <autogenerated> (init function)
//
// Assembly:
//
//	LEA "MCP_DEBUG_TOKEN" → AX (0xace18e)
//	CALL os.Getenv (0xace19a)
//	SETNE debugHardcodedToken (0xace1a2)
func init() {
	val := os.Getenv("MCP_DEBUG_TOKEN")
	debugHardcodedToken = val != ""
}

// RegisterServer appends a ServerRegistration to the global registry.
// It acquires registryMu write lock before modifying the slice.
//
// Binary address: 0xace1c0
// Source file: registry.go
//
// Assembly flow:
//  1. Lock registryMu (0xace1ea)
//  2. defer registryMu.Unlock via deferwrap1 (0xace1ef)
//  3. Append registration to registry slice (0xace224-0xace2a0)
//  4. Unlock and return
func RegisterServer(reg *ServerRegistration) {
	registryMu.Lock()
	defer registryMu.Unlock()
	registry = append(registry, reg)
}

// NewRegistration creates a new ServerRegistration and immediately registers it.
// It wraps the configure function and shouldRegister predicate into closures,
// then calls RegisterServer.
//
// Binary address: 0xace340
// Source file: registry.go
//
// Parameters (from register calling convention):
//
//	AX: name ptr, BX: name len
//	CX: description ptr, DI: description len
//	SI: configureServer func
//	R8: shouldRegister func
//	R9: additional parameter
//
// Assembly flow:
//  1. Allocates enabled closure (func1 at 0xace580) at 0xace380
//  2. Allocates disable closure (func2 at 0xace560) at 0xace3a0
//  3. Allocates ServerRegistration at 0xace40a
//  4. Populates all fields
//  5. Calls RegisterServer at 0xace4e0
//  6. Returns the registration
func NewRegistration(
	name string,
	description string,
	configureServer func(*slog.Logger, string, interface{}, interface{}, interface{}) (MCPServer, error),
	shouldRegister func() bool,
) *ServerRegistration {
	reg := &ServerRegistration{
		name:            name,
		configureServer: configureServer,
		shouldRegister:  shouldRegister,
	}

	// enabled and disable are closures over an internal boolean flag
	enabled := true
	reg.enabled = func() bool { return enabled }
	reg.disable = func() { enabled = false }

	RegisterServer(reg)
	return reg
}

// GetMCPRegistrations returns all registered ServerRegistrations that pass their
// shouldRegister predicate for the given environment type and session mode.
//
// Binary address: 0xacedc0
// Source file: registry.go
//
// Assembly flow:
//  1. RLock registryMu (inline atomic at 0xacee0e)
//  2. defer RUnlock via deferwrap1 (0xacf040)
//  3. Iterate registry slice (0xaceea0 loop)
//  4. For each entry, check if enabled callback (offset 0x28) returns true (0xaceeb4)
//  5. If enabled, call shouldRegister closure (0xaceedb)
//  6. If passes, append to result slice (0xaceef0-0xacef49)
//  7. RUnlock and return filtered slice
func GetMCPRegistrations(envType string, sessionMode string) []*ServerRegistration {
	registryMu.RLock()
	defer registryMu.RUnlock()

	var result []*ServerRegistration
	for _, reg := range registry {
		if reg.enabled == nil || !reg.enabled() {
			continue
		}
		if reg.shouldRegister != nil && !reg.shouldRegister() {
			continue
		}
		result = append(result, reg)
	}
	return result
}

// RegisterWithClaude registers an MCP server with Claude Code by calling the
// claude CLI with "mcp add" arguments. It constructs a unique server name using
// a timestamp, builds the claude command with appropriate arguments, and
// executes it.
//
// Binary address: 0xacf0a0
// Source file: registry.go
//
// Assembly flow:
//  1. Get current time via time.Now (0xacf0ed)
//  2. Format server name: fmt.Sprintf("%s-%d", port, timestamp) (0xacf158)
//  3. Format URL: fmt.Sprintf("http://localhost:%d", port) (0xacf1c1)
//  4. Build command: exec.CommandContext(ctx, "claude", "mcp", "add", "--transport", "http", name, url) (0xacf24b)
//  5. Execute: cmd.CombinedOutput (0xacf250)
//  6. On error: log warning with error details (0xacf337)
//  7. On success: parse output for URL confirmation (0xacf3a1)
//  8. Log info about successful registration (0xacf443)
//  9. Then run "claude mcp add" again for the scope (0xacf4e6)
func RegisterWithClaude(
	ctx context.Context,
	logger *slog.Logger,
	name string,
	port interface{},
	serverURL string,
) {
	now := time.Now()
	serverName := fmt.Sprintf("%s-%d", name, now.UnixNano())
	serverEndpoint := fmt.Sprintf("http://localhost:%s", serverURL)

	// Execute: claude mcp add --transport http <name> <url>
	cmd := exec.CommandContext(ctx, "claude", "mcp", "add", "--transport", "http", serverName, serverEndpoint)
	output, err := cmd.CombinedOutput()
	if err != nil {
		logger.Warn("failed to register MCP server with claude",
			"error", err,
			"output", string(output),
			"server", name,
		)
		return
	}

	outputStr := string(output)
	if strings.Index(outputStr, serverURL) >= 0 {
		logger.Info("registered MCP server with Claude Code and it recognized our URL",
			"server", name,
		)
	}

	// Register again with scope (claude mcp add --scope <scope> <name> <url>)
	cmd2 := exec.CommandContext(ctx, "claude", "mcp", "add", "--transport", "http", serverName, serverEndpoint, name)
	_, _ = cmd2.CombinedOutput()
}

// generateBearerToken generates a random bearer token for MCP server auth.
// If debugHardcodedToken is true, uses a fixed token for debugging.
// Otherwise generates 32 random bytes and base64url-encodes them.
//
// Called from BaseServer.Start (0xad01ad).
// Assembly evidence at 0xad0194-0xad0250:
//  1. crypto/rand.Read 32 bytes (0xad01ad)
//  2. If error: fmt.Errorf("failed to read random data: %w") (0xad01f2)
//  3. base64.URLEncoding.EncodeToString (0xad0220)
//  4. Store token on BaseServer
func generateBearerToken() (string, error) {
	if debugHardcodedToken {
		// Use hardcoded token for debugging
		return "debug-token", nil
	}

	buf := make([]byte, 32)
	_, err := rand.Read(buf)
	if err != nil {
		return "", fmt.Errorf("failed to read random data: %w", err)
	}
	return base64.URLEncoding.EncodeToString(buf), nil
}
