load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "cli",
    srcs = ["cli.py"],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "//cli_util:decorators",
        "//cli_util:logging",
        "//wt/client:cd_utils",
        "//wt/client:handlers",
        "//wt/client:view_formatter",
        "//wt/client:wt_client",
        "//wt/shared:configuration",
        "//wt/shared:constants",
        "@pypi//click",
        "@pypi//colorama",
        "@pypi//typer_slim",
    ],
)

py_binary(
    name = "wt_cli",
    srcs = ["__main__.py"],
    main = "__main__.py",
    visibility = ["//visibility:public"],
    deps = [":cli"],
)
