load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("//tools/lint:linters.bzl", "ruff_test")

py_library(
    name = "cli",
    srcs = ["cli.py"],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "//cli_util:decorators",
        "//cli_util:logging",
        "@pypi//click",
        "@pypi//colorama",
        "@pypi//typer_slim",
    ],
)

py_binary(
    name = "wt-cli",
    srcs = ["__main__.py"],
    main = "__main__.py",
    visibility = ["//visibility:public"],
    deps = [":cli"],
)

ruff_test(
    name = "ruff",
    srcs = [
        ":cli",
        ":demo_plugin",
        ":plugins",
    ],
)

py_library(
    name = "demo_plugin",
    srcs = ["demo_plugin.py"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "plugins",
    srcs = ["plugins.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//pluggy"],
)
