load("//devinfra/python:defs.bzl", "py_library", "py_test")

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    visibility = ["//devinfra/wt:__subpackages__"],
    deps = [
        "//devinfra/wt/testing:conftest",
        "@pypi//pytest",
    ],
)

py_test(
    name = "test_integration_cli_daemon",
    srcs = ["test_integration_cli_daemon.py"],
    data = ["//third_party/gitstatusd"],
    deps = [
        ":conftest",
        "//:conftest",
        "//devinfra/wt/shared:git_utils",
        "//devinfra/wt/testing:asserts",
        "@pypi//pygit2",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_integration_cli_output_format",
    srcs = ["test_integration_cli_output_format.py"],
    data = ["//third_party/gitstatusd"],
    deps = [
        ":conftest",
        "//:conftest",
        "//devinfra/wt:cli",
        "//devinfra/wt/shared:protocol",
        "//devinfra/wt/testing:asserts",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_integration_shell",
    srcs = ["test_integration_shell.py"],
    data = [
        "//devinfra/wt:wt_cli",
        "//third_party/gitstatusd",
    ],
    deps = [
        ":conftest",
        "//:conftest",
        "//devinfra/wt/shell:install",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
