load("//devinfra/python:defs.bzl", "py_binary", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "fetch_real_history_lib",
    srcs = ["fetch_real_history.py"],
    deps = ["@pypi//tenacity"],
)

py_binary(
    name = "fetch_real_history",
    main_module = "finance.augur.data.fetch_real_history",
    deps = [":fetch_real_history_lib"],
)
