apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia-device-plugin
  namespace: ducktape-flux
spec:
  retryInterval: 1m
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: nvidia-device-plugin

    namespace: ducktape-flux
  path: "./cluster/k8s/nvidia-device-plugin"
  prune: true
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: nvidia
      namespace: nvidia-device-plugin
  dependsOn:
    - name: node-feature-discovery
      namespace: ducktape-flux
