load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cmd",
    srcs = [
        "cmd_code_sign.go",
        "cmd_orchestrator.go",
        "cmd_poll.go",
        "cmd_print_sandbox.go",
        "cmd_setup.go",
        "cmd_task_run.go",
        "types.go",
        "utils.go",
    ],
    importpath = "github.com/anthropics/anthropic/api-go/environment-manager/cmd",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/api",
        "//internal/auth",
        "//internal/claude",
        "//internal/config",
        "//internal/input",
        "//internal/logger",
        "//internal/manager",
        "//internal/o11y",
        "//internal/o11y/diag",
        "//internal/orchestrator",
        "//internal/sandbox",
        "//internal/session",
        "//internal/util",
        "@com_github_spf13_cobra//:cobra",
    ],
)
