apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: git.allegedly.works/ducktape-ci/iron-proxy
    newTag: devel-20260819201301-06b8b19 # {"$imagepolicy": "flux-system:iron-proxy:tag"}
