"""CLI utilities package."""

load("@rules_python//python:defs.bzl", "py_library")
load("//tools/lint:linters.bzl", "ruff_test")

ruff_test(
    name = "ruff",
    srcs = [
        ":decorators",
        ":logging",
    ],
)

py_library(
    name = "decorators",
    srcs = ["decorators.py"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "logging",
    srcs = ["logging.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//structlog",
        "@pypi//typer_slim",
    ],
)
