load("@aspect_rules_js//js:defs.bzl", "js_info_files", "js_library", "js_test")

js_info_files(
    name = "sources",
    srcs = [":libs"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "libs",
    srcs = [
        "artifact.mjs",
        "io.mjs",
        "load_chunks.mjs",
        "normalize.mjs",
        "package_tree.mjs",
        "parse_asts.mjs",
        "parser_options.mjs",
        "program_analysis.mjs",
        "vendor_runtime.mjs",
    ],
    visibility = ["//visibility:public"],
)

js_test(
    name = "vendor_runtime_test",
    data = [
        "vendor_runtime.mjs",
        ":sources",
        "//devinfra/js/debundle/test_support:sources",
    ],
    entry_point = "vendor_runtime_test.mjs",
)
