load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "kubespand_lib",
    srcs = [
        "apid.go",
        "main.go",
    ],
    importpath = "github.com/agentydragon/ducktape/cluster/kubespand",
    visibility = ["//visibility:private"],
    deps = [
        "//cluster/kubespand/agentconfig",
        "//cluster/kubespand/api",
        "//cluster/kubespand/controllers/cluster:clusterctrl",
        "//cluster/kubespand/controllers/k8s:k8sctrl",
        "//cluster/kubespand/controllers/kubespan:kubespanctrl",
        "//cluster/kubespand/controllers/kubespand:kubespandctrl",
        "//cluster/kubespand/controllers/network:networkctrl",
        "@com_github_cosi_project_runtime//api/v1alpha1",
        "@com_github_cosi_project_runtime//pkg/controller/runtime",
        "@com_github_cosi_project_runtime//pkg/state",
        "@com_github_cosi_project_runtime//pkg/state/impl/inmem",
        "@com_github_cosi_project_runtime//pkg/state/impl/namespaced",
        "@com_github_cosi_project_runtime//pkg/state/protobuf/server",
        "@com_github_siderolabs_talos//internal/app/machined/pkg/controllers/cluster",
        "@com_github_siderolabs_talos//internal/app/machined/pkg/controllers/k8s",
        "@com_github_siderolabs_talos//internal/app/machined/pkg/controllers/kubespan",
        "@com_github_siderolabs_talos//internal/app/machined/pkg/controllers/network",
        "@com_github_siderolabs_talos//internal/app/machined/pkg/controllers/secrets",
        "@com_github_siderolabs_talos_pkg_machinery//constants",
        "@com_github_siderolabs_talos_pkg_machinery//resources/network",
        "@com_github_siderolabs_talos_pkg_machinery//resources/secrets",
        "@com_github_siderolabs_talos_pkg_machinery//version",
        "@org_golang_google_grpc//:grpc",
        "@org_uber_go_zap//:zap",
    ],
)

go_binary(
    name = "kubespand",
    embed = [":kubespand_lib"],
    goarch = "amd64",
    goos = "linux",
    static = "on",
    visibility = ["//visibility:public"],
)
