# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "app",
    srcs = ["app.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        "//cluster/cdk8s:cnpg",
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:gateway",
        "//cluster/cdk8s:generation",
        "//cluster/cdk8s:helm",
        "//cluster/cdk8s:manifest_roots",
        "//cluster/cdk8s:metadata",
        "//cluster/cdk8s:valkey",
        "//cluster/cdk8s/crd_bindings/flux:helmrelease",
        "//cluster/cdk8s/crd_bindings/flux:helmrepository",
        "//cluster/cdk8s/crd_bindings/flux:kustomization",
        "//cluster/cdk8s/crd_bindings/source_watcher:artifactgenerator",
        "//cluster/cdk8s/providers/cnpg:cluster",
        "//cluster/cdk8s/seaweedfs:s3",
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
        "@pypi//constructs",
    ],
)
