{{- if and .Values.rotator.enabled .Values.serviceAccountRotator.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ember.rotatorServiceAccountName" . }}
  labels:
    {{- include "common.labelsWith" (dict "context" . "extra" (dict "app.kubernetes.io/component" "rotator")) | nindent 4 }}
{{- end }}
