load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_library")

filegroup(
    name = "run_transform_entry_point",
    srcs = ["run_transform.mjs"],
    visibility = ["//visibility:public"],
)

_JSONC_DEPS = [
    "//:node_modules/jsonc-parser",
]

js_library(
    name = "libs",
    srcs = [
        "rewrite_specifiers.mjs",
        "runner.mjs",
        "write.mjs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//devinfra/js/debundle/analysis:libs",
        "//devinfra/js/debundle/common:libs",
        "//devinfra/js/debundle/extract:libs",
        "//devinfra/js/debundle/harness:libs",
        "//devinfra/js/debundle/rename:libs",
        "//devinfra/js/debundle/split:libs",
        "//devinfra/js/debundle/vendor:libs",
    ] + _JSONC_DEPS,
)

js_binary(
    name = "run_transform",
    data = [
        ":libs",
        ":run_transform_entry_point",
    ],
    entry_point = ":run_transform_entry_point",
    node_options = [
        "--max-old-space-size=8192",
    ],
    visibility = ["//visibility:public"],
)
