load("//devinfra/python:defs.bzl", "py_library", "py_test")

py_library(
    name = "filename_conventions",
    srcs = ["filename_conventions.py"],
    visibility = ["//visibility:public"],
    deps = ["@pypi//pygit2"],
)

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//pygit2",
        "@pypi//pytest",
    ],
)

py_test(
    name = "test_filename_conventions",
    srcs = ["test_filename_conventions.py"],
    deps = [
        ":conftest",
        ":filename_conventions",
        "@pypi//pygit2",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "frozen_specimens",
    srcs = ["frozen_specimens.py"],
    visibility = ["//visibility:public"],
    deps = ["@pypi//pygit2"],
)

py_test(
    name = "test_git_hook",
    srcs = ["test_git_hook.py"],
    legacy_create_init = 0,
    deps = [
        ":git_hook",
        "@pypi//pygit2",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "git_hook",
    srcs = ["git_hook.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":filename_conventions",
        ":frozen_specimens",
        "//devinfra:pytest_main",
        "//devinfra/precommit/enforce_bazel_tests",
        "//util:otel",
        "@pypi//opentelemetry_api",
        "@pypi//opentelemetry_sdk",
        "@pypi//pygit2",
    ],
)
