# gazelle:ignore

load("//devinfra/python:defs.bzl", "py_library")

py_library(
    name = "counters",
    srcs = ["counters.py"],
)

py_library(
    name = "exporter",
    srcs = ["exporter.py"],
    visibility = ["//cluster/cdk8s:__pkg__"],
    deps = [
        ":counters",
        "//cluster/cdk8s:flux",
        "//cluster/cdk8s:manifest_roots",
        "//cluster/cdk8s:namespaces",
        "//cluster/cdk8s/providers/prometheus_operator:pod_monitor",
        "//cluster/cdk8s/providers/prometheus_operator:podmonitor",
        "@pypi//cdk8s",
        "@pypi//cdk8s_plus_34",
    ],
)
