apiVersion: v1
kind: Secret
metadata:
    name: ankiweb-credentials
    namespace: claude-sandbox
    annotations:
        description: AnkiWeb account credentials
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:QHWUyiODpg5re2meFMf5MMxq1L1mU3gjxzRZ,iv:0ternkEKa67OwDwzYQNzdm/MA8fYXrPzFssGFiTtcg4=,tag:kyRLXgYPcrL9KOmpJGtQ+Q==,type:str]
    password: ENC[AES256_GCM,data:31l3n8jVOHc=,iv:3FdOOnk8chhd9WFcGIAZOrDNFoDI5ncKCZNWos4xTnQ=,tag:F7gt5cPgvjqVcRCYlyqTSg==,type:str]
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFY3pjalhvRWZteUtmRWZV
            VlFKTmtleXFrODZ5NHhPZDZhbVMyK3N0RkU4Ck1ucS9GNjBSMXJhUnZQYVFnZEZ5
            U1NuaVF0YWluR2k4a2c4dU1oUFlJeDQKLS0tIGNVZkxITzF6VHNvSlJXT085RHAz
            d1FUaEJkNkVQR0RuM0dNN3VmbDFpMUkK04l5fpLTVK44xMzOFXo+GsRnncxtHZnu
            qQgdajLYBj+YWQrqWIzVMqROYmtkQxGjcflCo7z12Y0UZKZ2GSvl6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQnl1aFhrcU9zUmZydjNv
            cDU4cFFPZlpzN3dVV2crUHlxbHJVa0VXYlNNCngwQ05CdE5vZTJkTUtUR3hzb25h
            Wk5ReTdtd256NVFBL0c4eVB2VTVha0EKLS0tIGpYeDRTT1JLbGxrOXNMVlNDUWtk
            dHl4WXM1cFpGWk1VRVZ4Wk5PRCtlMzQKf/mps0wfTKcV2spsCg81Cn7cWPD+Qngz
            VjJsegVqQInmb0yyoFjdPcwwYfDg83Ead8Q1MKgSEeCjER08ngBFWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T23:44:37Z"
    mac: ENC[AES256_GCM,data:Ax8lDwqwhTVLRRp4aLQOE/2JNiulO6fGWN1IukTWGiobyhLHPFzZJUBJ3hF/CYVtTfAwuSVkbdAv+JpO1O1IEVfzvuhZ0U8jhFcdsfFZ4ianKWVMPIvK4Z/QxzjI8UdF+IuQqu3wQb/J/m9DkAtHncLakADmUAYFqVhyeUHpd+s=,iv:OoJ5a35Q9RVXQzzLqUYsgYWN2mW7/BXd54RcckeudLo=,tag:J/1M0hqsoqcBQHeasMOYOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
