load("//devinfra/python:defs.bzl", "py_library", "py_test")

py_library(
    name = "rd_writer",
    srcs = ["rd_writer.py"],
    visibility = ["//laser:__subpackages__"],
)

py_test(
    name = "test_rd_writer",
    srcs = ["test_rd_writer.py"],
    deps = [
        ":rd_writer",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
