load("//devinfra/python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "compare_bin",
    main_module = "finance.augur.x.allocation_glide.compare",
    deps = [":compare"],
)

py_library(
    name = "compare",
    srcs = ["compare.py"],
    deps = [
        ":policy",
        "//finance/augur/model:series",
        "//finance/augur/rust:invocation",
        "//finance/augur/rust:simulator_ext",
        "//finance/augur/sim:backend",
        "//finance/augur/sim:external_series",
        "//finance/augur/sim:prepared",
        "//finance/augur/sim:results",
        "//finance/augur/sim:scenario",
        "@pypi//numpy",
    ],
)

py_test(
    name = "test_compare",
    srcs = ["test_compare.py"],
    data = [":compare_bin"],
    deps = [
        ":compare",
        "//:conftest",
        "//finance/augur:conftest",
        "//finance/augur/rust:invocation",
        "//finance/augur/sim:results",
        "//util/bazel:runfiles",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "policy",
    srcs = ["policy.py"],
    deps = [
        "//finance/augur/policy:cash_band",
        "//finance/augur/policy:sleeves",
        "//finance/augur/rust:simulator_ext",
    ],
)
